### ISSUE TITLE
Layer tutorial misses linetype setup

### ISSUE THREAD

**Issue by AlexShafir** [mozman/ezdxf#101]
From new user perspective, Layer tutorial goes prior to Linetype tutorial.

So, when first trying Layer tutorial, I get 'Linetype not defined' error.

Sure, Linetype tutorial mentions how to add existing linetypes to document, but it is hard to figure out at first.

Layer tutorial: https://ezdxf.readthedocs.io/en/master/tutorials/layers.html
Linetypes tutorial: https://ezdxf.readthedocs.io/en/master/tutorials/linetypes.html

**Comment by mozman** [comment]
I'm sorry to disappoint you, I hope you do not expect a refund.

**Comment by AlexShafir** [comment]
What do you mean by refund? And why close, it isn't resolved yet...
