### ISSUE TITLE
add_spline methods not rendering correctly when using decimal points

### ISSUE THREAD

**Issue by subsurfaceiodev** [mozman/ezdxf#1022]
**Describe the bug**
When using floats / decimal fit_points in add_spline, add_open_spline, etc. methods splines are not rendered correctly in AutoCAD. REGENALL after opening exported dxf command fixes this problem but it is not ideal.

**To Reproduce**
Information and data needed to reproduce the error:
Based on https://ezdxf.readthedocs.io/en/stable/tutorials/spline.html#splines-from-fit-points:
```
doc = ezdxf.new("R2000")

fit_points = [(0, 0, 0), (0.750, 0.500, 0), (1.750, 0.500, 0), (2.250, 1.250, 0)]
msp = doc.modelspace()
spline = msp.add_spline(fit_points)
```

**Expected behavior**
Splines to be rendered correctly by default

**Screenshots**
Before REGENALL:
![image](https://github.com/mozman/ezdxf/assets/109676812/2077ed67-0b54-40e2-9793-9f61b060d04a)
After REGENALL:
![image](https://github.com/mozman/ezdxf/assets/109676812/7e4c8c3d-a366-4fe6-9ac0-bef98e0d9eb7)

**Comment by mozman** [comment]
This is not a bug this is a feature of CAD applications.

In the default view the `SPLINE` is very small, so the CAD application does not waste time to render a high-resolution curve:

![image](https://github.com/mozman/ezdxf/assets/4230966/bb2eb586-9979-4fba-a832-eb1e31b1d39a)

The `drawing` add-on of `ezdxf` ignores the drawing extents and renders always a smooth spline by default:

![image](https://github.com/mozman/ezdxf/assets/4230966/a1275158-0fd8-4145-81e6-6fb855e1a481)

In this case you can zoom closer to the `SPLINE` by:

```python
from ezdxf import zoom

# snip -x-x-x-x-x

zoom.extents(msp)
doc.saveas("your.dxf")
```

This narrows the modelspace extents to the curve and the default view looks like this:

![image](https://github.com/mozman/ezdxf/assets/4230966/fe7e79db-65e5-498d-afa4-cbd8170532f4)

However, in general, you always need to use the `REGEN` command to get smoother curves.

**Comment by subsurfaceiodev** [comment]
Excellent as always, thanks @mozman
