### ISSUE TITLE
entity.dxf.invisible = 1 ignored / not exported

### ISSUE THREAD

**Issue by subsurfaceiodev** [mozman/ezdxf#1040]
**Describe the bug**
Setting entity.dxf.invisible = 1 is ignored when exported to dxf

**To Reproduce**
```python
import ezdxf

doc = ezdxf.new()
msp = doc.modelspace()

line = msp.add_lwpolyline(
    [(0, 0), (1, 1)]
)
line.dxf.invisible = 1

doc.saveas('mwe.dxf')

```

**Expected behavior**
Line should be hidden when viewing on modelspace in CAD software, when browsing dxf file using ezdxf browse tool group code 60 equal to 1 is not being exported.

**Screenshots**
![image](https://github.com/mozman/ezdxf/assets/109676812/2bfe438e-26e5-421d-a8cd-a3f30928d385)

**Comment by mozman** [comment]
Thank you!
