### ISSUE TITLE
Getting Bounding boxes of any entity

### ISSUE THREAD

**Issue by alison84r** [mozman/ezdxf#105]
Hello,
I want to know can we get the bounding boxes of any entity in DXF text, Block, Dimensions, MTEXT,
etc..
![image](https://user-images.githubusercontent.com/12997350/70998985-7f6f3d00-20fe-11ea-9f62-0326eddd43ea.png)
I have shown a image for reference. Where we are getting minimal corner and maximum corner we are getting when I select a text. 

Thanks In advance.

**Comment by mozman** [comment]
No!

**Comment by avinash-218** [comment]
from ezdxf import bbox

entity_box = bbox.extents([e])   # list of entity
