### ISSUE TITLE
Cannot read ACAD_TABLE in DXF 2004 Format

### ISSUE THREAD

**Issue by stefanodifrancesco** [mozman/ezdxf#1068]
**Describe the bug**
I'm encountering an issue when attempting to read the file "acad_table_simple.dxf" saved in DXF 2004 format. The output I'm getting is empty, as shown in the screenshot below:

<img width="212" alt="image" src="https://github.com/mozman/ezdxf/assets/8914928/db409e97-cd03-4a93-b0aa-9cc56c2cc26a">

**To Reproduce**
1. Open the file examples_dxf/acad_table_simple.dxf with AutoCAD and save it in DXF 2004 format.
2. Run the Python script "examples/entities/read_acad_table.py", ensuring to change the input to "acad_table_simple.dxf". The same happens for the file "acad_table_with_blk_ref.dxf".

**Expected behavior**
<img width="209" alt="image" src="https://github.com/mozman/ezdxf/assets/8914928/9f5da002-b24d-479e-abb5-cd38b9b385c6">

**Comment by mozman** [comment]
I guess you open the DXF file with AutoCAD and saved it as DXF R2004. 

The Problem: 
ACAD_TABLE requires at least DXF R2010. The exported table in a DXF R2004 file is not a ACAD_TABLE entity is just looks like that.

**Comment by stefanodifrancesco** [comment]
Thank you for your prompt response and for providing a fix. I have tested it with my DXF R2004 files and it works.
