### ISSUE TITLE
boundingbox calculation problem

### ISSUE THREAD

**Issue by yoriyouriri** [mozman/ezdxf#1078]
When I type the following content  in the Python 3 console：
```
    dxf_doc = ezdxf.readfile('F2-0511.dxf')
    msp = dxf_doc.modelspace()
    print(dxf_doc.header['$EXTMIN'] )
```
 i got:
```
    (173916.9636302038, 50395.78323825259, 0.0)
```
When I type the following content in the Python 3 console
```
    dxf_doc = ezdxf.readfile('F2-0511.dxf')
    msp = dxf_doc.modelspace()
    extents = bbox.extents(msp, fast=True)
    print(extents.extmin)
```
 i got:
`(173916.9636302038, -6375351396760.0, 0.0)`

i'm wondering why the values of `minY` from these two methods have so much big difference? 
minY from second method is a bit weird, i didn't find any entities in blank place?
[F2-0511.zip](https://github.com/mozman/ezdxf/files/15281640/F2-0511.zip)

**Comment by mozman** [comment]
I found the culprit: 
LWPOLYLINE(#4FAB) : extents=[(218919.631013219, -11249106.124038696, 0.0), (228890.52229157757, 11466017.639648438, 0.0)]

![image](https://github.com/mozman/ezdxf/assets/4230966/2c8bddd3-f7b1-4abc-ab86-29947075f3ee)

```python
POINTS = [(218969.6310157223, 112295.8227786999, 0.0, 0.0, 0.0),
 (218969.6310157223, 108455.6934995856, 0.0, 0.0, 0.0),
 (218969.6310145899, 108455.8221127223, 0.0, 0.0, 0.0),
 (218969.6310145899, 107355.6934995856, 0.0, 0.0, 0.0),  # <<<
 (218969.6310145899, 107355.6934995856, 0.0, 0.0, 0.0),  # <<< coincident point
 (218969.631013219, 105018.9770271163, 0.0, 0.0, -0.105069362517723),
 (226155.9223287149, 102073.9322948213, 0.0, 0.0, 0.0),
 (226679.8027970239, 102640.9121177326, 0.0, 0.0, 0.0),
 (226166.2477223321, 103115.4302806388, 0.0, 0.0, 0.0),
 (226709.1594593569, 103703.0070439484, 0.0, 0.0, 0.0),
 (227149.8281460448, 103295.8347999509, 0.0, 0.0, 0.0),
 (228720.5539262934, 104995.7833161484, 0.0, 0.0, 0.0),
 (228040.5130174204, 104995.7833161484, 0.0, 0.0, 0.0),
 (228040.5130174204, 105995.7831254135, 0.0, 0.0, 0.0),
 (228840.5221948667, 105995.7831254135, 0.0, 0.0, 0.0),
 (228840.5222903534, 109895.8227743711, 0.0, 0.0, 0.0),
 (228040.3895770951, 109895.8227743711, 0.0, 0.0, 0.0),
 (228040.5297859355, 112295.8227926101, 0.0, 0.0, 0.0)
 ]
```

The coincident point is a problem when the polyline has a constant width!

**Comment by mozman** [comment]
The new result: 

    expected $EXTMIN = (173916.9636302038, 50395.78323825259, 0.0))
    extents : [(173916.9636302038, 50395.78323825259, 0.0), (381937.5509118482, 175627.4375654887, 0.0)]

**Comment by yoriyouriri** [comment]
thank u for your reply, my problem has been solved!
but i've got two other files ,their values of  `extents.extmax` have something wrong. Is it caused by the same reason?
for F10-0513.dxf
```
expected $EXTMAX = (130905.7654143873, 189362.1346129119, 2.2807822e-09)
extents.extmax = (2322014.242823656, 189362.1346129119, 2.2807822e-09)
```
[F10-0513.zip](https://github.com/mozman/ezdxf/files/15288910/F10-0513.zip)

for F8-0511.dxf
```
expected $EXTMAX = (2143.043500423432, 46890.5798371546, 0.0)
extents.extmax = (98791.5755502141, 46890.57983715448, 0.0)
```
[F8-0511.zip](https://github.com/mozman/ezdxf/files/15288909/F8-0511.zip)

**Comment by yoriyouriri** [comment]
> thank u for your reply, my problem has been solved! but i've got two other files ,their values of `extents.extmax` have something wrong. Is it caused by the same reason? for F10-0513.dxf
> 
> `expected $EXTMAX = (130905.7654143873, 189362.1346129119, 2.2807822e-09)` i got `extents.extmax = (2322014.242823656, 189362.1346129119, 2.2807822e-09)`
> 
> [F10-0513.zip](https://github.com/mozman/ezdxf/files/15288910/F10-0513.zip)
> 
> for F8-0511.dxf
> 
> `expected $EXTMAX = (2143.043500423432, 46890.5798371546, 0.0)` i got `extents.extmax = (98791.5755502141, 46890.57983715448, 0.0)`
> 
> [F8-0511.zip](https://github.com/mozman/ezdxf/files/15288909/F8-0511.zip)

maybe it‘s not caused by the same reason, cause i've tried after i update ezdxf, there is nothing changed

**Comment by mozman** [comment]
These extents are caused by wrong information stored in the DXF file.

The bounding box calculation for TEXT and MEXT relys on the text-width information stored in the entities, because thus is much faster than rendering the text itself. 

 Sadly the information in DXF files is often not correct or exact like in these files. In this case the stored text-width is much too big:

    F10-0513.dxf: 
    MTEXT(#374) width: 2318597.618823946

![image](https://github.com/mozman/ezdxf/assets/4230966/80f08341-4326-42bd-84eb-d04b936449db)

    F8-0511.dxf:
    ...
    MTEXT(#165C) width: 101511.8675139806
    MTEXT(#165D) width: 101511.8675139806
    MTEXT(#165E) width: 101511.8675139806
 
   
![image](https://github.com/mozman/ezdxf/assets/4230966/69ec53cc-5819-43c6-a62a-a6824d20a001)

I don't want and will change the bounding box calculation for text entities - Python is already slow enough.

In your specific case you can exclude all text based entities - this will not work when these text-based entities are located in block references:
```python
    extents = bbox.extents(msp.query("* !TEXT !MTEXT"), fast=True)
```
![image](https://github.com/mozman/ezdxf/assets/4230966/5b21c842-2ce7-4b88-a40e-fc9e2799ffef)

![image](https://github.com/mozman/ezdxf/assets/4230966/b0dd554e-9c86-46e7-b41e-9982c8b7266c)

The extents of F10-0513.dxf still looks wrong, but there are entities on hidden layer "0":

![image](https://github.com/mozman/ezdxf/assets/4230966/012ff5eb-4096-4c49-b0a4-3cfbbc1f377a)


BTW: the information stored in HEADER variables like $EXTMIN and $EXTMAX are often not up to date - `ezdxf` doesn't update this information automatically.

```python
from ezdxf import appsettings, bbox

appsettings.update_extents(doc)   # updates extmin and extmax

# or manually:

extents = bbox.extents(msp, fast=True)
msp.reset_extents(extents.extmin, extents.extmax)

```

**Comment by yoriyouriri** [comment]
ok, i see, thanks for your detailed reply, it helps me a lot

**Comment by mozman** [comment]
## How to filter text-based entities included in nested block reference structures:

```python

def bbox_without_text_entities(msp):
    from ezdxf import disassemble, bbox, query

    # this explodes all INSERT entities (block references) recursively
    flat_entities = disassemble.recursive_decompose(msp)
    extents = bbox.extents(
        query.new(flat_entities, query="* !TEXT !MTEXT !ATTRIB"), fast=True
    )
    return extents

```

**Comment by yoriyouriri** [comment]
> ## How to filter text-based entities included in nested block reference structures:
> ```python
> def bbox_without_text_entities(msp):
>     from ezdxf import disassemble, bbox, query
> 
>     # this explodes all INSERT entities (block references) recursively
>     flat_entities = disassemble.recursive_decompose(msp)
>     extents = bbox.extents(
>         query.new(flat_entities, query="* !TEXT !MTEXT !ATTRIB"), fast=True
>     )
>     return extents
> ```

thank u , i will try this solution
