### ISSUE TITLE
ACI color question

### ISSUE THREAD

**Issue by liesauer** [mozman/ezdxf#108]
in  https://github.com/mozman/ezdxf/blob/7a5635584d7666a18b6fadfeecffbb2ab1ff1e06/ezdxf/lldxf/const.py#L158-L169

you defined white and black are `7`, but black should be `250`, at least in my autocad, it is `250`

**Comment by mozman** [comment]
ACI is just an Index and not a color, these constant values are used by AutoCAD by default to map the ACI to a display color, and shows WHITE on black (dark) background and BLACK on white (light) background.

And 250 is just black if you use the default plot style table `acad.ctb` any other plot style table can map 250 to any other color.

As I said ACI is not a color!

**Comment by liesauer** [comment]
i know ACI is not a color, i mean by default. it is no way to deal with the custom color table mapping,  i can only map to the default plot style table. so `7` is white on black background and black on white background, i see.
