### ISSUE TITLE
Error with bbox.extents()

### ISSUE THREAD

**Issue by yoriyouriri** [mozman/ezdxf#1081]
i'm trying get dxf bounds with bbox.extents():
```
dxf_doc = ezdxf.readfile('fd1.dxf')
msp = dxf_doc.modelspace()
extents = bbox.extents(msp, fast=True)
```
but i got error info like this:
![1715671759459](https://github.com/mozman/ezdxf/assets/56081362/37c02bce-a4ec-42f0-a5d3-48cecfa61567)

[fd1.zip](https://github.com/mozman/ezdxf/files/15304716/fd1.zip)

**Comment by mozman** [comment]
Hi!

You are working with very strange (crappy) DXF files. This one `fd1.dxf` is broken and AutoCAD cannot open it but BricsCAD can.

First you have to use the `ezdxf.recover` module to load such files:

```python
from ezdxf import recover, bbox

doc, auditor = recover.readfile("fd1.dxf")
if not auditor.has_errors:
    print(bbox.extents(doc.modelspace()))
```

This is the short version, read this how to load DXF files from unreliable sources: https://ezdxf.mozman.at/docs/drawing/recover.html

Sadly this doesn't help to load this file, it still contains invalid B-spline definitions which `ezdxf` can't handle.

**Comment by yoriyouriri** [comment]
ok, i see! 
there is another DXF file, and the error info is a little difference from above error, is it caused by the same reason?
![1715676950949](https://github.com/mozman/ezdxf/assets/56081362/b7a0d700-87b8-4c44-82eb-d920ee995db3)

btw, i've tried open it with AutoCAD 2022 successfully
[801.zip](https://github.com/mozman/ezdxf/files/15305900/801.zip)

**Comment by mozman** [comment]
`ezdxf` can now handle that file - fixes 1156 issues, mostly missing BLOCK definitions.

**Comment by mozman** [comment]
The file `801.dxf` only requires the `recover` module to open. (17 fixed issues)

**Comment by yoriyouriri** [comment]
thank u! i'll try
