### ISSUE TITLE
ZWCAD group

### ISSUE THREAD

**Issue by gswifort** [mozman/ezdxf#1085]
**Describe the bug**
Groups do not appear as groups in the ZWCAD, although they are visible in the group manager.
After executing the "AUDIT" command, I receive the following message: `AcDbGroup Entity (283) in group does not have group as persistent reactor Invalid Add persistent reactor`

**To Reproduce**
```python
import ezdxf

if __name__ == "__main__":

    doc = ezdxf.new()
    msp = doc.modelspace()

    l1 = msp.add_line((0, 0), (10, 10))
    l2 = msp.add_line((0, 10), (10, 0))

    doc.groups.new().set_data((l1, l2))

    doc.saveas("test.dxf")
```

**Comment by mozman** [comment]
If Autodesk Trueview (AutoCAD) gives no objection, it is DXF compliant. Trueview doesn't complain:

![image](https://github.com/mozman/ezdxf/assets/4230966/e74b2717-8ac8-4fe6-89ef-3799c433e2fc)

**Comment by gswifort** [comment]
That's right, the dxf object is valid. If I save the dxf in Autocad and open it in Zwcad, it works fine.

**Comment by mozman** [comment]
I reviewed the ´GROUP´ entity for adding reactors to entities. That shouldn't be that much work and the internal audit process of `ezdxf` already fix this issue 😁.
