### ISSUE TITLE
Issue with add_attrib

### ISSUE THREAD

**Issue by dweiss2** [mozman/ezdxf#110]
I'm trying to use the add_attrib method for blocks (instead of add_auto_blockref).  I've created a block with myblock = drawing.blocks.new(name="myblock") and then tried myblock.add_attrib("some_tag", "some text"). When I do this AutoCAD raises an error and aborts.

**Comment by mozman** [comment]
You have to attach the ATTRIB entity to a block reference (INSERT) not the block itself. To define a template attribute in the block add an ATTDEF entity, rtfm:

https://ezdxf.mozman.at/docs/tutorials/blocks.html
