### ISSUE TITLE
InvertedClippingPolygon2d.clip_polyline returns incorrect result

### ISSUE THREAD

**Issue by saschatimme** [mozman/ezdxf#1101]
I think the inverted clipping polygon routine does not work correctly.
Consider the following script

```python
import ezdxf
import ezdxf.math
from ezdxf.math.clipping import InvertedClippingPolygon2d


poly = [
    (4.1251, 261.58000000000004),
    (28.8749, 261.58000000000004),
    (28.8749, 393.14),
    (4.1251, 393.14),
    (4.1251, 261.58000000000004),
]
box = ezdxf.math.BoundingBox2d(
    [(0.6335999999999995, 5.2848, 0.0), (599.3664, 1008.890959916, 0.0)]
)

invertedClipping = InvertedClippingPolygon2d(ezdxf.math.Vec2.list(poly), box)

doc = ezdxf.new()
l = doc.modelspace().add_line(
    (12.119479999999951, 5.2848), (12.119479999999951, 1008.890959916)
)
print("to be clipped", ezdxf.math.Vec2(l.dxf.start), ezdxf.math.Vec2(l.dxf.end))
segments = invertedClipping.clip_line(
    ezdxf.math.Vec2(l.dxf.start), ezdxf.math.Vec2(l.dxf.end)
)
for segment in segments:
    print("Clipped segment:", segment)
```

This prints:

```
Clipped segment: (Vec2(12.119479999999951, 5.2848), Vec2(12.119479999999951, 1008.890959916))
Clipped segment: (Vec2(12.119479999999951, 261.58000000000004), Vec2(12.119479999999948, 393.14))
Clipped segment: (Vec2(12.119479999999943, 5.2848), Vec2(12.11947999999995, 1008.890959916))
```

which is incorrect.

However changing the x coordinate of the line to `12` results in 

```python
doc = ezdxf.new()
l = doc.modelspace().add_line(
    (12, 5.2848), (12, 1008.890959916)
)
print("to be clipped", ezdxf.math.Vec2(l.dxf.start), ezdxf.math.Vec2(l.dxf.end))
segments = invertedClipping.clip_line(
    ezdxf.math.Vec2(l.dxf.start), ezdxf.math.Vec2(l.dxf.end)
)
for segment in segments:
    print("Clipped segment:", segment)

```

Results in the basically correct result
```
Clipped segment: (Vec2(11.99999999999997, 5.2848), Vec2(12.0, 261.58000000000004))
Clipped segment: (Vec2(12.0, 393.14), Vec2(12.000000000000002, 1008.890959916))
```

**Comment by saschatimme** [comment]
The error also does not occur when I enlarge the boundary box

**Comment by saschatimme** [comment]
Looked a little bit more and the reason is that 
```

def polygon_line_intersections_2d(
    polygon: list[Vec2], line: tuple[Vec2, Vec2]
) -> list[Vec2]:
    """Returns all intersections of polygon with line.
    All intersections points are ordered from start to end of line.
    Start and end points are not included if not explicit intersection points.
```
returns points in the "wrong" order and this happens since the algorithm to compute intersection points introduces minor floating point errors. Notice the last digits of the x coordinates here
```
Clipped segment: (Vec2(12.119479999999951, 5.2848), Vec2(12.119479999999951, 1008.890959916))
Clipped segment: (Vec2(12.119479999999951, 261.58000000000004), Vec2(12.119479999999948, 393.14))
Clipped segment: (Vec2(12.119479999999943, 5.2848), Vec2(12.11947999999995, 1008.890959916))
```
And since the sorting algorithm is simply first by x and then by y coordinate this fails. The problem is here basically that this is a straight vertical line. In some sense an edge case, at the same time absolutely not an edge case.

I am getting reminded by the comments of my PhD advisor that you should never compute polygon stuff with floating point for this reason. But at the same time I totally understand also why you do it.

So this needs some sort of bandaid. My suggestion would be to do a less naive sorting algorithm in `polygon_line_intersections_2d`. Since you know all points are on a line you could for example sort the points by the distance to the start point

**Comment by mozman** [comment]
These classes have documentation, but it is not so complete that everyone can use it.

This function is used in the `drawing` add-on to clip viewports and block references with clipping paths and is tailored for that use. The outer bounds are stored in the entities as the bounding box of the content with extra space to avoid this problem.

Therefore, the outer bounds must be larger than the content. I will clarify that in the documentation.

**Comment by saschatimme** [comment]
But this was actually a red herring on my side. So even with larger boundaries, I have a case where the result is wrong in my code

**Comment by saschatimme** [comment]
First, thank you for the quick feedback. Forgot this previously :)

I tried to build a better reproducible case and noticed this

```
import ezdxf
import ezdxf.math
from ezdxf.math.clipping import InvertedClippingPolygon2d
import random

random.seed(0)


poly = [(400, 400), (400, 600), (600, 600), (600, 400), (400, 400)]
box = ezdxf.math.BoundingBox2d([(-10000, -10000), (10000, 10000)])

invertedClipping = InvertedClippingPolygon2d(ezdxf.math.Vec2.list(poly), box)

doc = ezdxf.new()
for x in range(100, 900, 10):
    doc.modelspace().add_line((x, 10), (x, 990))

for e in doc.modelspace().query("*"):
    print("to be clipped", ezdxf.math.Vec2(e.dxf.start), ezdxf.math.Vec2(e.dxf.end))
    segments = invertedClipping.clip_line(
        ezdxf.math.Vec2(e.dxf.start), ezdxf.math.Vec2(e.dxf.end)
    )
    if segments is not None and len(segments) > 0:
        doc.modelspace().delete_entity(e)
        for s in segments:
            doc.modelspace().add_line(s[0], s[1])

    print("clipped", segments)

doc.saveas("clipped_lines.dxf")
```

results in 

<img width="762" alt="Screenshot 2024-06-07 at 22 09 46" src="https://github.com/mozman/ezdxf/assets/4854317/1c71fedc-a5b6-45d8-8d6a-bccb6da460da">

My expectation would have been to have just an empty square in the middle. Am I misunderstanding the function?

**Comment by mozman** [comment]
Sorting the line segments by distance to start solves the fist issue:
![image](https://github.com/mozman/ezdxf/assets/4230966/dfd0db6a-ef75-4bcf-9b1a-fd67b45b4ae1)

But not the second, the algorithm in `polygon_line_intersections_2d()` seems to have a fundamental error.
![image](https://github.com/mozman/ezdxf/assets/4230966/e0c0f821-94bb-485e-b9f7-2ac400fc8bd4)

**Comment by mozman** [comment]
It is more complex.

I have a test in [665][1] for this case and it works:
```python
    def test_connection_line_create_intersection_point(self, inverted_polygon: ICP):
        """A line should be clipped at the diagonal connection line between 4<->0.
        There are two clipping lines 4->0 and 4<-0. The zero-length segment between the
        real segments should not be returned.
        """
        # 5  .|.|..|.|.
        # 4  .|.|..|.|.
        # 3  .|.0--1.|.
        # 2  axx=====xb
        # 1  .4------+.
        # 0  ..........
        #    0123456789
        result = inverted_polygon.clip_line(Vec2(0, 2), Vec2(9, 2))
        assert len(result) == 2
        l1, l2 = result
        assert l1[0].isclose((1, 2))
        assert l1[1].isclose((2, 2))
        # zero-length segment (2, 2) -> (2, 2) is ignored or outside!
        assert l2[0].isclose((2, 2))
        assert l2[1].isclose((8, 2))

```
![image](https://github.com/mozman/ezdxf/assets/4230966/ece21cc3-eb83-4aaa-b971-595a7a9f9bb8)

[1]: https://github.com/mozman/ezdxf/blob/master/tests/test_06_math/test_665_inverted_clipping_polygon.py
