### ISSUE TITLE
How to Get Dimension type

### ISSUE THREAD

**Issue by alison84r** [mozman/ezdxf#111]
I am not able get the dimension type.
Could you please help me out.
![image](https://user-images.githubusercontent.com/12997350/72223945-6e4d0b00-359a-11ea-9bdf-82e7fdffae3c.png)

In the above code I am getting always value as 160. 
Am I doing anything wrong in getting the dimension type ?

Thanks in advance

**Comment by mozman** [comment]
https://ezdxf.mozman.at/docs/dxfentities/dimension.html#ezdxf.entities.Dimension.dimtype
