### ISSUE TITLE
add_hatch --> predefined pattern error

### ISSUE THREAD

**Issue by wingtgniw** [mozman/ezdxf#1115]
**Describe the bug**
In the dxf file I created using set_pattern_fill with name="CTYSQST" and scale=1.0 as parameters, there is a description of the pattern in the description box, but it appears solid in the viewer.

it looked like a pattern made with JIS_LC_20A at a scale of about 0.25.

**Screenshots**

![image](https://github.com/mozman/ezdxf/assets/53434687/f043bb3a-22d3-4a8a-93e7-fcf2f9ac1fa7)

![image](https://github.com/mozman/ezdxf/assets/53434687/b169a833-9a3e-446b-ba08-a8811853bd3d)

**Comment by mozman** [comment]
The pattern `CTYSQST` is not included in the pre-defined patterns of `ezdxf`, so YOU have to provide the pattern-definition and this includes also the scaling.

Tutorial for loading HATCH pattern from a `.pat` file: https://ezdxf.mozman.at/docs/tutorials/hatch.html#load-hatch-patterns-from-file

**Comment by wingtgniw** [comment]
It is my mistake. Check predefined hatch patterns.
