### ISSUE TITLE
the arrow of diameter dimension is not as expected

### ISSUE THREAD

**Issue by Jimyzzp** [mozman/ezdxf#1126]
the arrow is not as expected

![image](https://github.com/user-attachments/assets/3c38d882-b383-46ae-b457-427aca7ddd55)

**Comment by mozman** [comment]
this error report is not as expected :smile:

**Comment by mozman** [comment]
This is a border case, and I will not fix this. If you need better results you have to use a proper CAD application.

**Comment by Jimyzzp** [comment]
thanks！I know how to render the arrow now.
Set the property "dimension_renderer" of Drawing object, implement my custom render class.
