### ISSUE TITLE
add_linear_dim raises DXFTableEntryError if dxf is exported from autocad

### ISSUE THREAD

**Issue by liesauer** [mozman/ezdxf#113]
default `dimstyle` of `add_linear_dim` is `EZDXF`, this dimstyle only exists in who is created by ezdxf, if my dxf is exported from autocad or any other software, this method always raises `DXFTableEntryError` if i don't has a explicit `dimstyle` parameter like `standard`(seems every dxf has `standard` dimstyle)

**Comment by liesauer** [comment]
i think using default `STANDARD` `dimstyle` instead may be better.

**Comment by mozman** [comment]
Dimstyle EZDXF is defined if you use `ezdxf.new(setup=True)`, else set dimstyle name by argument:
`msp.add_linear_dim(..., dimstyle='STANDARD')`.
