### ISSUE TITLE
LWPOLYLINE in R14 (AC1014) mode

### ISSUE THREAD

**Issue by iromero91** [mozman/ezdxf#114]
Hi. I am dealing with some old laser cutter control software that has major issues reading files newer than R14. I have managed to generate files that work there when using the `AC1015` mode. Unfortunately the library does not let me add LWPOLYLINE entities when in that mode. I am pretty sure LWPOLYLINEs were part of R14. I made some modifications to the library to change the minimum version for LWPOLYLINEs to DXF14 and that actually worked. Would you be opposed to such a patch?

**Comment by mozman** [comment]
Sorry R13/R14 is a "bastard" version of DXF, ezdxf convert this version to DXF R2000 automatically, you can only save DXF R12 or DXF R2000 and later. For your problem of "can't add LWPOLYLINE to AC1015", I need example code and a test DXF file.

**Comment by iromero91** [comment]
While [this patch](https://github.com/mozman/ezdxf/files/4072703/r14_lwpolyline.patch.txt) works for me(tm) I understand your rationale for not supporting R14. I think I can try retooling my code to use R12 instead but i need some way of converting LWPOLYLINEs into polylines. I haven't found an obvious way to do it for polylines containing arcs (bulge !=0)

**Comment by mozman** [comment]
But if this works, your cutter software seems to open R2000 files, because ezdxf can not and does not write R13/R14 files, really 😀

**Comment by iromero91** [comment]
Actually. if i run the exact same code, with the file version set to AC1015 the file will not open. And the files produced are indeed different. see attached. test_AC1015.dxf will not open.
[test_AC101x.zip](https://github.com/mozman/ezdxf/files/4074339/test_AC101x.zip)

**Comment by mozman** [comment]
You created test_AC1014.dxf with ezdxf and your applied patch?

Autodesk TrueView 2020 does not open test_AC1014.dxf (not a valid DXF file!), BricsCAD shows the file, ezdxf (0.11) loads the file and convert it to AC1015, but can't save it: missing handle error.

You found a loophole, I do not check for supported DXF version in new, which i will fix, so stick your used ezdxf version in requirements.txt or extend you patch ;) or use DXF12 with POLYLINE, using bulge values is shown below.

Append vertices with bulge to POLYLINE:

    p = msp.add_polyline2d([])
    p.append_vertex((x, y), dxfattribs={'bulge': 0.5})

or do it afterwards:

    p = msp.add_polyline2d([p0, p1, p2])
    p.vertices[0].dxf.bulge = 0.5

**Comment by iromero91** [comment]
Thanks again for the very detailed help! I was suspecting that AC1014 was not valid, but it appears the broken chinese laser software reads that bastard file just right. I will try the POLYLINE + R12 solution tomorrow. Hopefully it works so I don't have to maintain that ugly patch.

**Comment by mozman** [comment]
An another idea is to try replacing 'AC1015' by 'AC1014' and look if your cutter software accepts this hack:

```python
FILE1 = 'test_AC1015.dxf'
FILE2 = 'test_AC1014.dxf'

with open(FILE1) as fp:
    s = fp.read().replace('AC1015', 'AC1014')
    
with open(FILE2, mode='wt') as fp:
    fp.write(s)
```
If the software is not that picky like AutoCAD and ignores all unknown tags and entities, this could work. BricsCAD opens this fake R14 file, TrueView of course doesn't. 

I assume you are not using none ASCII characters in this simple cutter files.

**Comment by mozman** [comment]
Added user defined point format support to `add_polyline2d()`, like for `add_lwpolyline()`.

    p = msp.add_polyline2d([(1, 2, .5), (3, 4, 0)], format='xyb')

Or you can append formatted points to an existing polyline:

    p.append_formatted_vertices([(1, 2, .5), (3, 4, 0)], format='xyb')

I wrote some tests, but real world testing would be fine.

If you are brave you can test the alpha version of ezdxf 0.11a2: `pip install ezdxf==0.11a2`

**Comment by iromero91** [comment]
The new add_polyline2d with formatting worked perfectly! thanks!
