### ISSUE TITLE
odafc installation path is not returned correct 

### ISSUE THREAD

**Issue by rahulverma24497** [mozman/ezdxf#1146]
I noticed recently that odafc.win_exec_path is not returning correct path due to which odafc.is_installed() method is also failing and returning False even if ODA File Converter is installed on my windows machine. The main problem is ODA version is not being shown in returned path. 
Suppose my ODA installation path is- "C:\Program Files\ODA\ODAFileConverter 25.5.0\ODAFileConverter.exe"
But what odafc.win_exec_path returns is "C:\Program Files\ODA\ODAFileConverter\ODAFileConverter.exe"

Kindly fix this...

**Comment by mozman** [comment]
You have to create a [config](https://ezdxf.mozman.at/docs/options.html#config-files) file. The default location doesn't work any more and `ezdxf` has no sophisticated function to find the executable.
