### ISSUE TITLE
I didn't do anything, but the dimension was changed.

### ISSUE THREAD

**Issue by xbdr419** [mozman/ezdxf#1147]
**Describe the bug**
Read the file and save it directly as a new document，
In the saved new.dxf document, the text position changed when I adjusted the dimension
I don't see this in the original file, so I suspect something was changed when I saved it.

Looking forward to fixing this and keeping it the same as the original file.

**code**
```
f = 'test.dxf'
doc = ezdxf.readfile(f)
doc.saveas('new.dxf')
```
**video**

https://github.com/user-attachments/assets/d18dbab9-0451-44f0-a50c-cf1539316b48

**test file**
[test.zip](https://github.com/user-attachments/files/16634148/test.zip)

**Comment by mozman** [comment]
This is AutoCAD specific behavior and you have to know which DIM variable controls this specific behavior. I don't know it and there is no official or complete documentation of all DIM variables.

**Comment by xbdr419** [comment]
![image](https://github.com/user-attachments/assets/8f3617a5-94ef-4a31-962f-84d828ab50b6)

![image](https://github.com/user-attachments/assets/d475ba11-ba17-479b-848e-32cc8b02b06e)

Thanks，according to your tips, I found these parameters in the exported new.dxf,  as shown：
the standard is the modified style, and the parameters in [样式替换] are the original style, 
I change the parameters in standard to the parameters in [样式替换], and it's normal.
so, That should be the problem.

**Comment by xbdr419** [comment]
Will this be fixed please?
