### ISSUE TITLE
wrong units

### ISSUE THREAD

**Issue by danielmtzz** [mozman/ezdxf#115]
I'm opening this simple file in eDrawings Pro, but it is reading the diameter of the entity in mm instead of inches. The diameter should be 0.050''. Any ideas as to why this is the case?

`import ezdxf

doc = ezdxf.new()
doc.header['$INSUNITS']=1
doc.header['$MEASUREMENT'] = 0
msp = doc.modelspace()
msp.add_lwpolyline([(1.077,1.3155,1),(1.127,1.3155,1)],format='xyb',dxfattribs={'closed':1})
doc.saveas('test.dxf')`

![Capture](https://user-images.githubusercontent.com/34920524/72670478-b7beaf80-3a0b-11ea-9d8e-26792617b50b.PNG)

**Comment by mozman** [comment]
According to the DXF reference for [header variables](http://help.autodesk.com/view/OARX/2018/ENU/?guid=GUID-A85E8E67-27CD-4C59-BE61-4DC9FADBE74A) you have set the correct values, I can't provide anymore information about this topic. It may help to ask this question on stackoverflow, the user "Lee Mac" has a very deep understanding for such DXF details.

**Comment by mozman** [comment]
I did a test with BricsCAD which shows inches as measurement:

![inches](https://user-images.githubusercontent.com/4230966/72675069-59331900-3a7f-11ea-8874-fb7bac16137b.png)


This seems to be a problem which varies from application to application, maybe it helps to set `msp.block_record.dxf.units = 1`, and it is always a good practice to use simple values for such tests:

```python
# diameter = 1, radius = 0.5
msp.add_lwpolyline([(-0.5, 0, 1), (0.5, 0, 1)], format='xyb', dxfattribs={'closed': 1})
doc.set_modelspace_vport(1)

# the layout attribute block_record.dxf.units is '0' (unit less) by default,
# maybe setting to '1' helps.
msp.block_record.dxf.units = 1
```

**Comment by danielmtzz** [comment]
I get an error when I try to run the line `doc.set_modelspace_vport(1)
`


`>>> doc.set_modelspace_vport(1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Drawing' object has no attribute 'set_modelspace_vport'`

`msp.block_record.dxf.units = 1` ran just fine, but this still does not fix my problem with eDrawings.

When I open the file with CamBam+ the units are correct. Exporting a new dxf from CamBam+ and opening it in eDrawings works, but this is not ideal.

**Comment by mozman** [comment]
Sorry, `set_modelspace_vport()` works only in v0.11   which is in development stage.

Last resort: stackoverflow!

**Comment by mozman** [comment]
[DXF header variables reference](http://help.autodesk.com/view/OARX/2018/ENU/?guid=GUID-A85E8E67-27CD-4C59-BE61-4DC9FADBE74A) provided by Autodesk

`$LUNITS`:  Units format for coordinates and distances ?

If you find a solution, please post a comment here.
