### ISSUE TITLE
Do you have an example of the dxfpp and how to use it?

### ISSUE THREAD

**Issue by jjccvt** [mozman/ezdxf#116]
I need to print a dxf model in html for a web based website and it needs to show the drawing in a html page.

**Comment by mozman** [comment]
dxfpp does not render the drawing, it just generates a pretty html of the DXF code:

![image](https://user-images.githubusercontent.com/4230966/72697558-97444180-3b40-11ea-8d38-b4e007edabb8.png)

**Comment by jjccvt** [comment]
Hi, Thanks for the response. I just wanted to ask aswell, I have been looking how to pull a blocks attibutes etc and the insertion points do you have an example of how to do thi? ThanksJean Sent from Mail for Windows 10 From: Manfred MoitziSent: Monday, 20 January 2020 05:53To: mozman/ezdxfCc: jjccvt; AuthorSubject: Re: [mozman/ezdxf] Do you have an example of the dxfpp and how to use it? (#116) dxfpp does not render the drawing, it just generates a pretty html of the DXF code:—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by mozman** [comment]
https://ezdxf.mozman.at/docs/tutorials/blocks.html
