### ISSUE TITLE
Evaluating close points (vector)

### ISSUE THREAD

**Issue by ikwtif** [mozman/ezdxf#118]
Would it be possible to get a function to check for points/vectors to be close to each other where it is possible to check the different axis based on different tolerances?

https://github.com/mozman/ezdxf/blob/af767d852398261eec2db9f19fa1211363c7f435/src/ezdxf/math/vector.py#L311

The reason I ask is because I want to make an "inventory" of parts of a dxf. The drawing is a detail of a section of a concrete beam, with the information for the rebars containing it. The issue here is properly evaluating what number is supposed to be related to what text. 

- 1 2%%C20                      relates to 461
- 2 2%%C20                      relates to 461 and 27
- 3 bgl%%C8 alle 12cm    relates to 8 and 28

[example image](https://i.imgur.com/MMEqgHm.png)

**Comment by mozman** [comment]
This is a very application specific problem, you have to handle this problem by yourself, make new vector class by inheriting from `Vector()` or make your own comparison function.
