### ISSUE TITLE
``Insert.add_auto_attribs`` breaks multi-line attributes.

### ISSUE THREAD

**Issue by gswifort** [mozman/ezdxf#1191]
**Describe the bug**
I have defined a block with a multi-line attribute. After inserting a reference to the block and calling ``.add_auto_attribs()`` the multi-line attributes change to single-line.

**To Reproduce**
Version1.3.4
```py
import ezdxf


def main():
    doc = ezdxf.readfile("test.dxf")
    print(doc.dxfversion)  # AC1032
    msp = doc.modelspace()
    obj = msp.add_blockref("TEST", (0, 0))
    obj.add_auto_attribs({"ATTR": "10"})
    doc.saveas("test2.dxf")


if __name__ == "__main__":
    main()

```

**Screenshots**
- test.dxf
![image](https://github.com/user-attachments/assets/ee8c26ab-bd24-46ff-8812-5e8122855008)
- test2.dxf
![image](https://github.com/user-attachments/assets/ca1d6020-8ed0-4f0e-851d-3e6256e52923)

**Comment by mozman** [comment]
... because multi-line ATTRIBS are not supported.

**Comment by mozman** [comment]
This [example](https://github.com/mozman/ezdxf/blob/master/examples/blocks/insert_with_mtext_attrib.py) shows how to add multi-line ATTRIBS, but without "auto" features.

**Comment by gswifort** [comment]
Thank you!
