### ISSUE TITLE
reading/writing dxf file error

### ISSUE THREAD

**Issue by ikwtif** [mozman/ezdxf#120]
I was trying to read and write a dxf and found a bug, not sure if it's a known bug or if it's an error of mine.

I have a dxf where one of the layouts has text and lines drawn on the actual layout space (see image), which causes an issue when I try to open the dxf after adding a line. Deleting the contents in the layout tab the error doesn't happen and I can just open the file with the created line.

Opening the file afterwards doesn't show any errors besides "press enter to continue" and just loads an empty new dwg file. The file is basically completely broken at that point.

```
file_test = 'test.dxf'
doc = ezdxf.readfile(file_test, encoding='AC1027')
msp = doc.modelspace()
msp.add_line((0, 0), (10, 0), dxfattribs={'linetype':'Continuous', 'layer':'0'})
doc.saveas('test.dxf')
```

![image](https://user-images.githubusercontent.com/20071958/73480591-71b60400-439a-11ea-91d4-7d4fb5729a23.png)

**Comment by mozman** [comment]
`encoding='AC1027'`  is not a Python character encoding setting! DON'T use the `encoding` argument except you really know you need it!

**Comment by mozman** [comment]
Found the bug and fixed it!

**Comment by mozman** [comment]
Bugfix release v0.10.4 is available
