### ISSUE TITLE
having problem with invalid dxfstructure handling

### ISSUE THREAD

**Issue by sunggiyoon** [mozman/ezdxf#122]
when ezdxf.readfile('mygile.dxf') executed,
process failed with exit code 1.

I figured out when theres a empty line in dxf file, exdxf.lldxf.tagger.low_level_tagger() raise invalid DXFStructureError().

my dxf file coverted from .dwg file format by AutoCad 2020, has a lot of empty entities.

Like this
     $DIMBLK2
        1
  
       9 
As you see, between 1 and 9, theres a empty line and I think it causes an error.

Could you tell me how can I set default value when process encounter empty line when reading dxf rather than raising error?

thx.

**Comment by mozman** [comment]
This is a valid construct in the HEADER section, $DIMBLK2 is an empty string (= default closed filled arrow), this can  not cause the error. Please attach your DXF file for more information.

**Comment by sunggiyoon** [comment]
Unfortunately, due to company's security policy, it is impossible to attach my dxf files here.
However, now it works properly. What I did was changing my environment. I changed the  interpreter from python 3.8.1 to 3.7.6

**Comment by mozman** [comment]
To be clear, the reason is your (messy) environment, ezdxf works with CPython 3.6, 3.7 and 3.8 without any conditional branches depending on the used Python version.
