### ISSUE TITLE
Question about dynamic blocks

### ISSUE THREAD

**Issue by yidingfan** [mozman/ezdxf#125]
Hi there,
I just found out that I can not read the information in the dynamic block which are defined in AutoCAD. Is this supported by ezdxf? Or I just missed the way of doing it?

Thanks

**Comment by mozman** [comment]
No, I don't even know what dynamics blocks are, implementation details are not documented in the DXF reference.

**Comment by rurban** [comment]
DXF objectnames in the wild are: DYNBLOCKREF, ATTDYNBLOCKREF
I also haven't found out yet their structure.

**Comment by mozman** [comment]
I work with BricsCAD and BricsCAD loads dynamic blocks but can't create them, so I will not waste my time with that feature yet, maybe in the future.
