### ISSUE TITLE
[Feature] Add ATTDEF helper function for blocks

### ISSUE THREAD

**Issue by hjkatz** [mozman/ezdxf#13]
The statement "All ATTDEFS on BLOCKS will appear as ATTRIBS on INSERTS in a DXF file." is incorrect.

Unfortunately, "constant" defined ATTDEFS are **not** written as ATTRIBS on the INSERT. There is an op-code (70) for ATTDEF/ATTRIB flags where this can be checked:

- 1 = Attribute is invisible (does not appear).
- **2 = This is a constant attribute.**
- 4 = Verification is required on input of this attribute.
- 8 = Attribute is preset (no prompt during insertion).

This can lead to the situation where one might want to select attribute text from the BLOCK rather than the INSERT. What are your thoughts on adding the following features?

- Add `block.get_attrib_text(tag, default=None)` function similar to `insert.get_attrib_text()`.
- Add op-code 70 as a new tag to ATTDEF and ATTRIB entities.

If you like these solutions, then I will create a pull request with the changes. Thanks!

--Katz

**Comment by mozman** [comment]
Hi!

Tag-code 70 is already defined as Attrib/Attdef.dxf.flags

I would prefer an integrated solution like Insert.get_attrib(tag, const=True) to include constant attdefs from the block definition, but because this behavior requires a search through the block definition, this should not be the default behavior.

- get_attrib(tag, const=False)
- get_attrib_text(tag, const=False)
- has_attrib(tag, const=False)

Added changes to the develop branch.

What do you think?

Manfred

**Comment by hjkatz** [comment]
Why not both? You're going to need to get that information from the block anyways. But, even if you just want only the methods on the Insert, then I think you should change the 'search_const' param to something like 'include_attdefs'. The problem is you're actually returning the set of ATTDEFs not ATTRIBs anymore. Or, maybe all are needed?

- `Block.get_attdef(tag, default=None)`
- `Block.get_attdef_text(tag, default=None)`
- `Block.has_attdef(tag)`
- `Insert.get_attdef(tag, default=None)`
- `Insert.get_attdef_text(tag, default=None)`
- `Insert.has_attdef(tag)`

I'm just not sure that the constant flag is the only way of not copying an ATTDEF to an ATTRIB. And, anyways, there aren't methods for retrieving information about the ATTDEFs from a Block or Insert right now. I think adding those would be best.

**Comment by mozman** [comment]
ATTDEFs do not belong to the INSERT entity (except this wired const thing), there is already an ATTDEF generator function at the BLOCK entity (for attdef in block.attdefs()) and for const ATTRIBSs, I added a get_const_attdefs() generator.

Only Insert.attribs() returns a 'set' of ATTRIB entities, and this behavior is not changed, because ATTDEF do not belong to the INSERT entity.

get_attrib() just returns the requested ATTRIB, and now, if you set 'search_const=True', the ATTDEF for const ATTRIBS, but only if there is not an ATTRIB, for the requested tag, attached. If you ignore the additional dxfattribs of ATTDEF they are the same as ATTRIB.

There is no clear key word for this strange behavior, not 'search_const' nor 'include_attdefs'.

**Comment by hjkatz** [comment]
The additional ATTDEFs on the Block are not the same as the ATTRIBs on the Insert. They might have the same tag, but not the same text or defaults. I would think that being able to work with the ATTDEF on the Block level the same as working with ATTRIB on the Insert level would be good to have. But, it's your call. :)

I'm going to mark this as closed because your solution solves my use-case. Let me know when you release a new version. Thanks, again!

**Comment by mozman** [comment]
To clarify:

1. Block with ATTDEF(tag='a', flags=not const) -> INSERT + ATTRIB(tag='a')

2. Block with ATTDEF(tag='a', flags=const) -> INSERT + no ATTRIB

In case 1 the INSERT entity gets an append ATTRIB, in case 2 (const ATTRIB) the INSERT gets no appended ATTRIB.

Case 1 Insert.get_attrib('a') returns the appended ATTRIB entity, in case 2 Insert.get_attrib('a') return the ATTDEF from the block definition. (if 'search_const'=True)

Is this the behavior of AutoCAD? I just use TrueView, I can not replay these cases in AutoCAD.

**Comment by hjkatz** [comment]
The behaviour from autocad implies this, but it's actually a specification of the DXF. All ATTDEFs should be represented as ATTRIBs on the Insert, except for those that are constants.

I'm saying that separate from working with ATTRIBs through the Insert, it would be nice to have similar functions for working with ATTDEFs through the Block (since they behave so similarly).

Currently, you have:

- `Insert.attribs()`
- `Insert.get_attrib()`
- `Insert.has_attrib()`
- `Insert.get_attrib_text()`

But there are no corresponding functions for the Block, such as:

- `Block.attdefs()`
- `Block.get_attdef()`
- `Block.has_attdef()`
- `Block.get_attdef_text()`

I think adding those functions would be helpful.

P.S. I'm not sure why, but assuming I have `insert.dxf.name` defined, what is the difference between:
- `block = drawing.blocks[insert.dxf.name]`?
- `block.block`?

`block.attdefs()` exists, but not `block.block.attdefs()`. Why are some functions on the first block and not the second?

**Comment by mozman** [comment]
> ..., but it's actually a specification of the DXF. All ATTDEFs should be represented as ATTRIBs on the Insert, except for those that are constants.

From where do you get this information, I don't find this in the official DXF specification, have you link?

With `block = drawing.blocks[insert.dxf.name]` you get a BlockLayout, which provides all the add_... methods. `block.block` is the BLOCK entity itself, block.endblk is the ENDBLK entity.

Why do you need all these methods for managing ATTDEFs, as far as I understand ATTDEF - you create it and you forget it, or just use block.attdefs() to iterate over all ATTDEFs.

**Comment by hjkatz** [comment]
1. Sorry, I can't seem to find it in the DXF reference either. Here's a link to a forum about the issue though: https://forums.autodesk.com/t5/visual-lisp-autolisp-and-general/help-with-dxf-block-insert-attdef-attrib/td-p/895795 

2. Ah, ok. That makes sense, thanks.

3. You're assuming that I always want to iterate over the ATTDEFs. Sometimes I just want to select 1. It's really just a couple of wrapper methods. Perhaps someone wants the default value from an ATTDEF to use as text?

**Comment by mozman** [comment]
released v0.8.1

  * NEW: added support for constant ATTRIB/ATTDEF to the INSERT (block reference) entity
  * NEW: added ATTDEF management methods to BlockLayout (has_attdef, get_attdef, get_attdef_text)
  * NEW: added (read/write) properties to ATTDEF/ATTRIB for setting flags (is_const, is_invisible, is_verify, is_preset)

**Comment by hjkatz** [comment]
Thanks for being awesome!
