### ISSUE TITLE
Start and end width does not work

### ISSUE THREAD

**Issue by vaschthestampede** [mozman/ezdxf#130]
Hi!
I'm using the 0.11.1

The code that i'm using is this:
```
doc = ezdxf.new('R2000')
msp = doc.modelspace()
# point format = (x, y, [start_width, [end_width, [bulge]]])
# set start_width, end_width to 0 to be ignored (x, y, 0, 0, bulge).
points = [(0, 0, 0, .05), (3, 0, .1, .2, -.5), (6, 0, .1, .05), (9, 0)]
msp.add_lwpolyline(points)
doc.saveas("lwpolyline5.dxf")
```
It's the code from ezdxf Documentation Release 0.11.1b3 , Tutorials 4.2
 page 19.

The polyline in the dxf does not have start and width.
[lwpolyline5.zip](https://github.com/mozman/ezdxf/files/4319499/lwpolyline5.zip)

I apologize in advance if it turns out to be a trivial mistake of mine.

**Comment by mozman** [comment]
Thank you, found the bug, LWPOLYLINE was always exported with const_width=0.
