### ISSUE TITLE
ezdxf '0.11.1' : AttributeError: 'Insert' object has no attribute 'dxf' when using __str__

### ISSUE THREAD

**Issue by FenryrMKIII** [mozman/ezdxf#133]
I am trying to use the __str__ method of a _ezdxf.entities.insert.Insert object_.

When calling, the method, the code returns an error when executing : 

```
"{}(#{})".format(self.dxftype(), self.dxf.handle)
AttributeError: 'Insert' object has no attribute 'dxf'
```

As this is an implemented method, I guess there is an error in the code ?

**Comment by mozman** [comment]
The absence of the `dxf` attribute shows a destroyed (deleted) entity. Need more context!

**Comment by FenryrMKIII** [comment]
> The absence of the `dxf` attribute shows a destroyed (deleted) entity. Need more context!

Indeed, the entity was destroyed. Closing.
