### ISSUE TITLE
Method get_layout works in 0.9 but not in 0.11.1

### ISSUE THREAD

**Issue by FenryrMKIII** [mozman/ezdxf#136]
Using the method `get_layout` on a `ezdxf.layout.modern.layout.BlockLayout` works fine in version _0.9_.

Trying to use the same method on a `ezdxf.layout.blocklayout.BlockLayout `in version _0.11.1_ results in an error altough I understand this new object is the equivalent of previous one. 

Can someone help me figure out what is wrong ?

**Comment by mozman** [comment]
I can't find `BlockLayout.get_layout()` in the old sources, what should this method do?

**Comment by FenryrMKIII** [comment]
Apparently, this was a method a co-worker added on our side. Sorry, closing the issue.
