### ISSUE TITLE
Image import flags

### ISSUE THREAD

**Issue by ololomp** [mozman/ezdxf#14]
Hello! You've done a great module, thank you.  
Is it possible to add two or more flags when importing image or any other object type?
Image.dxf.flags has four possible flags - IMAGE_SHOW (1), IMAGE_SHOW_WHEN_NOT_ALIGNED (2), IMAGE_USE_CLIPPING_BOUNDARY (4) and IMAGE_TRANSPARENCY_IS_ON(8)

When I use flag IMAGE_TRANSPARENCY_IS_ON(8) the transparensy is on but the image disappears. I suppose it turns off  IMAGE_SHOW (1) flag

If it is applicable, I could help you with documentation, for example, tutorials

**Comment by mozman** [comment]
To set 2 flags you have to binary OR them FLAG1 | FLAG2, in this case you can also just ADD them FLAG1+FLAG2.

**Comment by ololomp** [comment]
Thanks for your answer! 
then modelspace.add_image (  image_parameters, dxfattribs={'flags':8|1} ) works perfect
