### ISSUE TITLE
Exception getting layer description

### ISSUE THREAD

**Issue by mbway** [mozman/ezdxf#148]
I have a cad file which causes a crash when I try to obtain the description of some of it's layers
```python
import sys
import ezdxf
from ezdxf import DXFKeyError

def main():
    doc = ezdxf.readfile(sys.argv[1])
    print(doc.acad_release)
    print(doc.dxfversion)
    print('---------------------------')
    for name, layer in doc.layers.entries.items():
        print('name:', name)
        try:
            print('description:', layer.description)
        except DXFKeyError:
            print('no description')
        print()

if __name__ == '__main__':
    main()
```
about half the layers raise the key error:
```
R2018
AC1032
---------------------------
name: "0"
description: ""

name: "1"
no description

... (and so on)
```

```
Traceback (most recent call last):
  File "/home/matthew/bug_report.py", line 18, in <module>
    main()
  File "/home/matthew/bug_report.py", line 13, in main
    print('description:', layer.description)
  File "/home/matthew/anaconda3/envs/physical_map_processing/lib/python3.8/site-packages/ezdxf/entities/layer.py", line 173, in description
    xdata = self.get_xdata(AcAecLayerStandard)
  File "/home/matthew/anaconda3/envs/physical_map_processing/lib/python3.8/site-packages/ezdxf/entities/dxfentity.py", line 949, in get_xdata
    return Tags(self.xdata.get(appid)[1:])
  File "/home/matthew/anaconda3/envs/physical_map_processing/lib/python3.8/site-packages/ezdxf/entities/xdata.py", line 52, in get
    raise DXFKeyError(appid)
ezdxf.lldxf.const.DXFKeyError: 'AcAecLayerStandard'
```
in `Layer.description()`, `DXFValueError` is caught and "" is returned. Should the `DXFKeyError` also be caught and result in a description of "" rather than crashing?

**Comment by mozman** [comment]
This is a bug, raising wrong exception `DXFKeyError` instead of  `DXFValueError`, will be fixed in the next release v0.12.2.

**Comment by mbway** [comment]
There is another unrelated crash with a different cad file trying to obtain the layer descriptions:
```
File "/home/matthew/anaconda3/envs/physical_map_processing/lib/python3.8/site-packages/ezdxf/entities/layer.py", line 177, in description
    return xdata[1].value
IndexError: list index out of range
```
the value of xdata during the crash is: `[DXFTag(1000, '')]`

**Comment by mozman** [comment]
Layer description is an undocumented feature. I used BricsCAD to get the required information, maybe AutoCAD writes different XDATA content, can you provide the DXF file?

**Comment by mozman** [comment]
No or just one tag in XDATA `AcAecLayerStandard` returning an empty string now.

**Comment by mbway** [comment]
does that mean you have fixed the issue? I'm not sure what program was used to create the cad files but I can say that multiple of them have the same issue where xdata contains only one element.

**Comment by mozman** [comment]
Fixed in the meaning of not raising an exception, but you also get just an empty string as description.

Did a test with BricsCAD and TrueView: I removed the the first empty string in XDATA, both apps open the modified DXF file without complaining, but also both do not show the layer description, so I think my fix behaves like BricsCAD and AutoCAD.
