### ISSUE TITLE
new insert with `.dxf.attribs_follow ==1` fails on .add_attribute

### ISSUE THREAD

**Issue by vlcinsky** [mozman/ezdxf#15]
Steps to reproduce:

- create a block
- insert the block and set `.dxf.attribs_follow=1` (either via dxfattribs or later explicitly `.dxf.attribs_follow=1`)
- try `insert.add_attrib(....)`

`add_attrib` fails on attempt to get last of attributes which are at the moment none. see [graphics.pyL537](https://github.com/mozman/ezdxf/blob/master/ezdxf/legacy/graphics.py#L537)

## Proposed solution
There are few places, where it could be affected, not sure, which one is the proper one:
- creation of insert shall ignore `attribs_follow` value in `dxfattribs` and keep it `0`.
- call to `_append_attrib_entity` shall handle empty list of attributes

## Workaround

When creating new insert, always ensure, the `attribus_follow` is kept in default value `0` even when planning adding some attributes.

**Comment by mozman** [comment]
The attribs_follow property is well managed by ezdxf and this case is clearly a misuse of attribs_follow ;), but I added a bugfix to make ezdxf more robust. And by this occasion I added delete_attrib() and delete_all_attribs() to the Insert() class.

Thank you for your bug report.

Best regards,
Manfred

**Comment by vlcinsky** [comment]
Wow. Fix and release within 7 hours. Really impressive. Apart from providing such an excellent package. Thanks a lot.

To explain my `.attribs_follow`: this is result of more general attempt to create copy of an existing entity. Instead of setting up one dxf property by one, I took dxfattribs from the original insert and passed it into creating function. I think, such an approach might fail in many more cases, as there may happen conflicts as assigning a handle, which already exists, defining a block definition which is already present etc.

Trying to fix such scenarios on library level might be quite difficult, even though in many cases it can be fixed by entity type defined set of dxf attributes, which shall be ignored if passed by dxfattribs argument. Ignoring could be silent or might issue a warning.

For the time being I will know, I shall think hard when creating new copy and do not rely on "one solution fits all situations" approach.

Regarding the `attribs_follow`: this is clearly a corner case. As I planned to create a block reference with variable attributes being present, I would think of `attribs_follow` being required to be `1` and was surprised by the fact, your code is keeping `attribs_follow` as entity lifecycle flag (what seems to be legitimate approach but is not obvious at the first moment).

Thanks for the quick fix and realease.
