### ISSUE TITLE
dxf.header['$EXTMAX'] differs from what AutoCAD 2020 

### ISSUE THREAD

**Issue by ilovetogetspamed** [mozman/ezdxf#153]
When I issue Command: EXTMAX in AutoCAD 2020 I get:
```EXTMAX = 9.4089,8.6257,0.0000 (read only)```

When I issue it in the Python 3 console i get:

 ```
>>> dxf.header['$EXTMAX']
(48.0, 48.0)
```

using the attached file  (AutoCAD Release 12 DXF file).
[cc1-plasma.zip](https://github.com/mozman/ezdxf/files/4553391/cc1-plasma.zip)

When I import it into my plasma cutter software I get the image at the AutoCAD generated dimensions.

Is there any other way to get the extents from your Python module?

**Comment by mozman** [comment]
No, the header vars are not maintained by ezdxf, for more information look at this [stackoverflow question](https://stackoverflow.com/questions/53517480/finding-the-size-of-a-dxf-file-using-ezdxf-python/53568570#53568570).

And the values you get for your example files, are exact the values written in the DXF header:
![image](https://user-images.githubusercontent.com/4230966/80667949-cdc71c00-8aa0-11ea-9c62-0de4e9c4b89f.png)

**Comment by ilovetogetspamed** [comment]
Thanks for the explanation.  Case closed ;-)
