### ISSUE TITLE
export order of embedded objects and xdata

### ISSUE THREAD

**Issue by vshu3000** [mozman/ezdxf#155]
I have a case when both embedded_objects and xdata present, AutoCAD refuses to open saved file.  I was able to get it to work by switching the order of embedded objects and xdata.

```
index 2d35d68..33959f0 100644
--- a/src/ezdxf/entities/dxfentity.py
+++ b/src/ezdxf/entities/dxfentity.py
@@ -795,8 +795,8 @@ class DXFEntity:
 
         # ! Last step !
         # write xdata, embedded objects
-        self.export_xdata(tagwriter)
         self.export_embedded_objects(tagwriter)
+        self.export_xdata(tagwriter)
```

IMHO AutoCAD is being too picky on this.

Please email wdong@wdong.org for test data if this description alone is not convincing enough.

**Comment by mozman** [comment]
This was a clear bug in ezdxf, thank you!
