### ISSUE TITLE
incorrect ellipse parameters

### ISSUE THREAD

**Issue by vshu3000** [mozman/ezdxf#157]
It seems to me sometimes the ellipse parameters, mainly start and end angles, are incorrect when insert is involved.  It's hard for me to explain so I've included a self-contained minimal test case. 

In this case, OpenCV is used to draw images (`pip install cv2`).  Only Ellipse and Insert are handled.  The rendered image is different from what I see from a CAD software (correct.png).

[submit.zip](https://github.com/mozman/ezdxf/files/4606967/submit.zip)

**Comment by mozman** [comment]
Hi!

1. Is `arc.dxf` created by ezdxf? Invalid DXF for TrueView but accepted by BricsCAD
2. Check the extrusion vector, if different to (0, 0, 1) you have to use an OCS for ARC, and ELLIPSE is an 3D entity all angles are around then extrusion vector.

**Comment by vshu3000** [comment]
The problem went away after I fixed my misunderstanding of the angles and after updating to the newest version.

Thanks!
