### ISSUE TITLE
AttributeError: 'Block' object has no attribute 'doc' when calling saveas method

### ISSUE THREAD

**Issue by FenryrMKIII** [mozman/ezdxf#159]
I have an `ezdxf.drawing.Drawing`. When calling `saveas` method, I receive the following error : 

`
AttributeError: 'Block' object has no attribute 'doc'
`

which is raised by  the method `export_base_class` of `dxfentity.py`

The error occurs on an ezdxf object of type `ezdxf.entities.block.Block object` and I am using ezdxf version `0.11.1`

Any idea what can go wrong ?

**Comment by mozman** [comment]
Not enough information.

**Comment by FenryrMKIII** [comment]
> Not enough information.

Hello,

What can I give you as additional information to try to track down the issue ?

**Comment by mozman** [comment]
Create a simple example script which reproduces the error.

**Comment by mozman** [comment]
I guess you are dealing with an deleted block definition, because you are deleting the block definition not by calling the public interface `doc.blocks.delete_block()`.

**Comment by FenryrMKIII** [comment]
> I guess you are dealing with an deleted block definition, because you are deleting the block definition not by calling the public interface `doc.blocks.delete_block()`.

Here is a simple script that reproduces the issue : 

`
import ezdxf
from pathlib import Path

dwg = ezdxf.readfile(Path(r'path\to\myfile.dxf'))
dwg.blocks.delete_block('block_name', safe=False)
`

this produces the following error : 
`'NoneType' object has no attribute 'dxf'` in file `entitydb.py`  at line 106 : 

`del self[entity.dxf.handle]`

in method `delete_entity`

**Comment by FenryrMKIII** [comment]
It seems this comes from the fact that `self.seqend` is None. This could be corrected by applying `self.new_seqend()` but I don't see this method being applied in my case

**Comment by mozman** [comment]
Deleting a BLOCK definition from a loaded file (as shown above) works as expected in the actual version v0.12.

Maybe your input DXF file is corrupt.

**Comment by FenryrMKIII** [comment]
Moving to 0.12.2 seems to solve the problem

**Comment by sharpuser** [comment]
# Create a new DXF drawing
drawing = dxf.drawing("sample.dxf")

# Add two blocks, each with 10 pins
for i in range(2):
    block = dxf.Block("block" + str(i + 1))
    block.add(dxf.Rectangle((0, 0), 10, 5))
    for j in range(10):
        block.add(dxf.Text("Pin " + str(j), (j, 2.5)))
    drawing.blocks.add(block)
    drawing.add(dxf.Insert(block.name, (10 * i, 0)))

# Save the DXF file
drawing.save()
 produce same error(AttributeError: type object 'DXFEngine' has no attribute 'Block')

**Comment by mozman** [comment]
This is the `ezdxf` package not `dxfwrite` !

This is the way to create blocks in `ezdxf`: https://ezdxf.mozman.at/docs/tutorials/blocks.html
