### ISSUE TITLE
Attribute entities placed on the wrong layer

### ISSUE THREAD

**Issue by mbway** [mozman/ezdxf#160]
If I create a block and place an attribute definition on a particular layer, ezdxf ignores this and places all ATTDEF and ATTRIB entities on layer 0.

For example the following:
![image](https://user-images.githubusercontent.com/4923501/81813291-2e356f00-951f-11ea-8284-a3dd76cb502b.png)
[attribute_block_1.dxf.zip](https://github.com/mozman/ezdxf/files/4621971/attribute_block_1.dxf.zip)

```python
import sys
import ezdxf

def main():
    doc = ezdxf.readfile(sys.argv[1])
    attrib = doc.blocks['BLOCK'].entity_space[1]
    print(attrib, attrib.dxf.layer)
    line = doc.blocks['BLOCK'].entity_space[0]
    print(line, line.dxf.layer)
    insert = list(doc.query('INSERT[layer=="INSERT_LAYER"]'))[0]
    print(insert, insert.dxf.layer)
    print(insert.attribs[0], insert.attribs[0].dxf.layer)
    line = list(insert.virtual_entities())[0]
    print(line, line.dxf.layer)

if __name__ == '__main__':
    main()
```
outputs
```
ATTDEF(#22B) 0
LWPOLYLINE(#226) BLOCK_OUTLINE
INSERT(#237) INSERT_LAYER
ATTRIB(#238) 0
LWPOLYLINE(#None) BLOCK_OUTLINE
```

**Comment by mozman** [comment]
Misunderstanding of using `super()` for skipping parent classes.

**Comment by mozman** [comment]
Hi!

The 'transform' branch is ready for testing, the example
"exploding_block_references.py" works:

Scaled Blocks:

[image: scaled_blocks.png]

Exploded by ezdxf:
[image: exploded.png]
The exploded text is not perfect equal to the scaled blocks version, but
close enough and oblique text angle transformation may not work for
arbitrary OCS (TEXT in 3D space), but for most use cases (extrusion=(0, 0,
1) or (0, 0, -1)) it is good enough.

Mirrored text in 2D seems also to work, first letter is different (1, 2, 3,
4):

[image: reflexions.png]
Not every combination of transformations will work perfectly, but at least
simple transformations without reflexions should work as expected, like the
deprecated transform_to_ucs() method.

Best regards,
Manfred



Am Mi., 13. Mai 2020 um 14:43 Uhr schrieb Matt Broadway <
notifications@github.com>:
