### ISSUE TITLE
Error: APP DATA can not be nested?

### ISSUE THREAD

**Issue by hschmiedhofer** [mozman/ezdxf#161]
Hi there, I was just trying to use ezdxf for parsing a DXF file written by CAD-T, which is basically an add-on for AutoCAD 2016.

~~~python
import ezdxf
doc = ezdxf.readfile("./dxf/UBT660_001.dxf")
~~~

However, I keep getting a 

`ezdxf.lldxf.const.DXFAppDataError: Invalid APP DATA structure in entity XRECORD(#4E6F), APP DATA can not be nested.`

Is this a known error? Can it be circumvented?

Greetings from Vienna,
Heinz

**Comment by mozman** [comment]
No this is not a known error and also an unknown and maybe undocumented usage of APPDATA, maybe you can post the DXF file (zipped).

**Comment by hschmiedhofer** [comment]
Ok, is it possible to send it via email? The DXF contains some confidential client info. BTW, i succeeded to load it with a legacy version (0.8.0).

**Comment by mozman** [comment]
Bitte gezippt an ezdxf@mozman.at senden, Danke.

**Comment by mozman** [comment]
v0.8.0 hat intern mit dem aktuellen Stand nicht mehr viel gemeinsam.

**Comment by mozman** [comment]
Beta release [v0.12.4b0](https://pypi.org/project/ezdxf/0.12.4b0/) should fix this issue.
