### ISSUE TITLE
dxf2code doesn't work if I open the file in Autodesk

### ISSUE THREAD

**Issue by RoeeMeshulam** [mozman/ezdxf#164]
Hello,
I'm using the dxf2code addon and when I'm converting my dxf to code and then run the code to create new dxf, the new dxf won't open in Autodesk products (but it does open on ABViewer 14).
Just to note that the original dxf do open on Autodesk with no problems.
The error I get on Autodesk:
`The following error was encountered while reading in ATTRIB starting at line 16684:
Invalid DXF data.
Invalid or incomplete DXF input -- drawing discarded.`

Thank you for your help.

**Comment by mozman** [comment]
This seems to be a missing text style or line type.

This is an very advanced feature, which should help to create a quick starting point for your code, but it is is probably not the right tool for you, if you don't know which additional work is required to create valid DXF files.
