### ISSUE TITLE
spline approximation error

### ISSUE THREAD

**Issue by mbway** [mozman/ezdxf#167]
the method `BSpline.approximate()` sometimes returns `Vector(0, 0, 0)` as one of the points which is incorrect.
This can be seen in the result of rendering the hatches_2.dxf example in the drawing addon:
![hatches2](https://user-images.githubusercontent.com/4923501/85210540-83dc1300-b338-11ea-89e5-7f05624f2029.png)

**Comment by mozman** [comment]
OK, this are really uncommon knot values, not starting a 0.0 instead at  `[2.825276861104652, 2.825276861104652, 2.825276861104652, 2.825276861104652, 8.585563484895022, 22.932710645602....`, I don't know if this is valid, but the solution is to just normalize such knot vectors as NURBS-Python does.

![hatches_2](https://user-images.githubusercontent.com/4230966/85219297-cf2b0b80-b3a2-11ea-85fc-fbbd557500ce.png)

**Comment by goatchurchprime** [comment]
For anyone who hits this issue, the need to shift the knot values to start at 0 got fixed by version 0.16 (March 2021), so now it evaluates points in the range `[ knots[order - 1],  knots[count] ]`
