### ISSUE TITLE
some DIMENSION entities do not have the type Dimension

### ISSUE THREAD

**Issue by mbway** [mozman/ezdxf#168]
when rendering the uncommon.dxf example from the drawing add-on, some entities are encountered which have the dxftype DIMENSION but which are not an instance of the ezdxf Dimension type (and so does not have a `virtual_entities` method):
```
entitiy has DIMENSION dfxtype but it not a dimension: LARGE_RADIAL_DIMENSION, <class 'ezdxf.entities.dxfentity.DXFTagStorage'>
```
is this because ezdxf does not understand this dimension type?

**Comment by mozman** [comment]
This is an undocumented DXF type, but there is a documentation in the ODA DWG documentation, 
 so support for this entity can be added, maybe.
