### ISSUE TITLE
some arcs and text entities don't seem to be transformed correctly

### ISSUE THREAD

**Issue by mbway** [mozman/ezdxf#169]
when drawing the floor plan dxf obtained from this website (and many others, but this is a freely available example of the problem):
https://cadkit.blogspot.com/p/sample-dxf-files.html

some arc entities do not appear in their correct locations or with the correct angles.
![floorplan](https://user-images.githubusercontent.com/4923501/85210764-9f481d80-b33a-11ea-9725-cadc71390382.png)

Another example is the example dxf I posted in https://github.com/mozman/ezdxf/pull/154
here, some text is also placed in the wrong locations
![rotated_and_scaled_arcs](https://user-images.githubusercontent.com/4923501/85210681-f8fc1800-b339-11ea-9490-4271a54d1de6.png)

I don't think the rendering is at fault, because, when using the cad_viewer to list the entity properties, the 'center' coordinates of the ellipses and the 'insert' coordinates of the text on the left (which are exactly what is provided by ezdxf) are incorrect and the renderer seems to be being faithful to those coordinates.

**Comment by mozman** [comment]
If I explode the blocks of the DXF file "'rotated_and_scaled_arcs.dxf"

```Python
doc = ezdxf.readfile(DATA_DIR / 'rotated_and_scaled_arcs.dxf')
msp = doc.modelspace()

for e in msp.query('INSERT[name=="ARC"]'):
    insert = cast('Insert', e)
    insert.explode()

doc.saveas(OUTBOX / 'exploded_rotated_and_scaled_arcs.dxf')
```
I got this with the latest ezdxf version and no other entities outside this area:

![image](https://user-images.githubusercontent.com/4230966/85219450-1fef3400-b3a4-11ea-827a-e2d56daf78a5.png)

If I do the same with "CADKitSamples\Floor plan.dxf" I got this:

![image](https://user-images.githubusercontent.com/4230966/85219570-4eb9da00-b3a5-11ea-9444-195f5ac55b41.png)

It seem to be an OCS transformation error in your front end, I will try to find it.

**Comment by mozman** [comment]
Added OCS transformation for arcs and circles, other entity types with OCS are: TEXT, HATCH, ATTRIB, TRACE, LWPOLYLINE and POLYLINE if 2D and need coordinate transformations if extrusion != (0, 0, 1).

**Comment by mbway** [comment]
ok. That's really useful to know. These issues have been lingering for a while. At some point I will look into creating a dxf file which has examples of all these entities requiring conversion to wcs to make sure the front end is behaving correctly.
I quickly tried applying this fix to text entities and it is definitely better than before, but the placements are still slightly wrong. I will look into this another time.
also, although the arcs are now placed in the correct locations, the draw angles are still wrong, so more work on the front end is required. Thanks for pointing me in the right direction.
![arcs](https://user-images.githubusercontent.com/4923501/85221712-07841700-b3ae-11ea-801b-4da43bca79fd.png)

**Comment by mozman** [comment]
The start- and endpoint properties of the Arc class return this points in
WCS, maybe it is easier to get reqired backend values from the WCS center
and this end points.

Matt Broadway <notifications@github.com> schrieb am So., 21. Juni 2020,
11:58:
