### ISSUE TITLE
plain text not removing all control codes

### ISSUE THREAD

**Issue by mbway** [mozman/ezdxf#170]
`mtext.plain_text()` does not seem to remove all control codes found in various CAD files. I've found some CAD files which have `^M^J` or `^J` used to denote a newline character, and the floorplan.dxf available [here](https://cadkit.blogspot.com/p/sample-dxf-files.html) has `%%u` control codes and I'm not sure what purpose these serve.

`^M^J` is a [standard notation](https://en.wikipedia.org/wiki/Caret_notation) but I don't know how the dxf file format distinguishes between these control codes and genuine caret characters.

I don't know if the `%%` control codes are standardized or documented anywhere, but it would be nice to be able to remove them. The `ezdxf.addons.drawing.utils.remove_formatting()` function replaces the `^M^J` and `^J` control codes, but I'm sure there are others that I'm unaware of.

on a related note, some CAD files appear to have control codes in Attrib entities so perhaps a plain_text method should be added to this class as well?

**Comment by mozman** [comment]
`%%u` underline formatting, until next `%%u` or until end of line.

Applying `plain_text()` to the TEXT entity in `drawing.text._get_plain_text()` will remove this code.

**Comment by mozman** [comment]
Can you show me an example file for `^M^J` am `^J` content?

**Comment by mbway** [comment]
I can have a look on Monday. I probably won't be able to give the whole files but I'll try to remove everything except for the text objects in question

**Comment by mozman** [comment]
I don't need the example files anymore, the problem should be solved, but
some tests with real word files would be good (cad_viewer.py).

Best regards,
Manfred

Am Fr., 26. Juni 2020 um 12:18 Uhr schrieb Matt Broadway <
notifications@github.com>:

**Comment by mbway** [comment]
I can't seem to find any Instances of this problem anymore. I did definitely see ^M^J in some rendered images before, and replacing ^M^J with a newline did fix it. Perhaps this was a bug with some other component and the text reported by ezdxf was correct. I did find literal '^M^J' instances when grepping through some DXF files but I couldn't find an instance where they were in the middle of a string. It was just part of some XML data for defining material properties I think

**Comment by mbway** [comment]
I found an example file which contains ^J characters instead of newlines. the ^J characters appear directly in the dxf file when opened in a text editor.

To reproduce:
- create a dwg file in AutoCAD web
- add an MTEXT element with a newline
- convert the dwg to a dxf using ODAFileConverter

the resulting dxf will have ^J characters rather than newline characters

dwg and dxf files:
[newline_test.zip](https://github.com/mozman/ezdxf/files/4845877/newline_test.zip)

![Screenshot from 2020-06-29 14-47-56](https://user-images.githubusercontent.com/4923501/86013881-8e249e00-ba17-11ea-9d5b-a435133b01c9.png)

(after removing `normalize_line_breaks()`)
![cad_viewer](https://user-images.githubusercontent.com/4923501/86014027-b9a78880-ba17-11ea-8ac7-a7f1f621a06d.png)

**Comment by mbway** [comment]
I did a bit more investigating, and it looks like genuine caret characters are encoded as `^ ` (that is, a caret followed by a space).
I wasn't able to copy a null byte into my browser but I was able to copy a tab character in, which did get encoded as `^I` so I assume that all of these characters would get encoded as well https://en.wikipedia.org/wiki/C0_and_C1_control_codes

[caret_notation.zip](https://github.com/mozman/ezdxf/files/4846024/caret_notation.zip)

![Screenshot from 2020-06-29 15-13-06](https://user-images.githubusercontent.com/4923501/86016715-1193be80-ba1b-11ea-84ff-c0bbf26201af.png)

the text isn't on a single line due to word wrapping
![Screenshot from 2020-06-29 15-13-01](https://user-images.githubusercontent.com/4923501/86016721-12c4eb80-ba1b-11ea-86ad-eb2b1b2e8b2a.png)

I created another file in AutoCAD and exported as dxf (so ODAFileConverter is not involved at all) and although the newlines weren't stored as ^J, the tab and caret characters were encoded the same which means I think the dxf format does use caret encoding for some special characters and it's not just a bug in ODAFileConverter
[cad_mtext.dxf.zip](https://github.com/mozman/ezdxf/files/4846112/cad_mtext.dxf.zip)
![image (2)](https://user-images.githubusercontent.com/4923501/86018536-6a645680-ba1d-11ea-8756-a3d3760ffee6.png)
![Screenshot from 2020-06-29 15-29-37](https://user-images.githubusercontent.com/4923501/86018549-6df7dd80-ba1d-11ea-8d7b-f8fd4fdc2627.png)
