### ISSUE TITLE
Set coordinate system projection

### ISSUE THREAD

**Issue by vaschthestampede** [mozman/ezdxf#173]
It's possible to set the model pace coordinate system projection?

Attached is a DXF file with only the model pace coordinate system projection set.

[Con sistema di coordinate.zip](https://github.com/mozman/ezdxf/files/4820157/Con.sistema.di.coordinate.zip)

**Comment by jmacura** [comment]
Yes, it is possible for newer DXF versions, see GeoData entity: https://ezdxf.mozman.at/docs/dxfobjects/geodata.html

(My AutoCAD Map 3D reports that your drawing is in UTM84-32N system, so ezdxf should report same)

**Comment by vaschthestampede** [comment]
I don't know if this is the correct way but it seams to work.

`doc = ezdxf.new(dxfversion='R2010',setup=True)`
`msp = doc.modelspace()`
`geodata = msp.new_geodata()`
`geodata.coordinate_system_definition = 'PROJCS["WGS 84 / UTM zone 32N",GEOGCS["WGS 84",DATUM["WGS_1984",SPHEROID["WGS 84",6378137,298.257223563,AUTHORITY["EPSG","7030"]],AUTHORITY["EPSG","6326"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],AUTHORITY["EPSG","4326"]],PROJECTION["Transverse_Mercator"],PARAMETER["latitude_of_origin",0],PARAMETER["central_meridian",9],PARAMETER["scale_factor",0.9996],PARAMETER["false_easting",500000],PARAMETER["false_northing",0],UNIT["metre",1,AUTHORITY["EPSG","9001"]],AXIS["Easting",EAST],AXIS["Northing",NORTH],AUTHORITY["EPSG","32632"]]'`

You can find the string after the `geodata.coordinate_system_definition` in site like https://epsg.io/32632 under "Export" -> "OGC WKT".

I hope this will be helpful.
