### ISSUE TITLE
HATCH clockwise arc and ellipse edge angles are weird

### ISSUE THREAD

**Issue by mozman** [mozman/ezdxf#175]
This creates a pie-hatch by a counter-clockwise arc:

```python
hatch = msp.add_hatch(color=1)
ep = hatch.paths.add_edge_path()
ep.add_line((0, 0), (1, 0))
ep.add_arc(
    center=(0, 0),
    radius=1,
    start_angle=0,
    end_angle=90,
    ccw=True,
)
ep.add_line((0, 1), (0, 0))
```
 And this creates the same hatch with a clockwise arc:
```python
hatch = msp.add_hatch(color=1)
ep = hatch.paths.add_edge_path()
ep.add_line((0, 0), (0, 1))
ep.add_arc(
    center=(0, 0),
    radius=1,
    start_angle=270,  # 360 - 90
    end_angle=360,  # 360 - 0
    ccw=False,
)
ep.add_line((1, 0), (0, 0))
```
The angles seem to be complement angles (360-angle) and this is also valid for ellipse edges.

Scripts to create test files are located [here](https://github.com/mozman/ezdxf/tree/master/issues/20200630%20hatch-curves).

If this is the correct way to define clockwise oriented curves, the rotation transformation is also incorrect.

Testing for extrusion != (0, 0, 1) has to be done too.

**Comment by mozman** [comment]
The DXF format stores the clockwise oriented start- and end angles for HATCH arc- and ellipse edges as complementary angle (360.0 - angle). This is a problem in many ways for processing clockwise oriented angles correct, especially rotation transformation won't work. Actual solution: convert clockwise angles into counter-clockwise angles and swap start- and end angle at loading from and exporting to DXF file.

This solution works at least for 2D rendering and transformation, this covers a big part of the real world usage of hatches, but has to be tested for 3D hatches (extrusion != 0, 0, 1) too.

**Comment by mozman** [comment]
First tests with 3D hatches and clockwise arc- and ellipse edges look good, in TrueView and with cad_viewer.py.

![image](https://user-images.githubusercontent.com/4230966/86227508-635c5600-bb8d-11ea-87d1-2fd1a1cba897.png)

![image](https://user-images.githubusercontent.com/4230966/86227631-9999d580-bb8d-11ea-92f7-6291d0728380.png)

**Comment by Jens-G** [comment]
> complementary angles (360.0 - angle).

Late to the party, but I wonder if this is anywhere officially documented? Even [the current DXF manual](https://help.autodesk.com/view/OARX/2018/ENU/?guid=GUID-DC5215D6-E73F-4DFF-8BE9-01CA9610FAEE) still says simply

<html>
<body>


Group code | Description
-- | --
50 | Start angle
51 | End angle


</body>
</html>

**Comment by mozman** [comment]
There's no official documentation on this, but it works until someone proves otherwise with an example.
