### ISSUE TITLE
Missing function get_rotation_direction_from_extrusion_vector in utils.py

### ISSUE THREAD

**Issue by Salmck** [mozman/ezdxf#176]
I installed ezdxf version 0.13 recently and I got error when I import draw_layout from ezdxf.addons.drawing.front_end.
![image](https://user-images.githubusercontent.com/22630892/86518218-68a5f300-be62-11ea-9832-47eef4b08cad.png)
I opened front_end.py and found a function named normalize_angle. By replacing normalise_angle to normalize_angle, I fixed this error. Run the same code again, I got another error.
![image](https://user-images.githubusercontent.com/22630892/86518325-8fb0f480-be63-11ea-85de-0d4aa5e9577d.png)
There is no function named get_rotation_direction_from_extrusion_vector in utils.py

**Comment by mozman** [comment]
Are you sure you are using 0.13 because front_end.py was renamed into frontend.py long ago. This looks like a broken installation, we do very much testing, such errors should be detected.

**Comment by Salmck** [comment]
Yep, I installed ezdxf version 0.13 by pip installing twice and no error occur when install.
I downloaded the source code and install, I fixed the problems.
Thanks for your reply!

**Comment by Salmck** [comment]
some code in https://ezdxf.readthedocs.io/en/stable/ seems out-of-date.
![image](https://user-images.githubusercontent.com/22630892/86526031-5909c700-bec1-11ea-83e4-503ec837e108.png)

**Comment by mozman** [comment]
Yes, docs are outdated, I will fix it, meanwhile look at the correct example: https://github.com/mozman/ezdxf/blob/master/examples/addons/drawing/draw_cad.py

**Comment by Salmck** [comment]
ok, thanks a lot!
