### ISSUE TITLE
found ENDSEC tag without previous SECTION tag

### ISSUE THREAD

**Issue by bluehenry** [mozman/ezdxf#179]
Hello, 

I want to read a dxf (version: AC1009) like the following. However, got 'ezdxf.lldxf.const.DXFStructureError: DXFStructureError: found ENDSEC tag without previous SECTION tag.' 

I checked out the SECTION and ENDSEC and they look good. I can view the dxf from https://viewer.autodesk.com/ correctly.

`
import ezdxf
doc = ezdxf.readfile("test.dxf")
`

Attached dxf in here.
[test.zip](https://github.com/mozman/ezdxf/files/4911403/test.zip)

Could you please take a look? Thanks!

Regards,
Henry

**Comment by mozman** [comment]
An really annoying bug, the SECTION tag has an trailing white space like "SECTION "!

**Comment by bluehenry** [comment]
Thanks @mozman .Really appreciated.

**Comment by bluehenry** [comment]
Hi @mozman, 

Just one more question, I can get the polyline in the above dxf like the following code. But how do I get the line color? Thanks!

`
import ezdxf
from ezdxf import DXFStructureError

try:
    doc = ezdxf.readfile("w3b1-0552-3250-PP-20200621.dxf")
    msp = doc.modelspace()
    polylines = msp.query('POLYLINE')
    for polyline in polylines:
        print('Polyline #{}'.format(polyline.dxf.handle))
        for i, location in enumerate(polyline.points()):
            print('Point at index {}: {}'.format(i, location))
except DXFStructureError as error:
    print(error)
`

Regards
Henry
