### ISSUE TITLE
Exception when drawing block which does not exist

### ISSUE THREAD

**Issue by mbway** [mozman/ezdxf#183]
the `DXFStructureError` exception needs to be caught somewhere in the frontend so that the case of a missing block can be handled rather than crashing

```
Traceback (most recent call last):
  File "find_ezdxf_crashes.py", line 54, in _draw_dxf_file
    Frontend(ctx, out).draw_layout(layout)
  File "/home/matthew/src/ezdxf_upstream/src/ezdxf/addons/drawing/frontend.py", line 71, in draw_layout
    self.draw_entities(layout)
  File "/home/matthew/src/ezdxf_upstream/src/ezdxf/addons/drawing/frontend.py", line 88, in draw_entities
    self.draw_entity(entity)
  File "/home/matthew/src/ezdxf_upstream/src/ezdxf/addons/drawing/frontend.py", line 115, in draw_entity
    self.draw_composite_entity(entity)
  File "/home/matthew/src/ezdxf_upstream/src/ezdxf/addons/drawing/frontend.py", line 311, in draw_composite_entity
    self.draw_entities(entity.virtual_entities())
  File "/home/matthew/src/ezdxf_upstream/src/ezdxf/addons/drawing/frontend.py", line 77, in draw_entities
    for entity in entities:
  File "/home/matthew/src/ezdxf_upstream/src/ezdxf/explode.py", line 170, in virtual_block_reference_entities
    raise DXFStructureError(f'Required block definition for "{block_ref.dxf.name}" does not exist.')

```

**Comment by mozman** [comment]
But a block reference to BLOCK which do not exists `IS` a DXF structure error. It's an invalid DXF file.

**Comment by mbway** [comment]
yes, but either the drawing fails and you have no output, or the error is optionally ignored which allows the drawing to complete so you have some output at the end. I require the drawing to be as fault tolerant as possible but I appreciate that you might not want this to be the default behaviour. I think the frontend should be able to choose to continue processing when it encounters an error which is not fatal.

**Comment by mbway** [comment]
since a lot of errors like this one often surround the calls to virtual_entities, how about wrapping it in a method of the front end like:
```
class FrontEnd:
  ...
    def virtual_entities(entity):
        return entity.virtual_entities()
```
So that the user can choose to override this method if they want to do eager evaluation and recover from errors?

**Comment by mozman** [comment]
1. Yes, I could add this, but only as an temporary fix, I can't fix the problems if I don't get feedback
2. try&catch `DXFStructureError()` is an option, there is no obligation to process invalid or crappy DXF files
3. call `doc.audit()` or `doc.validate()` before rendering to find & fix errors, I will add additional fixers to remove errors which are hard to manage inside of  `Frontend()`

**Comment by mbway** [comment]
ok. I did not know about the auditing functionality. That should hopefully deal with the kinds of errors I'm worried about.

**Comment by mbway** [comment]
is the auditing process supposed to fix this error currently? I'm still having crashes of the form `DXFStructureError(f'Required block definition for "{block_ref.dxf.name}" does not exist.')` after auditing

**Comment by mozman** [comment]
Yes this should be solved, but there is always a special case: INSERT is also used to insert XREFS and XREF_OVERLAYS, added an extra check for xrefs, but noticed now that this is unnecessary complex, because each xrefs has an empty block and could be handled as any usual empty block.

**Comment by mbway** [comment]
those changes seem to have fixed the problem. I no longer see any `does not exist` errors
