### ISSUE TITLE
Javascript/Node 

### ISSUE THREAD

**Issue by pranavramkrishnan** [mozman/ezdxf#196]
This such a fantastic repo, and I've learnt a lot about DXF concepts while using this module- thanks!

I am trying to evaluate how to use this mode from a node.js application - we essentially want to read/modify/write DXF files. 

Any pointers of known/good node modules you might be aware of? Thanks in advance!

**Comment by mozman** [comment]
Sorry, I don't use js/node.js regularly, therefore I on't know any DXF libraries for this eco-system.

**Comment by pranavramkrishnan** [comment]
Thanks!
