### ISSUE TITLE
AttributeError: entities

### ISSUE THREAD

**Issue by bitorbit** [mozman/ezdxf#20]
I get this error when using ezdxf.read() with stream from google cloud storage:

AttributeError: entities
/lib/ezdxf/sections/sections.py:69

ezdxf.readfile() working fine with same file (when not using google cloud storage).

Update: looks like this is fixed by removing CR characters from DXF files. Is it possible to support DXF files which are using CRLF as EOL?

**Comment by mozman** [comment]
ezdxf supports CRLF.

ezdxf uses the standard python readline() method of the given stream. The open command
should return a stream which has just a '\r' as line ending.

ezdxf.readfile() uses the io.open function, which works fine with the local file system.

ezdxf.read() accepts any stream open by the user, but take care of the file encoding.

**Comment by bitorbit** [comment]
Not 100% sure if this is related, but here is line 20 from lldxf\tagger.py:

lines = s.split('\n')

So if s contains \n\r this will not work as expected?

**Comment by mozman** [comment]
No, because in text mode you should always get '\n' as line ending from the stream object independent from the OS.

**Comment by bitorbit** [comment]
I understand but with google cloud storage that is not the case, probably because I have used BytesIO to get the file. Thanks anyway for your answer!
