### ISSUE TITLE
hatch edges not contiguous

### ISSUE THREAD

**Issue by mbway** [mozman/ezdxf#202]
the check about contiguous hatch path points appears to fail very often. Until now I've ignored them as they are not fatal, but it might be something that should be looked into?

This is an entity exported from a CAD file: I'm not sure whether the code representation is exact since there is a warning about `associative hatch not supported` but this script still gives the warnings:
```
warning: HATCH(#2D) edges not contiguous: (21006.330252226824, 23002.178375558648, 0.0) -> (21092.95083292218, 22915.557794863296, 0.0)
warning: HATCH(#2D) edges not contiguous: (21092.95083292218, 22912.022260957365, 0.0) -> (21006.330252226824, 22825.40168026201, 0.0)
```

```python
import ezdxf
import matplotlib.pyplot as plt

from ezdxf.addons.drawing import RenderContext, Frontend
from ezdxf.addons.drawing.matplotlib import MatplotlibBackend


def main():
    doc = ezdxf.new()
    layout = doc.modelspace()

    e = layout.add_hatch(
        dxfattribs={
            'layer': "0",
            'elevation': (0.0, 0.0, 0),
            'extrusion': (0.0, 0.0, 1.0),
            'pattern_name': "SOLID",
            'solid_fill': 1,
            'associative': 0,
            'hatch_style': 0,
            'pattern_type': 1,
        },
    )
    e.set_seed_points([(0.0, 0.0)])
    # 1. edge path: associative hatch not supported
    ep = e.paths.add_edge_path(flags=0)
    ep.add_line((20917.941904578507, 22913.79002791033), (21006.330252226824, 23002.178375558648))
    ep.add_arc(
        center=(21094.718599875145, 22913.79002791033),
        radius=2.499999999999985,
        start_angle=134.9999999999963,
        end_angle=225.0000000000034,
        ccw=True,
    )
    ep.add_line((21006.330252226824, 22825.40168026201), (20917.941904578507, 22913.79002791033))

    fig = plt.figure()
    ax = fig.add_axes([0, 0, 1, 1])
    ctx = RenderContext(doc)
    out = MatplotlibBackend(ax)
    Frontend(ctx, out).draw_layout(layout, finalize=True)
    fig.savefig('/tmp/test.png', dpi=300)


if __name__ == '__main__':
    main()

```

The resulting image looks fine
![test](https://user-images.githubusercontent.com/4923501/88932964-b0a81200-d276-11ea-96b3-cd6f36e5f2e3.png)

**Comment by mozman** [comment]
The current hatch boundary rendering will be replaced by Path() rendering in the future anyway.

Reversing arc- and ellipse edges is simple if represented as cubic Bezier curves, but terrible with arc- and ellipse curves and an ongoing source of errors.

**Comment by mbway** [comment]
ok. So it sounds like this warning should just be turned off for now since it's just noise?
Are you thinking of passing a parameter for whether to fill to the `draw_path` method or still use `draw_filled_polygon` for that?

**Comment by mozman** [comment]
I will use `draw_path()`, the path will be filled if `properties.filling` is not `None`. But I have no idea how to support holes/islands, maybe an additional interface is required.

**Comment by mbway** [comment]
it looks like at least matplotlib paths can handle holes by having MOVE_TO commands and specifying the hole with clockwise winding:
```python
from shapely.geometry import Polygon
from matplotlib.path import Path
from descartes import PolygonPatch
import matplotlib.pyplot as plt


def main():
    fig, ax = plt.subplots()
    fig.tight_layout()
    ax.set_aspect('equal', 'datalim')
    polygon = Polygon([(0, 0), (10, 0), (10, 10), (0, 10)], holes=[[(3, 3), (7, 7), (7, 3)]])
    patch = PolygonPatch(polygon)
    code_lookup = {
        Path.LINETO: 'LINE_TO',
        Path.MOVETO: 'MOVE_TO',
    }
    path = patch.get_path()
    print(path.vertices)
    print([code_lookup[c] for c in path.codes])
    ax.add_patch(patch)
    ax.autoscale()
    plt.savefig('hole.png')


if __name__ == '__main__':
    main()

```

```
[[ 0.  0.]
 [10.  0.]
 [10. 10.]
 [ 0. 10.]
 [ 0.  0.]
 [ 3.  3.]
 [ 7.  7.]
 [ 7.  3.]
 [ 3.  3.]]
['MOVE_TO', 'LINE_TO', 'LINE_TO', 'LINE_TO', 'LINE_TO', 'MOVE_TO', 'LINE_TO', 'LINE_TO', 'LINE_TO']
```
![hole](https://user-images.githubusercontent.com/4923501/88973967-cede3400-d2af-11ea-9b48-196cbe87d071.png)


https://bitbucket.org/sgillies/descartes/src/default/descartes/patch.py
https://sgillies.net/2010/04/06/painting-punctured-polygons-with-matplotlib.html

Qt might have something similar but I haven't really looked into it
https://www.qtcentre.org/threads/19463-Draw-polygon-with-holes

**Comment by mozman** [comment]
That looks good, SVG handles holes in a similar way.
