### ISSUE TITLE
Read close cordinates of dxf file

### ISSUE THREAD

**Issue by thakur-isha** [mozman/ezdxf#204]
I am working in python3.8 and I am reading .dxf file and fetching the coordinates and putting the coordinates in a text file to use at another code. I am fetching the coordinates but they are very far from each other in polygon shapes so when I am using those co-ordinated to draw images at another code they are distorting image shape(As my image contains arc and it joining it as polygon line). Suppose now I am getting 8 co-ordinates but I want to fetch 100 co-ordinates of a polygon and then it will resolve my issue. Please help how could I resolve it in python. Please check my code below:

```
import ezdxf
import os
import PIL.ImageDraw as ImageDraw,PIL.Image as Image


im = Image.new("RGB", (1000,1000))
draw = ImageDraw.Draw(im)
filename = "dxf_file.dxf"
file,ext = os.path.splitext(filename)

dwg = ezdxf.readfile(filename)
msp = dwg.modelspace()


lwpolylines = msp.query('LWPOLYLINE')

f = open(file+"_coordinates.txt", "w+")
for polyline in lwpolylines:
    points = ()
    f.write('lwpolyline #{}\n'.format(polyline.dxf.handle))
    for i, location in enumerate(polyline.lwpoints):
        points = points + ((location[0],location[1],),)
        f.write('Point at index {}: {}\n'.format(i, (location[0],location[1])))
    draw.polygon(points)
im.show()



f = open(file+"_coordinates.txt", "r")
print(f.read())
```

**Comment by thakur-isha** [comment]
import ezdxf
import os
import PIL.ImageDraw as ImageDraw,PIL.Image as Image


im = Image.new("RGB", (1000,1000))
draw = ImageDraw.Draw(im)
filename = "dxf_file.dxf"
file,ext = os.path.splitext(filename)

dwg = ezdxf.readfile(filename)
msp = dwg.modelspace()


lwpolylines = msp.query('LWPOLYLINE')

f = open(file+"_coordinates.txt", "w+")
for polyline in lwpolylines:
    points = ()
    f.write('lwpolyline #{}\n'.format(polyline.dxf.handle))
    for i, location in enumerate(polyline.lwpoints):
        points = points + ((location[0],location[1],),)
        f.write('Point at index {}: {}\n'.format(i, (location[0],location[1])))
    draw.polygon(points)
im.show()



f = open(file+"_coordinates.txt", "r")
print(f.read())

**Comment by thakur-isha** [comment]
Please help its urgent.

**Comment by mbway** [comment]
could you clarify what you mean by 'they are very far from each other in polygon shapes'?
without knowing what dxf file you are reading it's not clear what is going wrong and what you expect the output to be.

One thing that might be a problem is that you aren't doing anything to transform the polygon coordinates from the document coordinate system to pixel coordinates. depending on what units you are using for your dxf file the coordinates could be well outside the range of your 1000x1000 image.

If this is the problem, first loop over all your polylines and gather up all the points like you are already doing then transform from that bounding box to the coordinates of your image. so something like this: (I haven't checked that this works, but this is the general idea)
```python
points = []
for polyline in lwpolylines:
    for point in polyline.lwpoints:
        points.append((point.x, point.y))

image_width, image_height = 1000, 1000
minx = min(x for x, y in points)
maxx = max(x for x, y in points)
miny = min(y for x, y in points)
maxy = max(y for x, y in points)
bounding_box_width = maxx - minx
bounding_box_height = maxy - miny

transformation = Matrix44.translate(-minx, -miny, 0) @ Matrix44.scale(image_width / bounding_box_width, image_height / bounding_box_height)

for polyline in lwpolylines:
    polyline_points = transformation.transform_vertices(polyline.lwpoints)
    # do something with polyline_points
```
Also, the pixel coordinates have +y pointing down whereas the document coordinate system will have +y pointing up. So you have to deal with that as well.

if you just want an image, it might be easier for you to use matplotlib to draw your image rather than PIL because matplotlib will take care of the correct framing for you. You could do something like
```python
import matplotlib.pyplot as plt
fig, ax = plt.subplots()
fig.tight_layout()
ax.set_axis_off()
for polyline in lwpolylines:
    xs = [p.x for p in polyline.lwpoints]
    ys = [p.y for p in polyline.lwpoints]
    ax.fill(xs, ys)
fig.savefig('my_image.png')
```


This should be fine for drawing the points, but if you are writing them out to a file and using them together with other coordinates from somewhere else then I can't help without knowing what you are trying to do there.

**Comment by thakur-isha** [comment]
Thanks for your response @mbway. When I am plotting those co-ordinates wherever I have an arc in the image its not showing arc. I am a newbie in CAD images please help me if possible. When I am getting coordinates from .dxf file and it is returning me 5 points (x, y, start_point, end_point, bulge) and I don't know how could I use bulge to solve my problem. Please help if you have any ideas.  Please check below what I expect: 
![image](https://user-images.githubusercontent.com/50885035/89306521-ffbac200-d63d-11ea-991d-21be7aa5ebcd.png)


What I am getting:
![image](https://user-images.githubusercontent.com/50885035/89306052-5ecc0700-d63d-11ea-983d-41decdf15ed0.png)

**Comment by mbway** [comment]
Perhaps the drawing add-on would be a better starting point?
 https://ezdxf.readthedocs.io/en/stable/addons/draw.html

It deals with interpreting the cad file for you, breaking everything down into simple components.

If you just want to deal with this particular case, you can use `path = Path.from_lwpolyline()` followed by `path.approximate()` to obtain an approximation of the curved sections

**Comment by thakur-isha** [comment]
@mbway : Thanks again. Can you please help where could I use path = Path.from_lwpolyline() followed by path.approximate() in this code:
import matplotlib.pyplot as plt
fig, ax = plt.subplots()
fig.tight_layout()
ax.set_axis_off()
for polyline in lwpolylines:
    xs = [p.x for p in polyline.lwpoints]
    ys = [p.y for p in polyline.lwpoints]
    ax.fill(xs, ys)
fig.savefig('my_image.png')

**Comment by mbway** [comment]
try this.
```python
import matplotlib.pyplot as plt
from ezdxf.render.path import Path
fig = plt.figure()
ax = fig.add_axes([0, 0, 1, 1])
ax.set_aspect('equal', 'datalim')
ax.set_axis_off()
for polyline in lwpolylines:
    path = Path.from_lwpolyline(polyline)
    points = path.approximate()
    xs = [p.x for p in points]
    ys = [p.y for p in points]
    ax.fill(xs, ys)
fig.savefig('my_image.png')
```

**Comment by thakur-isha** [comment]
@mbway : I am getting error **ModuleNotFoundError: No module named 'ezdxf.render.path'** . I tried to install Path package but still getting error.

**Comment by thakur-isha** [comment]
@mbway : There is another way I can find the arc from bulge using below code 
**ezdxf.math.bulge_to_arc(location[2],location[3],location[4])**

but I am getting error **self.x = float(v[0]) TypeError: 'float' object is not subscriptable**

**Comment by mozman** [comment]
1. The module `ezdxf.render.path` is new in v0.14, which is still in [alpha](https://pypi.org/project/ezdxf/0.14a2/) stage.

2. If you want to use LWPOLYLINE you should read this [tutorial](https://ezdxf.mozman.at/docs/tutorials/lwpolyline.html).

3. [`bulge_to_arc()`](https://ezdxf.mozman.at/docs/math.html#ezdxf.math.bulge_to_arc), requires the start vertex, the end vertex and the bulge value. The arc starts a the LWPOLYLINE point which declares the bulge value and ends at the vertex of the following point. BTW the default point format of LWPOLYLINE is (x, y, start_width, end_width, bulge).

**Comment by thakur-isha** [comment]
@mozman : Thanks but when I am passing respective information in the function:
start_pt = location[2]
end_pt = location[3]
bulge = location[4]
ezdxf.math.bulge_to_arc(start_pt,end_pt,bulge) 

but it is giving error **self.x = float(v[0]) TypeError: 'float' object is not subscriptable**

**Comment by mozman** [comment]
Please read carefully: the default point format of LWPOLYLINE is (x, y, start_width, end_width, bulge), if `location` is the first point of LWPOLYLINE, location[0] is the x-coordinate of this point! 

`start_pt = (location[0], location[1])`,
`bulge = location[4]`, for `end_pt` you need then following LWPOLYLINE point.
