### ISSUE TITLE
Wipeout support?

### ISSUE THREAD

**Issue by mbway** [mozman/ezdxf#205]
What would it take to support wipeout entities?

currently there are several issues when rendering wipeout entities:
- `skipped entity WIPEOUT(...). Reason: "non copyable"` during the call to `virtual_entities` when a wpieout exists inside a block
- `skipped entity WIPEOUT(...). Reason: "Unsupported entity"` When a wipeout exists outside of a block

My understanding of wipeout is the following:
- wipeout entities can exist outside of blocks
- when inside blocks, wipeout entities can wipe out entities within the same block if they are below in the draw order, so the behaviour is exactly the same inside and outside of blocks
- layer ordering makes no difference (as layers ordering is independent of draw order)
- wipeouts remove anything below it in the draw order by pasting a rectangle of the background color. I think this is how autoCAD does it because you can't see the gridlines of the background through the wipeout entity (see below)
- in addition to pasting a rectangle of background color, the wipeout entity outline is also drawn (in the color of the entity)

With this in mind, I think it might be fairly easy to support wipeout entities in ezdxf and the drawing addon? I don't know anything about the internal dxf representation of wipeout however so that might still be tricky.

For the purposes of keeping the semantic meaning of the wipeout, I think `draw_wipeout` deserves to be it's own method of the frontend so that the behaviour can be overridden (for example choosing not to apply the wipeout but just draw the outline).

![wipeout_2](https://user-images.githubusercontent.com/4923501/89184140-3df9a800-d590-11ea-9f6a-40a762240a21.png)
![image (9)](https://user-images.githubusercontent.com/4923501/89184555-edcf1580-d590-11ea-8528-10467c59259e.png)

**Comment by mozman** [comment]
The WIPEOUT entity is based on the IMAGE entity and therefore the clipping path is defined by pixel coordinates and not in drawing units, we can put this on the todo list, but at the moment I don't want to worry about IMAGE or WIPEOUT rendering.

**Comment by mbway** [comment]
it's really annoying that the representation isn't simple. I would be happy to contribute the drawing side of the support once the entities can be interpreted (in the normal coordinate system). support for WIPEOUT would be useful for me in the long run but it isn't urgent.

how is the transformation from the drawing coordinate system and pixel coordinates stored? it must be somewhere for AutoCAD to render wipeout entities in the model space view.

**Comment by mbway** [comment]
This is great. Thanks for adding the support. However, when I try to draw the file from the screenshot above it crashes:
```
Traceback (most recent call last):
  File "examples/addons/drawing/cad_viewer.py", line 201, in _select_doc
    self.set_document(doc)
  File "examples/addons/drawing/cad_viewer.py", line 224, in set_document
    self.draw_layout('Model')
  File "examples/addons/drawing/cad_viewer.py", line 258, in draw_layout
    Frontend(self._render_context, renderer).draw_layout(layout)
  File "ezdxf/addons/drawing/frontend.py", line 92, in draw_layout
    self.draw_entities(layout)
  File "ezdxf/addons/drawing/frontend.py", line 110, in draw_entities
    self.draw_entity(entity, properties)
  File "ezdxf/addons/drawing/frontend.py", line 147, in draw_entity
    self.draw_composite_entity(entity, properties)
  File "ezdxf/addons/drawing/frontend.py", line 359, in draw_composite_entity
    draw_insert(entity)
  File "ezdxf/addons/drawing/frontend.py", line 349, in draw_insert
    self.draw_entities(insert.virtual_entities(skipped_entity_callback=self.skip_entity))
  File "ezdxf/addons/drawing/frontend.py", line 110, in draw_entities
    self.draw_entity(entity, properties)
  File "ezdxf/addons/drawing/frontend.py", line 149, in draw_entity
    self.draw_wipeout_entity(entity, properties)
  File "ezdxf/addons/drawing/frontend.py", line 249, in draw_wipeout_entity
    path = wipeout.boundary_path_wcs()
  File "ezdxf/entities/image.py", line 272, in boundary_path_wcs
    if not vertices[0].isclose(vertices[-1]):
IndexError: list index out of range
```
The problem is that `self.boundary_path` appears to be empty. Not sure why that is

I tried saving the entity to a file but drawing that doesn't seem to crash:
```python
e = layout.new_entity(
    'WIPEOUT',
    dxfattribs={
        'layer': "0",
        'lineweight': 0,
        'class_version': 0,
        'insert': (9474.436935155873, 6650.017880135767, 0.0),
        'u_pixel': (1045.000241517227, 0.0, 0.0),
        'v_pixel': (0.0, 1045.000241517227, 0.0),
        'image_size': (1.0, 1.0, 0.0),
        'image_def_handle': "0",
        'flags': 7,
        'clipping': 1,
        'brightness': 50,
        'contrast': 50,
        'fade': 0,
        'clip_mode': 0,
        'image_def_reactor_handle': "0",
        'clipping_boundary_type': 2,
        'count_boundary_points': 5,
    },
)
```
however, drawing this entity but setting the fill color to white gives:
![Figure_1](https://user-images.githubusercontent.com/4923501/89392246-30affb00-d701-11ea-8078-6bfc39116df4.png)

**Comment by mozman** [comment]
Added a factory function for the WIPEOUT entity: `Layout.add_wipeout()` to set the masking area by WCS coordinates. Otherwise this entity would be complete unusable. Example: https://github.com/mozman/ezdxf/blob/master/examples/entities/wipeout.py

**Comment by mbway** [comment]
here is the dxf file that crashes if that's useful. The \N characters are 'column breaks' which I might look into if I have time at some point since I realise the text rendering doesn't handle columns at all.

[wipeout_2.dxf.zip](https://github.com/mozman/ezdxf/files/5029288/wipeout_2.dxf.zip)

**Comment by mozman** [comment]
The actual version load the file without crashing:

cad_viewer.py:
![cad_viewer](https://user-images.githubusercontent.com/4230966/89482201-9e0f6a80-d799-11ea-8c2e-2aaafe305524.png)

draw_cad.py:
![draw_cad](https://user-images.githubusercontent.com/4230966/89482217-ab2c5980-d799-11ea-9448-2f42dc2b811f.png)
