### ISSUE TITLE
add_image - size_in_units different from set value

### ISSUE THREAD

**Issue by giancan** [mozman/ezdxf#21]
Dear @mozman ,
I tried to set specific value in size_in_unit but when I open the dxf these values are different.

`msp.add_image(insert=(4, 5), size_in_units=(12.1826,1.6305), image_def=my_image_def, rotation = 0)
`
When I open the CAD and check the image, I see:
12.1983,1.6326

Why is that? Is there anything I can do to safely get the required value in the output?
Thanks,
Gianluca

**Comment by mozman** [comment]
This also depends on image_def.dxf.image_size, check if you set the correct image size at dwg.add_image_def().

**Comment by giancan** [comment]
Actually I get the image size with PIL from the image itself and in the specific case it is 33697*4510.
Can you explain me the ratio so that perhaps I can modify the image_size to get the correct output?

**Comment by mozman** [comment]
see here: https://github.com/mozman/ezdxf/blob/c9c3bba1d48dd1717d9d44f31f828ef872888913/ezdxf/graphicsfactory.py#L326
