### ISSUE TITLE
Multiple Inserts with different geometries

### ISSUE THREAD

**Issue by pranavramkrishnan** [mozman/ezdxf#210]
Hi- 

I am looking to create a single block definition in my DXF, and then have multiple `inserts` (via `add_blockref`) for this block, each with a variation of the base block geometry.

For instance: 

The base block definition consists of a `polyline`. 

However, I wanted to pass in different points for each `insert`. What might be the best way to do this using `ezdxf`?

Here is my current attempt:
```
dxf_doc = ezdxf.new(dxfversion='R2018')
dxf_doc_msp = dxf_doc.modelspace()
base_block =  dxf_doc.blocks.new(name='shape1')
base_block.add_lwpolyline([0,0], [0,1], [1,1], [1,0]], is_closed=1)

for i in range(10): # say I wanted to create 10 different block_refs with different points
     dxf_doc_msp.add_blockref('shape1`, (0,0), .... would like to add different points for the polyline here....)

```

I was wonedering if you could point me in the direction on this or let me know if this is possible

Thanks in advance!

**Comment by mozman** [comment]
The same content for each block references is the main feature.

You have to create a new block for each variation.

**Comment by pranavramkrishnan** [comment]
Great, thanks for the clarification @mozman !

I am trying to add some attributes to my blocks in the following way:

```
block_def = dxf_doc.blocks.new(name='stud')
block_polyline = block_def.add_lwpolyline(polyline_points)
block_polyline.close()

block_insert = msp.add_blockref('stud', (0,0))
block_insert.add_attrib('STUDTAG', stud['tag'])
```

However, I'm getting the following error:
```
Traceback (most recent call last):
  File "model-blocks.py", line 177, in <module>
    block_insert.add_attrib('STUDTAG', stud['tag'])
  File "/usr/local/lib/python3.7/site-packages/ezdxf/entities/insert.py", line 317, in add_attrib
    attrib = cast('Attrib', self._new_compound_entity('ATTRIB', dxfattribs))
  File "/usr/local/lib/python3.7/site-packages/ezdxf/entities/dxfentity.py", line 894, in _new_compound_entity
    dxfattribs['layer'] = self.dxf.layer
AttributeError: 'Insert' object has no attribute 'dxf'
```

I've also tried:
```
values = {'STUDTAG': stud['tag']}
block_insert.add_auto_attribs(values)
```

But get the same error. Any advice?

**Comment by mozman** [comment]
Delete all attribs first: `Insert.delete_all_attribs()`

**Comment by pranavramkrishnan** [comment]
> Delete all attribs first: `Insert.delete_all_attribs()`

Thanks for the quick reponse @mozman:

Here is what I am trying:
```

**Comment by mozman** [comment]
Exploding a block reference DESTROYS the original block reference, you can not use `insert` after exploding!

**Comment by pranavramkrishnan** [comment]
Thanks!
