### ISSUE TITLE
can't import matplotlibBackend

### ISSUE THREAD

**Issue by Hamza442004** [mozman/ezdxf#211]
I'm following the doc [https://ezdxf.mozman.at/docs/addons/drawing.html#module-ezdxf.addons.drawing](url) but it hit me with
ModuleNotFoundError: No module named 'ezdxf.addons.drawing.matplotlib'

**Comment by mozman** [comment]
This is an optional dependency, you have to install matplotlib manually.

    pip install --user matplotlib
