### ISSUE TITLE
Document to String

### ISSUE THREAD

**Issue by pranavramkrishnan** [mozman/ezdxf#213]
Hey there- Instead of `doc.saveas` I would like to get the DXF `doc` as a string, so that I can handling saving elsewhere in my application.

Is there a method that I could get the entire `doc` as an ASCII string? Preferrably string over stream

**Comment by mbway** [comment]
you can write to a [StringIO](https://docs.python.org/3/library/io.html#io.StringIO) or [BytesIO](https://docs.python.org/3/library/io.html#io.BytesIO) using `Document.write(stream, fmt)`
For example:
```python
out = io.StringIO()
doc.write(out, fmt='asc')
print(out.getvalue())

# or 
out = io.BytesIO()
doc.write(out, fmt='bin')
print(out.getvalue())
```

**Comment by pranavramkrishnan** [comment]
Super thanks!
