### ISSUE TITLE
Interpreting GEODATA

### ISSUE THREAD

**Issue by mbway** [mozman/ezdxf#214]
I am trying to interpret the GEODATA of a georeferenced CAD file. [The documentation](https://images.autodesk.com/adsk/files/autocad_2012_pdf_dxf-reference_enu.pdf) is pretty much useless as it only describes what each variable holds but not what they mean. For example:
- `Reference point in coordinate system coordinates`
- `Horizontal units per UnitsValue enumeration` 
- `Coordinate projection radius`

Through trial and error I have determined that source_points and target_points are not to-do with the CAD file itself, but instead just define the transformation between the CRS of the CAD file and WGS84.

The `design_point` and `reference_point` together with the various scale factors seem like the most useful attributes but I haven't been able to figure out how to use them. Finding the vector from `design_point->reference_point` and adding that to each coordinate in the CAD file did not put the points in the correct location.

The `geo_rss_tag` attribute contains a WGS84 coordinate which is in the correct location, but since the attribute is something to do with RSS feeds I doubt this is the primary source for this information.

I don't know of any open source software that can read georeferenced CAD files either so I have nothing to refer to.

**Comment by jmacura** [comment]
Hi! I was also struggling with using georeferenced information from the DXF, see #30 .
I have not solved the coordinate resolution completely, as the project I was creating it for was cancelled and my attention towards this problem dropped. So I can't provide much more guidance beyond what you already know.

**Comment by mbway** [comment]
I have been able to make some progress today. I thought that my coordinates were incorrect but it turned out to be to do with how I was projecting the coordinates to display them on a map rather than them being incorrect. I will share my findings once everything is finalised.
