### ISSUE TITLE
DXF is broken after open and saving it

### ISSUE THREAD

**Issue by acschr** [mozman/ezdxf#215]
Hey,

After opening and saving my xdf cant be open later via AutoCAD or trueview (Applications Hang).
```
import ezdxf

doc = ezdxf.readfile("orig.dxf")
doc.saveas("new.dxf")
```

Left before saving, Right after saving
Do you know why there is a diffrence ?
![image](https://user-images.githubusercontent.com/70091970/91039763-6fa0e480-e60d-11ea-8f62-bc245332e478.png)

Big thanks

**Comment by mozman** [comment]
Can't help without the original DXF file.

**Comment by acschr** [comment]
I understood this but I can't send it =(, is there any way how I can check it by myself?
Big thanks

**Comment by mozman** [comment]
You can post the AutoCAD error message, but this will not help much without the original DXF file.

**Comment by mozman** [comment]
The highlighted `SUN` class is add by ezdxf automatically but is written like AutoCAD would write it. There must be another problem.

**Comment by mozman** [comment]
Some other ideas:

1. Does AutoCAD load the original file?
2. Use the AutoCAD `RECOVER` command to load the file and post the output of AutoCAD.
3. Save the original file with AutoCAD and check if the problems with ezdxf still exist.
4. You don't have to post the original file to the public on github, you can send the (zipped) file to ezdxf@mozman.at.

**Comment by mozman** [comment]
Found a bug when saving DXF R2018 files.

If your file contains HATCH entities and has DXF version R2018, retry the latest version of ezdxf from the master branch.

**Comment by yingma111** [comment]
> I understood this but I can't send it =(, is there any way how I can check it by myself?
> Big thanks

compress it and then send it
