### ISSUE TITLE
`Layouts.modelspace()` fails when layout is named MODEL instead of Model

### ISSUE THREAD

**Issue by felipeparaujo** [mozman/ezdxf#216]
I have a DXF (which I can't upload unfortunately) that was converted from a DWG file using ODAFileConverter. After parsing, `Layouts._layouts` has two keys: `MODEL` and `LAYOUT1`. When that's the case, `Layouts.modelspace()` fails because it's looking for `Model` instead of `MODEL`.

Adding `name = name.title()` to `Layouts.setup_from_rootdict()` fixes the issue for me but I don't know if that breaks definitions from the DXF spec (I'm not familiar with it).

Let me know if you need snippets from the file though, I can upload those.

**Comment by dmahr1** [comment]
Hello. I having this exact same issue, even when using the latest `ezdxf` built from master (not PyPI):
```
>>> drawing = ezdxf.readfile(path)
>>> drawing.modelspace()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/ezdxf-0.14b0-py3.6.egg/ezdxf/document.py", line 679, in modelspace
    return self.layouts.modelspace()
  File "/usr/local/lib/python3.6/dist-packages/ezdxf-0.14b0-py3.6.egg/ezdxf/layouts/layouts.py", line 165, in modelspace
    return cast(Modelspace, self.get('Model'))
  File "/usr/local/lib/python3.6/dist-packages/ezdxf-0.14b0-py3.6.egg/ezdxf/layouts/layouts.py", line 182, in get
    return self._layouts[name]
KeyError: 'Model'
```
Renaming the layout does appear to workaround the issue, but it's not an ideal solution:
```
drawing.layouts.rename('MODEL', 'Model')
drawing.modelspace()
```

**Comment by mozman** [comment]
Can you provide an example file?

**Comment by dmahr1** [comment]
@mozman Unfortunately I cannot share the entire file as it is from a client. I'm more of a GIS person rather than a CAD person, so I am kind of a noob with DXFs. Is there a way I can extract just the layouts?

These are their names before calling `rename()`:
```
>>> drawing.layouts.names()
dict_keys(['24x36', 'MODEL'])
```

**Comment by mozman** [comment]
This error should be fixed, please update to the current head. If the error is not fixed I need the whole file an excerpt is just not enough, there are many undocumented DXF features and settings  which I have see to handle it correct.

**Comment by dmahr1** [comment]
@mozman I completely understand. I will reach out if I can find a file that I am allowed to share. Until then, you can leave this issues closed.

Thanks for the fast replies!

**Comment by mozman** [comment]
New case insensitive layout name handling in v0.14b1 should solve this issue.

**Comment by dmahr1** [comment]
@mozman Holy cow, that worked!! I just reinstalled from master and it doesn't complain at all! Thank you so much for your help.

```
>>> drawing = ezdxf.readfile(path)
>>> drawing.modelspace()
<ezdxf.layouts.layout.Modelspace object at 0x7f8be4037240>
>>> Counter(e.dxftype() for e in drawing.modelspace())
Counter({'LWPOLYLINE': 2198, 'INSERT': 1459, 'TEXT': 656, 'MTEXT': 164, 'HATCH': 74, 'CIRCLE': 32, 'IMAGE': 1, 'LEADER': 1})
```
