### ISSUE TITLE
attribute missing from block

### ISSUE THREAD

**Issue by cypherunknown** [mozman/ezdxf#218]
Hi Mozman,

I created a dxf drawing including a block definition with attributes using the steps shown in the flag block example project. I also manged to insert this block to the model space, and fill in the attributes using ezdxf. 
However if I try to use Autocad's native 'insert' command on this drawing to insert a new instance of the block to the modelspace, it inserts the block but the attributes are not added to the block somehow. Even if i check the properties palette, it doesn't show any attributes. 
If I open the block with 'bedit' I can see the attributes correctly. If I change something in the block and save it, 'Insert' command works fine, i.e. it inserts the block with the attributes. It seems that somehow Autocad misses a link between the block definition and the attribute definitions until the block is modified and saved. 
Another interesting phenomenon is that if I try running 'attsync' or 'battman', it says that the drawing does not contain any attributed blocks (although it does). 
You can recreate these issues by creating a drawing with the flag example project, and then try insert, attsync or battman.

Could you advise how to solve this? The blocks with attributes that i create should be reused by colleagues that use vanilla Autocad.
Thanks in advance.

**Comment by cypherunknown** [comment]
I did exactly as it is shown in the flag example, so first created the block definition, then added the attdef. Only after this is ready do i add an instance to the modelspace.
If i open the block in the block editor it seems fine including the attributes. Also, all of the blocks that are inserted with my program (or with the flag example for that matter) show the attributes on the modelspace. Only if i then use the 'Insert' command to add another block of the same to the modelspace, this block lacks any attribute.
In addition, attsync or battman say that there aren't any attributed block.
If I open the dxf created by the flag example, i have the same experience. Could you take a look at that dxf maybe to see if it occurs to you as well?

**Comment by cypherunknown** [comment]
hi Mozman,
i read the created .dxf and your source .py codes to figure out what could have gone wrong i maybe i found something that could provide us with an explanation:
In the block.py, after acdb_bloc_begin he default value of the attribute flag (70 code) is 0. It means that the block does not have attribute. So i guess that when a block is created, this is set and then left as it is even if an attribute is added. I looked up the AcDbBlockBegin section in the created .dxf code and indeed it is 0; it is also the case in example flag dxf. So when i open this dxf with autocad, it reads this flag and registers that there are no attributes, hence battman or attsync or any other attribute related command will not work but give a warning that there aren't any attributes. When i edit the bloc with block editor and save it, autocad corrects this flag bit to 2, meaning that there are attributes.
Even if i change this by hand in the dxf file by opening it in notepad, it works.
So i think the solution could be to change this bit to two when creating an attribute definition.
Can you make this change in your code?
Im looking forward to hearing from you.

**Comment by cypherunknown** [comment]
What also worked for me: set the dxf attribute 'flags' to two when creating the block that you know will have an attribute. It will result in a correct block for autocad with correctly recognised attributes.

**Comment by mozman** [comment]
I hope this fixes the issue. I can not test this problem because BricsCAD is not that picky like AutoCAD and ignore if this flag is set or not.

**Comment by cypherunknown** [comment]
I tested it a couple of times and setting the flags tag to 2 when you know that the block is gonna contain attributes seems to be the solution. 
Cheers,
