### ISSUE TITLE
3D rotation?

### ISSUE THREAD

**Issue by bitorbit** [mozman/ezdxf#22]
Is there a way to rotate a (3D) block in other planes than XY?
 
    modelspace.add_blockref('FLAG', point, dxfattribs={
        'xscale': random_scale,
        'yscale': random_scale,
        'rotation': (-15, point1, point2) # maybe like this?
        # or like this: 'rotation_axis': 'X' ?
    })

**Comment by mozman** [comment]
Hi!

This is advanced stuff:

DXF Definition for the INSERT entity:

http://docs.autodesk.com/ACD/2014/ENU/index.html?url=files/GUID-235B22E0-A567-4CF6-92D3-38A2306D73F3.htm,topicNumber=d30e652301

There is just one rotation angle defined, I assume the extrusion direction defines the rotation axis.

In ezdxf the extrusion direction attribute is called 'extrusion'.

**Comment by bitorbit** [comment]
Thank you!
