### ISSUE TITLE
LWPOLYLINE vertex order

### ISSUE THREAD

**Issue by pranavramkrishnan** [mozman/ezdxf#221]
Hey there-

I am creating a number of closed `lwpolylines` (basically rectangles). I would then like to parse this DXF in a different application.

I was wondering if I could confirm the vertex ordering of a closed lwpolyline? Are vertex always clockwise or anti clockwise ordering? Wondering if I can be deterministic about this.

Thanks

**Comment by mozman** [comment]
There exist a new function in v0.14:

```Python
from ezdxf.math import has_clockwise_orientation

if has_clockwise_orientation(lwpolyline.vertices()):
```

```
