### ISSUE TITLE
dxf2png and appear unwanted fill

### ISSUE THREAD

**Issue by yingma111** [mozman/ezdxf#225]
Hello, I am working on converting a DXF file to PNG format, using one of the add-ons tool in ezdxf.
Below is the script that I ran to output an image file.

```
import matplotlib.pyplot as plt
import ezdxf
from ezdxf.addons.drawing import RenderContext, Frontend
from ezdxf.addons.drawing.matplotlib import MatplotlibBackend


def dxf2png(path_to_dxf='', path_to_output_png=''):
    doc = ezdxf.readfile(path_to_dxf)
    layout = doc.modelspace()
    fig = plt.figure()
    ax = fig.add_axes([0, 0, 1, 1])
    ctx = RenderContext(doc)
    out = MatplotlibBackend(ax)
    Frontend(ctx, out).draw_layout(layout, finalize=True)
    fig.savefig(path_to_output_png, dpi=300)
    plt.close(fig)


if __name__ == "__main__":
    dxf_file = "../../DXFFILE/3.dxf"
    s = dxf_file[dxf_file.rfind("/")+1:dxf_file.rfind(".")]
    png_file = "images_ezdxf/" + s + ".png"
    dxf2png(path_to_dxf=dxf_file, path_to_output_png=png_file)
```
Output is below:
![3](https://user-images.githubusercontent.com/53547240/92353344-abaa6e00-f112-11ea-8758-b6f04bb4f752.png)

But there two objects have errors, they should be holes, but filled. I framed them with red rectangle as below:
![3](https://user-images.githubusercontent.com/53547240/92353645-633f8000-f113-11ea-9e16-3a981311ea89.png)

And dxf file is:
[3.dxf.tar.gz](https://github.com/mozman/ezdxf/files/5181314/3.dxf.tar.gz)

**Comment by mozman** [comment]
Islands in Hatches are not supported yet.

**Comment by yingma111** [comment]
> Islands in Hatches are not supported yet.

Do you have a plan to support this?

**Comment by mbway** [comment]
the idea is to use `Path` objects to draw holes in the polygon (see https://github.com/mozman/ezdxf/issues/202#issuecomment-666694968). All of the necessary tools seem to be in place (creating clockwise and anticlockwise paths) but some work is needed to interpret the different types of nesting and turn them into one or multiple paths for drawing (see https://ezdxf.readthedocs.io/en/stable/tutorials/hatch.html > `hatch_style`)

**Comment by mozman** [comment]
Result of the current implementation:
![image](https://user-images.githubusercontent.com/4230966/94833097-02a01c00-040f-11eb-99f0-cde350dc50c8.png)

The additional holes at the bottom are correct, BricsCAD shows them too:
![image](https://user-images.githubusercontent.com/4230966/94833277-3d09b900-040f-11eb-9a05-ca8759d6ced9.png)

The current implementation does not support nested paths or overlapping paths:
![image](https://user-images.githubusercontent.com/4230966/94833539-878b3580-040f-11eb-9cf9-dcad2c113835.png)

The BricsCAD version, overlapping is also not correct:
![image](https://user-images.githubusercontent.com/4230966/94833673-b1dcf300-040f-11eb-9476-437a927b6d5d.png)

And the TrueView version:
![image](https://user-images.githubusercontent.com/4230966/94833975-1435f380-0410-11eb-8284-7f4a6cdef1fe.png)

**Comment by mozman** [comment]
Added a simple island detection algorithm based in bounding boxes, which is not very accurate but should work for most real world situations, where boundary paths do not overlap.

![image](https://user-images.githubusercontent.com/4230966/94909637-c4a10780-04a3-11eb-92a6-9b4429ae3ba1.png)

![image](https://user-images.githubusercontent.com/4230966/94910085-7c361980-04a4-11eb-83e7-5fd9068f3c24.png)

At the moment I don't care about overlap detection, because this feature would need much more calculation time and also requires a proper geometry library like Shapely, which provides the required low level functionality.

**Comment by mozman** [comment]
Added basic hatch pattern support but only by name matching, scaling and rotation is ignored:

![image](https://user-images.githubusercontent.com/4230966/94923749-a562a400-04bc-11eb-9894-1eb0583af997.png)

Added a new option to the param dict `use_hatch_pattern`, set option to `False` to draw hatch pattern as solid filling. Tried to roughly match the characteristics of the predefined pattern in BricsCAD and AutoCAD:

![image](https://user-images.githubusercontent.com/4230966/94923711-97ad1e80-04bc-11eb-86cf-bda3233b662f.png)
