### ISSUE TITLE
dxf2png and nothing in image

### ISSUE THREAD

**Issue by yingma111** [mozman/ezdxf#226]
Hello, I am working on converting a DXF file to PNG format, using one of the add-ons tool in ezdxf.
Below is the script that I ran to output an image file.

```
import matplotlib.pyplot as plt
import ezdxf
from ezdxf.addons.drawing import RenderContext, Frontend
from ezdxf.addons.drawing.matplotlib import MatplotlibBackend


def dxf2png(path_to_dxf='', path_to_output_png=''):
    doc = ezdxf.readfile(path_to_dxf)
    layout = doc.modelspace()
    fig = plt.figure()
    ax = fig.add_axes([0, 0, 1, 1])
    ctx = RenderContext(doc)
    out = MatplotlibBackend(ax)
    Frontend(ctx, out).draw_layout(layout, finalize=True)
    fig.savefig(path_to_output_png, dpi=300)
    plt.close(fig)


if __name__ == "__main__":
    dxf_file = "../../DXFFILE/222.dxf"
    s = dxf_file[dxf_file.rfind("/")+1:dxf_file.rfind(".")]
    png_file = "images_ezdxf/" + s + ".png"
    dxf2png(path_to_dxf=dxf_file, path_to_output_png=png_file)
```
I do this on 2900 images, and all are ok except five images below:
[(764).dxf.tar.gz](https://github.com/mozman/ezdxf/files/5182122/764.dxf.tar.gz)
[(4).dxf.tar.gz](https://github.com/mozman/ezdxf/files/5182133/4.dxf.tar.gz)
[E.tar.gz](https://github.com/mozman/ezdxf/files/5182150/E.tar.gz)

**Comment by mbway** [comment]
I tried viewing the dxf files in the cad_viewer and they rendered correctly. Then I set a breakpoint inside the matplotlib backend to see what is going on. It looks like the matplotlib backend is using the `properties.lineweight` attribute when drawing the path, whereas the Qt backend ignores it.
The line weight of these lines and paths is 0 which is why nothing appears in the output. You can the code below as a workaround. I'm not sure what a permanent fix would be though because I would have thought that a lineweight of 0 should be invisible. Maybe 0 lineweight is special? @mozman would know more about that.
```python
class CustomFrontend(Frontend):
    def override_properties(self, entity: DXFGraphic, properties: Properties) -> None:
        if math.isclose(properties.lineweight, 0):
            properties.lineweight = 0.5


def dxf2png(path_to_dxf='', path_to_output_png=''):
    doc = ezdxf.readfile(path_to_dxf)
    layout = doc.modelspace()
    fig = plt.figure()
    ax = fig.add_axes([0, 0, 1, 1])
    ctx = RenderContext(doc)
    out = MatplotlibBackend(ax)
    CustomFrontend(ctx, out).draw_layout(layout, finalize=True)
    fig.savefig(path_to_output_png, dpi=300)
    plt.close(fig)
```

**Comment by mozman** [comment]
BricsCAD also plot nothing (764.dxf) because of line weight=0, which means line weight of 0mm. The special values for `BYLAYER`, `BYBLOCK` and `DEFAULT` have values < 0, so  0 means really 0mm and plotting nothing is the correct result.

As fix its easier to change the `lineweight` of the entities:

```Python
for e in doc.modelspace():
    if e.dxf.lineweight == 0:
        e.dxf.lineweight = 0.25
```

**Comment by mozman** [comment]
My bad, BricsCAD do plot line weight 0, so the backend should maybe use the smallest line weight possible for line weight 0.

**Comment by mbway** [comment]
is it not the frontends job to resolve the lineweight to one of the 'usable' values (so 0 -> smallest), like it would for BYLAYER->usable width? That way, the messiness of dxf is handled in the frontend and the backends remain simple.

**Comment by mbway** [comment]
I see, so you think 0 should mean 'the thinnest supported by the backend' rather than some fixed thickness shared between backends. Either way works I suppose.

**Comment by mozman** [comment]
Reverted this commit and put solution into the frontend as suggested.

**Comment by msaadhassan** [comment]
public void DXFToBmpConversion()
        {
            var converter = new GroupDocs.Conversion.Converter("a.dxf");
            // set the convert options for BMP format
            var convertOptions = converter.GetPossibleConversions()["bmp"].ConvertOptions;
            // convert to BMP format
            converter.Convert("DXF to BMP.bmp", convertOptions); //during conversion you can use otherformats according to your need.
        }

**Comment by mozman** [comment]
@msaadhassan  You are lost, this is not a Javascipt library! :)
