### ISSUE TITLE
Incorrect layer color 7 resolving in drawing add-on

### ISSUE THREAD

**Issue by mozman** [mozman/ezdxf#227]
DXF entities using ACI color `BYLAYER` and a layer with ACI color 7 (white/black) should get a dark color if the background is light and vice versa.

The current implementation does not work correct, because the layer color is fixed in the constructor of the `RenderContext()` object, the current layout is always the modelspace with a dark background color.

The new implementation should also support manual background color overriding by the package-user: `RenderContext.current_layout.set_colors()`

**Comment by mozman** [comment]
New implementation works:

Black background:
![fillings_bg_black](https://user-images.githubusercontent.com/4230966/92554621-0ef8e500-f266-11ea-8608-f4c13ad821e4.png)

White background:
![fillings_bg_white](https://user-images.githubusercontent.com/4230966/92554635-17512000-f266-11ea-8eed-6cc7490b46b2.png)

Black transparent background

@mbway Is it possible in matplotlib to save PNG images with transparent background?
This image was created with background color "#00000000", but transparency is not present in image editor, no checker board as background visible:

![fillings_bg_transparent](https://user-images.githubusercontent.com/4230966/92555098-369c7d00-f267-11ea-9fe6-845a0d4f759a.png)

**Comment by mbway** [comment]
yes, it is possible to have transparent and translucent backgrounds in matplotlib:
```python
import matplotlib.pyplot as plt

fig = plt.figure()
ax = fig.add_axes((0, 0, 1, 1))


# already handled inside matplotlib backend constructor:
ax.xaxis.set_visible(False)
ax.yaxis.set_visible(False)
for s in ax.spines.values():
    s.set_visible(False)
##################


ax.plot([0, 1], [0, 1])
ax.set_facecolor('#ff000055')

fig.savefig('test.png', facecolor=ax.get_facecolor(), transparent=True)
```
results in this image (which is semi-transparent):
![test](https://user-images.githubusercontent.com/4923501/92578516-d962f480-f283-11ea-90db-6da0099bd062.png)

**Comment by mozman** [comment]
Perfect, thank you!
![fillings_bg_transparent](https://user-images.githubusercontent.com/4230966/92579147-1e3f5900-f28d-11ea-96c2-a5fff621bcba.png)
