### ISSUE TITLE
problems to add image

### ISSUE THREAD

**Issue by AmosEgel** [mozman/ezdxf#236]
Dear Manfred, 

first of all: Thanks for this beautiful piece of software (and documentation).

I have problems to add an image to my DXF. Please see the following code which is supposed to produce a filled circle as well as an imported image from a PNG file:

```
import ezdxf
import matplotlib.pyplot as plt
from ezdxf.addons.drawing import RenderContext, Frontend
from ezdxf.addons.drawing.matplotlib import MatplotlibBackend

# create document
doc = ezdxf.new('AC1015')
msp = doc.modelspace()

# add filled circle
hatch = msp.add_hatch()
edge_path = hatch.paths.add_edge_path()
edge_path.add_ellipse((5, 5), (0, 3), ratio=1)

# add image
my_image_def = doc.add_image_def(filename='blabb.png', size_in_pixel=(1440, 1440))
msp.add_image(insert=(20, 20), size_in_units=(5, 5), image_def=my_image_def, rotation=0)

# check image ID
image_defs = doc.objects.query('IMAGEDEF')
print(image_defs.first)

# save DXF
doc.saveas("dxf_with_blabb.dxf")

# convert to PNG
fig = plt.figure()
ax = fig.add_axes([0, 0, 1, 1])
ctx = RenderContext(doc)
out = MatplotlibBackend(ax)
Frontend(ctx, out).draw_layout(doc.modelspace(), finalize=True)
plt.show()
fig.savefig('dxf_with_blabb.png', dpi=300)
```
This is the image "blabb.png" which I try to import:

<img src="https://user-images.githubusercontent.com/16704045/93669274-6fbcc480-fa93-11ea-9eee-f7257186d72b.png" width="200">

This is the console output:

```
IMAGEDEF(#30)
skipped entity IMAGE(#31). Reason: "Unsupported entity"**
```
(The first line ("IMAGEDEF(#30)") is from the command `print(image_defs.first)`. The second line is from the PNG conversion.)

This is the result of the above code dxf_with_blabb.png:

<img src="https://user-images.githubusercontent.com/16704045/93669322-be6a5e80-fa93-11ea-8a69-8d7ddff30139.png" width="200">

As you can see, it only contains the circle that I was drawing, but not the image I tried to include.

I also inspected the created DXF file in two online CAD viewern, but neither of them properly showed the image.

**Comment by mozman** [comment]
The drawing add-on does not support images.

DXF files do not embed images so online viewers do not have access to your image on your HDD/SSD.

**Comment by AmosEgel** [comment]
I see. Thanks!
