### ISSUE TITLE
Add documentation for Polyface

### ISSUE THREAD

**Issue by johnthagen** [mozman/ezdxf#239]
Currently the [documentation for Polyface says "coming soon"](https://ezdxf.readthedocs.io/en/stable/tutorials/polyface.html). Would it be possible to add documentation for that?

**Comment by mozman** [comment]
Given the age of the universe, "soon" can mean anything.

**Comment by mozman** [comment]
To be little bit nicer: You don't want to handle the Polyface (is a POLYLINE) entity by yourself, use the [ezdxf.render.MeshBuilder](https://ezdxf.mozman.at/docs/render/mesh.html) factory instead. This is an uniform way to create 3D meshes. You can transform the content and you can render the result into any layout you want. Supported target entities are MESH, POLYFACE or single 3DFACE entities.

I will also add this lines the documentation ;-).
