### ISSUE TITLE
Example Correction

### ISSUE THREAD

**Issue by z3dev** [mozman/ezdxf#24]
I love the library, which is helping me to create the new import features for OpenJSCAD.org

I found that the mesh.py example creates inconsistent clockwise versus counter-clockwise faces. The impact is that the face orientation cannot be determined; outward versus inward facing.

I believe that Autocad creates all faces CCW and facing outward (right-handed rule). Please correct if not so.

Here's the fix:

# 6 cube faces
cube_faces_wrong = [
    [0, 1, 2, 3],
    [4, 5, 6, 7],
    [0, 1, 5, 4],
    [1, 2, 6, 5],
    [3, 2, 6, 7],
    [0, 3, 7, 4],
]
cube_faces = [
    [0, 3, 2, 1],
    [4, 5, 6, 7],
    [0, 1, 5, 4],
    [1, 2, 6, 5],
    [3, 7, 6, 2],
    [0, 4, 7, 3],
]

**Comment by mozman** [comment]
fixed in next release
