### ISSUE TITLE
Specify fonts in text styles

### ISSUE THREAD

**Issue by dec1** [mozman/ezdxf#243]
Hello.

If I follow your [tutorial for text](https://ezdxf.readthedocs.io/en/stable/tutorials/text.html)

I can write a dxf file.  When I open the dxf file in [QCad ](https://qcad.org/en) I can see that the text has been assigned the "Font Name"  "LiberationSerif-regular.ttf". Why has "-regular.ttf" been appended?
Does this mean that, the font has been embedded in the dxf file?

Im using wnidows 10 and ezdxf  0.14.1.
If I instead specify "Arial" (which Im pretty sure is available on windows 10?) instead of  "LiberationSerif" in my python code, the font does not seem to get exported properly. At least QCAD only shows "standard" as the font name. Similarly if I choose "Arial" as the font in QCad and save the file as dxf using QCad, then I cant find/read this with ezdxf (e.get_dxf_attrib("style") is "textsytle11").

Id like to be able to read font names (eg 'Arial')  set and saved via programs such as QCad, and write dxf files in such a way that QCad and co can read (and display) the font name I specify.

Any help would be greatly appreciated.
Best Wishes.
Declan

**Comment by dec1** [comment]
Note: After setting the font name to "Arial" in QCad and saving the file as dxf,  I can see with a text editor that teh dxf file produced  contains mention of Arial :

........................
AcDbTextStyleTableRecord
  2
textstyle11
 70
     0
 40
0.0
 41
1.1
 50
0.0
 71
     0
 42
2.5
  3
arial.ttf
  4

1001
ACAD
1000
Arial
1071
        0
  0
ENDTAB
..........

**Comment by mozman** [comment]
Font management is not part of the DXF file and DXF can not embed fonts.
You have to check the Fonts you are using are installed on your system and 
your CAD application knows where to find them.

**Comment by dec1** [comment]
Hello.

Arial is on my system, and as I said QCad can find/use it.

> Font management is not part of the DXF file

Im not sure I understand. Your tutorial describes specifying font LiberationSerif, and this works as described.

**Comment by mozman** [comment]
You have to use always the real TTF file name like "arial.ttf" not just "arial". The windows explorer and most other applications does not show the real file names, instead they show only font family names. Use a command line to list the real TTF file names:
```
cd C:\Windows\Fonts\
dir
```

"LiberationSerif-regular.ttf" is the real file name for the regular LiberationSerif font face.

By "Font management is not part of the DXF file" I mean, the DXF file format has no influence how a CAD application manage fonts or where they have to search for the fonts.

**Comment by dec1** [comment]
Thanks for the further clarification.

> You have to use always the real TTF file name like "arial.ttf" not just "arial". 

Does it make sense that your tutorial does not then? It specifies "LiberationSerif" and not ""LiberationSerif-regular.ttf"  (but the cad program apparently sees/uses the latter).

Also how do I read a font (name or file) from a dxf file? If my cad program writes "Arial" one can see from the snippet above that "arial.ttf" , "Arial" and   "textstyle11" are (all) written into the file. But when I try to read the font name with code like below I just get "textstyle11". Am I going about this wrong?

via    

```  
msp = doc.modelspace()
    for e in msp:
        Type = e.dxftype()
        if(Type == "TEXT"):
          style = e.get_dxf_attrib("style")  
          # style is "textstyle11" when using the file containing the dxf snippet above
```

Thanks in Advance

**Comment by mozman** [comment]
A text style is not a font. The text style `"LiberationSerif"` was created by setting argument `setup=True` in function `ezdxf.new()`.

The text style definition looks like this:
```
doc.styles.new('LiberationSerif', dxfattribs={'font': 'LiberationSerif-Regular.ttf'})
```
Print font of a text style:
```
style = doc.styles.get('textstyle11')
print(style.dxf.font)
```

**Comment by dec1** [comment]
Hello.

Sorry for the late reply, and thank you for yours.

So I now see I can read/write text including specifying the font (file name) as below.
The "style" here is basically just map from a (font) name to file (name)? 
And passing  argument `setup=True` in function `ezdxf.new()` just does this a few standard (windows?) font files as a convenience?

Please note that your [comment](https://ezdxf.readthedocs.io/en/stable/tutorials/text.html#new-text-style) about finding the font name on windows seems inaccurate. It doesn't seem to apply to my windows 10 machine at least:

If I open the fonts folder with windows explorer, using the  UNC convention, eg `\\computer-name\c$\Windows\Fonts`
I don't see any font-family Open Sans. If I right click on any, the 3rd tab (Details) list the "Title" which is maybe what's meant here?


Any thank you very much for providing such a valuable project.

```
import ezdxf

def write_it(file_path):
    doc_out = ezdxf.new('R2018')
    msp_out = doc_out.modelspace()

    # create text "styles" (map names to font files)
    doc_out.styles.new('myArial', dxfattribs={'font': 'arial.ttf'})
    doc_out.styles.new('mySylfaen', dxfattribs={'font': 'sylfaen.ttf'})
    doc_out.styles.new('myTimes', dxfattribs={'font': 'times.ttf'})

    # Using a text style
    msp_out.add_text("My Text Arial",
                 dxfattribs={
                     'style': 'myArial',
                     'height': 1.35}
                 ).set_pos((2, 6), align='LEFT')

    msp_out.add_text("My Text Times",
                 dxfattribs={
                     'style': 'myTimes',
                     'height': 1.35}
                 ).set_pos((2, 8), align='LEFT')


    msp_out.add_text("My Text Sylfaen",
                 dxfattribs={
                     'style': 'mySylfaen',
                     'height': 1.35}
                 ).set_pos((2, 10), align='LEFT')


    doc_out.saveas(file_path)

# --------------------------------------------------------------------------------------------
def read_it(file_path):
    doc_in = ezdxf.readfile(file_path)
    styles_in = doc_in.styles
    msp_in = doc_in.modelspace()

    for e in msp_in:

        Type = e.dxftype()
        if (Type == "TEXT"):
            my_str = e.get_dxf_attrib("text")
            style_name = e.get_dxf_attrib("style")
            style = styles_in.get(style_name)
            font = style.dxf.font
```
