### ISSUE TITLE
Portable way to find OS fonts directory

### ISSUE THREAD

**Issue by mozman** [mozman/ezdxf#245]
@mbway implemented multiple fonts support for the matplotlib backend (branch: `matplotlib-fonts`):

![image](https://user-images.githubusercontent.com/4230966/95041230-690a9000-06d6-11eb-9206-329d61815e44.png)

Need a way to find the default font folder on Windows, Linux and MacOS, any idea?

see: https://github.com/mozman/ezdxf/blob/matplotlib-fonts/src/ezdxf/addons/drawing/matplotlib.py#L316

**Comment by mbway** [comment]
If you wanted something generic (i.e. not tied to matplotlib) then you should probably detect the platform and do something specific for each.

For the Linux platform, there is no single font directory. There are quite a few. The `fc-list` command can be used to obtain paths to all the installed fonts. You could run this (you can also pass a search query to it) and parse the result to get the path of the font you want to use.
If you have an exact match, then you can use `fc-match`:
```
$ fc-match --format=%{file} DejaVuSans-Regular
/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf
```


Matplotlib has built-in functionality to find fonts: <https://matplotlib.org/3.1.1/api/font_manager_api.html>
```python
from matplotlib.font_manager import FontManager
font_manager = FontManager()
fonts = font_manager.ttflist
```
This searches for installed fonts, not just the ones bundled with matplotlib because I installed a new font (adding it to `~/.local/share/fonts` and it was able to find it

**Comment by mozman** [comment]
Thank you, I use the matplotlib FontManager() to collect all font directories and do a manual search for the true type font stored in the STYLE entity.

But the topic seems to be a bit more complicated than I thought, I got this error message for FontProperties(fname='...'):
```
ValueError: Could not parse font string: 'OpenSansCondensed-Light.ttf'
Expected end of text, found '-'  (at char 17), (line:1, col:18)
```

The  TTF filename is the only information stored in the DXF file (STYLE entity).

I need a function which returns the FontProperties() for a given true type font name. FontManager.findfont('OpenSansCondensed-Light.ttf') raises the same ValueError() exception.

**Comment by mozman** [comment]
Fixed an error in `get_font_measurement()` (used font as plain `str` instead of `FontProperties()`) and the previous exception does not occur anymore, "OpenSansCondensed-Light.ttf" in `draw_cad.py`:
![image](https://user-images.githubusercontent.com/4230966/95073403-1a2c1d00-070d-11eb-82ae-70fda6fb7dcc.png)


New issue: The font "stylu.ttf" triggers the assertion in `FontMeasurements.scale_from_baseline()`.

I disable this assertion.

**Comment by mbway** [comment]
removing the assertion is not 'safe' in that results **will** be wrong if the baseline isn't at 0. Although in practice it seems to only make a tiny difference. However I have fixed this issue like I said I would in #241. I will post a pull request soon.

**Comment by mbway** [comment]
also, I don't think that ignoring the font in `get_font_measurements` and `get_text_line_width` is a good idea either because you are measuring one font but scaling it pretending that it is another font. Really the `MatplotlibBackend` should keep a dictionary of `font` to `TextRenderer` so that measurements can still be reused as much as possible

**Comment by mozman** [comment]
Individual font caching was implemented only for the matplotlib backend, added this to the pyqt backend, but something went wrong (at merging), integration test `test_drawing_pyqt5_backend.py` fails:

```
    def test_get_text_width(backend):
>       assert backend.get_text_line_width('   abc', 100) > backend.get_text_line_width('abc', 100)
E       AssertionError: assert -323.6949752732157 > -211.1606325172477
```

And text in `cad_viewer.py` is upside-down now:

![image](https://user-images.githubusercontent.com/4230966/95156780-a71bb880-0797-11eb-9a82-25bf2db291ec.png)

Next issue: How to load a QFont from a TTF file? Google says something like `QRawFont`.

**Comment by mozman** [comment]
FontMeasurements in PyQtBackend:
![image](https://user-images.githubusercontent.com/4230966/95162120-2fed2100-07a5-11eb-89cd-3aa307948a82.png)

This values cause a negative scale value from `get_scale()` (desired_cap_height / measurements.cap_height)

Measurement results for "Xxp" in `get_font_measurements()`:
![image](https://user-images.githubusercontent.com/4230966/95162524-287a4780-07a6-11eb-8ce4-388dba9fc653.png)

FontMeasurements in MatplotlibBackend:
![image](https://user-images.githubusercontent.com/4230966/95162203-688cfa80-07a5-11eb-94e7-d1ac9558c183.png)

**Comment by mozman** [comment]
Test swapping values:

```
measurements = FontMeasurements(
                baseline=baseline,
                cap_height=baseline - upper_x.top(),
                x_height=baseline - lower_x.top(),
                descender_height=lower_p.bottom() - baseline,
            )
```

Result:

![image](https://user-images.githubusercontent.com/4230966/95163702-beaf6d00-07a8-11eb-8a57-0918e73b4235.png)

**Comment by mozman** [comment]
Loading a TTF font as QRawFont():
```python
# Is there a PyQt solution to find the absolute font path?
# Reusing matplotlib solution:
font_path = font_finder.absolute_font_path(name)
if font_path:
    raw_font = qg.QRawFont(font_path, 1.0, qg.QFont.PreferDefaultHinting)
    # todo: what now?

```

How to convert the QRawFont() into a QFont()? Or replacing QFont() by QRawFont()?

**Comment by mbway** [comment]
Really sorry about that. I only tested the matplotlib backend but checked that the two implementations were the same. The problem is that +y is down in Qt coordinates, so swapping the values around is the correct fix. The CAD is drawn the like CAD applications and matplotlib do: with +y up, but the `QGraphicsView` is flipped upside down at the end so it looks correct.

**Comment by mbway** [comment]
for Qt font handling, looks like [this approach](https://stackoverflow.com/a/30973961) could work? A comment says that the returned id is -1 if the loading failed. Also it looks like the colon at the front shouldn't be there (see [this answer](https://stackoverflow.com/a/55092351))

so something like this might work (note: this is pseudo code, haven't tested it)
```python
font_database = QFontDatabase()


if family not in font_database.families():
    font_id = font_database.addApplicationFont(path)
    if font_id == -1:
        print(f'error loading font: "{path}"')
        return default_font
    else:
        loaded_families = font_database.applicationFontFamilies(font_id)
        # maybe check that the requested family is indeed in the loaded loaded families
return font_database.font(family, point_size)
```

**Comment by mozman** [comment]
First implementation works, but have to reuse the matplotlib `font_finder` to get absolute font paths. 
```python
font_path = font_finder.absolute_font_path(name)
if font_path:
    font_db = qg.QFontDatabase()
    font_id = font_db.addApplicationFont(font_path)
    if font_id == -1:
        print(f'Error loading font: "{font_path}"')
    else:
        font_families = font_db.applicationFontFamilies(font_id)
        qfont = qg.QFont(font_families[0])
else:
    print(f'Font "{name}" replaced by default font.')

```

**Comment by mozman** [comment]
Font styles like italic and bold is a problem:

![image](https://user-images.githubusercontent.com/4230966/95196608-98a1c100-07d8-11eb-8b59-87a395acc433.png)

**Comment by mozman** [comment]
New implementation for the font finding process. Font properties are now stored in sane way like most other applications store font definitions: font-family, style, weight, ... see `fonts.py` module. ezdxf includes default font definitions to allow backends to choose a similar font, if the original font is not available on the running system.

Font definitions are generated by the matplotlib `FontManager()`, the `fonts.load()` functions loads the default definitions included in ezdxf, but accepts a path to a custom font-definition file (JSON),  the fonts of the running system can be added by `fonts.add_system_fonts()` and stored by `fonts.save()` as new default definitions (overwritten by next ezdxf update) or into a custom definition file.

Pyqt (left) and the matplotlib (right) backend:
![image](https://user-images.githubusercontent.com/4230966/95675652-1e4ab580-0bb9-11eb-88bb-c330818c0c1b.png)

**Comment by mozman** [comment]
Added TTF replacement font names for SHX fonts:

![image](https://user-images.githubusercontent.com/4230966/95704478-3a019a80-0c51-11eb-9382-2c34a93c2d3e.png)

These TTF fonts are not available for free, but were provided automatically by installing an Autodesk product. I think installing TrueView is sufficient for Windows and Mac. I don't see any legal way for Linux users, other than maybe a TrueView installation by `wine` and copying the TTF fonts from the `wine` installation.
