### ISSUE TITLE
Computing INSERT sub entities coordinates in "drawing" coordinates

### ISSUE THREAD

**Issue by FenryrMKIII** [mozman/ezdxf#247]
I want to compute the coordinates of the entities belonging to an insert and I want those coordinates to be relative to the insert point inside the drawing i.e. in "drawing coordinates".

Up to now, to achieve this, I was proceeding the following way for an `INSERT` entity that is stored in a variable `entity`:
- Get the `name` of the INSERT (`name = entity.dxf.name`)
- Get the related BLOCK (`block = drawing.blocks[name]`)
- for each entity within the BLOCK definition, recompute the coordintates by :
    getting the coordinates of the sub entity within the block
    getting the block base point 
    transforming the coordinates in the block reference frame into the drawing reference frame (take into account rotation, 
    translation, scaling) with reference to the INSERT insert point

This usually worked well except for some nested insert e.g. INSERT containing lines but also hatches. 

I tried a new ezdxf version to check if something could help me and I identified that the method `virtual_entities` from INSERT seems to do exactly what I want. **Is that correct ?**
However, the method seems to break on some entities e.g. compute correct coordinates for nearly all INSERT but put some INSERT as having negative coordinates altough they clearly don't.

Any help would be appreciated.

**Comment by mozman** [comment]
The `virtual_entities()` and `explode()` methods renders the entities of a block reference into world coordinates (WCS), the entities in the block definition are relative to block references point by definition.

To verify if the the `virtual_entities()` method produces incorrect result, I need example data, because so far the implementation works well for all tested scenarios. Did you take the [OCS](https://ezdxf.mozman.at/docs/concepts/ocs.html) into account?

**Comment by FenryrMKIII** [comment]
Hello,

Thanks a lot for reaching out. 

I will attach a part of the P&ID I am working on. I left the (I believe) problematic entities.
They are clearly located in positive coordinates, yet virtual_entities method states negative ones.

**Comment by mozman** [comment]
Your sample in BricsCAD:
![sample_brics_cad](https://user-images.githubusercontent.com/4230966/95677432-d716f180-0bc5-11eb-8556-4e7583bbd4b7.png)

Your sample with the ezdxf drawing add-on example `cad_viewer.py` which uses the `virtual_entities()` method to render block references:
![sample_ezdxf](https://user-images.githubusercontent.com/4230966/95677453-f44bc000-0bc5-11eb-955f-229a78919a80.png)

As you see the same result, if you examine the result of `virtual_entities()`:
```python
insert = msp.query('INSERT')
# Get the first LWPOLYLINE in the block reference
pline = list(insert[1].virtual_entities())[0]
pline.dxf.extrusion
```
You get the result (0, 0, -1), which is an OCS with -1 as z-axis.

```
In[26]: list(pline.vertices_in_wcs())
Out[26]: 
[Vector(219.870745, 570.958427, 0.0),
 Vector(219.870745, 575.958427, 0.0),
 Vector(219.870745, 580.958427, 0.0)]

In[27]: list(pline.vertices_in_ocs())
Out[27]: 
[Vector(-219.870745, 570.958427, 0.0),
 Vector(-219.870745, 575.958427, 0.0),
 Vector(-219.870745, 580.958427, 0.0)]

```

Everything is OK. Many DXF users are not aware of the OCS.

**Comment by FenryrMKIII** [comment]
No, I was not indeed. Thanks a lot for the help. And for developing ezdxf. It's a super useful package !
