### ISSUE TITLE
Creating your own hatching patterns

### ISSUE THREAD

**Issue by mkondratyev85** [mozman/ezdxf#248]
Is it possible to create your own hatching patterns in addition to the predefined? 
And is it possible to embend them in dxf file so the Autocad would open it correctly?
Thank you.

**Comment by mozman** [comment]
You can look at the [patterns.py](https://github.com/mozman/ezdxf/blob/master/src/ezdxf/tools/pattern.py) and the [_iso_pattern.py](https://github.com/mozman/ezdxf/blob/master/src/ezdxf/tools/_iso_pattern.py) modules, to see how the AutoCAD default patterns are created. More information is not available in the DXF reference and be aware only a few applications reproduce the pattern correct as far as I know, only Autodesk products and BricsCAD.

**Comment by mkondratyev85** [comment]
Thank you for the answer. I've looked at the way ezdxf accepts pattern definition. It looks like it's similar to the way AutoCad stores its pattern definitions in `.pat` files https://knowledge.autodesk.com/support/revit-products/learn-explore/caas/simplecontent/content/demystifying-revit-pat-hatch-files-explanation-the-pat-file-format-diagram-excel.html.

It's a nightmare to manually edit them. So, I created a simple gui editor for pattern definitions for `ezdxf`:
https://github.com/mkondratyev85/pattern_definition_editor.

![](https://raw.githubusercontent.com/mkondratyev85/pattern_definition_editor/main/gui.png)

It's written in python3 tkinter and has only basic functionality. 
It's far from being ideal, but if anyone would have similar task to construct custom hatches for `ezdxf` it may be helpful.

**Comment by salahuddintariq** [comment]
Hello, I want to create a hatch pattern like this using ezdxf. 

![image](https://user-images.githubusercontent.com/50765226/96618704-e46d6380-12ca-11eb-83d8-91082d08eb85.png)

Can you please guide how is it possible? I have already drawn a square solid hatch and it works fine but I do not know how to create annular ring using ezdxf.

**Comment by mkondratyev85** [comment]
I can see a solid rectangle that is filled with blue color with a rectangular hole inside. Do you want to repeat this over the area of some polygon?
I'm not the author of the `ezdxf` library, but from what I understand, you can create hatch patterns only using straight lines, i.e. you can't fill polygons with color in your hatch patterns.

**Comment by salahuddintariq** [comment]
I only want to create a solid annular square ring. 
So the blue area is the only part that I want to create. White space is a void and nothing exists there. 

Or I was thinking if I Python can read DXF file of this annular ring which I can generate from some other CAD software and then I can parametrize the Python code to generate solid annular rings of any dimensions. 

If someone can help out, I will appreciate that.

**Comment by salahuddintariq** [comment]
On page 50 of this document  (https://readthedocs.org/projects/ezdxf/downloads/pdf/stable/)

, there is a technique to do that but I am not sure how to implement it. It writes the DXF file but when I take it to CAD software, the DXF files does not draw anything.

Here is the Python code which can draw solid hatch and I want to extend it to draw annular square hatch.


import ezdxf

doc = ezdxf.new("R2010")  # create a new DXF drawing (AutoCAD 2010)
#msp1 = doc.modelspace()  # we are working in model space
 # draw outline
msp = doc.modelspace()
i = 10

hatch = msp.add_hatch(color=1)
        
msp.add_line((i, i), (0, i))
msp.add_line((0, i), (0, 0))
msp.add_line((0, 0), (i, 0))
msp.add_line((i, 0), (i, i))
       
doc.saveas("solid patch.dxf")  # save DXF drawing

**Comment by mkondratyev85** [comment]
This works:
```python
import ezdxf
doc = ezdxf.new('R2000')# hatch requires the DXF R2000 (AC1015) format or later
msp = doc.modelspace()

hatch = msp.add_hatch(color=1, dxfattribs={
    'hatch_style': 0,
    # 0 = nested
    # 1 = outer
    # 2 = ignore
})

# The first path has to set flag: 1 = external
# flag const.BOUNDARY_PATH_POLYLINE is added (OR) automatically
hatch.paths.add_polyline_path([(0, 0), (10, 0), (10, 10), (0, 10)], is_closed=1, flags=1)

# The second path has to set flag: 16 = outermost
hatch.paths.add_polyline_path([(1, 1), (9, 1), (9, 9), (1, 9)], is_closed=1, flags=16)

doc.saveas("solid_hatch_polyline_path_with_bulge.dxf")
```

At leas I can open file in QCAD and see the result.

The code snipped is from this page:
https://ezdxf.readthedocs.io/en/stable/tutorials/hatch.html

**Comment by salahuddintariq** [comment]
Thanks a lot. Yes it works in other CAD softwares but feel like my application does not recognized this DXF file and does not draw anything.

Is it possible to draw this annular square explicitly, export the DXF file and then to run a Python function dxf2code which can generate the code for the DXF? If that is possible, that will be very helpful. Can you please write one example which can make use of dxf2code by creating a sample DXF.
