### ISSUE TITLE
about block

### ISSUE THREAD

**Issue by ggfv** [mozman/ezdxf#25]
I have see your document about How to Get/Set block reference attributes,but i still do not  know how to get block reference attributes. Please you tell me how to do that in detail. Thank you! And I am weak in English,so please use simple terms.Thank you!

**Comment by jmacura** [comment]
Hi @ggfv 

From my experience with ezdxf, you can get attributes of a block reference like this (for example):
```
dxf = ezdxf.readfile("your_file.dxf")

for entity in dxf.modelspace():
    if e.dxftype() == 'INSERT':
        print(block.name)
        print(block.dxf.insert)
        print(block.dxf.extrusion)
        #...and so on.
```
Available attributes are described here: http://ezdxf.readthedocs.io/en/latest/blocks.html#block-reference

Hope it helps
