### ISSUE TITLE
Strange behaviour of attribs

### ISSUE THREAD

**Issue by mbway** [mozman/ezdxf#258]
I have discovered a situation where AutoCAD and ezdxf interpret the same file to have different text. I'm not sure of the cause but I was able to create a minimal example:
[new_file.dxf.zip](https://github.com/mozman/ezdxf/files/5476689/new_file.dxf.zip)

the correct (AutoCAD) interpretation:
![image (21)](https://user-images.githubusercontent.com/4923501/97896773-747cc580-1d2d-11eb-8b40-19439bcf9c36.png)
the ezdxf interpretation:
![image (22)](https://user-images.githubusercontent.com/4923501/97896779-75adf280-1d2d-11eb-994d-85728387dff6.png)

![image (23)](https://user-images.githubusercontent.com/4923501/97897318-37650300-1d2e-11eb-900c-cffe331cd23a.png)
![image (24)](https://user-images.githubusercontent.com/4923501/97897325-39c75d00-1d2e-11eb-9dfa-1c3fa56a35c3.png)

Ezdxf does not report any problems with the dxf file and by setting a breakpoint I was able to see that the drawing frontend sees the text as shown in the second image. Using a text editor, I can see that the true text does exist inside the dxf file.

**Comment by mozman** [comment]
This is a new to use MTEXT inside of an ATTRIB/ATTDEF entity, do documentation about that in the DXF reference, some information in the ODA DWG reference.
![image](https://user-images.githubusercontent.com/4230966/97950195-6adb7800-1d96-11eb-9c44-8f1420216c1d.png)


Embedded Objects are preserved as they are by ezdxf, if you start editing and copying these attributes this strategy fails of course. I have no idea yet how to support this feature.

**Comment by mozman** [comment]
There is some info in the DXF reference but as often misleading and does not represent the actual implementation:

![image](https://user-images.githubusercontent.com/4230966/97950481-49c75700-1d97-11eb-870c-bb365cfada8b.png)

**Comment by mbway** [comment]
I have ran into a few more strange issues which I think are caused by this same situation.
- some ATTRIBs have `\P` newline escape codes in them and ezdxf displays them as a single line with `\P` left in whereas AutoCAD displays them as multiple lines. I originally thought that under some situations `\P` is allowed in ATTRIB entities but I now think it was another case of embedded MTEXT but with the ATTRIB text synchronized with the MTEXT (even though `\P` doesn't make sense inside ATTRIB text)
- when an ATTRIB is created in AutoCAD with `Multiple Lines` selected it creates it with an embedded MTEXT, but unlike the other files I've seen it doesn't seem to sync the MTEXT contents with the ATTRIB text, meaning that ezdxf shows nothing at all
- I have CAD files where an MTEXT is embedded into an ATTRIB but `Multiple Lines` is *not* checked for the attrib. I don't know how these files were constructed.

![image (50)](https://user-images.githubusercontent.com/4923501/105838526-18da7500-5fc8-11eb-8581-4ebbe2fce474.png)

this file appears empty when rendered with ezdxf:
[att_with_new_line.dxf.zip](https://github.com/mozman/ezdxf/files/5872969/att_with_new_line.dxf.zip)
![att_with_new_line](https://user-images.githubusercontent.com/4923501/105838536-1bd56580-5fc8-11eb-945a-a81559e8d84e.png)


this file shows the `\P` being left in place. I wasn't able to remove all the unnecessary attributes so I anonymised them instead
![image](https://user-images.githubusercontent.com/4923501/105839056-d8c7c200-5fc8-11eb-8642-e095741cad23.png)
as you can see, multiple lines is off, even though multiple lines are displayed
![image (51)](https://user-images.githubusercontent.com/4923501/105841042-e894d580-5fcb-11eb-9404-871e19f6cc2e.png)
![image (52)](https://user-images.githubusercontent.com/4923501/105841090-fea29600-5fcb-11eb-8622-094fe6f3c292.png)
[att_extraction.dxf.zip](https://github.com/mozman/ezdxf/files/5873080/att_extraction.dxf.zip)

**Comment by mozman** [comment]
I hope this can be ignored when the embedded MTEXT is supported, and only the MTEXT content is used. I am not sure if I want to support creating such ATTRIB entities.

Fact: `\P` is not supported to create multi-line entities by TEXT:
![image](https://user-images.githubusercontent.com/4230966/105846701-d66f6300-5fdc-11eb-810f-4c872b3127ca.png)

**Comment by mozman** [comment]
@mbway Please do me a favor and save the attached example file for DXF R2013, R2010, R2007, R2004 and R2000 by AutoCAD.
BricsCAD creates two separated ATTRIB entities for the multi-line ATTRIB and I assume that the [DXF Reference](https://help.autodesk.com/view/OARX/2018/ENU/?guid=GUID-7DD8B495-C3F8-48CD-A766-14F9D7D0DD9B)
for ATTRIB R2018 with an "attached" MTEXT is just bullshit which was never implemented that way.

![image](https://user-images.githubusercontent.com/4230966/127733903-146b2482-121a-4226-9276-556f47defcb9.png)

BTW: If you can create an ATTRIB with embedded `AcDbXrecord` subclass (the keyword seems to be "secondary attributes") or stumble upon one, please upload an example. I assume this is a also a feature which does not exist or is not used in reality:

![image](https://user-images.githubusercontent.com/4230966/127734030-77665158-943e-4e46-a576-738649a0260e.png)


[attrib_with_mtext_R2018.zip](https://github.com/mozman/ezdxf/files/6910888/attrib_with_mtext_R2018.zip)

**Comment by mozman** [comment]
TrueView 2022 seems to handle embedded MTEXT differently than AutoCAD - the example "new_file.dxf" in TrueView 2022:
![image](https://user-images.githubusercontent.com/4230966/127763097-8390a99e-eee0-4a9e-8b3f-9303f9ba49d7.png)

But works as expected in BricsCAD:
![image](https://user-images.githubusercontent.com/4230966/127763112-6c261700-cfb8-42d2-b893-2917f8465a93.png)

This makes it difficult to check if the DXF export of ezdxf is 100% AutoCAD compatible.

**Comment by mbway** [comment]
here is the dxf example saved to many different versions with autocad
[attrib_with_mtext_many_versions.zip](https://github.com/mozman/ezdxf/files/6916760/attrib_with_mtext_many_versions.zip)

**Comment by mozman** [comment]
Thank you, this is an ATTRIB with an embedded MTEXT entity (as Embedded Object) which is already supported and looks like this in the latest ezdxf version:

![image](https://user-images.githubusercontent.com/4230966/128031892-2c3a13ec-eb53-447d-9b38-d40ea9de1775.png)

I am looking for an ATTRIB containing an `AcDbXrecord` subclass. I have no idea for what this subclass is used, how to create such an ATTRIB or even if this is a real feature of the ATTRIB entity, because the DXF R2018 Reference for ATTRIB is mostly wrong.

**Comment by mozman** [comment]
I close this issue, if there are problems with multi-line ATTRIB entities (only supported in R2018) saved by ezdxf, open a new issue.
