### ISSUE TITLE
Documentation for available DXF attributes in each version.

### ISSUE THREAD

**Issue by tom-f-oconnell** [mozman/ezdxf#26]
I couldn't find documentation on which attributes are available with which DXF versions. Are the supported attributes already accessible somewhere?

**Comment by mozman** [comment]
http://ezdxf.readthedocs.io/en/latest/entities.html

See:

- Common DXF attributes for DXF R12
- Common DXF attributes for DXF R13 or later
- every DXF entity doc section has a table with the supported DXF attributes, the version column indicates the minimum DXF version
