### ISSUE TITLE
Table objects, associated with element and assign value

### ISSUE THREAD

**Issue by vaschthestampede** [mozman/ezdxf#260]
Is It possible to crate a Table with attribute, associate it with a graphic object and assign values to the attributes?

I am attaching a sample file
[Italy.zip](https://github.com/mozman/ezdxf/files/5493454/Italy.zip)

In lisp language that are managed by "ADE" function.

**Comment by vaschthestampede** [comment]
Update:
I tried to load the file and save it.
The saved file have a different size and it have the right table, so ezdxf can handle it.

But I wasn't able find the object in the doc object.

**Comment by mozman** [comment]
If you mean `ACAD_TABLE` by "Table", ezdxf just preserve the data but does not support evaluation or creation of `ACAD_TABLE` entities.

**Comment by vaschthestampede** [comment]
Thanks for your reply, I hope that soon it will be possible.

**Comment by mozman** [comment]
Sorry, but i have to disappoint you, the table entity is very complex and barely documented and uses other barely documented entities in conjunction, therefore i have no motivation to implement this entity in the near future.

**Comment by vaschthestampede** [comment]
I feared it.
Finding documentation in lisp was also not easy at all.
