### ISSUE TITLE
filled inner contour

### ISSUE THREAD

**Issue by marfis89** [mozman/ezdxf#262]
Hi mozman,

great work so far! do you have any ideas to fill the inner contour of the plot ? the colors of outer and inner contours are different, so it should possible to detect which contour is inner and which is outer

i played a bit with inkscape, but i was not able to export it into the "right" format

Best regards Martin

![98805790-6e1ad780-2418-11eb-8dd2-ab32ead5b4b9](https://user-images.githubusercontent.com/13908411/98810396-7aeef980-241f-11eb-980a-eaa90936e5eb.png)

**Comment by marfis89** [comment]
![hatches_1](https://user-images.githubusercontent.com/13908411/98814817-8560c180-2426-11eb-9663-a6a291759f29.png)

![hatches_2](https://user-images.githubusercontent.com/13908411/98814822-85f95800-2426-11eb-8c8e-a4caa8025a96.png)

your examples work fine, so i just have to find the right parameter

**Comment by mbway** [comment]
I may be misunderstanding, but the filled shapes in your second post are [HATCH entities](https://ezdxf.readthedocs.io/en/stable/tutorials/hatch.html). Is the dxf in your first post just polylines or a hatch? Recently support has been added for [holes in hatches](https://github.com/mozman/ezdxf/issues/225) which seems to be what you need? You would just have to construct a hatch with the inner and outer contours that you have already.

**Comment by marfis89** [comment]
okay i understood how to create a new hatch. But how can i add a hatch for my existing file / existing polylines ? or is the only way to export the dxf with the right parameters from my cad programm ?

**Comment by mbway** [comment]
you could probably do it using CAD software, or by writing code to identify those entities, remove them and add a HATCH in their place, then set the hatch paths as the original entities.
