### ISSUE TITLE
I need support to import SVG to DXF

### ISSUE THREAD

**Issue by nguyenbs** [mozman/ezdxf#267]
I want to creat DXF from one or multiple SVG files using eazy DXF. Anyone have a clue?

**Comment by mozman** [comment]
Ezdxf is not a file format converter, see docs: https://ezdxf.mozman.at/docs/introduction.html#what-ezdxf-can-t-do

You can try asking this question on [stackoverflow](https://stackoverflow.com/), but I assume this question is not specific enough to be answered by anyone.
