### ISSUE TITLE
When using hatch entities, I was using hatch. Set_pattern_fill () for the predefined section line pattern that was not filled in completely

### ISSUE THREAD

**Issue by luoyu-123** [mozman/ezdxf#268]
Hello!Manfred Moitzi
When I used the readFile () function in exDXF to read the entity data in the DXF file and then used the hatch entity to generate the profile, the hatch entity was not fully populated
`# _*_ coding=utf-8 _*_
import ezdxf

dwg_file = ezdxf.readfile("profile_map2.dxf")
msp = dwg_file.modelspace()
print(dwg_file.dxfversion)
i = 1
for entity in msp:
    dxf_type = entity.dxftype()
    print(i,"dxftype:{}:{}".format(dxf_type, entity.dxfattribs()))
    i+=1
entity_list = []
# spline_list = []
for e in msp.query():

    if e.dxf.layer == "剖面图":
        if e.dxftype() == "LINE":

                line_dict = {"shapes": {
                    "coordinates": {"start": {"x": e.dxf.start.x, "y": e.dxf.start.y, "z": e.dxf.start.z},
                                    "end": {"x": e.dxf.end.x, "y": e.dxf.end.y, "z": e.dxf.end.z}},
                    "type": "LINE"
                }}
                entity_list.append(line_dict)
        elif e.dxftype() == "SPLINE":
            fit_points = e.fit_points
            degree = e.dxf.degree

            spline_dict = {"shapes": {
                "coordinates": {"fit_points": [fit_points[0], fit_points[1], fit_points[2]]},
                "degree": degree,
                "type": "SPLINE",

            }}
            entity_list.append(spline_dict)

def profile_map(entity_list, msp):
    """剖面图"""
    hatch = msp.add_hatch(dxfattribs={'hatch_style': 0})

    edge_path = hatch.paths.add_edge_path(flags=16)
    for i in range(len(entity_list)):
        print(i)
        type = entity_list[i]["shapes"]["type"]
        if type == 'LINE':
            """直线"""
            pnt = entity_list[i]["shapes"]["coordinates"]
            start_point = (pnt["start"]["x"], pnt["start"]["y"])
            end_point = (pnt["end"]["x"], pnt["end"]["y"])
            try:
                edge_path.add_line(start_point, end_point)
            except Exception:
                raise ValueError("创建LINE实体失败")
        elif type == "SPLINE":
            """bspline曲线"""
            degree = entity_list[i]["shapes"]["degree"]
            fit_points =entity_list[i]["shapes"]["coordinates"]["fit_points"]
            try:
                spline = edge_path.add_spline(fit_points, degree=degree)
            except Exception:
                raise ValueError("创建bspline实体失败")

        hatch.set_pattern_fill('ANSI31', scale=0.5)
profile_map(entity_list,msp)

dwg_file.saveas("profile_map2020-11-25.dxf")`

![image](https://user-images.githubusercontent.com/59160360/100192263-96342b80-2f2c-11eb-9a42-2718ccc7c150.png)
![image](https://user-images.githubusercontent.com/59160360/100192276-9e8c6680-2f2c-11eb-8da8-37dc3ee541ac.png)

**Comment by mozman** [comment]
The HATCH entity represents only the "filling" and has no border lines, if you need border lines you have to add them as separated DXF entities. This is the difference between a CAD application and a file format interface, you have to do a lot manually.

**Comment by luoyu-123** [comment]
First of all, thank you very much for your answer. What I want to describe is that when I "fill" the hatch entity, it doesn't "fill" the figure around the boundary.
Best wishes！

**Comment by mozman** [comment]
I can only help if you create a simple self contained example which shows the problem in an isolated environment. All testing done by mbway and myself do not show such an issues.

**Comment by luoyu-123** [comment]
Thank you very much!
Here is the code and sample I tested
[profile_tset.txt](https://github.com/mozman/ezdxf/files/5595355/profile_tset.txt)

[profile_map3.zip](https://github.com/mozman/ezdxf/files/5595362/profile_map3.zip)

**Comment by luoyu-123** [comment]
Thank you very much.The issue has been resolved.
Best wishes！
