### ISSUE TITLE
How to mark angle dimensions with ezdxf？

### ISSUE THREAD

**Issue by luoyu-123** [mozman/ezdxf#270]
I want to mark the angle of graphics in the dxf file, but I see that the factory function does not seem to be implemented in the document, is it true?
![image](https://user-images.githubusercontent.com/59160360/100496354-66845e00-318e-11eb-8b74-e840c9fecf04.png)

**Comment by mozman** [comment]
Not implemented yet!

**Comment by luoyu-123** [comment]
thank you ！
