### ISSUE TITLE
How to check whether a Point is inside a LWPolyline?

### ISSUE THREAD

**Issue by tropicoo** [mozman/ezdxf#271]
In my DXF file there are thousands of `LWPolyline` objects (rectangles) and there are thousands of `Point` objects which visually lay "inside" the "rectangles". For example some `LWPolyline` has 5 `Point` objects. How to check whether a `Point` is inside the particular `LWPolyline`?

Visual example.
![image](https://user-images.githubusercontent.com/888784/100622442-8b610880-3329-11eb-9ce1-3f273029a397.png)

Thank you for any help.

**Comment by mozman** [comment]
This is not really the domain of a file format interface but there exist a helper function for that task: https://ezdxf.mozman.at/docs/math.html#ezdxf.math.is_point_in_polygon_2d

The rest is a nice coding exercise.

**Comment by mbway** [comment]
you could also use an [Rtree](https://toblerity.org/rtree/) to narrow down the number of points which require an expensive intersection test.

**Comment by tropicoo** [comment]
@mozman @mbway Thank you for quick response. Implemented points to polygon mapping with Rtree spatial index and it's work very fast.
