### ISSUE TITLE
Complex linetypes problem

### ISSUE THREAD

**Issue by Andrpocc** [mozman/ezdxf#284]
hi mozman
I am trying to use ezdxf for auto drawing geodetic plans  in AutoCAD and it is important to work with complex linetypes
I were trying for some days, but creating new complex linetypes not working for me (simple works)
I also tried use example from tutorial, everything works but line looks incorrect, without any text
Can u explain what a problem? May be I need additional files
![2020-12-18_16-21-22](https://user-images.githubusercontent.com/57345999/102619174-15dca100-414d-11eb-9a1f-51fd357bdfbe.png)

```import ezdxf

doc = ezdxf.new('R2018')  # DXF R13 or later is required

doc.linetypes.new('GASLEITUNG2', dxfattribs={
    'description': 'Gasleitung2 ----GAS----GAS----GAS----GAS----GAS----GAS--',
    'length': 1,  # required for complex line types
    # line type definition in acadlt.lin:
    'pattern': 'A,.5,-.2,["GAS",STANDARD,S=.1,U=0.0,X=-0.1,Y=-.05],-.25',
})

msp = doc.modelspace()

msp.add_line((0, 0), (50, 50), dxfattribs={'linetype': 'GASLEITUNG2'})

doc.saveas('lines/test.dxf')

**Comment by Andrpocc** [comment]
Thanks, it works now! 
But the same problem, if just open dxf with defined linetypes and just save it

```
import ezdxf

doc = ezdxf.readfile('init2018.dxf') 

doc.saveas('test.dxf')
```
or if I'm using Importer

```
import ezdxf

from ezdxf.addons import Importer

from_doc = ezdxf.readfile('data/init_autocad_eng.dxf')
to_doc = ezdxf.new('R2018')
importer = Importer(from_doc, to_doc)
importer.import_table('linetypes')
importer.import_table('layers')
block_names = []
for n, block in enumerate(from_doc.blocks):
    if n > 2:
        block_names.append(block.block_record.dxf.name)
importer.import_blocks(block_names)
importer.finalize()
to_doc.saveas('test.dxf')
```
Can it be fixed? May be there are just the same problem

**Comment by mozman** [comment]
This is a "complex" topic and may not be solved at 100%!
