### ISSUE TITLE
complex linetypes doesn't save external .shx shape

### ISSUE THREAD

**Issue by clement-soler1** [mozman/ezdxf#292]
Hello,

While creating a new complex linetype that's using points and a custom shape defined on an external file, I've encountered a problem.

While executing my program, it works normally but when i'm trying to open the dxf file on an other app (I've tried with Autocad and ShareCad) the file doesn't contain the shape which was defined on an external file. It looks like the linetypes doesn't have the shape even when declared with the correct shape index.

Here is my code for generating the dxf file :

```import ezdxf

doc = ezdxf.new(dxfversion='R2010')
msp = doc.modelspace()


doc.linetypes.new('LIGNEARBRES', dxfattribs={
    'description': ' LIGNEARBRES lignearbres',
    'length': 1,
    'pattern': 'A,0,-1.731501,[260,C:\\Users\\Dev01\\Desktop\\GEOCADBIB\\arbre.shx,s=1],-1.736192',
})


msp.add_line((0, 0), (1, 1), dxfattribs={'linetype': 'LIGNEARBRES'})


doc.saveas('../output/test_line2.dxf')```

Have a nice day

**Comment by mozman** [comment]
The location where a CAD application should search for resources are not defined by the DXF reference. For most CAD applications it is necessary to show them the location of resources by a configuration setting even when absolute file paths are used. Sometimes it is better to store the resources next to your DXF file, but often even this does not help e.g. images work better referenced by (invalid) absolute paths than with relative paths. These are all topics (beside many others) which are not documented by the DXF reference.

My general advice to resource related problems: 
See DXF as a geometry exchange format and nothing more. Don't expect that fonts, images, xrefs, dimensions work properly and show the same result in every CAD application.
