### ISSUE TITLE
pickle.dump() raises error with Vec3 (Vector) at ezdxf v0.15

### ISSUE THREAD

**Issue by sato1214syun** [mozman/ezdxf#303]
Pickling variables include Vec3 (Vector) raises TypeError at ezdxf v0.15. Is it a bug?
I'm using v0.14 as a provisional measure.

```
test.py, line 7, in <module>
    pickle.dump(test_data, f)
  File "stringsource", line 2, in ezdxf.acc.vector.Vec3.__reduce_cython__
TypeError: no default __reduce__ due to non-trivial __cinit__
```

Code below is a simple example to reproduce this error.
```
import pickle
from ezdxf.math import Vector

test_name = "test.pickle"
test_data = Vector(1, 1, 1)
with open(test_name, "wb") as f:
    pickle.dump(test_data, f)

with open(test_name, "rb") as f:
    result = pickle.load(f)

print(result)
```

**Comment by mozman** [comment]
Support for the `pickle` protocol was never granted. You can disable the C-Extensions by setting the environment variable `EZDXF_DISABLE_C_EXT=1`.

**Comment by mbway** [comment]
you should be able to pickle the math objects now even when using the C-extensions (if you're using the latest code from git)

**Comment by sato1214syun** [comment]
@mozman @mbway  Thank you for the quick fix!
