### ISSUE TITLE
Remove block layer link

### ISSUE THREAD

**Issue by Gaetanbrl** [mozman/ezdxf#31]
First, thanks for this lib very usefull ! 
I search to dynamically remove layers  from DXF file. 

But some of layers are linked with an entity draw in a block. So, lib can't remove this layers.

Someone have solution to remove linked layers or remove entity in a bloc corresponding to one layer ?  

Thank you for your help ! 😄

**Comment by mozman** [comment]
(repeated answer from google groups)

To clarify: a layer is not a DXF container or something similar, a layer is defined by the layer table entry, but also EVERY entity with a reference to a layer (as DXF attribute) creates this layer without a layer table entry.

What do you want to achieve:

1. Deleting a layer definition from the Drawing?
2. Deleting all entities with a specific layer attribute?
