### ISSUE TITLE
How to get dxfattribs from line entity?

### ISSUE THREAD

**Issue by derekcbr** [mozman/ezdxf#313]
I can not figure out how to get dxfattribs from line entity?

```
msp = doc.modelspace()
lines = msp.query('LINE')
for i,line in enumerate(lines):
    print([(attrib.dxf.tag, attrib.dxf.text) for attrib in line.dxf.dxfattribs])
```
But it shows 'TypeError: 'DXFAttributes' object is not iterable'

How to get the DXFAttributes related to the line? Also is there a way to tell the difference between line and axis line by api?

**Comment by mbway** [comment]
you can use `all_existing_dxf_attribs()` to list the explicitly defined dxf attributes for this entity
```python
msp = doc.modelspace()
lines = msp.query('LINE')
for i,line in enumerate(lines):
    print([(attrib, line.dxf.get(attrib)) for attrib in line.dxf.all_existing_dxf_attribs()])
```
What do you mean by an 'axis line'?

**Comment by derekcbr** [comment]
Thanks a lot! Axis line I mean the dot line. Is it possible to tell the difference between the dot line(axis line) and the continuous line(exterior/interior wall)?
![dxf](https://user-images.githubusercontent.com/31892214/105044850-295b8e80-5aa2-11eb-895b-5bb18caad437.png)

**Comment by mbway** [comment]
you could use `RenderContext.resolve_linetype()` to determine whether a line is dashed or continous. This would work even for entities which have the linetype set to BYLAYER or BYBLOCK

**Comment by derekcbr** [comment]
Good to know that. I try below and return errors: AttributeError: 'str' object has no attribute 'dxf'
print(RenderContext.resolve_linetype(line.dxf,line.dxf.layer))

**Comment by mbway** [comment]
`resolve_linetype` an instance method not a static method. You have to construct a render context to use it.
```python
ctx = RenderContext(doc)
ctx.set_current_layout(layout)
```

**Comment by derekcbr** [comment]
Thanks a lot! It works well!
