### ISSUE TITLE
Wrong text height for ALIGNED text rendering

### ISSUE THREAD

**Issue by mozman** [mozman/ezdxf#324]
The text border calculation works well, but there is an issue with the text height for ALIGNED single line text, rendering by cad_viewer.py:

![image](https://user-images.githubusercontent.com/4230966/105595489-bbf67900-5d93-11eb-9e0a-7a27ca693825.png)

Same file in BricsCAD (same result in TrueView):
![image](https://user-images.githubusercontent.com/4230966/105595863-d4ff2a00-5d93-11eb-8392-40fa7b2028ca.png)

The text height adjustment for ALIGNED is applied here (branch `disassemble`):
https://github.com/mozman/ezdxf/blob/2f05855713d9ee302ec7356d905a051d6829bf33/src/ezdxf/addons/drawing/text.py#L205

```Python
        if alignment in ("FIT", "ALIGNED") and line_width > 1e-9:
            defined_length = (text.dxf.align_point - text.dxf.insert).magnitude
            stretch_factor = defined_length / line_width
            scale_x = stretch_factor
            if alignment == "ALIGNED":
                scale_y = stretch_factor
```

The basic idea is to apply the same stretch factor to scale_x and scale_y, but as the 1st image shows, the result is not correct. I assume this scaling should be applied anywhere else but I have no idea where.

WARNING: I moved many text related functions into a separated module: `ezdxf.tools.text`, which can be used independent from DXF entities and add-ons.

**Comment by mozman** [comment]
Test file was created by example file: https://github.com/mozman/ezdxf/blob/disassemble/examples/entities/text.py

**Comment by mozman** [comment]
Current state:
![image](https://user-images.githubusercontent.com/4230966/105624245-9fece900-5e20-11eb-92bc-cbb3edc68080.png)

Good enough for most real world cases.

**Comment by mozman** [comment]
I noticed also a slight difference for vertical MIDDLE alignment:

BricsCAD:
![image](https://user-images.githubusercontent.com/4230966/105624765-78981b00-5e24-11eb-8b00-4f1871e2eb3e.png)

cad_viewer.py:
![image](https://user-images.githubusercontent.com/4230966/105624772-89e12780-5e24-11eb-8055-c02292b8dbcb.png)

But this is maybe caused by the different fonts used. What I learned from calculating the text border box: MIDDEL means the center of the `cap_height` is shifted to the `baseline`.

I don't get the font "txt______.ttf" working: 
![image](https://user-images.githubusercontent.com/4230966/105624937-d416d880-5e25-11eb-8b9a-5e580406483b.png)

The font manager from matplotlib returns the correct font, but the displayed font looks more like (same result for cad_viewer.py and draw_cad.py):
![image](https://user-images.githubusercontent.com/4230966/105624864-391dfe80-5e25-11eb-8ba3-69ad8e9d06c7.png)

**Comment by mbway** [comment]
I agree with you that it looks like BricsCAD is vertically aligning to the capital letter center, whereas ezdxf is vertically centering to the lower case center (because that's what looked correct when I was reverse engineering) hence `VAlignment.LOWER_CASE_CENTER`. maybe `VAlignment.UPPER_CASE_CENTER` should also be calculated and used in some cases (which would be the center of an upper case `X`)?

**Comment by mozman** [comment]
Added an additional alignment UPPER_CASE_CENTER, and use it for MIDDLE_LEFT, MIDDLE_CENTER and MIDDLE_RIGHT:

cad_viewer.py:
![text_ezdxf](https://user-images.githubusercontent.com/4230966/105989571-9cb46000-60a1-11eb-886b-c8a4fd5b91fb.jpg)

BricsCAD (and TrueView):
![text_bricscad](https://user-images.githubusercontent.com/4230966/105989604-a8078b80-60a1-11eb-935c-4f75b71f1fb9.jpg)

Above example in cad_viewer.py:
![image](https://user-images.githubusercontent.com/4230966/105990229-7d6a0280-60a2-11eb-8ed9-f3540d894b9f.png)


Did **not** use it for MIDDLE, because LOWER_CASE_CENTER works well:

cad_viewer.py:
![text_middle_ezdxf](https://user-images.githubusercontent.com/4230966/105989750-d8e7c080-60a1-11eb-9dcb-6138b8b393ac.jpg)

BricsCAD:
![text_middle_bricscad](https://user-images.githubusercontent.com/4230966/105989727-cff6ef00-60a1-11eb-8890-7d0abcf95990.jpg)

Did not change anything for MTEXT - I recognized no problems.

I think we are done, I will close this issue.
