### ISSUE TITLE
How to draw a point with size attributes?

### ISSUE THREAD

**Issue by derekcbr** [mozman/ezdxf#326]
How to draw a point with bigger size like a black dot?

**Comment by mozman** [comment]
https://ezdxf.mozman.at/docs/dxfentities/point.html

**Comment by derekcbr** [comment]
I was trying below but did not work.
wmsp.add_point((mydefpoint[0],mydefpoint[1]),dxfattribs={'lineweight':120,'ltscale':4,'thickness':20})
I can not see any points. Please point out the mistakes.

**Comment by mozman** [comment]
https://ezdxf.mozman.at/docs/howto/viewer.html#dxf-entities-are-not-displayed-in-the-viewer
