### ISSUE TITLE
Hatch drawing regression

### ISSUE THREAD

**Issue by mbway** [mozman/ezdxf#328]
the following file renders correctly with ezdxf 0.14 but with the latest change to have nested polygon detection the hatches are completely skipped.
![image (53)](https://user-images.githubusercontent.com/69206249/106010143-04be7280-60b1-11eb-96f9-6991291d34d3.png)
![fig](https://user-images.githubusercontent.com/69206249/106010189-13a52500-60b1-11eb-83fd-9b7895e25b14.png)
[block_circles_with_hatch.dxf.zip](https://github.com/mozman/ezdxf/files/5881086/block_circles_with_hatch.dxf.zip)

There may be other problems, but the first one appears to be in `nested_polygon_detection`, the hatch has two paths (two circles) and in `fast_bbox_detection`:
```python
    boxed_paths = [
        # Fast bounding box construction:
        BoxStruct(BoundingBox2d(path.control_vertices()), path)
        for path in paths if len(path)
    ]
```

but since the path is an arc edge there are no control vertices so there are no bounding boxes created. `to_path()` in `draw_hatch_entity()` returns an empty path since the start and end vertices are identical

**Comment by mozman** [comment]
It's not the Path object, it's in the transformation of the Arc edge with applies a modulo 360, but this should be the same as before v0.15.

**Comment by mozman** [comment]
looks nice again :-)

![image](https://user-images.githubusercontent.com/4230966/106019179-a4d0c780-60c2-11eb-9280-445552c9aa16.png)

I hate the hatch rendering from PyQt, but it is very helpful to find such bugs.

**Comment by mbway** [comment]
great :) thanks for the fast response. I think the difference is that the version I was using didn't look for holes at all so it never had to convert the arcs to paths

**Comment by mozman** [comment]
Found an annoying fact: Vec3 to angle to Vec3 conversion:

![image](https://user-images.githubusercontent.com/4230966/106022637-58878680-60c6-11eb-9ae1-ed34c68ef154.png)

The problem seems to be in the sin function:

![image](https://user-images.githubusercontent.com/4230966/106022893-9684aa80-60c6-11eb-8c6e-6ca2c2a32447.png)

I don't know why removing the modulo operator fixed the error, because this conversion "nearly" the same.
