### ISSUE TITLE
Proportional font rendering issues

### ISSUE THREAD

**Issue by mozman** [mozman/ezdxf#333]
The magenta text frames are calculated by ezdxf with matplotlib support.

Arial Regular BricsCAD vs cad_viewer.py - this is very good:
![image](https://user-images.githubusercontent.com/4230966/106278736-84784880-623b-11eb-93f8-c0282eecfcdf.png)

Arial Narrow - `cad_viewe.py` stretches the text too wide:
![image](https://user-images.githubusercontent.com/4230966/106278633-58f55e00-623b-11eb-87ac-7f5e66b46fe4.png)

Arial Black perfect:
![image](https://user-images.githubusercontent.com/4230966/106279057-2009b900-623c-11eb-9b21-bd318bc600cc.png)

The example above shows also a problem of BOTTOM text alignment. BricsCAD (same in TrueView) renders the text with more space between baseline and descender:

Arial Regular:
![image](https://user-images.githubusercontent.com/4230966/106280137-c99d7a00-623d-11eb-97cd-323678feff13.png)

Arial Black:
![image](https://user-images.githubusercontent.com/4230966/106279459-be961a00-623c-11eb-990f-7571007f4d7f.png)

The font metrics do not show a difference which could explain this behavior. I guess this is not solvable with the tools we have.

Font measurements for Arial Regular:
```
Style name: ARIAL
Font name: arial.ttf
baseline: 0.0
cap_height: 1.0
x_height: 0.7245142981881685
descender_height: 0.2776686313032089
```
Font measurements for Arial Black:
```
Style name: Arial Black
Font name: ariblk.ttf
baseline: 0.0
cap_height: 1.0
x_height: 0.7245142981881685
descender_height: 0.27570399476096924
```

### And now really strange things

Wrong TOP text alignment for font "Baby Kruffy":
![image](https://user-images.githubusercontent.com/4230966/106280591-6d872580-623e-11eb-92e6-f81df985c1f6.png)

Font measurements:

```
Style name: Baby Kruffy
Font name: babyk___.ttf
baseline: 0.0
cap_height: 1.0
x_height: 0.9568982105060613
descender_height: 0.2832403309601693
```
Letters: "Xxp" :-)
![image](https://user-images.githubusercontent.com/4230966/106280860-bc34bf80-623e-11eb-8c1f-098e733a65d1.png)

Font Bouton, where the current font measurement can not succeed:
![image](https://user-images.githubusercontent.com/4230966/106281266-48df7d80-623f-11eb-99c1-8054b8272ec2.png)

Letters: "Xxp" :-)
![image](https://user-images.githubusercontent.com/4230966/106281336-60b70180-623f-11eb-9e5b-b774ba32d540.png)

```
Style name: BOUTON
Font name: BOUTON_International_symbols.ttf
baseline: 0.0
cap_height: 1.0
x_height: 1.0
descender_height: 0.008861940298507462
```
### Something positive at the end - regular fonts work very well:

![image](https://user-images.githubusercontent.com/4230966/106281815-05394380-6240-11eb-88bf-d1b645ae8d20.png)

![image](https://user-images.githubusercontent.com/4230966/106281932-30bc2e00-6240-11eb-9345-ba783535abd1.png)

Without the text frames it is hard to notice the difference to CAD applications:
![image](https://user-images.githubusercontent.com/4230966/106282306-b3dd8400-6240-11eb-880a-53cdb60f4872.png)

**Comment by mozman** [comment]
And `cad_viewer.py` renders SHX fonts nicer than BricsCAD:

![image](https://user-images.githubusercontent.com/4230966/106282910-87763780-6241-11eb-8d1a-0d86628345f6.png)

The marked text for the font TXT.SHX  looks good here (see #332), but the magic is that this is not the TXT.SHX font, it is the ROMANS.SHX font which maps to "romans__.ttf"

**Comment by mozman** [comment]
I recognized yet that we have to possibility to vectorize text:
![image](https://user-images.githubusercontent.com/4230966/106310531-fb293c00-6263-11eb-9372-39dc65bbb084.png)

The red polylines shows the `TextPath.vertices`, the white polylines are the polylines created by `TextPath.to_polygons()`. 
As you see the (0, 0) is an artifact and not a real boundary point of the char.

The Arial font used here uses only quadratic bezier curves, which I haven't implemented in my `Path` class, but this would be easy to add, because quadratic bezier curves are much simpler and faster than cubic bezier curves. This would add text vectorization support with the help of matplotlib.

**Comment by mozman** [comment]
First string to ezdxf Path conversion using matplotlib, exported as LWPOLYLINE entities:

![image](https://user-images.githubusercontent.com/4230966/106418551-e8c32400-6456-11eb-83df-649487d23892.png)

**Comment by mozman** [comment]
... and as HATCH entities:
![image](https://user-images.githubusercontent.com/4230966/106424220-1cf01200-6462-11eb-803c-41bfea07ea72.png)

This is finally a function that I can use in my job :-). It is not possible in Allplan to create transparent text for watermarks, and even exploding text in BricsCAD creates only outlines (LWPOLYLINES), which have to be filled afterwards.

**Comment by mozman** [comment]
This example shows the limits of my current approach for ALIGNED and FIT alignments:

![image](https://user-images.githubusercontent.com/4230966/106853776-879b8a80-66ba-11eb-987d-10ee957382af.png)

The text created by text2path (yellow) is **exact** 12 drawing units wide as defined by insert=(0, 0) and align_point=(12, 0), but TrueView and BricsCAD render the text (red) a little bit narrower and with an offset to (0, 0).

The text2path add-on scales the paths by their bounding box extents. I have no idea if it's possible to render a text to an exact length by the matplotlib TextPath() render tool, it only supports a size parameter, but no width factor or anything similar to scale the length of the text.

This is an example where ezdxf is correct, but does not match the result of CAD applications.

**Comment by mozman** [comment]
ALIGNED is solved, was my fault by introducing an arbitrary scaling factor, but this factor was necessary for at least one example:
![image](https://user-images.githubusercontent.com/4230966/106879971-166ccf00-66dc-11eb-9a71-8d9670f1f6b7.png)

**Comment by mozman** [comment]
draw_cad.py is OK (perfect!) - the error has to be in the PyQt5 backend used by cad_viewer.py:
![image](https://user-images.githubusercontent.com/4230966/106882392-f8ed3480-66de-11eb-97f3-4aca698b9147.png)

![image](https://user-images.githubusercontent.com/4230966/106882683-54b7bd80-66df-11eb-8978-85c2007f4e48.png)

**Comment by mozman** [comment]
Stretch factor of QFont was not set in the pyqt backend, but doing so makes the result worse :-(

![image](https://user-images.githubusercontent.com/4230966/106886745-854e2600-66e4-11eb-9f10-62658efacaa1.png)

**Comment by mbway** [comment]
if you want to go down this route, in my own code I'm using matplotlib to render the text paths and using Qt to display them. This way I can achieve the same results when rendering to images or displaying, but the matplotlib text rendering is unfortunately slower.

```python
from PyQt5 import QtGui as qg
from matplotlib.path import Path as MatplotlibPath

def matplotlib_path_to_qt_path(path: MatplotlibPath) -> qg.QPainterPath:
    out = qg.QPainterPath()
    assert len(path.vertices) == len(path.codes)
    points = list(reversed(path.vertices.tolist()))
    codes = list(reversed(path.codes))
    while codes:
        code = codes.pop()
        if code == MatplotlibPath.STOP:
            points.pop()
        elif code == MatplotlibPath.MOVETO:
            out.moveTo(*points.pop())
        elif code == MatplotlibPath.LINETO:
            out.lineTo(*points.pop())
        elif code == MatplotlibPath.CURVE3:
            (x1, y1), (x2, y2) = points.pop(), points.pop()
            assert codes.pop() == MatplotlibPath.CURVE3
            out.quadTo(x1, y1, x2, y2)
        elif code == MatplotlibPath.CURVE4:
            (x1, y1), (x2, y2), (x3, y3) = points.pop(), points.pop(), points.pop()
            assert codes.pop() == MatplotlibPath.CURVE4
            assert codes.pop() == MatplotlibPath.CURVE4
            out.cubicTo(x1, y1, x2, y2, x3, y3)
        elif code == MatplotlibPath.CLOSEPOLY:
            points.pop()  # will be (0, 0)
            out.closeSubpath()
        else:
            raise ValueError(code)
    return out

```

**Comment by mozman** [comment]
The drawing add-on is more your baby :-).

For me the current status is good enough as this is only a problem for certain fonts, hopefully a minority of the fonts used in real drawings.

Luckily the default fonts which I have chosen, do not look that bad. I think we are as close to the (AutoCAD) standard as we can with reasonable effort (yellow outlines by matplotlib):

![image](https://user-images.githubusercontent.com/4230966/106895134-22fb2280-66f0-11eb-9a6f-c75a42643660.png)
