### ISSUE TITLE
Create new xdf and import existing draw

### ISSUE THREAD

**Issue by s6carlo** [mozman/ezdxf#34]
Hi,
 for a small project I have to draw simple entities (lines, arc..) to create a "frame" and the add more "complex" dxf draws taken from  a given file inside this frame and save the new draw.
The draw taken from the given file have to be moved and scaled. Could someone suggest the best method to reach this result?

Thanks for this great project, actually I was looking for something similar in php, but I'm going to move to Phyton and use this.

**Comment by mozman** [comment]
It is safer to open an existing file add your changes and save it as new DXF drawing.

There exists an importer class to import model space entities and block definitions, but it is old code and not very well tested - it may/will fail, DXF files later than R12 have complex and often not well documented structures and ezdxf was never designed to do such tasks. Example usage:
https://github.com/mozman/ezdxf/blob/5cb1fb0298707d69d1b039858523b97990d85fba/integration_tests/test_import_blocks.py#L19
      
docs: https://ezdxf.readthedocs.io/en/latest/importer.html
