### ISSUE TITLE
How to categorize between exterior wall and interior wall?

### ISSUE THREAD

**Issue by derekcbr** [mozman/ezdxf#349]
I am trying to to categorize the exterior wall and interior wall by ezdxf functions. Only by geometrical sizes and coordinates, it seems quite difficult to implement. Any helps will be much appreciated!
![wall](https://user-images.githubusercontent.com/31892214/107315455-b6a66780-6ad1-11eb-8feb-177ff3af80c4.png)

**Comment by mozman** [comment]
No.
