### ISSUE TITLE
knot_values   knot_values_uniform  knot_values_by_control_points

### ISSUE THREAD

**Issue by dflstone** [mozman/ezdxf#35]
how i use **EdgePath.add_spline(fit_points=None, control_points=None, knot_values=None, weights=None, degree=3, rational=0, periodic=0)**

 from ezdxf.tools import knot_values   
ImportError: cannot import name 'knot_values'

**Comment by mozman** [comment]
Knot value helper functions now located in ezdxf.algebra.bspline like knot_open_uniform() and knot_uniform(), this module also provides other helper tools for creating splines like bspline_control_frame() which creates a valid BSpline object from *fit_points* and *degree*.

All this works just with the latest developer version!

Get required parameters for add_spline():
```
bspline = bspline_control_frame(your_fit_points, degree=3)
your_edge_path.add_spline(
  fit_points=your_fit_points,
  control_points=bspline.control_points,
  knot_values=bspine.knot_values(),
  degree=3,
)

# or simpler by helper method:
your_edge_path.add_spline_control_frame(fit_points=fitpoints)
```
see also example: https://github.com/mozman/ezdxf/blob/933e86e769c17a41afe8df6eefa2230caf619b60/examples/using_hatch.py#L146
