### ISSUE TITLE
Arc angles are given in radians, not degrees

### ISSUE THREAD

**Issue by davidmurray** [mozman/ezdxf#36]
Hello,

The documentation mentions that, for arcs, angles are [given in degrees](http://ezdxf.readthedocs.io/en/latest/arc_entity.html). However, I have found that angles are actually given in radians in my own testing. Would it be possible to correct this in the documentation?

Thanks,
David

**Comment by mozman** [comment]
According to the DXF Reference all angles using group code 50-58 are stored in DXF files in degrees.

http://help.autodesk.com/view/OARX/2018/ENU/?guid=GUID-3F0380A5-1C15-464D-BC66-2C5F094BCFB9

Did also some testing now:
```
import ezdxf

dwg = ezdxf.new('R2000')
modelspace = dwg.modelspace()

delta = 30
for count in range(12):
    modelspace.add_arc(center=(0, 0), radius=10+count, start_angle=count*delta, end_angle=(count+1)*delta)

dwg.saveas('using_arcs.dxf')
```
This outputs 12 arcs with 30 degree:
![image](https://user-images.githubusercontent.com/4230966/42462222-efa5873c-83a2-11e8-8724-f87eb955d7ec.png)

**Comment by davidmurray** [comment]
Hi @mozman 

Thanks for the quick reply. I had made in a mistake in my own code. Sorry!

Regards,
David
