### ISSUE TITLE
using R2000 version will cause every single chinese becomes unicode format

### ISSUE THREAD

**Issue by liesauer** [mozman/ezdxf#366]
![image](https://user-images.githubusercontent.com/8676741/112080083-499bec80-8bbc-11eb-9d9d-71ea6552af50.png)

![image](https://user-images.githubusercontent.com/8676741/112080112-591b3580-8bbc-11eb-8eeb-d3e7c93c0460.png)

it should be look like this, using `R2013` is fine, but autocad 2007 doesn't support `R2013` version.
![image](https://user-images.githubusercontent.com/8676741/112080403-e6f72080-8bbc-11eb-84ee-2b2c71227d08.png)

**Comment by mozman** [comment]
DXF R2007 and later uses utf-8 encoding, DXF R2004 and prior uses codepages to encode text. The `/U+xxxx` encoding is the way DXF stores characters not supported by the chosen codepage.

Try setting   `doc.encoding = gbk` for DXF R2000 to use codepage `gbk` (ANSI_936 UnifiedChinese).

For more information see: https://ezdxf.mozman.at/docs/dxfinternals/fileencoding.html

**Comment by liesauer** [comment]
@mozman it works, thanks!
