### ISSUE TITLE
A number of URLs referenced use insecure http:// connections

### ISSUE THREAD

**Issue by johnthagen** [mozman/ezdxf#367]
I noticed that the DXF reference in the generated HTML for the DXF Pretty Printer took me to

http://help.autodesk.com/view/OARX/2018/ENU/?guid=GUID-235B22E0-A567-4CF6-92D3-38A2306D73F3

A more secure version of this would be to prepend `https://` onto all of the URLs so that users are using secure connections by default.

Doing a quick search there are a number of other URLs within the project that could likely be changed to use secure `https://`.

- https://github.com/mozman/ezdxf/search?q=http%3A%2F%2F

**Comment by mozman** [comment]
Not every link will work as `https://` and I don't wanna check them all. I don't see `http://` as a problem without transferring personal data.

**Comment by johnthagen** [comment]
@mozman Would you accept a PR if I check and correct some number of those that can be fixed?

**Comment by mozman** [comment]
Yes, but this is still work for me, because I can't merge your PR blindly.

**Comment by johnthagen** [comment]
Okay, totally fine to close this issue if you'd like. Don't want to add extra unwanted work.

**Comment by mozman** [comment]
Thank you for your understanding.
