### ISSUE TITLE
How to remove the blank border of the ezdxf drawing

### ISSUE THREAD

**Issue by chibai** [mozman/ezdxf#376]
I'm trying to map the dxf entities from vector-format to pixel-format, but the render image has always some blank border.
I don't know if this is my matplotlib coding problem or ezdxf coding problem.

here's my code
```python
fig = plt.figure()  
ax = fig.add_axes([0, 0, 1, 1])  
ctx = RenderContext(dxf_doc)  
out = MatplotlibBackend(ax)  
Frontend(ctx, out).draw_layout(dxf_doc.modelspace(), finalize=True)  
fig.savefig(dxf_img_path, bbox_inches = 'tight',pad_inches = 0)  
```

![test](https://user-images.githubusercontent.com/5702248/112599043-5b92bf00-8e4a-11eb-9f0e-adcb9490d053.png)

**Comment by mbway** [comment]
It's a matplotlib problem. you just need to remove the margins in the axes before you render the document like so:
```python
fig = plt.figure()  
ax = fig.add_axes([0, 0, 1, 1])  
ax.margins(0)
ctx = RenderContext(dxf_doc)  
out = MatplotlibBackend(ax)  
Frontend(ctx, out).draw_layout(dxf_doc.modelspace(), finalize=True)  
fig.savefig(dxf_img_path, bbox_inches = 'tight',pad_inches = 0)  
```

**Comment by chibai** [comment]
> It's a matplotlib problem. you just need to remove the margins in the axes before you render the document like so:
> 
> ```python
> fig = plt.figure()  
> ax = fig.add_axes([0, 0, 1, 1])  
> ax.margins(0)
> ctx = RenderContext(dxf_doc)  
> out = MatplotlibBackend(ax)  
> Frontend(ctx, out).draw_layout(dxf_doc.modelspace(), finalize=True)  
> fig.savefig(dxf_img_path, bbox_inches = 'tight',pad_inches = 0)  
> ```

Thanks a lot. This is a stupid issue~
hahahahaha
