### ISSUE TITLE
Drawing problem on ARRAYCLASSIC presentation

### ISSUE THREAD

**Issue by chibai** [mozman/ezdxf#380]
[test.zip](https://github.com/mozman/ezdxf/files/6236421/test.zip)

![test](https://user-images.githubusercontent.com/5702248/113141705-9dfa3880-925c-11eb-8d60-25742fe57fc4.png)
```python
    fig = plt.figure(dpi=600)
    ax = fig.add_axes([0, 0, 1, 1])
    ax.margins(0)
    ctx = RenderContext(dxf_doc)
    ctx.current_layout.set_colors(bg='#FFFFFF')
    out = MatplotlibBackend(ax, font=font_manager.FontProperties(fname=font_path))
    Frontend(ctx, out).draw_layout(dxf_doc.modelspace(), finalize=True)
    fig.savefig(dxf_img_path)
```
![image](https://user-images.githubusercontent.com/5702248/113142678-c0d91c80-925d-11eb-99d2-94555be8bdc9.png)
![image](https://user-images.githubusercontent.com/5702248/113142736-d2babf80-925d-11eb-84e1-02cb50f3ffc6.png)

The drawing didn't represent correctly while processing ARRAY element

**Comment by chibai** [comment]
> I'm not familiar with the ARRAY dxf entity but excluding the text I can't see anything drawn incorrectly in the screenshot other than the lines being thicker than the screenshot above.
> If you are talking about the text not rendering correctly then that is likely an issue with the font you are using see #379

Sorry, I didn't point out. It's not the Text problem, the office chair is different for the direction. 
![image](https://user-images.githubusercontent.com/5702248/113233348-9c1e8c80-92d1-11eb-87b8-5eaa72141acb.png)
![image](https://user-images.githubusercontent.com/5702248/113233411-bb1d1e80-92d1-11eb-82f3-548ca5b91e88.png)

**Comment by mozman** [comment]
Error confirmed. 

About the font problems: The DXF file uses the font format "TTC" and the font "simsun.ttc", which is supported by the PyQT backend but not by the Matplotlib backend:

![image](https://user-images.githubusercontent.com/4230966/113241409-ef331800-92ae-11eb-9a22-5bf35a888be5.png)

"simsun.ttc" is installed on my system but the Matplotlib font manager does not recognize the font format TTC.

**Comment by mozman** [comment]
The font problem is NOT caused by Matplotlib, it is just another annoying DXF feature: The font "宋体" is only defined by XDATA the `Textstyle.dxf.font` attribute is a blank line! By replacing this blank line by "simsun.ttc", even Matplotlib works:

![image](https://user-images.githubusercontent.com/4230966/113246806-0b888200-92ba-11eb-96c6-b08b1e683c30.png)

@chibai - Was this file created by AutoCAD?

**Comment by chibai** [comment]
> The font problem is NOT caused by Matplotlib, it is just another annoying DXF feature: The font "宋体" is only defined by XDATA the `Textstyle.dxf.font` attribute is a blank line! By replacing this blank line by "simsun.ttc", even Matplotlib works:
> 
> ![image](https://user-images.githubusercontent.com/4230966/113246806-0b888200-92ba-11eb-96c6-b08b1e683c30.png)
> 
> @chibai - Was this file created by AutoCAD?
> 
> Edit: I have no idea why the PyQt backend works! I assume the default font of the PyQt backend supports chinese characters, because the `font` property is also an empty string.

Thanks very much for your answer about TEXT problem. 
Howerver, my main concern is about the different INSERT enitities appearance about the ezdxf-drawing and AutoCad-showing, Please check my reply  to mbway.
![image](https://user-images.githubusercontent.com/5702248/113251174-65a63900-92f4-11eb-9de5-efd00e14f9a0.png)
![image](https://user-images.githubusercontent.com/5702248/113251195-7060ce00-92f4-11eb-9482-681f341bc710.png)

Thank you for your contribution to the AutoCad(dwg/dxf) community!

**Comment by mozman** [comment]
I'm afraid I can't help. This is not a multi INSERT (MINSERT). However this block references are placed (ARRAY?), the result are simple INSERT entities, like the entity  13C4:

![image](https://user-images.githubusercontent.com/4230966/113280465-9bdbbc80-92e4-11eb-9cfd-eb61c50e280c.png)

The DXF representation is a simple INSERT (sx=-1; rotation=90):
![image](https://user-images.githubusercontent.com/4230966/113280623-d2193c00-92e4-11eb-8b60-b8d27d99d61d.png)

Ezdxf applies the scaling factor and the rotation angle in the same way as BricsCAD:
![image](https://user-images.githubusercontent.com/4230966/113280724-f7a64580-92e4-11eb-9733-98057dffc1dd.png)

Ezdxf v0.16:
![image](https://user-images.githubusercontent.com/4230966/113280762-07258e80-92e5-11eb-90da-20a44396b498.png)
Test file: [insert.zip](https://github.com/mozman/ezdxf/files/6242826/insert.zip)

I don't have a clue what happens here!

**Comment by mbway** [comment]
one thing that is a bit different about this file is how deeply the chairs are nested. There are 3 levels of insert entities. Maybe there is something wrong with how the transformations are combined? btw AutoCAD also interprets the file correctly

AutoCAD rendering:
![image (58)](https://user-images.githubusercontent.com/4923501/113286837-a1390700-92e4-11eb-858b-396332bd43d8.png)


![image](https://user-images.githubusercontent.com/4923501/113286757-8bc3dd00-92e4-11eb-8ae9-806c382db7d5.png)

**Comment by mozman** [comment]
OK, I try to create similar nested block structures for debugging.

**Comment by mozman** [comment]
One level deep was enough:
BricsCAD:
![image](https://user-images.githubusercontent.com/4230966/113288996-e9a9f200-92ef-11eb-83b7-f7d33a1b8b2b.png)

Ezdxf v0.16:
![image](https://user-images.githubusercontent.com/4230966/113289336-58874b00-92f0-11eb-9f43-3929c28abee1.png)

And only x-scaling is affected?!

**Comment by mozman** [comment]
The current reflection compensation does not work for multiple reflections in nested block references.

I have no idea how to solve this issue, or if the current implementation is even capable to solve this problem.

**Comment by mozman** [comment]
@mbway I added a new INSERT transformation in branch "new-insert-transformation". The implementation solves THIS issue but I am not confident if this is the correct way, see also the commit message.

I hope you have some time for testing.

ezdxf:
![image](https://user-images.githubusercontent.com/4230966/113387853-6939ce80-938d-11eb-90b2-5e0b2161a05a.png)

BricsCAD:
![image](https://user-images.githubusercontent.com/4230966/113387943-938b8c00-938d-11eb-9ce4-21df6b9fb6bf.png)
