### ISSUE TITLE
DXF file can be opened by cad2007 or above, but not by cad2007

### ISSUE THREAD

**Issue by liunx7594** [mozman/ezdxf#381]
DXF file can be opened by cad2007 or above, but not by cad2007

If using cad2007 to open DXF, an error will be reported:Error 50 in graph header, line 960.
Invalid or incomplete DXF input - drawing aborted.

The DXF file data of 960 is as follows：
![image](https://user-images.githubusercontent.com/55911351/113234922-d0e01300-92d4-11eb-9c6e-e65926a134aa.png)

My version is ezdxf 1.6
python version is python3.7

**Comment by mozman** [comment]
There exist no ezdxf version 1.6, and "cad2007" is not the reference implementation which defines if a DXF file is valid. Check this issue with Trueview, AutoCAD or BricsCAD. Only if these applications cannot open the file the error is confirmed.

As far I can see, the "error" is in the HEADER section, which is clearly an error of "cadf2007", unknown header variables should and will be ignore by every CAD application which reads DXF files. BTW: the tag combination (9, "$XCLIPFRAME"), (280, 0) is valid.

**Comment by liunx7594** [comment]
I'm sorry, the correct version should be 0.16.0.
I don't quite understand what you mean. Do you mean that cad2007 software can't handle $XCLIPFRAME?


But it's strange: I draw three ranges on my CAD。
![image](https://user-images.githubusercontent.com/55911351/113466040-441b8d80-946b-11eb-8ebd-289de996018c.png)
I export the file "drawing5.dxf" from cad2007.
And the selected format is "AutoCAD 2007 DXF (. DXF)"
Then I try to use the following code
![image](https://user-images.githubusercontent.com/55911351/113466106-a70d2480-946b-11eb-86d6-d71374420282.png)

And, I use cad2007 to open it again, and it will appear: error 50 in graph header, line 960
Invalid or incomplete DXF input - drawing aborted.
Cad2007 cannot open this file.
Finally, I try to open it with cad2016. Cad2016 successfully opened it。
But something more strange happened. It had a rectangle left
![image](https://user-images.githubusercontent.com/55911351/113466351-ae353200-946d-11eb-8f86-b26b26e21363.png)

I'm looking forward to opening this file with cad2007. What should I do?

**Comment by mozman** [comment]
Ok, pleas be more specific: cad2007 = AutoCAD 2007?

**Comment by mozman** [comment]
I see, the group code changed fron 290 to 280 by AutoCAD 2010. I will fix this.
