### ISSUE TITLE
Can block points coordinates be accessed?

### ISSUE THREAD

**Issue by derekcbr** [mozman/ezdxf#384]
Is it possible for his below information be accessed through ezdxf? And we can get the four points in the block?
Layer               SybClass                                        Handle
COLUMN |   | AcDbEntity:AcDbBlockReference | 2C7D

**Comment by mozman** [comment]
I don't understand your question. Please,  provide more information.

**Comment by derekcbr** [comment]
> I don't understand your question. Please, provide more information.

It is a square pillar (block) consists of 4 points in layer column. I can not find the 4 points.

**Comment by mozman** [comment]
This is **not** very helpful.

**Comment by jmacura** [comment]
Hi, I understood that you want to access coordinates of an inserted block, correct?
Perhaps see #214 and #30 and [this part](https://ezdxf.readthedocs.io/en/stable/blocks/insert.html) of the documentation, if it helps you somehow. I found it quite cumbersome to access block coordinates.

**Comment by derekcbr** [comment]
> Hi, I understood that you want to access coordinates of an inserted block, correct?
> Perhaps see #214 and #30 and [this part](https://ezdxf.readthedocs.io/en/stable/blocks/insert.html) of the documentation, if it helps you somehow. I found it quite cumbersome to access block coordinates.

Correct, You are right! Thank you for the help!
