### ISSUE TITLE
Image to DXF

### ISSUE THREAD

**Issue by RasmusGrift96** [mozman/ezdxf#386]
Hi,

I want to convert a bunch of images to DXF, just like it can be done at https://convertio.co/ 

It looks like ezdxf can be the solution but I'm not really sure where to start.

I upload an image -> do something with it -> than I save/write it as a DXF.

Thanks in advance!
R

**Comment by mbway** [comment]
It depends on what you want the scope of the problem to be. A bitmap image consists of pixels not geometric objects such as lines. The main challenge will be extracting the geometry from the image. At that point, constructing a dxf file from the geometry is almost trivial in comparison. I don't want to discourage you but this is a very challenging problem.

You asked for where to start so I will give you an overview of where you might want to look:

- The general problem of understanding the content of images is the field of 'computer vision'.
    - There are very good libraries such as [openCV](https://docs.opencv.org/master/d6/d00/tutorial_py_root.html) and [scikit-image](https://scikit-image.org/) with implementations of computer vision algorithms which you may find useful
- The problem of extracting text from images, called OCR (Optical character recognition). I don't have any specific recommendations here but there will be python libraries available for it

If you choose to constrain the problem to just look for straight lines in an image and generate a dxf file containing those lines then I think that should be achievable.
I would suggest using a probabilistic Hough transform to detect the line segments. [OpenCV has a function which you can use for this: HoughLinesP](https://docs.opencv.org/3.4/dd/d1a/group__imgproc__feature.html#ga8618180a5948286384e3b7ca02f6feeb). There is also [LSD](https://docs.opencv.org/master/db/d73/classcv_1_1LineSegmentDetector.html) although from memory I think this detector is intended for real world images but either should be fine. Either way you will probably get a lot of outliers that you want to filter out.

**Comment by RasmusGrift96** [comment]
Thanks for your prompt reply.
I want to use this to convert images of black lines on White background to DXF sketches I can use in solid works. (The images are not that complex, Just black and white pixels)

I'm well aware of the various computer vision techniques.
I already have my images ready in Python and I can detect the line segments. I'm just not sure how I should input these images to this library. Does it have something to do with msp.add_text?

Sorry for the questions.
Kind regards
R

**Comment by mbway** [comment]
I'm confused. some of your statements seem contradictory:
- `I can detect the line segments`: So you want to add lines to a dxf file? see [here](https://ezdxf.readthedocs.io/en/stable/layouts/layouts.html#ezdxf.layouts.BaseLayout.add_line)
- `how I should input these images to this library`: so do you want to create a dxf file with the images embedded inside the file? then see [here](https://ezdxf.readthedocs.io/en/stable/layouts/layouts.html#ezdxf.layouts.BaseLayout.add_image) (note that the file doesn't actually include the image content, but links to it and the CAD application will load in the image separately), but then why are you detecting line segments at all?
- `Does it have something to do with msp.add_text`: what does converting `images of black lines` have anything to do with text?

**Comment by RasmusGrift96** [comment]
I think we are confusing each other haha. So If I onderstand correctly this Will probably be the process:

1. I have my image.
2. I perform Hough transform to get all the start and end coordinates of all the lines of my image.
4. I do the Ezdxf setup (as seen in de example)
3. I put these coordinates into the add_line function 
4. I can export IT to a ezdxf

Not sure about the last two steps

Thanks in advance

**Comment by mbway** [comment]
note that a standard Hough transform detects lines not line segments, but that's a technicality.

I'm surprised that you can handle performing a Hough transform but not reading the ezdxf documentation but regardless, would something like this be what you are looking for:
```python
from typing import Tuple, List
import ezdxf
from ezdxf.document import Drawing
from ezdxf.addons.drawing.matplotlib import qsave


Point = Tuple[float, float]


def create_dxf_from_lines(lines: List[Tuple[Point, Point]]) -> Drawing:
    doc = ezdxf.new()
    layout = doc.modelspace()

    for a, b in lines:
        layout.add_line(a, b)

    return doc


def main():
    lines = [
        ((0, 0), (1, 1)),
        ((0, 1), (0, 2))
    ]

    doc = create_dxf_from_lines(lines)
    doc.saveas('out.dxf')
    qsave(doc.modelspace(), 'out.png')


if __name__ == '__main__':
    main()
```
the qsave is optional for if you want to also render your dxf back to an image. this might be useful for debugging.

**Comment by RasmusGrift96** [comment]
Thanks for taking the time! That's very useful!

Kind regards

**Comment by arslan-ahmad-dev** [comment]
I recently came across a great [](https://www.loadmytools.com/png-to-dxf)  which has been super useful in my projects — thought it might be helpful for others reading this too.
