### ISSUE TITLE
Rename layout.

### ISSUE THREAD

**Issue by Rahulghuge94** [mozman/ezdxf#387]
layout.rename function not working properly as it changes name of layout but when i try to get layout by name which i have set it gives keyerror.
also when i open the dxf in autocad it steel shows names i have given but doesnt get opened when i try to.

**Comment by mozman** [comment]
`Layout.rename()` is an internal API. I added this info to the documentation now. Please use `doc.layouts.rename(old_name, new_name)`to rename paper space layouts.
