### ISSUE TITLE
Insert explode error

### ISSUE THREAD

**Issue by DarkoPrelic** [mozman/ezdxf#389]
While exploding block reference that contains an arc, the center of arc doesn't get translated correctly (X coordinate sign reversed) if Scale X or Scale Y is negative, but if both are negative then its correct.

[door_explode_test.zip](https://github.com/mozman/ezdxf/files/6303494/door_explode_test.zip)

In this example when we explode a block reference center of arc is:
Vec3(-3940.478716796758, 1969.5438069471343, 0.0)
which is wrong.

**Comment by mozman** [comment]
ezdxf v0.16.1 produces the same visual result as BricsCAD, except for the OCS:

ezdxf extrusion=(0, 0, -1):
![image](https://user-images.githubusercontent.com/4230966/114644794-7aad9f80-9cd8-11eb-9e60-0c6164ff1a08.png)

BricsCAD extrusion = (0, 0, 1):
![image](https://user-images.githubusercontent.com/4230966/114644846-93b65080-9cd8-11eb-9fcf-8849b8a8a28d.png)

Both results represent the **same** ARC in WCS! 
See the docs for more information about the OCS: https://ezdxf.mozman.at/docs/concepts/ocs.html

**Comment by DarkoPrelic** [comment]
I looked up about the OCS and got the idea of what is going on with extrusion vector.
What I'm trying to achieve is when I explode that block reference I want to get coordinates of arc center and arc angle's start angle and end angle as if extrusion vector was (0, 0, 1). Is there a function for converting Arc entity from (0, 0, -1) extrusion to (0, 0, 1) extrusion or I need to code it?

**Comment by mozman** [comment]
The [OCS](https://ezdxf.mozman.at/docs/math.html#ocs-class) class can convert vertices between OCS and WCS. There exist no special function for angle conversion.

**Comment by DarkoPrelic** [comment]
We solved the problem thank you for helping.
