### ISSUE TITLE
Divide by zero error

### ISSUE THREAD

**Issue by TitanUranus365** [mozman/ezdxf#394]
I've run across an issue while using the to_splines_and_polylines functionality.

In have_bezier_curves_g1_continuity there are calls to normalize
te = (b1_pnts[-1] - b1_pnts[-2]).normalize() and ts = (b2_pnts[1] - b2_pnts[0]).normalize()

If the points are equal you get a vec3 of 0,0,0 with a magnitude of 0
This causes normalize to crash with a divide by 0 error

Thanks!

**Comment by mozman** [comment]
Please show me your data, because your are dealing with degenerated bezier curves with coincident control points (p0 == p1 or p2==p3). What was the source of the bezier curves or how were they created.

**Comment by mozman** [comment]
I just treated the symptom not the disease! Please provide your data or your code. I want to know where this degenerated bezier curves were created.

**Comment by TitanUranus365** [comment]
I wrote up a quick example


[test.zip](https://github.com/mozman/ezdxf/files/6319355/test.zip)

**Comment by mozman** [comment]
Thank you for this exceptional example.

I added a check to add linear Bèzier curves as LINE_TO commands, which creates straight line segments for this example:

![image](https://user-images.githubusercontent.com/4230966/114980654-0ec06800-9e8d-11eb-87ab-e14985caefe8.png)

It is an improvement but not perfect as you can see at the location X, with two consecutive LINE_TO commands. The triangles are the markers of the LWPOLYLINE segments.

Nice to see, that some developers can read the documentation or the source code or at least can find the examples ;).
