### ISSUE TITLE
MText change text issue

### ISSUE THREAD

**Issue by krsnsk** [mozman/ezdxf#40]
Hi Mozman,
First of thanks for this great package. It is awesome. 
I have some issues with mtext. i try to change a mtext with below code. It works with out any error. But i got an autocad error when i try to open DXF (Invalid or incomplete DXF input -- drawing discarded.).
```
import ezdxf
dwg = ezdxf.readfile("DEMO.dxf")
msp = dwg.modelspace()
for i in msp.query("MTEXT"):
    with i.edit_data() as data:
        data += "append some text" + data.NEW_LINE
        data.text = "Replacement for the existing text."
dwg.saveas("output1.dxf")  

import ezdxf
dwg = ezdxf.readfile("DEMO.dxf")
msp = dwg.modelspace()
for i in msp.query("MTEXT"):
    i.set_text("some text")
dwg.saveas("output1.dxf")  
```
I checked original and changed DXF files.  mtext group code 1 is moved under 101 (embed object) at changed file. I try to change it manually and move it to above 101 (like original). It works after this change. 

Could you please help about this issue?
Autocad 2018 / DXF version AC1032
Python 3.6.6 / ezdxf 0.8.8

Original File: [http://pasted.co/af623681](http://pasted.co/430b49ec)
Output: http://pasted.co/fca4bca9
Output Manually Edited: http://pasted.co/af623681

Output (MText part):
```
100
AcDbMText
 10
2762.147931969048
 20
2327.073414283525
 30
0.0
 40
2.5
 41
18.85176797699841
 46
0.0
 71
1
 72
5									  
 73
1
 44
1.0
101
Embedded Object
 70
1
 10
1.0
 20
0.0
 30
0.0
 11
2762.147931969048
 21
2327.073414283525
 31
0.0
 40
18.85176797699841
 41
0.0
 42
15.42803547066848
 43
15.04263301500682
 71
2
 72
1
 44
18.85176797699841
 45
12.5
 73
0
 74
0
 46
0.0
  1
Replacement for the existing text.
  0
ENDSEC
```
Original (MText part):
```
100
AcDbMText
 10
2762.147931969048
 20
2327.073414283525
 30
0.0
 40
2.5
 41
18.85176797699841
 46
0.0
 71
     1
 72
     5
  1
{\fArial|b0|i0|c162|p34;CHANGE;\P\P\PTEXT}
 73
     1
 44
1.0
101
Embedded Object
 70
     1
 10
1.0
 20
0.0
 30
0.0
 11
2762.147931969048
 21
2327.073414283525
 31
0.0
 40
18.85176797699841
 41
0.0
 42
15.42803547066848
 43
15.04263301500682
 71
     2
 72
     1
 44
18.85176797699841
 45
12.5
 73
     0
 74
     0
 46
0.0							  
  0
ENDSEC
```

**Comment by mozman** [comment]
Hi!

This will take a while, the group code (101, Embedded Object) is new to me and also undocumented by Autodesk. Maybe it helps to use an older DXF format, but I don't know when Autodesk introduced this group code.

![image](https://user-images.githubusercontent.com/4230966/43732670-942be0e2-99b2-11e8-8436-55cba45cdfdc.png)

**Comment by mozman** [comment]
The develop branch has basic support for embedded objects, ezdxf reads and writes the embedded data as it is,  no interpretation no modification, just enough to not break DXF files with embedded objects at saving.

**Comment by krsnsk** [comment]
Hi Mozman,
Thanks for your answer. I check older version mtext.set_text() works with AC1027. 

There was some differences on mtext part. At new version (AC1032) there is no XDATA. But acad put that 101 embed object.  

![image](https://user-images.githubusercontent.com/246337/43909296-ad40840a-9c02-11e8-8c82-491f2a2e4f4a.png)



I added those files (same file saved as two diffrent version) if you need another data i am happy to help you.
[acad.zip](https://github.com/mozman/ezdxf/files/2274801/acad.zip)

**Comment by mozman** [comment]
Thank you!

As you said, Autodesk replaced XDATA by Embedded Object, this is not really important for ezdxf, because XDATA for MTEXT is also undocumented like the new Embedded Object and ezdxf does not use any of this data.

The develop branch of ezdxf can read, modify and write DXF files with embedded objects without destroying them.
