### ISSUE TITLE
Ole failed to extract data

### ISSUE THREAD

**Issue by liunx7594** [mozman/ezdxf#404]
My python version is python3.7 , exdxf version is 0.16, cad  soft is Auto2016,dxffile version is Auto2007dxf.

**My DXF file contains only the following data**

![image](https://user-images.githubusercontent.com/55911351/115514545-c94dd180-a2b6-11eb-8e0e-49b9482b6cbc.png)

**I try to extract the data using the following code**

![image](https://user-images.githubusercontent.com/55911351/115517938-4464b700-a2ba-11eb-8bc7-9b8c49ef7f68.png)

**The results show that**

OLE2FRAME(#14C)
b'\x80U8\xe5\xdc\x05^\xf7\x89@\x04K\xe1}J\x1b\x83@\x00\x00\x00\x00\x00\x00\x00\x00dQ\x120U\x1a'
Traceback (most recent call last):
  File "C:/Users/L/Documents/code/PycharmProjects/1.py", line 11, in <module>
    byte_data = hex_strings_to_bytes(bin_data[0])
  File "C:\Users\L\.conda\envs\py3.7\lib\site-packages\ezdxf-0.16-py3.7.egg\ezdxf\tools\binarydata.py", line 16, in hex_strings_to_bytes
    byte_array.extend(unhexlify(hexstr))
TypeError: argument should be bytes, buffer or ASCII string, not 'int'

**I try to use**

![image](https://user-images.githubusercontent.com/55911351/115518150-7249fb80-a2ba-11eb-8cca-1c1ef66c40b6.png)

**The results show that**

OLE2FRAME(#14C)
b'\x80U8\xe5\xdc\x05^\xf7\x89@\x04K\xe1}J\x1b\x83@\x00\x00\x00\x00\x00\x00\x00\x00dQ\x120U\x1a'
Traceback (most recent call last):
  File "C:/Users/L/Documents/code/PycharmProjects/1.py", line 12, in <module>
    byte_data = hex_strings_to_bytes(bin_data)
  File "C:\Users\L\.conda\envs\py3.7\lib\site-packages\ezdxf-0.16.2b1-py3.7.egg\ezdxf\tools\binarydata.py", line 16, in hex_strings_to_bytes
    byte_array.extend(unhexlify(hexstr))
binascii.Error: Non-hexadecimal digit found

**How can I extract data from ole?
In addition, can I extract the binary data of the whole ole completely?**

**Comment by mozman** [comment]
This is binary data as bytes, and that is the data stored in OLE objects, proprietary undocumented binary data. That is also the reason why there is no support for OLE objects - they are useless in practice.

**Comment by liunx7594** [comment]
Can I export or read the data in OLE by other means? Not through ezdxf, or any other way

**Comment by mozman** [comment]
The AutoCAD SDK. But this is the wrong place to get information about that.
