### ISSUE TITLE
delete_entity cannot delete all elements

### ISSUE THREAD

**Issue by liunx7594** [mozman/ezdxf#405]
There are three lines in my DXF file.

![image](https://user-images.githubusercontent.com/55911351/115520211-80008080-a2bc-11eb-8e56-a3dfa5b61533.png)

I try to execute the following code

```
import ezdxf

cad = ezdxf.readfile('a.dxf')
msp = cad.modelspace()
for m in msp:
    msp.delete_entity(m)
cad.save()
```
The result is as follows: there is a straight line left

![image](https://user-images.githubusercontent.com/55911351/115520397-b211e280-a2bc-11eb-91af-967cc07e62a8.png)

**Comment by mozman** [comment]
Can't help without the DXF file.

**Comment by liunx7594** [comment]
My DXF file is very simple, only contains these three lines. 
Cad is AutoCad2007. 
Dxf file is 2007dxf
Ezdxf is 0.16
Python is 3.7

**Comment by mozman** [comment]
Can't help without the DXF file.

**Comment by liunx7594** [comment]
This is the source DXF file.
GitHub website doesn't seem to be able to upload DXF files, I change the suffix to TXT

[a1.txt](https://github.com/mozman/ezdxf/files/6355977/a1.txt)

This is the modified file using the code.

[a2.txt](https://github.com/mozman/ezdxf/files/6355988/a2.txt)

**Comment by mozman** [comment]
That is OK, you can also upload zip-files (.zip).

**Comment by mozman** [comment]
Never, really **never** delete objects from containers your are iterating, always create a temporary copy:

```Python
for entity in list(msp):
    msp.delete_entity(entity)
```

**Comment by liunx7594** [comment]
Okay, I will. Thank you very much

**Comment by liunx7594** [comment]
Okay, I will. Thank you very much
