### ISSUE TITLE
Layer supposed to be off are still displayed

### ISSUE THREAD

**Issue by DUPONTMatthis** [mozman/ezdxf#410]
Hello there !

I'm currently facing a situation, and I don't know if I'm misunderstanding the documentation, or if there's a real problem with this functionality.

Goal : Creating layers with some of them non visible by default when opening the DXF with a CAD software
Problem : Those supposed to be non visible actually are
Detail :

I've created many layers in my DXF : 
`    for idx, entities in `enumerate(entities_list):`
`       # Création des layers`
`       output_dxf.layers.new(name=dxfs[idx][1])`

And I've tried to set some of them as non visible with the `.off()` function : 
`        if not dxfs[idx][3]:`
`            logging.info("Layer à masquer :")`
`            logging.info(dxfs[idx][1])`
`            output_dxf.layers.get(dxfs[idx][1]).off()`
`        else:`
`            logging.info("Layer à afficher :")`
`            logging.info(dxfs[idx][1])`
`            output_dxf.layers.get(dxfs[idx][1]).on()`

As a result, I do have some layers for which layer.is_on() returns True, and some others for which it returns False (so far, it's exactly what I expect) : 
`logging.info("Liste des layers créés :")`
`    for layer in doc.layers:`
`        logging.info(layer.dxf.name)`
`        logging.info(layer.is_on())`

![ListeLayerCrees](https://user-images.githubusercontent.com/25500906/115725361-1480e680-a382-11eb-9b0a-89121435e8a1.png)

But when I open the DXF, all the layers that are supposed to be non visible end up being visible : 
![LayerVisibles](https://user-images.githubusercontent.com/25500906/115725521-367a6900-a382-11eb-9166-621e07cb7cee.png)

Do you have any clue of what's going on ? Did i miss something, is it a misuse of the `.on()` / `.off()` function ? Or is it a real issue ?

I did my work thanks to the following documentation : https://ezdxf.readthedocs.io/en/stable/tutorials/layers.html
I'll also join the DXF to this thread (I opened it with LibreCAD, does it change anything compares to others CAD softwares ?) : https://file.io/PNmCODde0CHu

Thanks you very much for any information you could give me.

Sincerely,

Matthis DUPONT

**Comment by mozman** [comment]
If I understand you correct, you are testing this with LibreCAD?

If yes - validate this by another CAD software, I don't care about bugs reported by LibreCAD users.

**Comment by mozman** [comment]
![image](https://user-images.githubusercontent.com/4230966/115739390-2f595800-a38e-11eb-92f7-88d8e5d113df.png)

In BricsCAD the 4th layer "eau_potable-inconnu" is off.

This is an error in LibreCAD.
