### ISSUE TITLE
Drawing bug for complex block definition?

### ISSUE THREAD

**Issue by chibai** [mozman/ezdxf#414]
[test.zip](https://github.com/mozman/ezdxf/files/6395951/test.zip)
```python
import matplotlib.pyplot as plt
from ezdxf import recover
from ezdxf.addons.drawing import RenderContext, Frontend
from ezdxf.addons.drawing.matplotlib import MatplotlibBackend
dxf_doc, dxf_auditor= recover.readfile('test.dxf')
fig = plt.figure(dpi=200)
ax = fig.add_axes([0, 0, 1, 1])
ax.margins(0)
ctx = RenderContext(dxf_doc)
ctx.current_layout.set_colors(bg='#FFFFFF')
out = MatplotlibBackend(ax)
Frontend(ctx, out).draw_layout(dxf_doc.modelspace(), finalize=True)
fig.savefig('test.png')
```
![test](https://user-images.githubusercontent.com/5702248/116495849-5657e280-a8d6-11eb-9711-1637a6a83351.png)
next is how it shows in AutoCad
![image](https://user-images.githubusercontent.com/5702248/116495935-87381780-a8d6-11eb-8b43-ec967a973f0d.png)

I guess the nest block definition make the work hard

**Comment by chibai** [comment]
Dear mozman,
@mozman 
I think I found related proble about the issue!

```python
from ezdxf import recover, bbox
dxf_doc, dxf_auditor= recover.readfile('test.dxf')
msp = dxf_doc.modelspace()
cache = bbox.Cache()
total_bbox = bbox.extents(msp, cache=cache)
print(total_bbox)
```

![test](https://user-images.githubusercontent.com/5702248/120314822-38830080-c30e-11eb-96c1-44b427d29b8b.png)

This is the two points in AutoCad
![1622546360(1)](https://user-images.githubusercontent.com/5702248/120314985-6e27e980-c30e-11eb-925e-0a6deee4fac6.png)

I guess the bug fix only consider the drawing location but not the bounding box location fix???

**Comment by mozman** [comment]
This is an block reference scaling (reflection) error in the bounding box calculation.
