### ISSUE TITLE
ezdxf view doesn't show true color of a filled polygon

### ISSUE THREAD

**Issue by mkondratyev85** [mozman/ezdxf#426]
If I have a polygon that is filled with color via setting an attribute 'true_color' it fills with grey when I see it via ezdxf view. While it correctly displays when I see it in Autocad.

**Comment by mozman** [comment]
1. Don't expect AutoCAD quality.
2. No example file? No screenshot? nothing?

**Comment by mkondratyev85** [comment]
[plane.zip](https://github.com/mozman/ezdxf/files/6445232/plane.zip)

In the zip file is the example dxf file created via ezdxf with attribute 'true_color' set to different values for each polygon. When I open via ezdxf view command it only shows polygons filled with grey color.

**Comment by mkondratyev85** [comment]
The version of ezdxf I use is 0.16b0

**Comment by mozman** [comment]
Thanks for the bug report, will be fixed soon.
