### ISSUE TITLE
work in ezdxf 0.16.2 but not work in ezdxf 0.16.3b0

### ISSUE THREAD

**Issue by chibai** [mozman/ezdxf#429]
[test.zip](https://github.com/mozman/ezdxf/files/6472083/test.zip)
```python
from ezdxf import recover
doc, auditor = recover.readfile('test.dxf')
print(auditor)
```
under ezdxf-0.16.3b0
![image](https://user-images.githubusercontent.com/5702248/118118413-7c759a80-b41f-11eb-8310-695bf2fa5539.png)
I got error! ezdxf.lldxf.const.DXFValueError: ACAD
under ezdxf-0.16.2
![image](https://user-images.githubusercontent.com/5702248/118118513-9b742c80-b41f-11eb-9b4e-23d65196bacc.png)

I wonder if this is a bug or just a feature for more strict dxf format

**Comment by mozman** [comment]
Thank you, that is the reason why beta releases exist.
