### ISSUE TITLE
INSERT can attach undefined attribute

### ISSUE THREAD

**Issue by aeoleader** [mozman/ezdxf#44]
From my understanding, a block is required to define attdef entities before an INSERT entity can attach attrib to itself, but during a random test I found out that ezdxf allows the user to attach undefined attributes to INSERT. I don't know whether it is a valid operation or a bug. Testing code is below:
```
### Append attribute to block
block = dxf.blocks.get('Ç°Æ¬(L)-0')
msp = dxf.modelspace()
### Add block definition
block.add_attdef('Style', (0.5, -0.5), {'height': 0.25, 'color': 3})
block.add_attdef('Size', (0.5, -10.0), {'height': 0.25, 'color': 4})
block.add_attdef('Fabric', (0.5, -20.0), {'height': 0.25, 'color': 4})

values = {
    'Style': "Gangster",
    'Size': "160/23",
    'Fabric': "Demin"
}
insert = msp.add_blockref('Ç°Æ¬(L)-0', (100, 100), dxfattribs={'xscale': 1.0, 'yscale': 1.0, 'rotation': 15})
insert.add_attrib('Style', 'Gangster')
insert.add_attrib('Size', '160/23')
insert.add_attrib('Fabric', 'Demin')
insert.add_attrib('Sdf', 'sdfs')     ### Undefined attribute
for attrib in insert.attribs():
    #attrib.is_invisible = True
    print(attrib.dxf.tag)
```
Result:

Style
Size
Fabric
Sdf

**Comment by mozman** [comment]
ATTDEF is used as template by CAD applications (AutoCAD) to create ATTRIB entities and query additional data from the user, therefore ATTDEF is not required to use an ATTRIB entity. 

_ezdxf_ uses ATTDEF by add_auto_blockref() to add an INSERT with appended ATTRIBS defined as ATTDEF in the BLOCK layout, data is provided as parameter _values_ as dict with tag: value entries.
