### ISSUE TITLE
Missing usage of the DIMENSION insert attribute

### ISSUE THREAD

**Issue by chibai** [mozman/ezdxf#453]
[test.zip](https://github.com/mozman/ezdxf/files/6581540/test.zip)
```python
import matplotlib.pyplot as plt
from ezdxf import recover
from ezdxf.addons.drawing import RenderContext, Frontend
from ezdxf.addons.drawing.matplotlib import MatplotlibBackend
dxf_doc, dxf_auditor= recover.readfile('test.dxf')
fig = plt.figure(dpi=200)
ax = fig.add_axes([0, 0, 1, 1])
ax.margins(0)
ctx = RenderContext(dxf_doc)
ctx.current_layout.set_colors(bg='#FFFFFF')
out = MatplotlibBackend(ax)
Frontend(ctx, out).draw_layout(dxf_doc.modelspace(), finalize=True)
fig.savefig('test.png')
```
drawing result:
![test](https://user-images.githubusercontent.com/5702248/120413782-812ccf00-c38b-11eb-9234-7426333ee6f9.png)

showing result in AutoCad:
![1622600201(1)](https://user-images.githubusercontent.com/5702248/120413883-aa4d5f80-c38b-11eb-9dd7-ad742e28e053.png)

**Comment by mbway** [comment]
i assume you are referring to the difference in the zoom/view rather than the colors (since you are changing the background color yourself).

ezdxf does not use view information that may be stored in the dxf file when rendering, instead it expands the view to fit all entities in view, however you can set the view limits after the fact, see #451. It looks like there are some entities far from the main drawing. This is quite common in my experience. If you scroll over to it can you see these entities in AutoCAD (make sure that all layers are visible in autocad)?

**Comment by chibai** [comment]
> i assume you are referring to the difference in the zoom/view rather than the colors (since you are changing the background color yourself).
> 
> ezdxf does not use view information that may be stored in the dxf file when rendering, instead it expands the view to fit all entities in view, however you can set the view limits after the fact, see #451. It looks like there are some entities far from the main drawing. This is quite common in my experience. If you scroll over to it can you see these entities in AutoCAD (make sure that all layers are visible in autocad)?

Got it, thank you for your answering

**Comment by chibai** [comment]
> i assume you are referring to the difference in the zoom/view rather than the colors (since you are changing the background color yourself).
> 
> ezdxf does not use view information that may be stored in the dxf file when rendering, instead it expands the view to fit all entities in view, however you can set the view limits after the fact, see #451. It looks like there are some entities far from the main drawing. This is quite common in my experience. If you scroll over to it can you see these entities in AutoCAD (make sure that all layers are visible in autocad)?

[test_no_dimension.zip](https://github.com/mozman/ezdxf/files/6583432/test_no_dimension.zip)

I manually delete the dimension entites of the picture
![test_no_dimension](https://user-images.githubusercontent.com/5702248/120457470-0edadf80-c3c9-11eb-9a2b-88b40874008d.png)

I cannot find any invisible entities, but at least 
I think the dimension inside the Insert has some problems?

**Comment by chibai** [comment]
> u increase the contrast in the image you posted

Thanks very much for yourt testing, but I really cannot select the isolate far entities in AutoCad~I will try to identity them
I think the blcok-nest-block-nest-block will finally make you crazy~

**Comment by mozman** [comment]
This is a real bug - a dimension within a block within another block and DIMENSION itself is an anonymous block. That shouldn't drive anyone crazy :), it should just work regardless of the nesting level.

**Comment by mozman** [comment]
The current implementation is not that bad:

![image](https://user-images.githubusercontent.com/4230966/120492818-b0a70000-c3ba-11eb-9e09-ba4239e8a484.png)

There must be another issue beside using DIMENSION inside nested blocks. The red DIMENSION is nested up to 3 levels deep.

**Comment by mozman** [comment]
This is the next level of incorrect DXF files: a DXF file that lies!

I reduced the content of the original file to the bare minimum:
![image](https://user-images.githubusercontent.com/4230966/120880924-a577ee00-c5cd-11eb-8939-5fe6e747ae5a.png)

I edited one DIMENSION by BricsCAD and saved the file:

![image](https://user-images.githubusercontent.com/4230966/120880946-d7895000-c5cd-11eb-931c-08c6ba2e8ee6.png)

This is the result shown by the *ezdxf* viewer:
![image](https://user-images.githubusercontent.com/4230966/120880978-056e9480-c5ce-11eb-8e0e-de871b0b40d0.png)

The red circle shows the DIMENSION rendered by BricsCAD at the correct location, the blue circle shows the original DIMENSION block content at the incorrect location.
CONCLUSION: the original content is incorrect located and BricsCAD and AutoCAD can detect the invalid location and can correct them.

I don't know how to do this.

At least this is not a real bug of *ezdxf*, it's just another DXF quirks.

**Comment by mozman** [comment]
A first idea is to check the first `POINT` entity at layer "Defpoints" against `Dimension.dxf.defpoint` (group code 10 in the DXF reference). 

BUT: I don't think the `POINT` entities are mandatory and the first `POINT` entity doesn't have to be the group code 10 "defpoint".

**Comment by mozman** [comment]
The whole issue is based on a misunderstanding of the `Dimension.dxf.insert` attribute.
