### ISSUE TITLE
Mirror operation on LWPolylines

### ISSUE THREAD

**Issue by dmtvanzanten** [mozman/ezdxf#459]
I am using ezdxf to generate a design consisting of meandering LWPolylines and would like import the exported .dxf output to Ansys HFSS. 

An example of a typical design would be
```python
from ezdxf import math
doc = ezdxf.new('R2000')
msp = doc.modelspace()

data = [(0, 0, 0), (10, 0, 1), (10, 4, 0), (0, 4, -1), (0,8,0), (10,8,0)]
line = msp.add_lwpolyline(data, format='xyb')
line.dxf.const_width = 1
```
<img src="https://user-images.githubusercontent.com/980920/121178390-bb501200-c85e-11eb-9801-b60e9a10d925.png" width=50% height=50%>

To apply mirror operations on the lwpolylines I run the following code which indeed gives me a mirrored return when checking the design using Frontend.draw_layout().
```python
m = math.Matrix44()
m[0,0] = -1
line.transform(m)
```
<img src="https://user-images.githubusercontent.com/980920/121178895-50530b00-c85f-11eb-9840-f554b675fb48.png" width=50% height=50%>

Both in AutoCAD (top) Klayout (bottom) I get the same result when I open the design using doc.saveas('model.dxf')
<img alt="AutoCAD" src="https://user-images.githubusercontent.com/980920/121179200-b8095600-c85f-11eb-806c-e7d939f61c82.png" width=50% height=50%>
<img alt="KLayout" src="https://user-images.githubusercontent.com/980920/121179314-e0915000-c85f-11eb-9737-b50fb52af999.png" width=50% height=50%>

However, in Ansys HFSS I get the following result when importing the same output .dxf file. 
<img alt="KLayout" src="https://user-images.githubusercontent.com/980920/121179657-44b41400-c860-11eb-9700-7036c867bd6d.png" width=50% height=50%>

Initially I would think this is a bug in Ansys HFSS but I noticed that applying a mirror operation in AutoCAD and saving it as .dxf would actually give me the correct result when importing into Ansys HFSS. So appearently the mirror operation done in AutoCAD is different from what I do above. 

Digging deeper into the transformations applied, I noticed that vectices of the lwpolylines actually don't change when applying the transformation, but the .dxf.extrusion attribute does change from (0,0,1) to (0,0,-1). Is this behavior correct? 

```python
data = [(0, 0, 0), (10, 0, 1), (10, 4, 0), (0, 4, -1), (0,8,0), (10,8,0)]
line = msp.add_lwpolyline(data, format='xyb')
line.dxf.const_width = 1
data1 = line.get_points()
print('Extrusion before:', line.dxf.extrusion)

m = math.Matrix44()
m[0,0] = -1
line.transform(m)
data2 = line.get_points()
print('Extrusion after:', line.dxf.extrusion)

print('Equal vertices:', hash(tuple(data1)) == hash(tuple(data2)))
```

Besides that this causes an issue from me, I can also imagine one would like to mirror a geometry without actually having the extrusion vector flip.

**Comment by mozman** [comment]
It's a working and correct implementation because you get the right result in AutoCAD, and it works for any situation. If another CAD application ignores the OCS, the extrusion vector defines that OCS, that's really not my problem. By the way, even AutoCAD uses transformed extrusion vectors for some 2D entity transformations - in the long run no CAD application that works with DXF can ignore the OCS, not even those that only work in 2D.

**Comment by dmtvanzanten** [comment]
To be honest I have next to no knowledge about OCS and WCS other than the explanations at the ezdxf readthedocs. Could you perhaps comment on the following behavior.

I use the same code as above to generate my designs but this time I set the `.dxf.thickness` attribute to some nonzero value using the `dxfattribs={'thickness': 0.3}` keyword attribute in the `msp.add_lwpolyline()` call. Next I save the design using the `doc.saveas()` method like earlier. 

When I don't apply a mirror operation (similar as above) to the lpolyline entity, I get the following result (figure below) when I open the design in AutoCAD. Note that the entity is extruded in the **positive** z-direction. 
<img src="https://user-images.githubusercontent.com/980920/121218032-ac7b5680-c882-11eb-8bf7-2056cbadc386.png" width=80%>

When I do apply a mirror operation to the lpolyline entity, I get the following result (figure below) when I open the design in AutoCAD. Note that the entity is extruded in the **negative** z-direction. 
<img src="https://user-images.githubusercontent.com/980920/121218174-cf0d6f80-c882-11eb-8aab-4f4145d78896.png" width=80%>

Finally, when I load the first design (without mirror operation apllied), and apply a mirror operation in AutoCAD alone the +y-direction I get the following (figure below). Note that the entity remains extruded in the **positive** z-direction.  
<img src="https://user-images.githubusercontent.com/980920/121218670-3d523200-c883-11eb-80ca-286dd9b8c460.png" width=80%>

I fully agree with you that it is of no concern to ezdxf when other dxf implementions are not complete and ignore the OCS. 

If, considering the above, you think the implementation of transformations in ezdxf is indeed correct, could you please point me to how I would be able to mirror an entity while keeping the extrusion direction unchanged..

**Comment by mozman** [comment]
The "thickness" transformation of *ezdxf* is incorrect and will be fixed.

**Comment by mozman** [comment]
The fixed OCS transformation produces the expected result by using a negative thickness:
![image](https://user-images.githubusercontent.com/4230966/121287639-39093180-c8e2-11eb-9547-28d0621649ea.png)

**Comment by dmtvanzanten** [comment]
Thank you for you swift replies and all the work.

I have been looking at this issue a little bit more as well but from a different angle. I'm still using the exdxf version as pulled from conda-forge. Using that version and with the following change, I'm able to produce the images below. 

Changes to `transform_extrusion()` in [transformtools.py](https://github.com/mozman/ezdxf/blob/b67fb7862b5ee837b592ea53d9f7f5bebc422b4a/src/ezdxf/math/transformtools.py#L46). 
```python
# replaced line 73 with the following
if m.determinant() < 0:
  new_extrusion = y_axis.cross(x_axis).normalize()
else:
    new_extrusion = x_axis.cross(y_axis).normalize()
```

Changes to `LWPolyline.transform()` in [lwpolyline.py](https://github.com/mozman/ezdxf/blob/b67fb7862b5ee837b592ea53d9f7f5bebc422b4a/src/ezdxf/entities/lwpolyline.py#L338). 
```python
# replaced lines 349-352 with 
f = -1 if m.determinant() < 0 else 1
lwpoints = [
  (v[0], v[1], p[2], p[3], f*p[4]) 
  for v, p in zip(vertices, self.lwpoints)
]
```
I use the following code to test the output. 
```python
doc = ezdxf.new('R2000')
msp = doc.modelspace()

ocs = OCS((0, 1, 1))
data = [(0, 0, 0), (10, 0, 1), (10, 4, 0), (0, 4, -1), (0,8,0), (10,8,0)]
line1 = msp.add_lwpolyline(data, format='xyb', dxfattribs={
    'thickness': 0.3,
    'extrusion': ocs.uz})
line1.dxf.const_width = 1

ocs = OCS((0, 1, 1))
line2 = msp.add_lwpolyline(data, format='xyb', dxfattribs={
    'thickness': 0.3,
    'extrusion': ocs.uz})
line2.dxf.const_width = 1
```

The the two following figures only _line1_ is visible and from two different angles. 
![image](https://user-images.githubusercontent.com/980920/121311735-fc9afd00-c904-11eb-80db-89d3543bbb32.png)

![image](https://user-images.githubusercontent.com/980920/121311496-c3628d00-c904-11eb-9565-a3314d5243f0.png)

In the next image I include _line2_ and apply the following transform to it. This should be a mirror operation in the XZ plane.
```python
m = math.Matrix44.chain(
    math.Matrix44.z_rotate(0),
    math.Matrix44.scale(-1,1,1)
)
line2.transform(m)
```
![image](https://user-images.githubusercontent.com/980920/121311920-29e7ab00-c905-11eb-93a1-00590c664ec3.png)

In the next image I include _line2_ but apply a different transform to it. This should be a mirror operation in the YZ plane.
```python
m = math.Matrix44.chain(
    math.Matrix44.z_rotate(0),
    math.Matrix44.scale(1,-1,1)
)
line2.transform(m)
```
![image](https://user-images.githubusercontent.com/980920/121311035-4afbcc00-c904-11eb-88ec-be281ce9fc10.png)

Regardsless the transformation in the *Z plane, the extrusion vector remain unchanged in the Z-direction which is roughly what I would expect from transformation in any *Z plane. Consisder for example which rotates around Z by pi/2 and mirrrors in YZ plane. 

```python
ocs = OCS((0, 1, 1))
data = [(0, 0, 0), (10, 0, 1), (10, 4, 0), (0, 4, -1), (0,8,0), (10,8,0)]
line1 = msp.add_lwpolyline(data, format='xyb', dxfattribs={
    'thickness': 0.3,
    'extrusion': ocs.uz})
line1.dxf.const_width = 1

ocs = OCS((0, 1, 1))
line2 = msp.add_lwpolyline(data, format='xyb', dxfattribs={
    'thickness': 0.3,
    'extrusion': ocs.uz})
line2.dxf.const_width = 1

m = math.Matrix44.chain(
    math.Matrix44.z_rotate(np.pi/2),
    math.Matrix44.scale(1,-1,1)
)
line2.transform(m)
```

Form the second image below it is visible that both extrusion vectors are point in the same z-direction. 
![image](https://user-images.githubusercontent.com/980920/121316419-99f83000-c909-11eb-8888-84b10790e049.png)

![image](https://user-images.githubusercontent.com/980920/121316695-de83cb80-c909-11eb-9001-b2cd52707dff.png)

I don't have any good idea about how these changes to teh code will affect other use-cases. Do you perhaps have a bunch of tests I can run to check whether these changes will break anything? I would be happy to do that I case you would consider tkaing this approach. 

I will now go ahead and try these test designs with the recent chanegs you applied. Personally I would be less happy to use a negative thickness to get the extrusion to go in the positive direction. But if the changes above break too much I can perfectly understand you would rather take the negative thickness solution.

**Comment by mozman** [comment]
There are some tests in the repo: https://github.com/mozman/ezdxf/tree/master/tests

**Comment by mozman** [comment]
The critical OCS entities are ARC (start, end angle) and LWPOLYLINE/POLYLINE with bulge values, HATCH/MPOLYGON with ARC and/or ELLIPSE (also OCS in HATCH) as edge paths and LWPOLYLINE with bulge values as boundary paths.

**Comment by mozman** [comment]
As I said, the current solution works in 2D / 3D for all situations and in reality it doesn't matter what the user expects as long as the geometric result is correct - and it has taken a very long way to get these usable results.

**Comment by mozman** [comment]
```Python
# replaced line 73 with the following
if m.determinant() < 0:
  new_extrusion = y_axis.cross(x_axis).normalize()  # LH: left-handed
else:
    new_extrusion = x_axis.cross(y_axis).normalize()  # RH: right-handed
```

Your code marked with `LH` generates an extrusion vector for a left-handed Cartesian coordinate system, which does not work well as an OCS, since all angles in OCS objects would have to be adjusted differently depending on the orientation of the OCS (`LH` or `RH`), like you have shown in the following lines for the value `bulge`. In addition, the function `determinant()` is very computationally intensive. Without a compelling reason, I don't want to waste computing time because Python is already slow anyway.

**Comment by dmtvanzanten** [comment]
I imlemented the suggested changes picking up from commit [b3028f3](https://github.com/dmtvanzanten/ezdxf/commit/b3028f33678ac6f3ee6e07813b367f28253f66e1) and ran the test from the repo. Indeed there are some test that fail which are related to transformations applied to lwpolylines, arcs and text. The rest all runs fine. I did some work to see how difficult it is to adjust the lwpolylines/arcs/text entities to make them compatible again. This work is available [here ](https://github.com/dmtvanzanten/ezdxf/tree/dvz_pre459_mirror_issue). The branch also contain some work on the Matrix44 class (both the cython and python implementation) to add a simplified determinant33() method. 

The changes that had to be applied in the work above indeed relate to flipping bulge values and arc start and end angles. I did notice however that this is exactly what AutoCAD does when you apply a mirror transformation to an arc (even when the extrusion vector != [0,0,1]). More generally, AutoCAD does the same operation on the extrusion vector as I suggest above. I don't agree that this transforms a right to a left-handed system because the OCS is always right-handed. Sure, in case you transform the x-axis, y-axis and z-axis using a mirror transformation, the resulting axes will span a left-handed system, but that is just what a mirror operation does.

**Comment by mozman** [comment]
The OCS is only defined by the extrusion vector and the x- and y-axis are calculated by the [Arbitrary Axis Algorithm](https://help.autodesk.com/view/OARX/2018/ENU/?guid=GUID-E19E5B42-0CC7-4EBA-B29F-5E1D595149EE) by applying the right-hand rule. How should a left-handed coordinate system be stored?

I don't waste my time to check if your solution produces the geometrically same result for ALL transformations of OCS entities like the existing solution already does.
