### ISSUE TITLE
Unexpected Spline behaviour

### ISSUE THREAD

**Issue by mbway** [mozman/ezdxf#463]
Some of my code relies on the assumption that certain dxf entities can contain multiple drawing primitives (like Insert) and others cannot (like Point). With the latest ezdxf release I have encountered a problem where a Spline appears to have multiple children (previous ezdxf versions did not do this). This is caused by `make_path` returning a path containing LineTo commands in addition to adjacent Curve4To commands. My custom backend can chain adjacent Curve4To commands into a single spline representation but it cannot represent a sequence of Curve4To and LineTo as a 'spline'.

I suppose you could argue either way, but I don't think that paths formed from splines should contain straight line segments in them.

[example.zip](https://github.com/mozman/ezdxf/files/6633000/example.zip)

```python
import ezdxf
from ezdxf.path import make_path

if __name__ == '__main__':
    doc = ezdxf.readfile('example.dxf')
    spline = list(doc.modelspace())[0]
    path = make_path(spline)
    for command in path:
        print(command.type)
```
outputs:
```
Command.CURVE4_TO
Command.CURVE4_TO
Command.LINE_TO
Command.LINE_TO
Command.LINE_TO
Command.LINE_TO
Command.LINE_TO
Command.LINE_TO
Command.LINE_TO
Command.LINE_TO
Command.LINE_TO
Command.LINE_TO
Command.LINE_TO
```

**Comment by mbway** [comment]
Thinking about it, I should be able to work around this by representing each line segment as a bezier curve with control points spaced accordingly, so it isn't a huge issue, but it the behaviour is unintended then it might still be worth looking at?

**Comment by mozman** [comment]
I guess this happend because there are very flat bezier curve segments, where the 1st and the 2nd, and the 3rd and the 4th control point are very close , which caused another issue #394. 

This is maybe the source for this issue: https://github.com/mozman/ezdxf/blob/b7e8d5793d4209e294722856a7e7e1520bf6ea04/src/ezdxf/path/tools.py#L619

**Comment by mbway** [comment]
There is a problem with `Path.all_lines_to_curve*()` because it can result in an empty path being returned. I think it's just another tolerance issue with an isclose deciding whether the line segment is too short to convert. You can probably safely ignore this but I'm just letting you know:
```python
import ezdxf
from ezdxf.path import make_path

dxf_doc = ezdxf.new()
dxf_layout = dxf_doc.modelspace()
spline = dxf_layout.add_spline(degree=3, dxfattribs={'layer': 'abc'})
x = 1e14
spline.control_points = [(x, x),
                         (x + 0.1, x + 0.1),
                         (x + 0.2, x + 0.2),
                         (x + 0.3, x + 0.3),
                         (x + 0.4, x + 0.4),
                         (x + 0.5, x + 0.5),
                         ]

path = make_path(spline)
print(list(path))
path.all_lines_to_curve4()
print(list(path))
```
prints:
```
[LineTo(end=Vec3(100000000000000.3, 100000000000000.3, 0.0)), LineTo(end=Vec3(100000000000000.2, 100000000000000.2, 0.0)), LineTo(end=Vec3(100000000000000.0, 100000000000000.0, 0.0))]
[]
```
