### ISSUE TITLE
How to use linetypes?

### ISSUE THREAD

**Issue by Cyberduke01** [mozman/ezdxf#467]
I am trying to change the different type of lines to draw. I followed the tutorial on adding the different lines seen here:

https://ezdxf.readthedocs.io/en/stable/tutorials/linetypes.html

But when I somehow not finding how to change the type of the line I am actually drawing, here is an example of what I am trying to achieve:
msp.add_line(start,end, dxfattribs={linetype: 3})

**Comment by chibai** [comment]
This is not how to ask question.~
1. Please show the full code(quote with ```python and ```), and save to dxf file.
2. Then upload the dxf file(compress to zip) to prove your concern.

**Comment by mozman** [comment]
Most DXF resources are referenced by their name like `... dxfattribs={"linetype": "DOTTED}` or `entity.dxf.linetype = "DOTTED"`, for more information about the common graphical DXF attributes see the [docs](https://ezdxf.readthedocs.io/en/stable/dxfentities/dxfgfx.html#common-graphical-dxf-attributes).
