### ISSUE TITLE
Support for config files

### ISSUE THREAD

**Issue by mozman** [mozman/ezdxf#483]
Added support for config files: https://ezdxf.mozman.at/docs/options.html

@mbway If you have the time, please see if this works as another developer would expect.

**Comment by mbway** [comment]
looks like a good idea. On POSIX it's good practice to use the [XDG directories](https://wiki.archlinux.org/title/XDG_Base_Directory)
```python
ezdxf_config_dir = os.path.join(os.getenv("XDG_CONFIG_HOME", os.expanduser("~/.config")), "ezdxf")
ezdxf_cache_dir = os.path.join(os.getenv("XDG_CACHE_HOME", os.expanduser("~/.cache")), "ezdxf")
```

For the external editor, I think it's best to store that as a command string to be formatted for maximum compatibility. For example if I wanted to use gvim, i could enter
```
text_editor = gvim +{line_number} "{path}"
```
then in python this could be formatted with `text_editor.format(line_number=..., path=...)`

if my editor didn't support passing line numbers, i could just exclude `{line_number}` from the command and it won't get used.

small note: in the documentation, the `config file loading order` list seems reversed. shouldn't the highest priority come first in the list?

Another thing for the documentation: as a user, it would be nice to know what trade-offs there are for the options in addition to what they provide. Like I imagine `auto_load_fonts` has the drawback of making scripts take longer to load? but typically is this loading time significant? Why might I want to set it to true / false?

**Comment by mozman** [comment]
Thank you for your feedback!

I will add a separated comment for each topic.

Loading order of config files:

The behavior shown in a short example:
First loaded config file and therefore lowest priority: `~/.ezdxf/ezdxf.ini` from the users home directory:
option_1 = A
option_2 = B

next is `ezdxf.ini` in the current working directory:
option_1 = B

The second config file does not replace the first one, just option_1 is set to B, option_2 stays as it is:

current config:
option_1 = B
option_2 = B

The next config file is specified by the environment variable `EZDXF_CONFIG_FILE` and has higher priority than the 2 before:
option_2 = C

final config:
option_1 = B
option_2 = C

The later a config file is loaded the higher is its priority and the highest priority has the config file loaded by the developer after importing `ezdxf`, which overrides all previous loaded config options:

```Python

import ezdxf

ezdxf.options.read_file("my_configuration.ini")

```

Maybe the term "priority" is misleading and should be left out.

**Comment by mbway** [comment]
ok. It is slightly confusing because I wouldn't expect the default settings file to be read if I specify an alternative, but there is nothing wrong with that so long as it's explained
