### ISSUE TITLE
Is there an API that does not export files and only gets DXF content

### ISSUE THREAD

**Issue by qilong777** [mozman/ezdxf#484]
I just want Python to generate the corresponding DXF content from the data and return it to Node. If not, maybe I'll make my own

**Comment by qilong777** [comment]
Generating files can be a performance drain because of the amount of data.

**Comment by mozman** [comment]
???

**Comment by mbway** [comment]
@qilong777 do you mean like being able to write to a BytesIO or StringIO to avoid writing to the filesystem? It looks like that is already supported with:
```python
out = io.BytesIO()
doc.write(out, fmt='bin')
out.seek(0)
data = out.read()
```

**Comment by mozman** [comment]
There is a method to create base64 encoded data from a DXF document:
https://ezdxf.mozman.at/docs/drawing/drawing.html#ezdxf.document.Drawing.encode_base64

```Python

# return data to browser ...
return b'data:application/octet-stream;base64,' + doc.encode_base64()

```
