### ISSUE TITLE
Support for AEC entities?

### ISSUE THREAD

**Issue by mbway** [mozman/ezdxf#495]
I came across a CAD file with [AEC entities](https://birchlerarroyo.com/autocad/what-is-aec-objects-in-autocad.html) and noticed that ezdxf was not rendering them.
Attached is a dwg file with an AEC entity (wall) and a dxf file which was created by converting the dwg file with ODAFileConverter. It seems that ODA is preserving the entity in some way because the entity is visible in AutoCAD, however nothing appears when viewed by ezdxf.

The entity seems to be a proxy entity. When drawn the entity is skipped with
```
WARNING: ACAD_PROXY_ENTITY(...) entity was skipped because: "Cannot parse DXF entity"
```

[aec_wall.zip](https://github.com/mozman/ezdxf/files/6839744/aec_wall.zip)

![image (45)](https://user-images.githubusercontent.com/4923501/126140692-85829d2b-ef83-407a-92d7-7b48b3487fa0.png)
![image (44)](https://user-images.githubusercontent.com/4923501/126140696-a24da19e-595a-495a-9920-603d5f5ec63a.png)

**Comment by mozman** [comment]
AEC is an undocumented data format embedded in DXF in a kind like ACIS, the data is just preserved, but will never be processed by ezdxf. This is way beyond the scope of ezdxf.

**Comment by mbway** [comment]
do you think the proxy is also encoded in a custom format? shouldn't the proxy contain primitives for when the application doesn't support the custom data type?

**Comment by mbway** [comment]
I can't find any specification for AEC so I think reverse engineering would be the only way to decipher the data unfortunately. I did find [this](http://paulbourke.net/dataformats/sat/sat.pdf) for ACIS though which you might have already seen. looks like the data is essentially lisp code for constructing the entity, stored in a binary format.

It looks like I will be able to manually explode these entities using AutoCAD as a workaround for supporting these entities natively

**Comment by mozman** [comment]
I know this ACIS documentation for version 7.0 the last number version was 25.0 in 2014, see #420.

**Comment by mozman** [comment]
Added basic support for ACAD_PROXY_ENTITY:

- `drawing` add-on shows proxy graphics for all unsupported entities if a proxy graphic exist
- convert proxy graphic into DXF entities:

```Python

import ezdxf
from ezdxf.proxygraphic import ProxyGraphic

doc = ezdxf.readfile("aec_wall.dxf")
msp = doc.modelspace()

proxy_entities = list(msp.query("ACAD_PROXY_ENTITY"))
for proxy_entity in proxy_entities:
    if proxy_entity.proxy_graphic:
        for entity in ProxyGraphic(proxy_entity.proxy_graphic, doc).virtual_entities():
            msp.add_entity(entity)
        proxy_entity.destroy()  # remove original proxy entity if not required anymore

```

This may reveal some errors in the `ProxyGraphic()` class if AEC entities use more complex proxy graphic entities like `mesh` or `shell` which if have never seen in the wild.

**Comment by mbway** [comment]
this is great. Thank you for adding this feature. There are still situations where the proxy will not be drawn. For example if the AEC entity is inside a block the error is `ACAD_PROXY_ENTITY(...) entity was skipped because: "non copyable"` rather than `Cannot parse DXF entity` and no proxy is drawn. Is this a simple fix or would it require lots of changes? Here is an example

[aec_inside_block.zip](https://github.com/mozman/ezdxf/files/6847557/aec_inside_block.zip)

**Comment by mbway** [comment]
should there be a check that `self.proxy_graphics != IGNORE_PROXY_GRAPHICS` before drawing the proxy of the unsupported entity?

**Comment by mozman** [comment]
Processing proxy entities inside block references is complicated, because the current algorithm requires to copy an entity and transformed this copy into a new location. I can not copy complex or unknown entities i don't understand like the ACAD_PROXY_ENTITY. A solution would be to just copy the virtual proxy graphic entities and transform them, but this is a complete new feature - I will look at this.

**Comment by mbway** [comment]
I'm not sure what the best solution for this would be, but the entity stack with `enter_entity` and `exit_entity` aren't properly maintained when drawing a `DXFTagStorage` (so OLE2FRAME or proxy graphic). For the time being I'm just going to use
```python
    def handle_dxf_tag_storage(self, entity: DXFTagStorage) -> None:
        self.out.enter_entity(entity, Properties())
        super().handle_dxf_tag_storage(entity)
        self.out.exit_entity(entity)
```
in my custom frontend. It's not technically correct as `DXFTagStorage` doesn't inherit from `DXFEntity` and the `Properties()` is just a placeholder but it does at least provide something on the stack while drawing these entities

**Comment by mozman** [comment]
Idea: wrapping entities which do not inherit from `DXFGraphic` into a `DXFGraphicProxy` object which do inherit from `DXFGraphic` and passing the `dxf` namespace attribute and the `virtual_entities()` method through. This should be good enough for internal usage in the `drawing` add-on. This proxy object should never leave the drawing add-on.

The `DXFTagStorage` storage class has now also a `virtual_entities()` method but is not a real graphic entity. By wrapping each `DXFTagStorage` into `DXFGraphicProxy`, we could remove the special handling of the  `DXFTagStorage` entity:

```Python
    def draw_entities(...):
        for entity in entities:
            if not isinstance(entity, DXFGraphic):
                entity = DXFGraphicProxy(entity)
            properties = self.ctx.resolve_all(entity)
            self.override_properties(entity, properties)
            if properties.is_visible:
                self.draw_entity(entity, properties)
            else:
                 self.skip_entity(entity, "invisible")
```

OLE2FRAME handling has to be adjusted (or gets a minimal implementation), but this is a minor effort to get a universal solution.
