### ISSUE TITLE
Conda package for ARM systems down-reved

### ISSUE THREAD

**Issue by ryangoss** [mozman/ezdxf#503]
The versions of ezdxf available from conda are close to latest (0.16.4), but for ARM based Mac (e.g. M1) and arm32 (e.g. Raspberry Pi) are significantly older (0.14.2).  At time of writing this the latest release of (0.16.5 was released 3 days ago).

https://anaconda.org/conda-forge/ezdxf
 linux-64  v0.16.4
 win-64  v0.16.4
   noarch  v0.14.2
 osx-64  v0.16.4

**Comment by mozman** [comment]
I do not maintain the anaconda packages.
