### ISSUE TITLE
Incorrect layer color 

### ISSUE THREAD

**Issue by TommyK82** [mozman/ezdxf#508]
I seem to have a similar issue then in the issue "Incorrect layer color 7 resolving in drawing add-on #227"

After updating from 16.1 to 16.5 this is not longer  working:

RenderContext.current_layout.set_colors(bg='#FFFFFF') 

The backgroundcolor is now  black instead of white

**Comment by mozman** [comment]
@mbway Your commit 8680f4822e8873b28ed0dfdb9d486341ba7c5aac resets the current layout and the associated foreground and background color

**Comment by mbway** [comment]
calling `backend.set_background()` after calling `frontend.draw_layout()` should still work right? but you won't be able to control whether ACI color 7 is drawn as light or dark.

Hopefully my pull request addresses this issue and gives back full control while being easy to use
