### ISSUE TITLE
cannot set layer name directly on a polyline3d entity

### ISSUE THREAD

**Issue by ghemann** [mozman/ezdxf#510]
There seems to be 2 ways to attach an entity to a layer, either using the `dxfattribs` when calling the `add_polyline3d`, `add_lwpolyline`, etc functions, or assign after the object creation using `entity.dxf.layer = <layer_name>`.

With `add_polyline3d` specifically though, it seems I have to use the attributes tag.  If I try to set the name on the entity after creation, I can print `entity.dxf.layer` and it says it took it, but when i load the file into CAD, it never took and defaults to layer 0.   Seems specifically with polyline3d though, other entities seem ok.   I've tried this with both 0.15.1 which I currently use, and the 0.16.5 version (latest at the time of posting this).

**Comment by mozman** [comment]
Read the docs: https://ezdxf.readthedocs.io/en/stable/usage_for_beginners.html#examine-dxf-entities

**Comment by ghemann** [comment]
Not sure this document answers the question.   Why would the functionality be different between lwpolyline and a 3d polyline?

**Comment by mozman** [comment]
There is no different handling for DXF attributes in LWPOLYLINE or POLYLINE entities, show a short example for what you did and what you expect.
