### ISSUE TITLE
Generated DXF files can not be opened in TrueView

### ISSUE THREAD

**Issue by BerndiDasBrot** [mozman/ezdxf#52]
Hi. I'm trying to open a DXF file (readfile) and just save it first again (saveas). When I open this new file I get an error message from Autodesk TrueView:

Group 280 (was-a-zombie-flag) expected on line 180.
Invalid or incomplete DXF input -- drawing discarded.

I also tried a cleanup. Without success. What can i do?:-( See attachment, please. I use Python 3.7.0, ezdxf 0.8.8 and TrueView 2018.

[dxf_test.zip](https://github.com/mozman/ezdxf/files/2460020/dxf_test.zip)

**Comment by mozman** [comment]
This is an upgrade error from DXF version R13/R14 to R2000, ezdxf has no direct support for DXF R13/R14 files. The bug is fixed in the next release v0.8.9 and in the current develop branch.
