### ISSUE TITLE
DXFValueError since v0.14

### ISSUE THREAD

**Issue by Korijn** [mozman/ezdxf#521]
I've been working with ezdxf for a while to parse DXF files the company I work for produces.

Since v0.14 I get the following error when trying to load files `ezdxf.lldxf.const.DXFValueError: All entities have to be on the same layout (modelspace or any paperspace layout but not a block).`

Looks like this is the problem:

```
(Pdb) ![(e.dxf.owner, e) for e in entities]
[('1F', <class 'ezdxf.entities.line.Line'> LINE(#1B9)),
 ('1F', <class 'ezdxf.entities.line.Line'> LINE(#E4)),
 ('1F', <class 'ezdxf.entities.line.Line'> LINE(#1B7)),
 ('1F', <class 'ezdxf.entities.line.Line'> LINE(#18F)),
 ('1F', <class 'ezdxf.entities.line.Line'> LINE(#72)),
 ('1F', <class 'ezdxf.entities.line.Line'> LINE(#E0)),
 ('1F', <class 'ezdxf.entities.line.Line'> LINE(#ED)),
 ('1F', <class 'ezdxf.entities.line.Line'> LINE(#DB)),
 ('1F', <class 'ezdxf.entities.line.Line'> LINE(#76)),
 ('1F', <class 'ezdxf.entities.line.Line'> LINE(#DC)),
 ('1F', <class 'ezdxf.entities.line.Line'> LINE(#192)),
 ('1F', <class 'ezdxf.entities.spline.Spline'> SPLINE(#212)),
 ('1F', <class 'ezdxf.entities.line.Line'> LINE(#1A5)),
 ('1F', <class 'ezdxf.entities.line.Line'> LINE(#DD)),
 ('1F', <class 'ezdxf.entities.line.Line'> LINE(#DE)),
 ('1F', <class 'ezdxf.entities.spline.Spline'> SPLINE(#202)),
 ('1F', <class 'ezdxf.entities.line.Line'> LINE(#E9)),
 ('2', <class 'ezdxf.entities.layer.Layer'> LAYER(#19A)),    <----
 ('1F', <class 'ezdxf.entities.line.Line'> LINE(#DA)),
 ('1F', <class 'ezdxf.entities.line.Line'> LINE(#EB)),
 ('1F', <class 'ezdxf.entities.line.Line'> LINE(#183)),
 ('1F', <class 'ezdxf.entities.line.Line'> LINE(#1AC)),
 ('1F', <class 'ezdxf.entities.spline.Spline'> SPLINE(#1F6)),
 ('1F', <class 'ezdxf.entities.line.Line'> LINE(#E7)),
 ('1F', <class 'ezdxf.entities.line.Line'> LINE(#1A1)),
 ('1F', <class 'ezdxf.entities.line.Line'> LINE(#197)),
 ('1F', <class 'ezdxf.entities.line.Line'> LINE(#14A)),
 ('1F', <class 'ezdxf.entities.line.Line'> LINE(#19D)),
 ('1F', <class 'ezdxf.entities.line.Line'> LINE(#16C)),
 ('1F', <class 'ezdxf.entities.line.Line'> LINE(#1B6)),
 ('1F', <class 'ezdxf.entities.line.Line'> LINE(#1A0)),
 ('1F', <class 'ezdxf.entities.line.Line'> LINE(#1AA)),
 ('1F', <class 'ezdxf.entities.line.Line'> LINE(#1AD)),
 ('1F', <class 'ezdxf.entities.line.Line'> LINE(#70)),
 ('1F', <class 'ezdxf.entities.line.Line'> LINE(#F4)),
 ('1F', <class 'ezdxf.entities.line.Line'> LINE(#EC))]
```

I'm wondering if there's anything I can do with ezdxf to fix the problem or load the file regardless, other than staying at v0.13.1?

**Comment by mozman** [comment]
More information is needed to help. The first issue I see is a LAYER table entry in the same container as graphical entities, which is not possible, valid or useful. A LAYER entry can only exist in the LAYERS table.

**Comment by Korijn** [comment]
Well, I understand that, but I have a database full of files with this kind of problem. With ezdxf 0.13.1 I was able to query the files and grab whatever data I needed from the files.

With the new versions I can't anymore. Is theresome way to disable the validation?

**Comment by mozman** [comment]
No, because this is more than a `DXFValueError`, it is an `DXFStructureError`.

This error message appears only in `DXFGroup.set_data()`, there are 2 scenarios:

1. You are loading an invalid DXF files - discard it!
2. You create this invalid structure - don't do it!

**Comment by mozman** [comment]
While this is a true DXF structural error, AutoCAD will open files with such errors without complaint.

**Comment by Korijn** [comment]
Unfortunately I am not in a position to discard these files, and have to work with them. I guess I will just stay at version 0.13.1 then.

It doesn't really matter to me that the files are invalid, I need to extract information from them and move on.

Thanks for your explanations.

**Comment by mozman** [comment]
Validation is necessary because ezdxf can modify existing DXF files and also create new DXF files. There are already enough DXF libraries and applications that create invalid DXF files, I try to avoid this for ezdxf.

**Comment by mbway** [comment]
If you have sensitive files that you can't disclose, is it possible to either remove everything sensitive from an existing file or create a brand new one which still triggers the validation error?
