### ISSUE TITLE
Unwanted extra padding when converting to raster

### ISSUE THREAD

**Issue by Hagen013** [mozman/ezdxf#523]
What I am trying to do is convert a .DXF file to a georeferenced .TIF. DXF contains geometry with coordinates in a linked coordinate system. I can get gdal.transform (basically just corners coordinates and resolution) by using ezdxf.bbox, but it looks like after rendering the vector image to a raster, there is extra padding around the edges of the image that is not captured by ezdxf.bbox. Is there any simple option in RenderContext, Frontend, MatplotlibBackend to avoid adding unwanted padding in the process of converting? 

![Screenshot from 2021-08-16 14-40-01](https://user-images.githubusercontent.com/19376385/129731210-a6946739-a5d4-4761-bf90-9f865e5261bd.png)

Desired output:

![desired_output](https://user-images.githubusercontent.com/19376385/129732142-8881cf8d-7153-4ec4-83b8-1207070d4d02.png)

**Comment by Hagen013** [comment]
Another possible solution would be getting bbox coordinates of the whole image (not just of the stored geometry) if they are stored in .DXF file itself (I'm not very familiar with dxf yet).

**Comment by mbway** [comment]
the margin is from matplotlib I think. Try using
```python
ax.set_xmargin(0)
ax.set_ymargin(0)
fig.savefig('...', bbox_inches=0, pad_inches=0)
```
If that doesn't work, search for different ways of removing margins in matplotlib.

for your second comment, this issue should be useful: #219 and #269

**Comment by mbway** [comment]
Also, for georeferencing you might find #217 useful. It provides a `get_crs_transformation` method which might be more convenient for getting the georeferenced transform
