### ISSUE TITLE
A dxf file export to PDF unit problem

### ISSUE THREAD

**Issue by lukaszolek** [mozman/ezdxf#532]
I have a mockup.dxf file generated by ezdxf - size 1490x1100 mm. I need to save it to PDF, however the draw_cad.py from examples saves it scaled. The generated PDF has size: 16,7x12,2 cm (with some borders). 
It is approximately in 1:10 scale. Do you have any ideas, why this happens? How to generate 1:1 PDF?

[mockup.pdf](https://github.com/mozman/ezdxf/files/7127659/mockup.pdf)
[mockup.dxf.zip](https://github.com/mozman/ezdxf/files/7127660/mockup.dxf.zip)

**Comment by mozman** [comment]
FAQ #550
