### ISSUE TITLE
Read file, edit header, save file - Header changes not present

### ISSUE THREAD

**Issue by ark-** [mozman/ezdxf#537]
**Describe the bug**
I have a DXF file without a header. This is exported from OpenSCAD. I try to add units to the header and save back the dxf file, a default header seems to be added but the INSUNITS parameter isn't present.

**To Reproduce**
Information and data needed to reproduce the error:
1. The python script
``` python
doc = ezdxf.readfile("see_below.dxf")
doc.header["$INSUNITS"] = ezdxf.units.MM
doc.header["$MEASUREMENT"] = 1
doc.saveas("out.dxf")
```
2. The DXF

``` dxf
  0
SECTION
  2
BLOCKS
  0
ENDSEC
  0
SECTION
  2
ENTITIES
  0
LINE
  8
0
 10
20
 20
20
 11
0
 21
20
  0
LINE
  8
0
 10
0
 20
20
 11
0
 21
0
  0
LINE
  8
0
 10
0
 20
0
 11
20
 21
0
  0
LINE
  8
0
 10
20
 20
0
 11
20
 21
20
  0
LINE
  8
0
 10
4
 20
4
 11
4
 21
9
  0
LINE
  8
0
 10
4
 20
9
 11
9
 21
9
  0
LINE
  8
0
 10
9
 20
9
 11
9
 21
4
  0
LINE
  8
0
 10
9
 20
4
 11
4
 21
4
  0
ENDSEC
  0
SECTION
  2
OBJECTS
  0
DICTIONARY
  0
ENDSEC
  0
EOF
```
 
3. This is on latest stable EzDXF from PyPi

**Expected behavior**
The $INSUNITS and $MEASUREMENT variables to exist in a HEADER section of the `out.dxf`

**Comment by mozman** [comment]
The header variables `$INSUNITS` and `$MEASUREMENT` require DXF version R2000 or later. Your source DXF file (which you did not include) is DXF R12, because for any DXF version later the `HEADER` section is mandatory.

Try to set the DXF version inside of _ezdxf_ to R2000, this may or may not work - _ezdxf_ is not a DXF converter.

```Python
import ezdxf
from ezdxf import units

doc = ezdxf.readfile("where_is_the_file.dxf")
doc.header["$INSUNITS"] = units.MM
doc.header["$MEASUREMENT"] = 1

doc.dxfversion = "R2000"
doc.saveas("r2000.dxf")
```

**Comment by ark-** [comment]
Well that did it. 

Thank you very much!

I wonder if there could be an error which states something like "You're setting a header value which is not supported by your DXF Version"?

**Comment by ark-** [comment]
If you think this is something which is value added, feel free to reopen the issue to track. Otherwise I'll close it.

Thanks again :)
