### ISSUE TITLE
ezdxf.addons.odafc.exec_path does not exist

### ISSUE THREAD

**Issue by dweiss2** [mozman/ezdxf#539]
**Describe the bug**
The documentation for ODAFC states that `ezdxf.addons.odafc.exec_path` will show the current executable path. It does not.

**To Reproduce**
    
    >>> from ezdxf.addons import odafc
    >>> odafc.exec_path
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    AttributeError: module 'ezdxf.addons.odafc' has no attribute 'exec_path'

ezdxf version 0.16.6, Windows 10.

**Expected behavior**
Return the path as listed in the documentation

**Suggestion**
I think it would be nice to be able to set the path for the executable. Here is my suggestion on a way to do it. 
   
    # Add this function
    @contextmanager
    def _modified_environ(**environ: dict[str, str]) -> None:
        """
        Temporarily set the process environment variables.
        """
        old_environ = dict(os.environ)
        os.environ.update(environ)
        try:
            yield
        finally:
            os.environ.clear()
            os.environ.update(old_environ)
    
    # Modify this function
    def export_dwg(
        doc: Drawing,
        filename: str,
        version: Optional[str] = None,
        *,
        audit: bool = False,
        replace: bool = False,
        oda_path: str = None
    ) -> None:
        """Use an installed `ODA File Converter`_ to export a DXF document `doc`
        as a DWG file.

        Saves a temporary DXF file and convert this DXF file into a DWG file by the
        ODA File Converter. If `version` is not specified the DXF version of the
        source document is used.

        Args:
            doc: `ezdxf` DXF document as :class:`~ezdxf.drawing.Drawing` object
            filename: export filename of DWG file, extension will be changed to ".dwg"
            version: export file as specific version, by default the same version as
                the source document.
            audit: audit source file by ODA File Converter at exporting
            replace: replace existing DWG file if ``True``
            oda_path: path to the oda file converter if not default

        .. versionchanged:: 0.15

            added `replace` option

        """
        if version is None:
            version = doc.dxfversion
        export_version = VERSION_MAP[version]
        dwg_file = Path(filename).absolute()
        out_folder = Path(dwg_file.parent)
        if dwg_file.exists():
            if replace:
                dwg_file.unlink()
            else:
                raise FileExistsError(f"File already exists: {dwg_file}")
        if out_folder.exists():
            with tempfile.TemporaryDirectory(prefix="odafc_") as tmp_dir:
                dxf_file = Path(tmp_dir) / dwg_file.with_suffix(".dxf").name

                # Save DXF document
                old_filename = doc.filename
                doc.saveas(dxf_file)
                doc.filename = old_filename

                arguments = _odafc_arguments(
                    dxf_file.name,
                    tmp_dir,
                    str(out_folder),
                    output_format="DWG",
                    version=export_version,
                    audit=audit,
                )
                # NEW PART
                oda_path = os.getenv('PATH') + f';{oda_path}' if oda_path else os.getenv('PATH')
                with _modified_environ(PATH=oda_path):
                    _execute_odafc(arguments)
        else:
            raise FileNotFoundError(
                f"No such file or directory: '{str(out_folder)}'"
            )

**Comment by mozman** [comment]
The file path for `ODAFileConverter.exe` on Windows can now be set by `ezdxf.addons.odafc.win_exec_path` or by [config file](https://ezdxf.mozman.at/docs/options.html#config-files).

```Ini
[odafc-addon]
win_exec_path = "C:\Program Files\ODA\ODAFileConverter\ODAFileConverter.exe"
```
