### ISSUE TITLE
Error while converting DXF to PNG

### ISSUE THREAD

**Issue by radheygupta** [mozman/ezdxf#541]
For some DXF files, I am getting error **"IndexError: tuple index out of range"** while converting from DXF to png.

I have attached a python script and the DXF file that can be used to trigger the error.

[error_ezdxf.zip](https://github.com/mozman/ezdxf/files/7217124/error_ezdxf.zip)

**Comment by mozman** [comment]
From where did you get this DXF file or which application created this DXF file?

One HATCH edge spline has a weird knot configuration: A clamped B-spline with degree=3 requires that the first and the last 4 knot values are the same:

```Text
(0.0, 0.0, 0.0, 0.0, <<< OK!
0.0530679973774894, 
0.1167307518033354, 
0.1307954512868446, 
0.1987009449596935,
0.2453042576556086, 
0.2811314410294223, 0.2811314410294223, 0.2811314410294223, 0.2811314413221608)  <<< NOT OK!
```

**Comment by radheygupta** [comment]
I got this DXF file by converting a DWG file via an online tool _https://cloudconvert.com/dwg-to-dxf_
Also, I tried to use ODA FILE CONVERTER to get DXF from the DWG file, getting exact same error for that DXF file also.

**Comment by mozman** [comment]
The issue seems to be already in the DWG file.
