### ISSUE TITLE
Support for "forward" and "backward" history buttons

### ISSUE THREAD

**Issue by mozman** [mozman/ezdxf#546]
@mbway My mouse has two buttons for browser history navigation (forward & backward). I want to add this functionality to the DXF browser, but didn't find a solution by google, maybe you know the answer how to setup this Qt actions.

I replaced "Alt+Left" by `Qt.Key_Back` for testing, but this didn't work, and I want to assign both shortcuts "Alt+Left" and "Backward" to the action or create two actions with the same target method.

The browser actions setup can be found here. https://github.com/mozman/ezdxf/blob/53a3931c40c6b066de3356119dc229fe343c1393/src/ezdxf/addons/browser/browser.py#L124

**Comment by mbway** [comment]
I think QAction shortcuts can only be keyboard shortcuts, which makes sense, but you can still trigger the action yourself if you listen to mouse events:
```python
    def mousePressEvent(self, event: qg.QMouseEvent) -> None:
        super().mousePressEvent(event)
        if event.button() == qc.Qt.BackButton:
            self._entity_history_back_action.trigger()
```

If you want to set custom 'shortcut text' so it says 'Entity History &Back    Alt+Left or Back' or something like that, then you might be able to do that using a tab character: https://stackoverflow.com/a/1967140

**Comment by mozman** [comment]
Thank you!

These buttons on the mouse do not trigger the `mousePressEvent()`, it seems they are special "media" keys or so. I use the default Windows driver because the Logitech drivers are very buggy, so I don't see what command or key-code the driver assigns to these buttons.

I will add a simple toolbar to solve this issue.

**Comment by mbway** [comment]
to identify what event you need to handle, consider calling `self.installEventFilter(self)` and implementing:
```python
    def eventFilter(self, obj: qc.QObject, event: qc.QEvent) -> bool:
        if obj == self:
            print(event)
        return False
```

**Comment by mozman** [comment]
Thank you, using `installEventFilter()` helped to identify the problem: the extra buttons on my mouse, or the system events triggered by these buttons, are not handled by Qt (`DXFStructureBrowser(QMainWindow)`) . Chrome, Firefox and Opera support these buttons as browser history forward and backward.
