### ISSUE TITLE
dimension line text

### ISSUE THREAD

**Issue by pvk988** [mozman/ezdxf#557]
Thank you very much for creating 'ezdxf' !

1 ![image](https://user-images.githubusercontent.com/92176871/136596640-933daa27-1c03-4ac0-9e9f-59a554d26621.png)

2 ![image](https://user-images.githubusercontent.com/92176871/136596693-3ccaa992-0846-453f-a852-2bb8ff3d1bfb.png)

3 ![image](https://user-images.githubusercontent.com/92176871/136596724-ce3ebb1a-d156-4fad-97ad-de5135e18d33.png)

4 ![image](https://user-images.githubusercontent.com/92176871/136596744-94a24d7b-6309-405a-9f51-13b05fe6fa75.png)

def dim_style(name, m, ht):

    doc.dimstyles.new(name, dxfattribs={
        'dimdle': 1,
        'dimexe': 1,
        'dimasz': 2,
        'dimblk': 'OBLIQUE',
        'dimtxsty': 'cs_gost_if_' + Fn,
        'dimtad': 1,
        'dimtfill': 1,
        'dimtxt': ht,
        'dimscale': m,
        'dimexo': 1
    })

doc.styles.new(tst, dxfattribs={"font": "cs_gost2304.shx"})

Please help with this problem

**Comment by mozman** [comment]
I don't understand the issue, please provide more information and a full example script.

**Comment by pvk988** [comment]
script
[Python.zip](https://github.com/mozman/ezdxf/files/7314949/Python.zip)

**Comment by mozman** [comment]
fixed in ezdxf v0.17
