### ISSUE TITLE
Entity Color (ForeGround Color)

### ISSUE THREAD

**Issue by tridiserkan** [mozman/ezdxf#559]
Hi,

I am having trouble with saving .dxf as .png image. Not every time however, in some dxf files it turned out layers can be colored. 

In one of the cases, entities showed green whatever the background was. 

Now I know how to change background color but I couldn't find any solution for changing entities' colors.

Do you have a solution?

Thank you for your work!

Serkan

**Comment by mbway** [comment]
I don't really understand the first half of your question, but to change entity properties you can either edit the dxf before rendering (eg with entity.dxf.rgb see [here](https://ezdxf.readthedocs.io/en/stable/howto/content.html#get-set-entity-rgb-color)) or inherit from `Frontend` and implement `Frontend.override_properties()` (see [here](https://github.com/mozman/ezdxf/blob/0cec5e8a0df82013942f644f5fc2b1bbaafe6eac/src/ezdxf/addons/drawing/frontend.py#L147))

**Comment by mbway** [comment]
there is no autocomplete for `entity.dxf` because it's contents aren't known until runtime. It's basically a dictionary but accessed like a regular object
