### ISSUE TITLE
Problem installing pinned version with pip

### ISSUE THREAD

**Issue by Marcelo5444** [mozman/ezdxf#569]
Hi when i try to install verrsion > 0.16 in order to use the zoom feature with pip, I get the following error

pip3 install ezdxf==0.16
ERROR: Could not find a version that satisfies the requirement ezdxf==0.17.1b2 (from versions: 0.6.0, 0.6.1, 0.6.2, 0.6.3, 0.6.4, 0.6.5, 0.7.0, 0.7.1, 0.7.2, 0.7.3, 0.7.4, 0.7.5, 0.7.6, 0.7.7, 0.7.8, 0.7.9, 0.8.0, 0.8.1, 0.8.2, 0.8.3, 0.8.4, 0.8.5, 0.8.6, 0.8.7, 0.8.8, 0.8.9, 0.8.10b2, 0.8.10b3, 0.8.10, 0.9b1, 0.9, 0.10a0, 0.10b0, 0.10b1, 0.10b2, 0.10b3, 0.10b4, 0.10, 0.10.1b0, 0.10.1, 0.10.2, 0.10.3, 0.10.4, 0.11a1, 0.11a2, 0.11a3, 0.11a4, 0.11b0, 0.11b1, 0.11b2, 0.11b3, 0.11, 0.11.1b1, 0.11.1b2, 0.11.1, 0.11.2b0, 0.11.2, 0.12b0, 0.12b1, 0.12b2, 0.12b3, 0.12, 0.12.1b0, 0.12.1, 0.12.2b0, 0.12.2, 0.12.3b0, 0.12.3, 0.12.4b0, 0.12.4, 0.12.5b0, 0.12.5, 0.13b0, 0.13b1, 0.13b3, 0.13b4, 0.13b5, 0.13b6, 0.13, 0.13.1, 0.14a0, 0.14a1, 0.14a2, 0.14a3, 0.14a4, 0.14a5, 0.14b1, 0.14b2, 0.14b3, 0.14b4, 0.14, 0.14.1b0, 0.14.1, 0.14.2, 0.15a0, 0.15a1, 0.15a2, 0.15a3, 0.15a4, 0.15b0, 0.15b1, 0.15b2, 0.15, 0.15.1b0, 0.15.1, 0.15.2b0)
ERROR: No matching distribution found for ezdxf==0.17.1b2

Running on fresh installing linux 20.4.

**Comment by mozman** [comment]
ezdxf v0.16 requires Python 3.7

**Comment by Brice-D** [comment]
i am facing an issue while trying to install the latest version (see the screenshot below). Any idea how i can install it with the tag [all]? 
![Screenshot 2021-11-09 at 01 07 06](https://user-images.githubusercontent.com/24481556/140837827-6182b3e7-991b-4d46-8cf9-c9eacb08aef1.png)
)

**Comment by mozman** [comment]
use: `pip3 install ezdxf[all]`
