### ISSUE TITLE
HATCH rendering issue of text box boundary paths

### ISSUE THREAD

**Issue by bdaniere** [mozman/ezdxf#573]
**Describe the bug**

Hi,

I'm coming back with a new question / problem about the DXF - SVG conversion.
On the following model, the conversion is correct for the vast majority of entities.

However, the element (HATCH) corresponding to handle "17ECC6" does not appear correctly.
Indeed, in the SVG output, the element is centered in the middle of the SVG and looks like a horizontal bar chart. 
This should be located in the middle diagram of the right column. 

**To Reproduce**

```
from ezdxf.addons import odafc
from ezdxf.addons.drawing import matplotlib

doc = odafc.readfile("DWG_PATH")
dxf_modelspace = doc.modelspace()


matplotlib.qsave(
        layout=dxf_modelspace,
        filename="OUTPUT_PATH",
        bg="#FFFFFF00",
    )
```

[power_unit_1.zip](https://github.com/mozman/ezdxf/files/7475881/power_unit_1.zip)

**Screenshots**

![image](https://user-images.githubusercontent.com/36926578/140342690-0b9908a2-ab98-4220-a99a-041e663de3dc.png)

**Comment by mbway** [comment]
Different versions of ODAFileConverter can sometimes produce different outputs so it would be easier if you uploaded the converted DXF file you are trying to draw.

Also an image of what you're expecting could be useful (if you have access to another CAD application which displays correctly)

Also, you are specifying SVG output, does this mean that other output formats like PNG are working?

**Comment by bdaniere** [comment]
Here is the DXF file :  [power_unit_1.zip](https://github.com/mozman/ezdxf/files/7481675/power_unit_1.zip)
The error is also present on output in another format, such as PNG

The expected result would be not to have this set of geometry resembling a horizontal bar chart :
![image](https://user-images.githubusercontent.com/36926578/140485108-8b6bdf47-1b8e-4a37-8a36-db4d7db00bce.png)


In case you have an Autodesk account, here is an access to the DWG file on this document : https://autode.sk/3o2RyB0

I can see that the basic geometry is correct (the hatch is there, in the right place): it's probably the filling that spreads out on the final drawing

**Comment by mozman** [comment]
This is a valid HATCH with valid closed edge loops. 

This is the extracted and selected HATCH entity in BricsCAD, same result when selected in the original DXF file:

![image](https://user-images.githubusercontent.com/4230966/140604114-8f2fe480-ca55-4664-a061-000f0eb4282d.png)


I have no idea why only one loop is rendered and the rest is not:

- island detection is "nested", this means all paths are used
- multiple independent boundary paths in one HATCH entity is valid and a common usecase
- the loop orientation (clockwise or counter-clockwise) has no meaning for DXF

**Comment by mozman** [comment]
The edge paths have the "textbox" flag set, which the DXF reference explains as ... nothing like always.

I assume this should define a recess for a text object. The handling of this path is complicated, because it should be subtracted inside a filling and ignored inside a hole, which can't be done easily by the current implementation.

**Comment by mozman** [comment]
Next problem: text box overlapping fill and hole can't be handled by the PyQt and Matplotlib backends in the current implementation:

DXF file in BricsCAD:
![image](https://user-images.githubusercontent.com/4230966/140635470-ca1d5b82-f361-4546-bc85-ac4808e500a9.png)

ezdxf view (PyQt):

![image](https://user-images.githubusercontent.com/4230966/140635494-49c93f52-b3a8-413c-9bee-02ee5e246cb8.png)

ezdxf draw (Matplotlib):
![image](https://user-images.githubusercontent.com/4230966/140635523-43b11a6f-6586-4a90-8fb3-69e4ebef8acf.png)


This requires the text box to be split on the border between the fill and the hole, this is way beyond what I want to implement.

Simple solutions: 
1. Ignoring stand alone text boxes as separated boundaries at the top level outside of any other boundary, which should solve this issue
2. Text box inside of another boundary: invalid rendering result as it is
