### ISSUE TITLE
boundingbox calculation bug in ezdxf

### ISSUE THREAD

**Issue by chibai** [mozman/ezdxf#574]
**Describe the bug**
In this dxf file, I want to calculate the boundingbox of whole image. 
But I think this result is wrong.

[test.zip](https://github.com/mozman/ezdxf/files/7480164/test.zip)

**To Reproduce**
```
from pathlib import Path
import ezdxf
from ezdxf import bbox
doc = ezdxf.readfile('test.dxf')
cache = bbox.Cache()
ext = bbox.extents(doc.modelspace(), cache= cache)
print(ext)
```
result is below:
```
python test.py
findfont: Font family [''] not found. Falling back to DejaVu Sans.
Matplotlib RuntimeError: In affine_transform: Invalid vertices array.
Matplotlib RuntimeError: In affine_transform: Invalid vertices array.
Matplotlib RuntimeError: In affine_transform: Invalid vertices array.
Matplotlib RuntimeError: In affine_transform: Invalid vertices array.
Matplotlib RuntimeError: In affine_transform: Invalid vertices array.
Matplotlib RuntimeError: In affine_transform: Invalid vertices array.
[(-2531981575.7466483, 1204.7609229232767, -0.0008778303645091671), (2532846575.411637, 68940.94752145144, 151.9999999995343)]
```

**Expected behavior**
I wish the boudingbox calculation could correct

**Screenshots**
![1636081265(1)](https://user-images.githubusercontent.com/5702248/140451264-48ccd949-c2e5-4042-9ee5-3dd87a2faf0f.png)

**Comment by mozman** [comment]
Fixed calculation returns: [(43602.91986147462, 1204.7609229232767, -0.0008778303645091671), (472897.0736118274, 68940.94752145144, 151.9999999995343)]

There are hidden entities on a disabled layer!

![image](https://user-images.githubusercontent.com/4230966/140649611-38787846-8407-48ab-8d86-1c68ad62ecc5.png)

**Comment by chibai** [comment]
@mozman Dear, found another one
[test.zip](https://github.com/mozman/ezdxf/files/7495047/test.zip)
```
from pathlib import Path
import ezdxf
from ezdxf import bbox
doc = ezdxf.readfile('test.dxf')
cache = bbox.Cache()
ext = bbox.extents(doc.modelspace(), cache= cache)
print(ext)
``` 
```
Traceback (most recent call last):
  File "E:\projectsDevelopment\ezdxf_test\test.py", line 6, in <module>
    ext = bbox.extents(doc.modelspace(), cache= cache)
  File "E:\Python\Python39\lib\site-packages\ezdxf-0.17.1b3-py3.9.egg\ezdxf\bbox.py", line 141, in extents
    for box in multi_flat(entities, flatten=flatten, cache=cache):
  File "E:\Python\Python39\lib\site-packages\ezdxf-0.17.1b3-py3.9.egg\ezdxf\bbox.py", line 171, in multi_flat
    box = extends_([entity])
  File "E:\Python\Python39\lib\site-packages\ezdxf-0.17.1b3-py3.9.egg\ezdxf\bbox.py", line 161, in extends_
    for _box in multi_recursive(entities_, flatten=flatten, cache=cache):
  File "E:\Python\Python39\lib\site-packages\ezdxf-0.17.1b3-py3.9.egg\ezdxf\bbox.py", line 110, in multi_recursive
    for primitive in primitives:
  File "E:\Python\Python39\lib\site-packages\ezdxf-0.17.1b3-py3.9.egg\ezdxf\disassemble.py", line 560, in to_primitives
    yield make_primitive(e, max_flattening_distance)
  File "E:\Python\Python39\lib\site-packages\ezdxf-0.17.1b3-py3.9.egg\ezdxf\disassemble.py", line 505, in make_primitive
    primitive = cls(entity)
  File "E:\Python\Python39\lib\site-packages\ezdxf-0.17.1b3-py3.9.egg\ezdxf\disassemble.py", line 119, in __init__
    self._convert_entity()
  File "E:\Python\Python39\lib\site-packages\ezdxf-0.17.1b3-py3.9.egg\ezdxf\disassemble.py", line 298, in _convert_entity
    corner_vertices = text_line.corner_vertices(
  File "E:\Python\Python39\lib\site-packages\ezdxf-0.17.1b3-py3.9.egg\ezdxf\tools\text.py", line 158, in corner_vertices
    return TextLine.transform_2d(
  File "E:\Python\Python39\lib\site-packages\ezdxf-0.17.1b3-py3.9.egg\ezdxf\tools\text.py", line 223, in transform_2d
    insert = Vec3(insert)
  File "E:\Python\Python39\lib\site-packages\ezdxf-0.17.1b3-py3.9.egg\ezdxf\math\_vector.py", line 61, in __init__
    self._x, self._y, self._z = self.decompose(*args)
  File "E:\Python\Python39\lib\site-packages\ezdxf-0.17.1b3-py3.9.egg\ezdxf\math\_vector.py", line 168, in decompose
    length = len(data)
TypeError: object of type 'NoneType' has no len()
```

**Comment by chibai** [comment]
[test.zip](https://github.com/mozman/ezdxf/files/7560274/test.zip)
There's a complex dxf file, make the python program broken~~Is that because out of memory?
```
import ezdxf
from ezdxf import bbox
doc = ezdxf.readfile('test.dxf')
cache = bbox.Cache()
visible_non_text_entities = [e for e in doc.modelspace() if e.dxf.invisible == 0 and e.dxftype() not in ['MTEXT', 'TEXT', 'ATTRIB', 'HATCH']]
ext = bbox.extents(visible_non_text_entities, cache= cache)
print(len(list(visible_non_text_entities)))
print(ext)
```
results is below
```
python test.py
findfont: Font family [''] not found. Falling back to DejaVu Sans.
Matplotlib RuntimeError: In affine_transform: Invalid vertices array.
Matplotlib RuntimeError: In affine_transform: Invalid vertices array.
```

**Comment by mozman** [comment]
I have no idea why this crashes and the debugger doesn't help. I can only fix this if you find a simpler example for this issue.

**Comment by chibai** [comment]
> I have no idea why this crashes and the debugger doesn't help. I can only fix this if you find a simpler example for this issue.

```
import ezdxf
from ezdxf import bbox
doc = ezdxf.readfile('test.dxf')
cache = bbox.Cache()
visible_non_text_entities = [e for e in doc.modelspace() if e.dxf.invisible == 0 and e.dxftype() not in ['MTEXT', 'TEXT', 'ATTRIB', 'HATCH']]
for entity in visible_non_text_entities:
    print(entity)
    print(bbox.extents([entity], cache=cache))
#ext = bbox.extents(visible_non_text_entities, cache= cache)
print(len(list(visible_non_text_entities)))
#print(ext)
```
I can identify the broken time: when calculate the boundingbox of INSERT(#7C32)
I'm trying to separate the single INSERT as one DXF file

**Comment by mozman** [comment]
The real culprit are the INSERT `17ED` and the LWPOLYLINES `17E7` and `17E7` which have an elevation of `2.99...e+99` which moves them very far into the territory of floating point imprecision errors.

**Comment by chibai** [comment]
> The real culprit are the INSERT `17ED` and the LWPOLYLINES `17E7` and `17E8` which have an elevation of `2.99...e+99` which moves them very far into the territory of floating point imprecision errors.
> 
> EDIT: this is the first useful application for the new property `DXFEntity.source_of_copy`

Any plan or idea to fix this?

**Comment by mozman** [comment]
Setting the elevation of all INSERT entities to `0` is maybe hot-fix:
```python
for e in doc.entitydb.values():
    if e.dxftype() == "INSERT":
        e.dxf.insert = e.dxf.insert.replace(z=0)
```
For the real fix I need some time.

**Comment by chibai** [comment]
> Setting the elevation of all INSERT entities to `0` is maybe a hot-fix:
> 
> ```python
> for e in doc.entitydb.values():
>     if e.dxftype() == "INSERT":
>         e.dxf.insert = e.dxf.insert.replace(z=0)
> ```
> 
> For the real fix I need some time.

Got it, I will update it in my code~

**Comment by mozman** [comment]
The bounding box calculation for the last example should work. Please close this issue if the fix work for you and do not add further example files, just open a new issue. The bounding box calculation just shows the issues, the errors causing the issues are different.
