### ISSUE TITLE
Too fast end in the TABLE BLOCK RECORD.

### ISSUE THREAD

**Issue by jeff38100** [mozman/ezdxf#58]
Hi, 

Thanks for your work.

I try to transfert a block between two file and insert it.

I can open the dxf source with the original block, it's an Autocad save as to dxf.

When i open the new file, Autocad give me an error 

`Erreur dans la table BLOCK_RECORD
Fin prématurée de l'objet à la ligne 2502.
Entrée DXF incomplète ou non valable -- dessin ignoré.`

> BLOCK_RECORD
>   5
> 5FC
> 102
> {ACAD_XDICTIONARY
> 360
> 5F3
> 102
> }
> 330
> 1
> 100
> AcDbSymbolTableRecord
> 100
> AcDbBlockTableRecord
>   2
> cartoucheA4
> 340
> 0
> 102
> {BLKREFS
> 102
> }
>  70
> 4
> 280
> 1
> 281
> 0
> 1001
> **AcDbDynamicBlockGUID**
> 1000
> {5586419D-FB6E-394D-82BC-A22B4349C6F1}
>   0
> ENDTAB
> 

There was an dynamic block in here but i delete it and purge.

Edit : 
When i replace __AcDbDynamicBlockGUID__ by __Acad__ , it's work with Autocad. (Work with libreCAD with this issue)

Thx

**Comment by mozman** [comment]
The internal DXF structures for the latest DXF versions are very complex and NOT DOCUMENTED by the DXF reference, so transfer data between files without adjusting handles, GUIs and so on will probably not work and is not recommended. I am considering to remove the DXF importer module - chances are high for broken DXF files.
