### ISSUE TITLE
Sample DXF file of MULTILEADER for MTEXT with columns needed

### ISSUE THREAD

**Issue by mozman** [mozman/ezdxf#583]
BricsCAD can't create MULTILEADER for MTEXT content with columns in it.

I want to know if AutoCAD can create such MULTILEADERS, it should look like this mockup:
![image](https://user-images.githubusercontent.com/4230966/144172247-b5a6d619-0c34-4b52-87c7-d8d80bff8522.png)

If AutoCAD or any other CAD application like GstarCAD or ZWCAD can create such MULTILEADERS please post a **zipped** sample DXF file here.

A Multileader for each column type would be great:
- static
- dynamic (auto height)
- dynamic (manual height)

The content contains no line breaks: `1AAAA 2BBBB 3CCCC 4DDDD 5EEEE 6FFFF`

The button to create columns in the MTEXT editor in BricsCAD looks like this and maybe looks similar in other CAD applications:
![image](https://user-images.githubusercontent.com/4230966/144173341-988b3277-78d1-4054-83a2-74a3bf0c378f.png)

Thank you in advance for you help.

**Comment by chibai** [comment]
[not_good_mleader_example.zip](https://github.com/mozman/ezdxf/files/7639312/not_good_mleader_example.zip)

Is this work for you, this is created by AutoCad 2020

**Comment by mozman** [comment]
Thank you!

Ezdxf shows only the proxy graphic - column support seems to be the intention:

![image](https://user-images.githubusercontent.com/4230966/144401956-b236d723-8b88-4218-a29f-8c77a880349a.png)

But even TrueView2022 (from Autodesk) struggles: this is what TrueView shows:
![image](https://user-images.githubusercontent.com/4230966/144401475-51aad0f1-2aa2-4718-9798-59258ba0bcc3.png)

... and BricsCAD:

![image](https://user-images.githubusercontent.com/4230966/144402834-fb25dc11-4aff-4efa-98a0-77d020a65584.png)

Does any image above look like the source DWG drawing in AutoCAD 2020?

**Comment by chibai** [comment]
TrueView2022 (from Autodesk) is what it looks like in AutoCad.

For the static columns, I set the column as 2 but it seems didn't work when I save and reopen the dxf file.
I will try it next work day
