### ISSUE TITLE
Add support to release linux aarch64 wheels

### ISSUE THREAD

**Issue by odidev** [mozman/ezdxf#584]
I’m trying to build Linux AArch64 wheels but the repository [mozman/manylinux-wheel-builder](https://github.com/mozman/manylinux-wheel-builder) does not have aarch64 support. 

@mozman , Could you please let me know your plan for adding AArch64 support in the same. I can help with this.

**Comment by mozman** [comment]
I am not the creator of the `manylinux-wheel-builder`, I just use it and I have no idea how to add this feature.
