### ISSUE TITLE
Viewport.AcDbViewport crash

### ISSUE THREAD

**Issue by coreydexter** [mozman/ezdxf#59]
When calling the method `AcDbViewport` on an instance of Viewport the following crash happens. 

  File "lib\site-packages\ezdxf\modern\viewport.py", line 210, in AcDbViewport
    return self.tags.sublasses[2]
AttributeError: 'ExtendedTags' object has no attribute 'sublasses'

This is due to a typo in this line `self.tag.sublasses[2]` - notice the missing `c`. It should instead be `self.tag.subclasses[2]`.

For example when trying to use the Viewport method `set_frozen_layers` this crash occurs. 

This is using version 0.8.8.

**Comment by mozman** [comment]
Fixed it, thank you!

**Comment by coreydexter** [comment]
Thanks!

**Comment by mozman** [comment]
Added some tests and changed parameter `layer_handles` to `layers` of method `Viewport.set_frozen_layers(layers)`, because `set_frozen_layers()` accepts now handles and `Layer()` objects, extracting dxf handles from `Layer()` object is not necessary (new in v0.8.9 or develop branch).
