### ISSUE TITLE
Geometric Tolerance Matplotlib Rendering not supported

### ISSUE THREAD

**Issue by joejoseph007** [mozman/ezdxf#598]
Is Geometric Tolerance supported by ezdxf? I've been trying to render some dxf files with geometric tolerances like;
 - Flatness
 - Position
 - Runout
 - Parallelism
 - Perpendicity, etc
But I get a "skipped entity TOLERANCE(#!!). Reason: "unsupported""
Is there a workaround to render them, or are there plans to support this?

I've used the code given in the documentation to render the dxf using matplotlib:
https://ezdxf.readthedocs.io/en/stable/addons/drawing.html

Here is the dxf from Autodesk viewer and the render from ezdxf
![image](https://user-images.githubusercontent.com/33567223/148130607-bc6bd688-151d-447d-8488-5ee07737d630.png)
![image](https://user-images.githubusercontent.com/33567223/148130547-e6ab473c-e280-41b3-9c95-59d15f56869f.png)

**Comment by mozman** [comment]
It is not supported, because that is the documentation by Autodesk:
![image](https://user-images.githubusercontent.com/4230966/148156663-0cefd99f-917e-4bc4-a248-4a1f62ab4ce6.png)

Really that's all!
