### ISSUE TITLE
polyline read as lwpolyline in DXF2007

### ISSUE THREAD

**Issue by Mambix** [mozman/ezdxf#6]
I have librecad dxf that is saved as DXF2007
It contains this polyline:
![image](https://cloud.githubusercontent.com/assets/6792150/23331165/42063da2-fb58-11e6-9d9e-4da8c7d171b0.png)

I read this and it is returned as lwpolyline. When I save it into new dxf file I get this:
![image](https://cloud.githubusercontent.com/assets/6792150/23331160/17d910ea-fb58-11e6-9718-a356964e7e92.png)

Shouldn't this be read as polyline so I can keep Arc inside this polyline?

**Comment by mozman** [comment]
I need your DXF file and your python code to response.

**Comment by Mambix** [comment]
```Python
import ezdxf
import os

move = (100.0, 100.0)
source = '../dxf/blocks/ezdxf.dxf'
target = '../dxf/ezdxf.dxf'
src = ezdxf.readfile(source)
dxf = ezdxf.new(src.dxfversion)
lay = dxf.layers.get('0')
lay.set_color(2)
if os.path.isfile(target):
    if ezdxf.is_dxf_file(target):
        dxf = ezdxf.readfile(target)
target_msp = dxf.modelspace()
source_msp = src.modelspace()

for e in source_msp:
    print e.dxftype
    points = e.get_rstrip_points()
    newPoints = []
    for p in points:
        newPoints.append( (p[0] + move[0], p[1] + move[1]) )
    poly = target_msp.add_lwpolyline(newPoints, dxfattribs={
        'layer': e.dxf.layer,
        'flags': e.dxf.flags
    })
    poly.closed = e.closed

dxf.saveas(target)
```

[DXF](https://s3-eu-west-1.amazonaws.com/backup.red-mamba.com/ezdxf.dxf)

**Comment by mozman** [comment]
You just forgot to copy all point values (x, y, startwidth, endwidth, bulge), the bulge value defines the rounded edges:

    import ezdxf

    move = (100.0, 100.0)
    source = 'issue6.dxf'
    target = 'issue6copy.dxf'

    src = ezdxf.readfile(source)
    dxf = ezdxf.new(src.dxfversion)
    lay = dxf.layers.get('0')
    lay.set_color(2)
    target_msp = dxf.modelspace()
    source_msp = src.modelspace()

    for e in source_msp.query('LWPOLYLINE'):
        newPoints = []
        mx, my = move
        # get_points() returns  (x, y, start_width, end_width, bulge)
        for p in e.get_points():
            # you have  to copy the start- and end width and the bulge values
            x, y, sw, ew, b = p
            newPoints.append((x+mx, y+my, sw, ew, b))
        poly = target_msp.add_lwpolyline(newPoints, dxfattribs={
            'layer': e.dxf.layer,
            'flags': e.dxf.flags
        })
        poly.closed = e.closed

    dxf.saveas(target)
