### ISSUE TITLE
How to split layers into dxf files?

### ISSUE THREAD

**Issue by xuniuer** [mozman/ezdxf#60]
Sorry for this. It should be a help information.

I check doc and tutorials to find means to split layers from a source dxf file into different dxfs which will only contain one layer corresponding to source dxf.

> dwg = ezdxf.readfile("source.dxf")
> for layer in dwg.layers:
> ....dwg_new = ezdfx.new()
> ....dwg_new.add_layer(layer)
> ....dwg_new.saveas(layer.dxf.name + '.dxf')
> 

How to do this?

**Comment by mozman** [comment]
Please post your question at the [python-ezdxf](https://groups.google.com/forum/#!forum/python-ezdxf) forum, because the answer maybe is also useful for other users.

**Comment by xuniuer** [comment]
I try to post it the forum, but the connection from China to google is forbidden. Pity! Anyway, thanks.

**Comment by mozman** [comment]
Splitting DXF files is not possible, but you can copy the file and delete all entities of all other layers, 
layers are just an attribute of DXF entities, there is no layer entity containing any entities, layer table entries just define some additional attributes of a layer, but is not necessary. Just assign a new layer name to an DXF entity to move the entity to another layer.

```python
from shutil import copyfile
import ezdxf

ORIGINAL_FILE = 'test.dxf'
FILE_COPY = 'test2.dxf'

KEEP_LAYERS = {'Layer1', 'Layer2', 'AndSoOn...'}
KEEP_LAYERS_LOWER = {layer.lower() for layer in KEEP_LAYERS}

# copy original DXF file
copyfile(ORIGINAL_FILE, FILE_COPY)

dwg = ezdxf.readfile(FILE_COPY)
msp = dwg.modelspace()
# AutoCAD treats layer names case insensitive: 'Test' == 'TEST'
# but this may be not true for all CAD applications.
# And NEVER delete entities from a collection while iterating.
delete_entities = [entity for entity in msp if entity.dxf.layer.lower() not in KEEP_LAYERS_LOWER]

for entity in delete_entities:
    msp.unlink_entity(entity)
   
dwg.save()
```

**Comment by xuniuer** [comment]
Thanks for your reply and friendly comments. It works.

**Comment by xuniuer** [comment]
> I try to post it the forum, but the connection from China to google is forbidden. Pity! Anyway, thanks.

More points about internet connection. In China, Internet connection to some sites is forbidden, such as Google, Facebook, Yube and so on, except by VPN licensed by Government. Bigger enterprises can deploy VPN, but the smaller cannot apply. So, as software developer in a small enterprise in China, it's hard to use google's services such as Android resources, although there are some mirror sites. Maybe it's hard to understand, but it's the fact. Wish the situation could change in the future.

**Comment by mozman** [comment]
A world without Google services, unimaginable for me.

**Comment by xuniuer** [comment]
We, at least I, generally use Bing, which provides international search service as one option. Local search engines, such as baidu, sogou, are less used. There are too many ads in search results. Too business to software developers.

In China, creation is being encouraged by government policies for many years. With limited resources, the policy is trade-off, obviously.  Without Google services, the world is limited. So does Creation, I bet.

Luckily, we can use github, stackoverflow, nabble to acquire useful information. They meet my need basically. Thanks!
