### ISSUE TITLE
ELLIPSE are not read in R13

### ISSUE THREAD

**Issue by sebheitzmann** [mozman/ezdxf#604]
**Describe the bug**

I have a file which is read without error but all the ELLIPSE in the file have the default value for CENTER and Radius. So all my ELLIPSE arc are trigonometric circle ( center = 0,0,0 and radius 1 ).

I've try several tools to open my DXF and sometimes it works fine and sometime not or it crash the tool ( QCAD for exemple ).

Can't attach a DXF File. You can find it here : https://github.com/sebheitzmann/dxftest/blob/main/320886.dxf

Thanks for any advice.

**Comment by sebheitzmann** [comment]
My Use case is to read the DXF and transform some entities in a gerber format. That's what i get : 

![image](https://user-images.githubusercontent.com/2197902/148507517-295b5328-f73d-4a2e-9de3-d8d7dc398fe1.png)

**Comment by sebheitzmann** [comment]
It should be like that : 

![image](https://user-images.githubusercontent.com/2197902/148507738-ed461386-6462-498e-ac32-4767b0b90cb7.png)

**Comment by mozman** [comment]
FYI: you can attach zipped DXF files

**Comment by mozman** [comment]
This is not fixable:

1. Autodesk Trueview does not open the file!
2. BricsCAD does not open the file!
3. An important DXF structure is missing:

This is how an ELLIPE entity should look like:

![image](https://user-images.githubusercontent.com/4230966/148512126-e6fbd933-6c27-4f03-937a-c6c253fe44ef.png)

That is in "your" DXF file:

![image](https://user-images.githubusercontent.com/4230966/148512265-5b65644f-6863-43a8-bcc6-3c2a08bc13c7.png)

The important subclass marker string "AcDbEllipse" is missing!

Report the bug to the vendor of the application which created this DXF file.

**Comment by mozman** [comment]
The TEXT entities are also invalid because of the missing the "AcDbText" subclass marker string and two of them even lack a handle, which is not valid for DXF13 and newer. Only the LINE and DIMENSION entities seems to be valid to a certain degree, but the DIMENSION entities do not have the required anonymous BLOCK with the entity geometry so they will not be shown by ezdxf.

**Comment by sebheitzmann** [comment]
Thank you very much for your analysis. I have sucessfully opened the file with librecad and saved it and it works fine.
It's not related to ezdxf. Unfortunatelly the vendor is dead and not able to transform the export. 

Thanks again. I close the issue.
