### ISSUE TITLE
Don't Wrap Instance Methods with 'functools.lru_cache' 

### ISSUE THREAD

**Issue by mozman** [mozman/ezdxf#617]
Interesting article about using the `lru_cache` for instance methods:
https://rednafi.github.io/reflections/dont-wrap-instance-methods-with-functoolslru_cache-decorator-in-python.html

tl;dr: `lru_cache` may prevent garbage collection of the instance

@mbway 
Should I add a `self.get_font_properties.cache_clear()` and `self.get_qfont.cache_clear()` at the end of the `finalize()` method in `MatplotlibBackend` and `PyQtBackend`? A quick test did not show any disadvantages, do you have any concerns?

**Comment by mbway** [comment]
maybe it would be better to have a non-member function decorated with lru_cache which takes the font and font properties and caches based on that rather than caches based on the `self` parameter which causes the garbage collection issue. so:
```python
class A:
    def get_a(self):
        _get_a(self.a, self.b)


@lru_cache
def _get_a(a, b):
    return 123
```
that way the cache can be shared between instances
