### ISSUE TITLE
dxf has dense lines, wrong to png image

### ISSUE THREAD

**Issue by zhongqingbin** [mozman/ezdxf#618]
The dxf has dense lines, and the picture is displayed
![标准层1(2~15自然层)-水平构件-分母-楼板-布置平面图](https://user-images.githubusercontent.com/7828474/150139275-cd789f75-28a3-444b-b46c-2b95904de02d.png)

incorrectly when it is converted to png.The desired effect should be like this
![QQ截图20220119212342](https://user-images.githubusercontent.com/7828474/150139498-e3eb7d4c-4945-422b-9328-3340d9ce6c55.png)

dxf file

[dxfToPng.zip](https://github.com/mozman/ezdxf/files/7897449/dxfToPng.zip)

**Comment by mozman** [comment]
None of the current backends of the `drawing` add-on support HATCH pattern perfectly and this will not change in the future.

**Comment by tf0054** [comment]
For my case, itd be great to work with Forge cloud from AutoDesk. And because it enables you to use accoreconsole.exe of AutoCAD, the result pngs are perfect. (So far, dxf created by ezdxf works peefect with Forge. Thank you so much @mozman )

**Comment by mozman** [comment]
Ezdxf gets proper hatch pattern support in v0.18.1, unfortunately for you these hatch lines are too dense and took even with the fast PillowBackend over 320 seconds. Such hatches can be handled by professional CAD applications which may use a kind of "Level of Detail" approach but not by ezdxf.

Nonetheless, thanks for your example, which shows that I have to add a timeout for such cases ;).
