### ISSUE TITLE
Option draw_viewports_first Does not work when plotting layout paperspace

### ISSUE THREAD

**Issue by Marcelo5444** [mozman/ezdxf#634]
**Describe the bug**
The default option of draw_viewports_first in layout class does not work in some CAD programs (ZWCAD)

**To Reproduce**
This can be easily reproduced with the script viewports_in_paperspace.py that can be found in the examples.
Some changes needs to be done in order to place the text above some entities of the world.

Change lines from 130-133 to 

paperspace.add_text(
        "Viewport to 3D Mesh", dxfattribs={"height": 0.18, "color": 1}
    ).set_pos((16, 10), align="CENTER")
    
When exporting to pdf, The mesh is plotted above the text

**Comment by mozman** [comment]
I cannot fix ZWCAD!

**Comment by Marcelo5444** [comment]
Do you know any reference software where this option works when exporting the PDF?

**Comment by mozman** [comment]
No, even AutoCAD (TrueView) ignores this flag and also ignores the default draw order: by ascending handles, which is in all CAD applications and also ezdxf, the order of creation.

![acad](https://user-images.githubusercontent.com/4230966/153244539-0206ef28-ee0c-449c-ad98-0930ae78afdf.png)

**Comment by mozman** [comment]
The `plot_layout_flags` were reset to 0 after calling `page_setup()`. This has changed now.

Do not rely on default values, they may change in the future - always enable/disable features that are important to you yourself.

![image](https://user-images.githubusercontent.com/4230966/153255988-1dd7f7e4-58e7-4e03-9b06-43ebdb0f01de.png)
