### ISSUE TITLE
Unknown header-variable $LASTSAVEDBY is ignored (AC1015)

### ISSUE THREAD

**Issue by JuergenWeichand** [mozman/ezdxf#64]
While opening an AC1015-DXF in AutoCAD 2016 the following message occurs. 
`Unbekannte Header-Variable $LASTSAVEDBY ignoriert auf Zeile 18.`

According to https://docs.rs/dxf/0.3.0/dxf/struct.Header.html the minimum AutoCAD Version for `$LASTSAVEDBY` is R2004.

**Comment by mozman** [comment]
But it doesn't hurt also.
