### ISSUE TITLE
BSpline flattening comment:  set() must preserve order?

### ISSUE THREAD

**Issue by Longhan9926** [mozman/ezdxf#656]
**Describe the bug**
Hello, I found some strange behavior when using the `spline.flattening` method. I checkout the ezdxf repo and found the source code for this method have a weird comment as shown here.

![image](https://user-images.githubusercontent.com/53202289/158740132-c7a11621-4f75-46c8-9e8a-5d271e4be7ee.png)

It appears to me that this line doesn't preserve order of knots in any way. I added sorting after this line and solved my problem. but I am not sure whether this is a bug or not? Would you mind spare some time and check out this problem? Thanks.

**Comment by mozman** [comment]
Since Python 3.6 the order of dict() keys and set() is preserved, at least for CPython and PyPy.

This comment is just a reminder for myself for this condition.

**Comment by Longhan9926** [comment]
Thank you for the reply. I am using python 3.9. From my observation, the set object itself is unordered, `__iter__` of set() object behaves differently than `__str__` and didn't preserve the order; and when `list()` takes in a iterable it preserves the order of that iterable; so `list(set())` didn't behave as expected under some circumstances.

![image](https://user-images.githubusercontent.com/53202289/158770306-9076ff65-4424-48dc-bf6b-e2d96a6159d9.png)

**Comment by mozman** [comment]
This seems to be correct, `set()` does not preserve order.
