### ISSUE TITLE
Document could be wrong for LWPolyline

### ISSUE THREAD

**Issue by Coxious** [mozman/ezdxf#66]
Hi,

In this page https://ezdxf.readthedocs.io/en/latest/tutorials/lwpolyline.html

> The curved segment is drawn from the vertex with the defined bulge value to the following vertex, the curved segment is always a circle, the diameter is relative to the vertex distance, bulge = 1.0 means the diameter equals the vertex distance, bulge = 0.5 means the diameter is the half of the vertex distance. bulge > 0 the curve is on the right side of the vertex connection line, bulge < 0 the curve is on the left side.

However, when I dealing with it, I found that the bulge factor actually not refers to the diameter but the radius. Can you check it out?

Many thanks!

**Comment by mozman** [comment]
![image](https://user-images.githubusercontent.com/4230966/51654600-f3f63600-1f98-11e9-8989-9ec0f6093964.png)

For `bulge = 1`, the diameter is the vertex distance, but the explanation is wrong, the height `h` of the circle segment is half the vertex distance times bulge value, see also the [LWPOLYLINE](https://ezdxf.readthedocs.io/en/latest/dxfentities/lwpolyline.html) documentation.
