### ISSUE TITLE
Text alignment throwing AssertionError

### ISSUE THREAD

**Issue by kurt-rhee** [mozman/ezdxf#666]
**Describe the bug**
Following the tutorial for text here:  https://ezdxf.readthedocs.io/en/stable/tutorials/text.html
Setting the alignment for text causes the following error:

```
File "/media/H/Python/Nevados/helios.core/_env/lib/python3.8/site-packages/ezdxf/entities/text.py", line 299, in set_placement
    assert isinstance(align, **TextEntityAlignment)**
```

**To Reproduce**
Information and data needed to reproduce the error:
1. Removing the align='Center' in the code below works as expected.

```
      msp.add_text(
            text=row['text'],
            dxfattribs={
                'layer': f"block_{row['block']}_tracker_label",
                'rotation': 90,
                'height': 5
            }
        ).set_placement(
            p1=(row['x'], row['pile_vec_end'].y),
            align='CENTER'
        )
```

2. Information about the *ezdxf* version and the OS.
EZDXF 0.17.2 Ubuntu 20.04

3. If a 3rd party DXF file causes the error, add a *simplified* and *zipped* 
   DXF file which still triggers the error.
   DXF created by EZDXF

**Confidential Data**
If you have sensitive files that you can't disclose, try to remove everything 
sensitive from an existing file or create a brand new one which still triggers 
the error. Alternatively, you can send the zipped files to confidential@mozman.at, 
this data is only saved locally (no cloud upload of any kind) and the files are 
deleted after the error has been fixed.

**Expected behavior**
I would expect text alignment to change to centered.

**Screenshots**
![image](https://user-images.githubusercontent.com/33131958/162013010-62e66abf-cc74-43bd-b409-f3a4972e23c5.png)

**Comment by bobblkabb** [comment]
Would you please share the new code?

**Comment by kurt-rhee** [comment]
I unfortunately no longer work for the company where I was writing this and don't have access to the code.  I'm sorry and best of luck.
