### ISSUE TITLE
Scaling hatch with draw png

### ISSUE THREAD

**Issue by Joerockclimber** [mozman/ezdxf#672]
The hatch is not scaling correctly when converting to png.

    def hatch_test(self):
        rec = [(-0.5, -0.5), (0.5, -0.5), (0.5, 0.5), (-0.5, 0.5), (-0.5, -0.5)]
        hatch = self.msp.add_hatch()
        hatch.paths.add_polyline_path(
            rec, is_closed=True
        )
        hatch.set_pattern_fill("ANSI31", scale=.5, color=3)

    def to_png(self, filename):
        if self.filename:
            filename = self.filename
        matplotlib.qsave(layout=self.msp, filename=filename.replace('.dxf', '.png'))

I expect the scale to change. So the density of lines should increase or decrease.

Instead I get the same image every time.

![test - Copy](https://user-images.githubusercontent.com/38697108/164074202-a2b563a1-47b4-428e-aea5-95f6aea1b6e7.png)

**Comment by mozman** [comment]
Same as #618.

**Comment by Joerockclimber** [comment]
K Thanks for the quick response
