### ISSUE TITLE
Default measurement units

### ISSUE THREAD

**Issue by Tarvald** [mozman/ezdxf#68]
Hi,
Can we somehow set default measurement units to inches?
We tried 
```
        self.dwg = ezdxf.new('ac1032')
        self.main_space = self.dwg.modelspace()
        self.msp = self.dwg.new_layout('layout')

        self.msp.page_setup(units='inch', rotation=0)
```
however it does not work

also in source code we found left todo:

```
        # TODO: don't know how to set inch or mm mode in R12
        units = units.lower()
        if units.startswith('inch'):
            units = 'Inches'
            plot_paper_units = 0
            unit_factor = 25.4  # inch to mm
        elif units == 'mm':
            units = 'MM'
            plot_paper_units = 1
            unit_factor = 1.0
        else:
            raise DXFValueError('Supported units: "mm" and "inch"')
```
Our clients are only from USA and they really don't what to change it manualy each time.
We were using some other (and older) library before and it was in inches by default.

Thanks for the help :)

**Comment by ioztelli** [comment]
I have a same problem.So i found a solution to   change files  in site-packages/exdxf/templates.
```
$INSUNITS
 70
4
```
to 
```
$INSUNITS
 70
1
```

Another units you can use this header section from Autocad Sites.
https://www.autodesk.com/techpubs/autocad/acad2000/dxf/header_section_group_codes_dxf_02.htm

$INSUNITS | 70 | Default drawing units for AutoCAD DesignCenter blocks:0 = Unitless; 1 = Inches; 2 = Feet; 3 = Miles; 4 = Millimeters; 5 = Centimeters; 6 = Meters; 7 = Kilometers; 8 = Microinches; 9 = Mils; 10 = Yards; 11 = Angstroms; 12 = Nanometers; 13 = Microns; 14 = Decimeters; 15 = Decameters; 16 = Hectometers; 17 = Gigameters; 18 = Astronomical units; 19 = Light years; 20 = Parsecs
-- | -- | --

**Comment by jmacura** [comment]
OT: I didn't know that DXF supports AU, ly, pc units 😳  Quite funny. What can you project with units this big? Neither a space elevator is large enough 😄

**Comment by Tarvald** [comment]
Hi Guys,
We figured out the same solution :)
It works.

Thanks a lot:)

**Comment by mozman** [comment]
@ioztelli It is probably not the best idea to edit the template file, because all edits are lost at the next update. _ezdxf_ has an interface to set header variables, see [docs](https://ezdxf.mozman.at/docs/header_section.html): `drawing.header['$INSUNITS'] = 1`

There is also a `$MEASUREMENT` variable to set 'english' or 'metric' units, but I am not an AutoCAD user.

**Comment by ioztelli** [comment]
> @ioztelli It is probably not the best idea to edit the template file, because all edits are lost at the next update. _ezdxf_ has an interface to set header variables, see [docs](https://ezdxf.mozman.at/docs/header_section.html): `drawing.header['$INSUNITS'] = 1`
> 
> There is also a `$MEASUREMENT` variable to set 'english' or 'metric' units, but I am not an AutoCAD user.

I checked on Autocad 2017 , it works perfectly.
`dwg.header['$INSUNITS'] = 6  # Meters
dwg.header['$AUNITS'] = 0  # Decimal degrees
dwg.header['$MEASUREMENT'] = 1  # Measurement Metric`

**Comment by mozman** [comment]
Added a paragraph for header variables and units setup to the [howto](https://ezdxf.mozman.at/docs/howto.html) section of the documentation.
