### ISSUE TITLE
The new DXF file laser printing software won't open

### ISSUE THREAD

**Issue by shine-flower** [mozman/ezdxf#681]
I first read the local DXF file, did not do any processing directly generated new DXF file. The use of my laser printing software ezcad2.exe can not open the newly generated DXF file.
```text
doc = ezdxf.readfile("D:\\work\\33333.dxf")
doc.saveas("asdasasfsa.dxf")
```
Then I used the file comparison tool 'Beyond Compare' and saw that the contents in the file /n/ R etc. were not the same as the source file. And some data was deleted.
The following image shows the source file on the left and the new generated file on the right
![image](https://user-images.githubusercontent.com/105044629/167528728-eb5b16e3-3c72-4bee-974a-6b642c61ee2a.png)
![image](https://user-images.githubusercontent.com/105044629/167528763-3a2807d9-bd29-4492-9138-35ce5cb1a7e7.png)
![image](https://user-images.githubusercontent.com/105044629/167528904-85cad548-fa8a-45ef-b070-b68c85b89d1a.png)
![image](https://user-images.githubusercontent.com/105044629/167528954-49abdfeb-50d4-4e00-ac6f-9e23e1a8be21.png)

**Comment by mozman** [comment]
If AutoCAD can open it, everything is fine!
