### ISSUE TITLE
Ezdxf is not very friendly to read files from the file server

### ISSUE THREAD

**Issue by shine-flower** [mozman/ezdxf#682]
When I read files from the server side, I need to do a base64 encode first, and then I can call ezDXF.decode_base64 method to get DXF template. Operations are repetitive, and base64 doesn't work well when files are large.
```text
# doc = ezdxf.readfile("D:\\work\\33333.dxf")
file_bypes_base64 = base64.b64encode(urlopen(device_url).read())
doc = ezdxf.decode_base64(file_bypes_base64)
```
I read the file directly using 'open' in the code. This is not true when it is an HTTP file URL. Later there will be a relevant optimization?
![image](https://user-images.githubusercontent.com/105044629/167530015-08d88c86-41c2-48ca-bcf6-017a4ec10a25.png)

**Comment by mozman** [comment]
What do you want?

**Comment by shine-flower** [comment]
> 你想要什么？
I want to read a DXF file from a URL with an HTTP link.

For example: https://user-images.githubusercontent.com/105044629/167530015-08d88c86-41c2-48ca-bcf6-017a4ec10a25.dxf.

But ezDXF has not found a better method. Filename can only be a local file, not a file on the browser/file server

```text

doc = ezdxf.readfile(filename)

` ` `

**Comment by shine-flower** [comment]
> 您可以从任何`TextIO`流（不仅仅是文件系统上的文件）加载`ezdxf.read()`
> 
> https://github.com/mozman/ezdxf/blob/35c83519d3cbcffad02a09a2cb46b5d1f7785fe4/src/ezdxf/filemanagement.py#L69
> 
> 使用类似文件的界面查看[urllib以读取 URL](https://docs.python.org/3/library/urllib.request.html)

>But using urllib to read the URL returns an array of bytes, whereas ezDXf.read () is TextIO.
>
>I looked at ezDXF.decode_base64 (), which is the bytes array processing, so later can be directly optimized to a method. Processing bytes arrays directly, rather than base64 encoding and then decoding. I think it's a messy step

**Comment by shine-flower** [comment]
> > 您可以从`TextIO`流（文件系统上的任何文件加载）`ezdxf.read()`
> > https://github.com/mozman/ezdxf/blob/35c83519d3cbcffad02a09a2cb46b5d1f7785fe4/src/ezdxf/filemanagement.py#L69
> > 
> > 使用类似文件的界面查看[urllib以读取URL](https://docs.python.org/3/library/urllib.request.html)
> 
> > 但是使用 urllib 读取 URL 返回一个字节数组，而 ezDXf.read() 是 TextIO。
> > 我看了一下ezDXF.decode_base64()，里面是字节数组的处理，所以后面可以直接优化成一个方法。直接处理字节数组，而不是 base64 编码然后解码。我认为这是一个混乱的步骤。而且，实际上，大多数文件仍在专用服务器上

**Comment by mbway** [comment]
Try this
https://docs.python.org/3/library/io.html#io.TextIOWrapper

**Comment by mbway** [comment]
Although I do agree that `decode_base64` does some useful things like normalising newlines and detecting the text encoding so it might be nice to have a separate function to read bytes and have `decode_base64` call into that

**Comment by mozman** [comment]
Join an array of bytes:

    >>> data = [b"a", b"b", b"c"]
    >>> b"".join(data)
    b'abc'
