### ISSUE TITLE
Text alignment renders wrong in AutoCAD when converted from dxf to dwg using ODAFileConverter

### ISSUE THREAD

**Issue by George-Jiang** [mozman/ezdxf#688]
**Describe the bug**
I add a text with middle_center alignment at the position of (0,0) in ezdxf, and save it as dxf.
The .dxf file shows perfect in AutoCAD. 
But when converted to dwg using ODAFileConverter, the text renders a little in up and right direction in AutoCAD, while the alignment is still 'middle_center'. If I double click the text, it will return to the right position.

The code:

import ezdxf
dwg = ezdxf.new('AC1024')
msp = dwg.modelspace()
text = msp.add_text('123').set_pos((0,0,0)).set_align('middle_center')
dwg.saveas('123.dxf')

ezdxf version is 0.17.2

.dxf file shown in AutoCAD
![image](https://user-images.githubusercontent.com/28250495/169704597-22788c9a-1e99-404e-9fed-5be80007dd74.png)

.dwg file shown in AutoCAD
![image](https://user-images.githubusercontent.com/28250495/169704612-29bacba4-0db1-4597-b350-84a6d997eee6.png)

.dxf and .dwg files:
[drawings.zip](https://github.com/mozman/ezdxf/files/8749754/drawings.zip)

**Comment by mozman** [comment]
How should I fix this? I am not the maintainer of the Open-Design-Alliance File-Converter!

**Comment by George-Jiang** [comment]
I think it might not be an issue from the ODA side, for I created the same text in AutoCAD, saved it as .dxf format, and then used ODA to convert it to dwg. Both .dxf file and .dwg file are shown correctly in AutoCAD.

And files created by ezdxf using 'R12' then converted, are shown correctly in AutoCAD too.
But any version later than 'R12' doesn't work, like the 'R2010' mentioned above.

Is there any difference between 'R12' and 'R2010' from ezdxf side that may cause this issue?

**Comment by mozman** [comment]
Set the text location and alignment by the `set_pos()`  or better with then new `set_placement()` methods at once:

```Python
from ezdxf.enums import TextEntityAlignment

text.set_placement((0, 0, 0), align=TextEntityAlignment.MIDDLE_CENTER)

```

If you use the `set_align()`  method you have to know how to set the `dxf.insert` and `dxf.align_point` attributes correctly.

**Comment by George-Jiang** [comment]
I tried both set_pos() and set_placement(). However, the render problem still exists.

odafc.export_dwg(dwg, '123.dwg',version='R12')

When conveted in 'R12' format, the render problem is solved. But the 'R12' does not support advanced features.

It seems everything's okay in ezdxf. Then, it might be an ODA issue. I'll write them an email to see if they have any clues.

**Comment by imamiao** [comment]
Hi, Jiang. I meet the same problem. And I made some attempts then found the reason.
The DXF document saying “If group 72 and/or 73 values are nonzero, then the first alignment point values are ignored and AutoCAD calculates new values based on the second alignment point and the length and height of the text string itself (after applying the text style). If the 72 and 73 values are zero or missing, then the second alignment point is meaningless.
”.
But the actual is when I set 72 and/or 73 values to nonzero, the first alignment point is effective still. As you find, it appear in R13 and after, and not appear in R12 and before.
Why the DXF file exported by AutoCAD and using ODA converted to dwg file the result is right? Because the DXF file exported by AutoCAD ,the text's first alignment point was calculated and satted.

**Comment by George-Jiang** [comment]
> Hi, Jiang. I meet the same problem. And I made some attempts then found the reason. The DXF document saying “If group 72 and/or 73 values are nonzero, then the first alignment point values are ignored and AutoCAD calculates new values based on the second alignment point and the length and height of the text string itself (after applying the text style). If the 72 and 73 values are zero or missing, then the second alignment point is meaningless. ”. But the actual is when I set 72 and/or 73 values to nonzero, the first alignment point is effective still. As you find, it appear in R13 and after, and not appear in R12 and before. Why the DXF file exported by AutoCAD and using ODA convert it to dwg file then can normal display? Because the DXF file exported by AutoCAD ,the text's first alignment point was calculated and setted. So I think It's a bug of AutoCAD. For resolve it, you can
> 
> 1. Setting the first alignment point by youself;
> 2. Using ODA convert DXF to R12 or before;
> 3. Asking Autodesk to fix the bug.(I am not hopeful about this.😂)

Thank you so much. I'll set the first alignment manually.
