### ISSUE TITLE
Drawing addons - errors with some entities

### ISSUE THREAD

**Issue by bdaniere** [mozman/ezdxf#689]
Hello, 

I have some problems when converting a DXF file to SVG format (using the drawing addons).
If one of the elements in the DXF file has an error, the whole conversion will be in error. I've had the case for elements with an invalid with (causing an **AssertionError**) or Hatch entities causing **RecursionError**.

Wouldn't it make sense to exclude these elements from the conversion if an error is detected? Couldn't a PR with simple exception handling be added?

So, in drawing.frontend.draw_entities :

```
def draw_entities(
        self,
        entities: Iterable[DXFGraphic],
        *,
        filter_func: FilterFunc = None,
    ) -> None:
        if filter_func is not None:
            entities = filter(filter_func, entities)
        for entity in entities:
            if not isinstance(entity, DXFGraphic):
                if self.config.proxy_graphic_policy != ProxyGraphicPolicy.IGNORE:
                    entity = DXFGraphicProxy(entity)
                else:
                    self.skip_entity(entity, "Cannot parse DXF entity")
                    continue
            properties = self.ctx.resolve_all(entity)
            self.override_properties(entity, properties)
            if properties.is_visible:
                try:
                    self.draw_entity(entity, properties)
                except (ValueError, AssertionError, RecursionError) as error:
                    self.skip_entity(entity, error)

            else:
                self.skip_entity(entity, "invisible")

```

**Comment by mozman** [comment]
I don't think silencing the exceptions is a good solution. Nobody will send error reports if there are no exceptions - nobody reads log files, or worse - I get error reports about missing entities in the output file without any clue about the reasons.

If the error is in `ezdxf` or in the drawing add-on - it should be fixed, and if the DXF file contains errors, maybe the `recover` module can be extended to fix them.

Post an (zipped) example file or send it to confidential@mozman.at. 

If you can't post or send an example file you will have to wait until someone else can.

**Comment by bdaniere** [comment]
Indeed, my logic is different: my objective is to obtain a result at the end of the conversion.
I have sent you a file with a RecursionError  : the using audit=True corrects other error types.

I will look at using the custom frontend: it seems like a good idea to avoid forking the original code too much. 

And eventually, if I encounter other errors during file conversion, not correctable with the auditor: I would create new issues to share the anomalies.

**Comment by mozman** [comment]
This may not be an error, it just shows the limits of `ezdxf`, the `HATCH(#4C9FDE)`  has 18_689 boundary path  and the `fast_bbox_detection()` function tries to recursively find the order of exterior and interior paths and this reaches the default recursion limit of Python.

You are expecting too much from `ezdxf` it is not a replacement for a CAD application.

**Comment by mozman** [comment]
Setting the recursion limit to 10_000 (default is 1_000) leads to a `MemoryError` exception. It could still be an error in the algorithm but this test data is not very helpful to find it.
