### ISSUE TITLE
Error when calling functions within modules

### ISSUE THREAD

**Issue by bonsoire** [mozman/ezdxf#693]
I'm having trouble using all of the functions within a module. 
For example the convert function within the 'odafc' module. 

The function is present in the modules python file however, I cannot make a call to the function. 

When printing the directory of the odafc module certain functions are not present. 
Perhaps it is relevant that this is true for all modules within the ezdxf package installed on my computer. 
Another example of this is when trying to make a call to functions that return entity properties. Such as polyline bulge values. 

EZDXF Version: 0.18b5
OS: Linux (Ubuntu)

The specific error is module 'name of module' has no attribute 'name of function'

Have you encountered an error like this previously?

**Comment by mozman** [comment]
Maybe this FAQ can help: https://ezdxf.mozman.at/docs/faq.html#imported-ezdxf-package-has-no-content-readfile-new
