### ISSUE TITLE
AutoCad can not open dxf file created by ezdxf0.18b5

### ISSUE THREAD

**Issue by chibai** [mozman/ezdxf#697]
**Describe the bug**
DXF file created by same script with different EZDXF version
0.17.2 file works well
but 0.18b5 can not be open

**To Reproduce**
```
import ezdxf
doc = ezdxf.new(dxfversion=ezdxf.DXF2018, setup=True)
doc.modelspace().add_line(start=(0, 0), end=(10, 10))
doc.saveas("line.dxf")
```

**Confidential Data**
[0.17.2.zip](https://github.com/mozman/ezdxf/files/8973139/0.17.2.zip)
[0.18b5.zip](https://github.com/mozman/ezdxf/files/8973140/0.18b5.zip)

**Comment by chibai** [comment]
Thank you for your hotfix, I will close this issue onece you release 0.18b6.

**Comment by mozman** [comment]
Autodesk products have bad DXF parsers and ridiculous error messages. I would stop supporting their applications until they improve their quality if they weren't so important.

**Comment by chibai** [comment]
> Autodesk products have bad DXF parsers and ridiculous error messages. I would stop supporting their applications until they improve their quality if they weren't so important.

Please don't do this~~I will send your complain on Autodesk Forums
