### ISSUE TITLE
With Ubuntu 22.04 + ODAFileConverter version (22.10, 22.12 or 23.6) return code is 131, which means `_odafc_failed` always returns true

### ISSUE THREAD

**Issue by autonomobil** [mozman/ezdxf#707]
System:
- ubuntu 22.04
- python 3.9
- ezdxf 0.17.2
- ODAFileConverter 22.10, 22.12 or 23.6 (tried all three) 

With Ubuntu 22.04 + ODAFileConverter version (22.10, 22.12 or 23.6) return code is `131`, which means `_odafc_failed()` always returns true, which means `_execute_odafc()` raises an error even if the odafc operation (dwg -> dxf) operation was successful.
Also this comment is wrong
```
# note: currently, ODAFileConverter does not set the return code
```
 as odafc returns an error code:
 ```
ODA File Converter failed: return code = 131.
```

I guess check for "Linux" system should be done before checking the `proc.returncode` for 0.

https://github.com/mozman/ezdxf/blob/b65091c796de5128ededa0773c11ffd83ea4f5a0/src/ezdxf/addons/odafc.py#L463-L474

Something like 

```python
    stderr = stderr.strip()
    if system == "Linux":
        # ODAFileConverter *always* crashes on Linux even if the output was successful
        return stderr != "" and stderr != "Quit (core dumped)"
    elif proc.returncode != 0:
        return True
    else:
        return stderr != ""
```

**Comment by mozman** [comment]
Please do me a favor and test this with the current beta version v0.18b7.

I added some integration tests for the odafc add-on: https://github.com/mozman/ezdxf/blob/master/integration_tests/test_odafc.py

This test do work on Linux Mint 20.3 (Kernel 5.4.0) and the ODAFileConverter 23.4.0 installed as AppImage.

**Comment by mozman** [comment]
The issue was reproducible on Linux Mint 21.
