### ISSUE TITLE
Is there a way to create a multi-polygon?

### ISSUE THREAD

**Issue by symonsoft** [mozman/ezdxf#71]
Need to create polygon with holes like the one that can be implemented as MultiPolygon feature in GeoJSON.

**Comment by symonsoft** [comment]
Please, may you provide an example of creation 2D multipolygon.

**Comment by mozman** [comment]
There is no MultiPolygon entity in DXF.

**Comment by symonsoft** [comment]
@mozman So there is no way to create a polygon with hole?
