### ISSUE TITLE
Two test failures on non-x86 architectures

### ISSUE THREAD

**Issue by musicinmybrain** [mozman/ezdxf#713]
**Describe the bug**
Two tests fail on `aarch64`, `ppc64le`, and `s390x` architectures, while all tests pass on `x86_64` and `i686`. Output from the two tests is identical (except for the function pointer address) on all three architectures on which they fail.

```
=================================== FAILURES ===================================
___________________________ test_circle_outside_rect ___________________________
rect = [(-1, -1), (1, -1), (1, 1), (-1, 1)]
    def test_circle_outside_rect(rect):
        c = circle(16, 3)
        result = clip_polygon_2d(rect, c, ccw_check=False)
        assert len(result) == 4
        for v in rect:
>           assert v in result
E           assert (-1, -1) in [Vec2(1.0, -0.9999999999999999), Vec2(1.0, 1.0), Vec2(-1.0, 0.9999999999999999), Vec2(-1.0, -0.9999999999999998)]
tests/test_06_math/test_618_clipping.py:64: AssertionError
_____________________ test_mapbox_earcut[issue142-Cython] ______________________
filename = PosixPath('/builddir/build/BUILD/ezdxf-0.18/integration_tests/mapbox-test-data/issue142.json')
earcut = functools.partial(<function earcut_driver at 0xffffa8c0f380>, func=<built-in function earcut>)
    @pytest.mark.parametrize(
        "earcut", [py_earcut, cy_earcut], ids=("CPython", CYTHON)
    )
    def test_mapbox_earcut(filename: Path, earcut):
        name = filename.stem
        with filename.open("rt") as fp:
            data = json.load(fp)
            shape = data[0]
            holes = data[1:]
            triangles = earcut(shape, holes)
>           assert len(triangles) == EXPECTED[name], f"{name}.json failed"
E           AssertionError: issue142.json failed
E           assert 7 == 4
E            +  where 7 = len([(Vec2(5.62675358811389, 31.94879819160804), Vec2(-16.369709114391867, 28.341954255099814), Vec2(5.62675358811389, 31.... 1.1716264034331543), Vec2(-8.602352370111433, 2.142874784407777), Vec2(-6.833718161055838, -0.6655405509524673)), ...])
integration_tests/test_mapbox_earcut.py:110: AssertionError
=========================== short test summary info ============================
FAILED tests/test_06_math/test_618_clipping.py::test_circle_outside_rect - as...
FAILED integration_tests/test_mapbox_earcut.py::test_mapbox_earcut[issue142-Cython]
============ 2 failed, 6823 passed, 31 skipped in 83.09s (0:01:23) =============
```

The `test_circle_outside_rect` failure appears to be a platform-dependent floating-point rounding difference. The nature of the `test_mapbox_earcut[issue142-Cython]` is less obvious.

**To Reproduce**
Information and data needed to reproduce the error:
1. I encountered these errors packaging ezdxf 0.18 for Fedora Linux, but it should be sufficient to run the tests in question on any real or emulated virtual machine of the architectures in question.
2. Using Fedora Linux 37/Rawhide (development version) and ezdxf 0.18.
3. I’m happy to do experiments and test candidate patches in emulation on my machine and/or on real hardware in the Fedora infrastructure.

**Confidential Data**
N/A

**Expected behavior**
All tests should pass.

**Comment by mozman** [comment]
Hi!

These test should pass now, the first one (618) is really fixed, the second one is just disabled.

FYI: The tests ran under Ubuntu 22.04 arm64 on a Raspberry Pi 400 without errors.

**Comment by musicinmybrain** [comment]
Works for me! Thank you for the investigation and quick fix.
