### ISSUE TITLE
$FINGERPRINTGUID and $VERSIONGUID changes at  loading

### ISSUE THREAD

**Issue by mozman** [mozman/ezdxf#729]
### Discussed in https://github.com/mozman/ezdxf/discussions/728

<div type='discussions-op-text'>

<sup>Originally posted by **chrmangold** August 10, 2022</sup>
Hi!

I want to know if the following is an intended behaviour of ezdxf package.

`# open a simple dxf file (eg. acad_table_simple.dxf)`
`doc = ezdxf.readfile(dxf_path)`

`# then print special header variables `
`print(doc.header['$FINGERPRINTGUID'])`
`print(doc.header['$VERSIONGUID'])`

valid uuids will be printed out. 
**But** - one can find the values in the dxf file. The printed uuids are not identical to the ones in the dxf file

**And** - each time I restart this snippet I get different uuids printed out. 

For me it seems like an unwanted situation, but I am not quite sure about that.

I need to be able to identify one drawing out of some attributes. 
So what is the best way to achieve this goal?

Thanks for any suggestions,

Chris 
</div>

**Comment by mozman** [comment]
The indented behavior is:

- `$FINGERPRINTGUID` never changes after document creation
- `$VERSIONGUID` changes at every export

That's fixed now.

**Comment by chrmangold** [comment]
Thank you very much for this nearly immediate response and fix.
