### ISSUE TITLE
Hatch entity has opposite x coordinates 

### ISSUE THREAD

**Issue by hahaha1213817** [mozman/ezdxf#736]
**Describe the bug**
Some Hatch entities queried from a dxf file have opposite x value, like -10000 instead of 10000.

**To Reproduce**
Information and data needed to reproduce the error:
1. query hacth entities in the dxf file given below,using query string: r"HATCH[layer=='S-TL-WALL']"

**Confidential Data**

[lost_wall.zip](https://github.com/mozman/ezdxf/files/9430225/lost_wall.zip)

**Expected behavior**
all hatch entities in this file should have positive x coordinates

**Screenshots**
![image](https://user-images.githubusercontent.com/55276147/186833369-ad5a050b-9ed0-4577-bc20-6a8b31fe80fa.png)
both hatches in this pic should be on the positive X-axis

**Comment by mozman** [comment]
Object Coordinate System: https://ezdxf.mozman.at/docs/concepts/ocs.html
