### ISSUE TITLE
Importing complex linetypes

### ISSUE THREAD

**Issue by andrpocc** [mozman/ezdxf#737]
Hi!
Is this warning can be fixed? What is wrong with my dxf file? Please, help :)
```
Required shape file entry "KUST_UZK_POLOS" not found.
Required shape file entry "zmm5.shx" not found.
Required shape file entry "zkp.shx" not found.
Required shape file entry "D:\ДОКУМЕНТЫ\ООО АЛМАКС\БИБЛИОТЕКИ\ТИПЫ ЛИНИЙ\ТОПОГРАФИЯ 500.SHX" not found.
Required shape file entry "ТОПОГРАФИЯ 500" not found.
Required shape file entry "more.shx" not found.
Required shape file entry "zds.shx" not found.
Required shape file entry "zmr.shx" not found.
Required shape file entry "ZHELEZ_DOR" not found.
Required shape file entry "zbbm.shx" not found.
Required shape file entry "zkbm.shx" not found.
```

My file: [dxf.zip](https://github.com/mozman/ezdxf/files/9437859/dxf.zip)

My code:
```python
from ezdxf.addons.importer import Importer
from ezdxf.filemanagement import new, readfile
from ezdxf.lldxf.const import DXF2018

fdoc = readfile("2013.dxf")
tdoc = new(DXF2018)

importer = Importer(fdoc, tdoc)
importer.import_table("linetypes")
importer.finalize()

tdoc.saveas("new.dxf")
```

As result, in new file, i have broken linetypes.

But I can find STYLE in dxf manually by shx name:
```
STYLE
  5
766
330
3
100
AcDbSymbolTableRecord
100
AcDbTextStyleTableRecord
  2

 70
     1
 40
0.0
 41
1.0
 50
0.0
 71
     0
 42
0.75
  3
more.shx
  4

  0
  ```
  
  So, I think, is there problem in parsing dxf?

**Comment by andrpocc** [comment]
`ezdxf/sections/table.py`
```python
def find_shx(self, shx_file: str) -> Optional["Textstyle"]:
        """Find the shape file (SHX file) text style table entry, by a case
        insensitive search.

        A shape file table entry has no name, so you have to search by the
        font attribute.

        Args:
            shx_file (str): shape file name like "gdt.shx"

        """
        lower_name = shx_file.lower()
        for entry in iter(self):
            if entry.dxf.font.lower() == lower_name:
                return entry
        return None
```
There are no style entries of linetypes in `iter(self)`. They are just skipped.

**Comment by andrpocc** [comment]
```
STYLE
  5
16894C
330
3
100
AcDbSymbolTableRecord
100
AcDbTextStyleTableRecord
  2
Legend
 70
     0
 40
0.0
 41
1.0
 50
0.0
 71
     0
 42
1.0
  3
calibri.ttf
  4

1001
ACAD
1000
Calibri
1071
      256
  0
```
There are only text styles like this, as I understand.

**Comment by mozman** [comment]
1. Use the [Importer](https://ezdxf.mozman.at/docs/addons/importer.html) add-on only for simple tasks
![image](https://user-images.githubusercontent.com/4230966/187056880-8e61ffe0-0d78-496d-9123-f0ec7b9a8140.png)


2. Resource data is not stored in DXF files, you have to ship the required files like SHX files or images by yourself along with the DXF file
3. Make sure your CAD application or DXF viewer is proper configured to find resource files.
4. ADVICE: Don't use complex line types, because only AutoCAD and very compatible applications can display them - this is bad for a drawing EXCHANGE format

**Comment by andrpocc** [comment]
Ok, I'll try to fix it myself.
