### ISSUE TITLE
drawing: the configuration.pdmode / pdsize values are ignored 

### ISSUE THREAD

**Issue by bdaniere** [mozman/ezdxf#739]
Hello,

I have converted DWG files to SVG format using addons.drawing
(I have also tested conversion to raster output formats such as .png)

On some files, including [sample.zip](https://github.com/mozman/ezdxf/files/9450780/sample.zip) , I have some problems with the rendering of HATCH entities:
some HATCH entities (for example the entity with the handle "FBE37") are composed of several points but their geometrical representation makes the whole more difficult to read
I tried to modify the configuration by changing the config.pdmode but this information is not taken into account 

Is this approach correct to change the representation of the point entities on the final render? 
(the goal is to change the pdmode value when converting from 32 (the default value) to 0)

**To Reproduce**

```Python
    from ezdxf.addons import odafc
    from ezdxf.addons.drawing.matplotlib import qsave
    from ezdxf.addons.drawing.config import Configuration

    doc = odafc.readfile("sample.dxf")

    config = Configuration.defaults()
    config = config.with_changes(
        pdmode=0,

    )

    qsave(
        layout=doc.modelspace(),
        filename="1344465490_convert.svg",
        bg="#FFFFFF00",
        config = config
    )

```

I work with Ubuntu 22.04.01 LTS / I tested with the latest versions of ezdxf (0.18)

On the left the visual of the area on the DXF file, on the right the rendering on the svg conversion :

![Capture d’écran du 2022-08-30 09-51-24](https://user-images.githubusercontent.com/36926578/187381473-750b33b8-45c3-43a6-80ee-26cc06b2ade1.png)

**Expected behavior**

I would like the gemetric representation of point entities to be center dot (.) , and not a center dot (.) + circle 
(nb : The value of configuration.pdsize is also ignored)

**Comment by mozman** [comment]
This seems to be an issue of the `Matplotlib` backend. The points are drawn by the `Frontend` as dimensionless points:

![image](https://user-images.githubusercontent.com/4230966/187584965-eaa23e6b-2e53-4e3f-a0ae-0c63737eecfe.png)

![image](https://user-images.githubusercontent.com/4230966/187584255-63731664-6466-402b-9c02-1b1888b4974c.png)

But the `savefig()`  method exports circles as shown by your screenshots.

There must be a setting in `matplotlib` to prevent this, but I'm not aware of it.

**Comment by mozman** [comment]
BTW: Using the `POINT` entity to create a "hatching" is really a hack and shouldn't be used, because they are dimensionless and the displayed result is not really defined, except by the assigned lineweight which is also ambiguous for a dimensionless point.

**Comment by mozman** [comment]
There was really an error in the default configuration of the drawing add-on, this doesn't solve the rendering of circles by `matplotlib` but you can suppress `POINT` rendering at all. See issue #765 if this is a solution for you.

```Python
config=config.with_changes(pdmode=1)  # do not plot any point geometry
```
