### ISSUE TITLE
Cannot get displayed position of inserts as autocad software shows

### ISSUE THREAD

**Issue by Gary-Chow** [mozman/ezdxf#74]
Mozman,
Hi, thank you very much for this amazing work. Wonderful and helpful!!!

**Needs:**
Extract entities **displayed** in a **certain area** in Autocad, and saveas a new dxf file. As a result, a dxf file will be splited to several dxf files.

**Problem:**
Only get the basepoint of the insert without other position attributes. The basepoints of inserts in my file are randomly fat away from themselves. So the basepoint coordinate cannot be used to determine the displayed position.

**Efforts:**
1. Insert is not iterable;
2. search blocks in modelspace which have the same name as the inserts. I use attribs and dxf.start (or dxf.insert) to get position info of object in blocks, codes shown as below. However, the position values of attribs and dxf.start are the same, meaning cannot use obj position to get the displayed coordinate of the blocks.
`dxf = ezdxf.readfile(file_name)`
`msp = dxf.modelspace()`
`for block in dxf.blocks:`
`　for obj in block:`
`　　get_position_from(obj.attribs())`
`　　get_position_by(obj.dxf.start) `

Thank you very much. 
(I am from China, without access to services of many websites, such as google)

Gary

**Comment by mozman** [comment]
You are expecting CAD functionality, which is not the domain of ezdxf, in the DXF file you have the BLOCK definition and the INSERT, which says where to insert the BLOCK (with scaling and rotation), which is than the work of the CAD application to execute this instructions.

**Comment by Gary-Chow** [comment]
Thank you for your suggestion. I will follow it.
