### ISSUE TITLE
DXFTableEntryError: Layer of Entity not in Layers

### ISSUE THREAD

**Issue by GeneralX-NL** [mozman/ezdxf#744]
Hello,

While processing a DXF file of unknown make and model, I encountered a DXFTableEntryError when I tried this:
`layer = someDrawing.layers.get(someEntity.dxf.layer)`

Where someDrawing is a Drawing and someEntity is a Line Entity from an EntitySection.  The DXFTableEntryError exception message brings up the name of the layer of the Entity.

I would expect that the layer of any Entity can be found in the Layers table of the Drawing. Apparently, that is not true. 
However: this particular DXF file can be opened in TrueView and DraftSight, where the entities that trigger the DXFTableEntryError can be viewed. They indeed belong to the layer that triggered the DXFTableEntryError. When I checked the overview of layers in these programs, the offending layer is present.

When I export the file from DraftSight as a DXF type that is officially supported by ezdxf, the layer is suddenly present in the Layers table. Apparently, a 'reliable' DXF editor can handle this type of file, without any prompts for data corruption.

Is this an issue with ezdxf, or with the source file? 

PS: I would share the source file, but it has confidential data. I would export the offending entities, but those would not throw a DXFTableEntryError.

Sincerely,
Vincent

**Comment by mozman** [comment]
The DXF format does not require a layer table entry for layers used by DXF entities, therefore this is the intended behavior of the  the `LayerTable.get()` method.

**Comment by GeneralX-NL** [comment]
Ohh I see, so basically the answer to my question is 'no'. I asked because I followed along with the Tutorial on Layers:
[https://ezdxf.readthedocs.io/en/stable/tutorials/layers.html#check-available-layers](url) 
Which suggests that I can loop over 'all layers' by iterating over layers, find number of layers by getting length of layers, etc. Apparently, that is not true in the strictest interpretation of 'all layers in a DXF file'. Sorry.

That begs the question; what would be the way to actually get all layers? I guess I would have to iterate over all entities, append all of them to a data structure of my own and use that instead. Thanks for the help so far. I guess I didn't know as much about DXF as I thought. Also, thanks for the super fast reply :)

**Comment by mozman** [comment]
This will find most likely all layer names used by DXF entities in layouts and blocks:

```python
from ezdxf.entities import is_graphic_entity

all_layer_names = [e.dxf.layer for e in doc.entitydb.values() if is_graphic_entity(e)]
```
The DXF format is a very sloppy file format and mostly defined by the behavior of AutoCAD.
The layer table entry is optional, text style entries are required otherwise AutoCAD will not open the DXF file and so on, and none of these rules are documented by the DXF reference.
