### ISSUE TITLE
UCS Translated Dimensions in MatPlotLib

### ISSUE THREAD

**Issue by logangutk** [mozman/ezdxf#747]
There is a bug that incorrectly displays dimensions through Matplotlib figure.show(), but it saves to a *.dxf correctly. When using ucs to translate the view from anything other than the XY plane, the dimensions shown in matplotlib figures do not rotate correctly. The white image was created using matplotlib. The black image was created using the dxf file being opened with Edrawings. I've attached two images to compare, as well as a link to my Github to access the script and it's associated dimensions csv to recreate the bug.

![Edrawings_display](https://user-images.githubusercontent.com/108148730/192629743-04e8fbf9-46d5-40dc-a119-75a9669bfec2.png)
![matplotlib_display](https://user-images.githubusercontent.com/108148730/192629746-8b631f6a-07f2-471c-b6dc-85252bca0cb9.png)

https://github.com/logangutk/EZDXF-GUI-v1

**Comment by mozman** [comment]
The bugfix works but you will not see the dimension text, because the `drawing` add-on does not support 3D text. 

For your information: the drawing add-on does only 2D rendering (ignores the z-axis) and therefore supports only TOP view rendering!

**Comment by logangutk** [comment]
Okay, thank you! Is there going to be any future effort to add 3D dimension text to the drawing add-on?

**Comment by mozman** [comment]
There are no plans for this in the near future.
