### ISSUE TITLE
layer.get_color returns 7 for every layer in dxf file

### ISSUE THREAD

**Issue by SBelkaid** [mozman/ezdxf#75]
extracting the color for every layer in my dxf file returns the int 7. Even though the plot in AutoCAD shows two different colours. Am I missing something when parsing the file before the colours can be read correctly?

```
>>> dwg = ezdxf.readfile('/Users/johndoe/Desktop/ISDA/GISAPI_documentatie/Ri4A1802_Peiling.dxf')
>>> for l in dwg.layers:
...     print(l.get_color())
7
7
7
7
7
7
7
7
```

<img width="508" alt="screenshot" src="https://user-images.githubusercontent.com/13128170/53721303-30a03180-3e63-11e9-9994-6d4e55e1f6cc.png">

the actual drawing should show two colours.

**Comment by mozman** [comment]
Colors assigned by a plot profile are not stored  in the DXF file (your screenshot does not load).

**Comment by SBelkaid** [comment]
Image has been uploaded. Why do you think the get_color function only returns 7?

**Comment by mozman** [comment]
Hi, first I am not an AutoCAD expert, I use other CAD software, so I can't tell yo why AutoCAD do anything, and second, this picture helps not really, not clear where the lines get their color, from layer, by ACI (AutoCAD Color Index), or truecolor value, if ACI, the ACI color can get overridden by plot profiles, and that only the few possibilities I know, maybe there are much more way to give an entity its color in AutoCAD.

If the color value (7) of the layer does not match the line color shown (1=red), means only the lines get their color from another source, or color 7 is overridden by a plot profile.

**Comment by SBelkaid** [comment]
I'm also not an AutoCAD expert, but if I load the file into AutoCAD then the different colours show. But when reading it into ezdxf and extracting the colours for the layers it does not give the correct color. Which other source in the dxf file can I try to get the correct colour from?
