### ISSUE TITLE
Hatch Islands

### ISSUE THREAD

**Issue by jeroenVerdonschot** [mozman/ezdxf#76]
Hi Mozman,

Great library. Works like a charm!
I wondered when you will include hatch islands?

Please let me know, or if I can help.

thanks,

Jeroen

**Comment by JuanCasado** [comment]
Yay, that would be great.
It is not totally clear if that is a missing feature or it it has been implemented but the tutorial for the documentation has not been done yet.
Please could someone give more information about it.

**Comment by mozman** [comment]
New tutorial: https://ezdxf.mozman.at/docs/tutorials/hatch.html#create-hatches-with-multiple-boundary-paths-islands
