### ISSUE TITLE
1006 dxf, dxf 2 svg , more points appear, Why?

### ISSUE THREAD

**Issue by srillia** [mozman/ezdxf#765]
ezdxf Version: [v1.0.0b1](https://github.com/mozman/ezdxf/releases/tag/v1.0.0b1)
[git-issue.zip](https://github.com/mozman/ezdxf/files/9926654/git-issue.zip)
nzk-1.dxf:
![image](https://user-images.githubusercontent.com/25891673/199675733-d4012090-46fc-417b-8a19-533e697018d2.png)
nzk-1.svg:
![image](https://user-images.githubusercontent.com/25891673/199675937-b4bf6141-8c7f-428b-8ce9-be920bc97436.png)

**Comment by mozman** [comment]
This is maybe the same issue as #739.

**Comment by srillia** [comment]
I read it  #739,  can not solve this now ?

**Comment by srillia** [comment]
how to set the line to black ,when I set transprant, the line alse white, check the doc, not found the right config.

**Comment by srillia** [comment]
> I read it #739, can not solve this now ?

if not ,
1. can control dxf some actions to prevent this?
2. or convert to svg, then remove the point from svg, by changing the svg raw text ?
like this:

```
           <g id="PathCollection_68">
                <g clip-path="url(#p85afc7f867)">
                    <use xlink:href="#m35b58e3d41" x="187.478017" y="90.989064"
                        style="fill: #ffffff; stroke: #ffffff" />
                </g>
            </g>

```
this maybe  represent a point in svg.

**Comment by mozman** [comment]
You can suppress point rendering at all by setting the `HEADER` variable `doc.header["$PDMODE"] = 1`. There was an error in the default configuration of the `drawing` add-on, so this just works with the current version of `ezdxf` in the `master` branch.

But this can also be done by the `Configuration` object of the `drawing` add-on:

```Python
from ezdxf import recover
from ezdxf.addons.drawing import matplotlib
from ezdxf.addons.drawing.config import Configuration

# Exception handling left out for compactness:
doc, auditor = recover.readfile('nzk-1.dxf')

if not auditor.has_errors:
    config = Configuration.defaults()
    matplotlib.qsave(
        doc.modelspace(), 
        'nzk-1.svg',
        config=config.with_changes(pdmode=1),  # do not plot any point geometry
    )
```
![image](https://user-images.githubusercontent.com/4230966/200183185-5e8c5a8a-f615-4769-9ea5-ca532d5a3037.png)

If this doesn't work at your system, you have to update `ezdxf` to current version in the `master` branch.

**Comment by srillia** [comment]
Totally thank you ! Nick job! remarkable!
