### ISSUE TITLE
layer name parse wrong, while layer name contains Chinese characters, num, english letters at same time

### ISSUE THREAD

**Issue by dunhaiyang** [mozman/ezdxf#766]
my layer name is "00-ZT-道路"
`doc = ezdxf.readfile(file_name)`
`layers = doc.tables.layers.entries.keys()`
`print(layers)`
and the result is "00-zt-道路",
The uppercase English letters became lowercase

**Comment by mozman** [comment]
This is not wrong, because for the DXF format the layer names are case-insensitive, therefore all tables store the entry keys in lowercase. The layer names itself are not altered!
