### ISSUE TITLE
having an issues with the ODA file converter on ubuntu 22.04.

### ISSUE THREAD

**Issue by Chetan-Yeola** [mozman/ezdxf#767]
Hello @mozman , 
Your git hub repository is interesting. I am trying to read a dwg file using  odafc.readfile() function. but facing some issue. UnknownODAFCError: ODA File Converter failed: return code = 127. I am using the ubuntu 22.04. 

![image](https://user-images.githubusercontent.com/72593205/200292896-d0347aa9-d27e-4c2a-97ec-4c36eef6d497.png)

**Comment by mozman** [comment]
I added a new config option for the odafc add-on: `unix_exec_path`. This may help if the `which` command can not find the ` ODAFileConverter` command  and also adds support for AppImages provided by ODA.

 This requires `ezdxf` v1.0.0rc1 which is not released on PyPI yet.

To use an AppImage read the updated docs for the odafc add-on: https://ezdxf.mozman.at/docs/addons/odafc.html and the current download link of the AppImage for version 23.10 is broken, use this link to version 23.9: https://download.opendesign.com/guestfiles/Demo/ODAFileConverter_QT5_lnxX64_8.3dll_23.9.AppImage

**Comment by Chetan-Yeola** [comment]
Hi @mozman.
Thanks for the reply. when new version of ezdxf comes out on PyPI?

**Comment by mozman** [comment]
The next release candidate `1.0.0rc1` will be published next weekend and the final `1.0.0` version will surely come later this year.

**Comment by Chetan-Yeola** [comment]
> The next release candidate `1.0.0rc1` will be published next weekend and the final `1.0.0` version will surely come later this year.
Thank you..!
