### ISSUE TITLE
Problems when setting dimgap of dimension with text valign = center.

### ISSUE THREAD

**Issue by ruben-ksdm** [mozman/ezdxf#77]
I'm setting dimgap for dimension with text valign='center'.
```
import ezdxf
from ezdxf.tools.standards import setup_drawing, setup_dimstyle, setup_styles
from ezdxf.options import options
from ezdxf.render.arrows import ARROWS


def setup_dimstyles(dwg: 'Drawing', domain: str = 'all') -> None:
    setup_styles(dwg)
    ezdxf_dimstyle = setup_dimstyle(
        dwg,
        name='EZDXF',
        fmt='EZ_M_232_H100_M',
        style=options.default_dimension_text_style,
        blk=ARROWS.architectural_tick)
    ezdxf_dimstyle.dxf.dimgap = 2
    ezdxf_dimstyle.dxf.dimexe = 0.15
    ezdxf_dimstyle.set_text_align(valign='center')
    dwg.header['$DIMSTYLE'] = 'EZDXF'
    ezdxf_dimstyle.copy_to_header(dwg)


dwg = ezdxf.new('R2010', setup=True)
msp = dwg.modelspace()
setup_dimstyles(dwg)
dim = msp.add_aligned_dim(
    p1=[0, 0], p2=[10, 0], distance=2)
dim.render()
dwg.saveas("GapTest.dxf")
```
And look what I'm getting.
![image](https://user-images.githubusercontent.com/47742758/54693261-bbf61400-4b3f-11e9-88ea-ca07b69c71f0.png)
As you see the dimgap is 2, but it isn't rendered on the dimension... And when I change the value to 2.01 from AutoCAD I'm getting right rendering.
![image](https://user-images.githubusercontent.com/47742758/54693480-273fe600-4b40-11e9-8c71-26b7bde4ddcc.png)
So is there a problem with ezdxf or I'm doing something wrong?

**Comment by mozman** [comment]
ezdxf will NEVER render exact like AutoCAD - you get what you get. ezdxf is not a CAD application.

**Comment by ruben-ksdm** [comment]
Ok, so this means that I can't set dimension gaps with ezdxf? If so, it would be great to see some warning in the documentation.
