### ISSUE TITLE
dxfToPng Error

### ISSUE THREAD

**Issue by qing0** [mozman/ezdxf#777]
Hello @mozman ,

I used examples\addons\drawing\draw_cad.py to convert a dxf file with a single line of text to png, but the following error occurred.

![企业微信截图_20221116100540](https://user-images.githubusercontent.com/46280740/202066127-7c811aa8-0948-4d36-9665-ab9738b7e8e7.png)

After debugging, the font was found to be the problem, which may be caused by the shx file I used. How can I solve this error

![image](https://user-images.githubusercontent.com/46280740/202067155-8ca5be02-ba5b-4ff0-81ff-c6acbe63f896.png)

**Comment by mozman** [comment]
If this fix doesn't work, reopen the issue and post the new stack trace.
