### ISSUE TITLE
'vertices' must be 2D with shape (M, 2). Your input has shape (0,).

### ISSUE THREAD

**Issue by qing0** [mozman/ezdxf#778]
Hi @mozman
I have raised this problem on #777, but according to your modification, the problem still hasn't been solved. The root cause of the problem is the position in the picture.
![image](https://user-images.githubusercontent.com/46280740/202382818-528e1f76-cb98-4cde-87f8-467781b31189.png)
Here are the two monitors I added. path.verticles are ndarray[60,2], but [(v.x, v.y) for v in vertices] is of 0 length. Then checkShape error when using path(), I don't know what verticles should look like to satisfy this condition.
![image](https://user-images.githubusercontent.com/46280740/202383516-efbbdc6c-0002-4dc3-acac-1895eb28b424.png)

Attached is my zip file for testing
[test.zip](https://github.com/mozman/ezdxf/files/10028986/test.zip)

**Comment by mozman** [comment]
I need your whole stack trace because I can not reproduce the error, the fallback font does not raise this error.

    PS C:\Users\mozman\Downloads\test> ezdxf draw -o test.png .\Drawing3.dxf
    loading file ".\Drawing3.dxf"...
    findfont: Font family ['zbtxt'] not found. Falling back to DejaVu Sans.
    exporting to "test.png"...

Just to be clear: you have to install the latest `ezdxf` version from github, the version on PyPI doesn't have the fix!

**Comment by qing0** [comment]
> Referen

Thanks for your reminding. I updated the latest version, and there are no bugs after the test, but the text is garbled.
![image](https://user-images.githubusercontent.com/46280740/202394905-3a87a2e5-fdf9-4040-8837-4139522546db.png)
I used another dxf file to test, and the previous exception reappeared.
Attached is my zip file for testing
[test.zip](https://github.com/mozman/ezdxf/files/10029354/test.zip)

**Comment by qing0** [comment]
> > Referen
> 
> Thanks for your reminding. I updated the latest version, and there are no bugs after the test, but the text is garbled. ![image](https://user-images.githubusercontent.com/46280740/202394905-3a87a2e5-fdf9-4040-8837-4139522546db.png) I used another dxf file to test, and the previous exception reappeared. Attached is my zip file for testing [test.zip](https://github.com/mozman/ezdxf/files/10029354/test.zip)
This is the stack trace
![image](https://user-images.githubusercontent.com/46280740/202395371-29f952e7-73e5-48dc-99a5-77b26ac42fbc.png)

**Comment by mozman** [comment]
Thank you, this exception should be handled by the fix in commit 410ed91.

**Comment by qing0** [comment]
> Thank you, this exception should be handled by the fix in commit [410ed91](https://github.com/mozman/ezdxf/commit/410ed91b9049754b51efc18e54844ec1464ae9ed).

Thank you very much for your reply. The problem has indeed been solved.
