### ISSUE TITLE
Writing script for 2D projections creation from existing dxf.

### ISSUE THREAD

**Issue by ruben-ksdm** [mozman/ezdxf#78]
Hi! First of all, thank you for your hard work!
I want to write a program, that will generate 2D projections of the 3D DXF objects automatically... And I liked ezdxf, so I want to understand if I can do all that with the ezdxf? Can I access all the geometry of the file?
If so, can you give me some hints to get the job done?
Thanks.

**Comment by ruben-ksdm** [comment]
And yes... Objects are in blocks in the target dxf files... + They are in R12 version (but I hope I'll change the version in the future).

**Comment by jmacura** [comment]
Hi @ruben-ksdm ! It depends on what you mean by "2D projections of the 3D objects". If it programmatically means just ommiting the Z value of object's coordinates, then it's definitely possible, if you mean some kind of geometric/spatial projection, then you will have to use another library as well.
If you are looking for a help with objects in blocks, check corresponding parts of the documentation: [Block](https://ezdxf.mozman.at/docs/blocks/block.html) & [Insert](https://ezdxf.mozman.at/docs/blocks/insert.html) ;-)
