### ISSUE TITLE
DXF unicode encoded layer names should not raise an exception

### ISSUE THREAD

**Issue by chungkang** [mozman/ezdxf#782]
**Describe the bug**
When I'm trying to read dxf file which includes German Umlauts(ä, ö, ü) letters in layer name, it shows the error below.
![image](https://user-images.githubusercontent.com/36185863/203872053-255b621f-3501-420d-8bc7-dd9d4c79d559.png)

**To Reproduce**
Information and data needed to reproduce the error:
1. A *simplified* Python script which triggers the error.
doc = ezdxf.readfile("umlaut_layer_test.dxf")

3. Information about the *ezdxf* version and the OS.
dzdxf 0.17.2 / Window 11

4. If a 3rd party DXF file causes the error, add a *simplified* and *zipped* 
[dxf](https://drive.google.com/file/d/1mpQR5R44RR_aMpHo8Ib9wSBLtXRdsCv1/view?usp=share_link)

**Expected behavior**
Checking the error when reading the letter Umlauts ü(Unicode Character: \U+00FC)

**Comment by mozman** [comment]
Can not open your DXF file!

This works in the current version of ezdxf:

![image](https://user-images.githubusercontent.com/4230966/203900207-4f378edc-acf1-49fb-b328-28addf3235e2.png)


![image](https://user-images.githubusercontent.com/4230966/203900118-1a1b0432-2b78-4a8b-bca7-40922d818cb7.png)

**Comment by mozman** [comment]
The recover module decodes the DXF unicode encoding: `\U+00FC` -> ü

Documentation of the `recover` module: https://ezdxf.mozman.at/docs/drawing/recover.html

**Comment by chungkang** [comment]
recover module works well. Thanks
