### ISSUE TITLE
An issue in the __virtual_entities__ interface that causes some problems in other entities rendering 

### ISSUE THREAD

**Issue by IvanKachaikinCendas** [mozman/ezdxf#783]
Hi @mozman! First of all, thanks once again for your amazing package that makes my life easier every day 🤩

I think however that I found some issue in the plan that you may find below. **What happens specifically**: in the file `hatches_orig.dxf` (available in the archive below) you may find a single block reference with a few hatches inside it. If you view it using `ezdxf view` you will see the following image:

![ezdxf-view-orig](https://user-images.githubusercontent.com/94542840/204343122-c5244081-8f78-4363-9768-7295b58fce66.png)

Whereas in AutoCAD it looks like that:

![autocad-view-no-ezdxf](https://user-images.githubusercontent.com/94542840/204343319-6de38a05-e6d5-4348-afc6-e358a1df950f.png)

After that, if you explode the block reference using `ezdxf` (the plan that I get: `hatches_exploded_ezdxf.dxf` is also available in the archive attached), you will get the following images:

- `ezdxf view`
![ezdxf-view-orig](https://user-images.githubusercontent.com/94542840/204343526-4de55d0f-00d5-4510-9aef-9b83f00e8a9a.png)
- AutoCAD
![autocad-view-ezdxf](https://user-images.githubusercontent.com/94542840/204343727-42bcccd0-13e0-417c-81db-2096d79c2a4d.png)

So it starts looking the same, moreover **the most interesting thing**: if you explode the block reference in AutoCAD (the file that I get: `hatches_exploded_autocad.dxf` is also available in the archive attached), it also looks the same in both `ezdxf view` and AutoCAD, and it looks just as the original file view in AutoCAD:

- `ezdxf view`
![ezdxf-view-autocad-exploded](https://user-images.githubusercontent.com/94542840/204344520-599c503d-d690-4531-b4c7-50a05e4b663b.png)
- AutoCAD
![autocad-view-no-ezdxf](https://user-images.githubusercontent.com/94542840/204344575-76bbcab6-015e-406d-8724-00161df5b86b.png)

As `ezdxf` is completely able to render the hatch pattern in the provided DXFs, I suppose that this issue happens somewhere inside the `__virtual_entities__` protocol that is called on both block reference explosion and on the `Frontend.draw_entities`.

Please let me know what do you think about this issue, do not hesitate to ask for any additional info and thanks for taking it into account.

The archive with files:
[hatches_github_issue.zip](https://github.com/mozman/ezdxf/files/10106258/hatches_github_issue.zip)

**Comment by mozman** [comment]
The transformation of the block reference was not applied to the pattern filling, this is fixed now, but the fix works only for uniform scaling as expected, because `ezdxf` does not support non-uniform scaling of patterns. The current implementation takes the scaling factor from the x-axis: scaling factor = length of the transformed x-axis unit-vector.

![image](https://user-images.githubusercontent.com/4230966/205485620-ff831a59-40aa-4b9c-bca9-316c2c0b128d.png)

**Comment by IvanKachaikinCendas** [comment]
@mozman Ok got it, thanks a lot for the fix and for this clarification!
