### ISSUE TITLE
dxf file not opening in Autocad

### ISSUE THREAD

**Issue by rossop** [mozman/ezdxf#8]
The following test script is meant to create a .dxf file with some line and circles. The script runs with no errors, but I am not able to load the dxf files on Autocad. 

When I try to load the file on A360 view the error is "Unrecoverable exit code from extractor: -1073741831"
```
  1 import ezdxf                                                                    
  2 import numpy as np                                                              
  3 import scipy.io as sio                                                          
  4 import pathlib                                                                  
  5 import sys                                                                      
  6                                                                                 
  7 data = {'circles':[[5, [13, 2]], [19, [15, 15]], [19, [12, 4]], [8, [8, 13]],   
  8         [3, [29, 29]],[2, [8, 11]], [1, [2, 6]]],                               
  9         'lines':[[[12, 18], [3, 2], 'CONTINUOS', 'B'],                          
 10         [[29, 4], [18, 15], 'DASHED', 'A'],                                     
 11         [[5, 24], [10, 16], 'DASHED', 'A'],                                     
 12         [[8, 20], [21, 23], 'DOTTED', 'B'],                                     
 13         [[7, 28], [5, 25], 'CONTINUOS', 'B'],                                   
 14         [[3, 14], [4, 29], 'CONTINUOS', 'A'],                                   
 15         [[11, 16], [13, 3], 'DOTTED','A']]}                                     
 16         #line format [x_start, x_end], [y_start, y_end], style, layer           
 17                                                                                 
 18 dwg = ezdxf.new('AC1015') # Version necessary for saving images                 
 19 msp = dwg.modelspace()                                                          
 20 layout = dwg.layout()                                                           
 21                                                                                 
 22 dwg.layers.new(name = 'CIRCLES',dxfattribs={'linetype': 'DASHED', 'color': 5})  
 23 dwg.layers.new(name = 'A', dxfattribs={'color': 5})                        
 24 dwg.layers.new(name = 'B', dxfattribs={'color': 5})                        
 25 dwg.layers.new(name = 'C', dxfattribs={'color': 5})                        
 26                                                                                 
 27 # WRITE                                                                         
 28 for circle in data['circles']:                                                  
 29     r = circle[0]                                                               
 30     center = tuple(circle[1])                                                   
 31     msp.add_circle(center, r, dxfattribs = {'layer': 'CIRCLE'})                 
 32 print 'circle'                                                                  
 33                                                                                 
 34 for line in data['lines']:                                                      
 35     line_strt = (line[0][0], line[1][0])                                        
 36     line_end  = (line[0][1], line[1][1])                                        
 37     msp.add_line(line_strt, line_end, dxfattribs= {'linetype':line[2],          
 38         'layer':line[3]})                                                       
 39 print 'lines'                                                                   
 40                                                                                 
 41                                                                                 
 42                                                                                 
 43                                                                                 
 44 dwg.saveas('issue#01.dxf')    ```

**Comment by mozman** [comment]
You use undefined linetypes and AutoCAD seems to be very picky about line types, unlike layers.

Edited your script to show how to print the available line types and how to add new line types, there are some predefined line types in ezdxf.tools.standards.

    import ezdxf
    from ezdxf.tools.standards import linetypes

    data = {'circles': [[5, [13, 2]], [19, [15, 15]], [19, [12, 4]], [8, [8, 13]],
                        [3, [29, 29]], [2, [8, 11]], [1, [2, 6]]],
            'lines': [[[12, 18], [3, 2], 'CONTINUOUS', 'B'],
                      [[29, 4], [18, 15], 'DASHED', 'A'],
                      [[5, 24], [10, 16], 'DASHED', 'A'],
                      [[8, 20], [21, 23], 'HIDDEN', 'B'],
                      [[7, 28], [5, 25], 'CONTINUOUS', 'B'],
                      [[3, 14], [4, 29], 'CONTINUOUS', 'A'],
                      [[11, 16], [13, 3], 'DOT', 'A']]}
    # line format [x_start, x_end], [y_start, y_end], style, layer

    dwg = ezdxf.new('AC1015')  # Version necessary for saving images

    # create new linetypes:
    for name, desc, pattern in linetypes():
        try:  # you can only create not existing line types
            dwg.linetypes.new(name=name, dxfattribs={'description': desc, 'pattern': pattern})
        except ValueError:
            pass  # ignore already existing line types

    print('available line types:')
    for linetype in dwg.linetypes:
        print(linetype.dxf.name)

    msp = dwg.modelspace()
    layout = dwg.layout()


    dwg.layers.new(name='CIRCLES', dxfattribs={'linetype': 'DASHED', 'color': 5})
    dwg.layers.new(name='A', dxfattribs={'color': 5})
    dwg.layers.new(name='B', dxfattribs={'color': 5})
    dwg.layers.new(name='C', dxfattribs={'color': 5})

    # WRITE
    for circle in data['circles']:
        r = circle[0]
        center = tuple(circle[1])
        msp.add_circle(center, r, dxfattribs={'layer': 'CIRCLE'})

    for line in data['lines']:
        line_strt = (line[0][0], line[1][0])
        line_end = (line[0][1], line[1][1])
        msp.add_line(line_strt, line_end, dxfattribs={'linetype': line[2],
                                                      'layer': line[3]})

    dwg.saveas('issue08.dxf')

**Comment by rossop** [comment]
Am I correct to use tuples for variables defining center of the circle, and line extremes?

**Comment by rossop** [comment]
For some reason A360.view doesn't support DOT as linetype.

**Comment by mozman** [comment]
Change the dxf format from 'AC1015' to 'AC1027' and A360 opens the DXF file.

Added 'DOTTED' line type to show how to create your own line types:

    import ezdxf
    from ezdxf.tools.standards import linetypes

    data = {'circles': [[5, [13, 2]], [19, [15, 15]], [19, [12, 4]], [8, [8, 13]],
                        [3, [29, 29]], [2, [8, 11]], [1, [2, 6]]],
            'lines': [[[12, 18], [3, 2], 'CONTINUOUS', 'B'],
                      [[29, 4], [18, 15], 'DASHED', 'A'],
                      [[5, 24], [10, 16], 'DASHED', 'A'],
                      [[8, 20], [21, 23], 'HIDDEN', 'B'],
                      [[7, 28], [5, 25], 'CONTINUOUS', 'B'],
                      [[3, 14], [4, 29], 'CONTINUOUS', 'A'],
                      [[11, 16], [13, 3], 'DOTTED', 'A']]}
    # line format [x_start, x_end], [y_start, y_end], style, layer

    dwg = ezdxf.new('AC1027')  # Version necessary for saving images

    for name, desc, pattern in linetypes():
        try:  # you can only create not existing line types
            dwg.linetypes.new(name=name, dxfattribs={'description': desc, 'pattern': pattern})
        except ValueError:
            pass  # ignore already existing line types

    # Define your own line types:
    # dxf linetype definition
    # name, description, elements:
    # elements = [total_pattern_length, elem1, elem2, ...]
    # total_pattern_length = sum(abs(elem))
    # elem > 0 is line, < 0 is gap, 0.0 = dot;
    my_line_types = [
        ("DOTTED", "Dotted .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .", [0.2, 0.0, -0.2]),
        ("DOTTEDX2", "Dotted (2x) .    .    .    .    .    .    .    . ", [0.4, 0.0, -0.4]),
        ("DOTTED2", "Dotted (.5) . . . . . . . . . . . . . . . . . . . ", [0.1, 0.0, -0.1]),
    ]
    for name, desc, pattern in my_line_types:  # I know that DOTTED does not exist
        dwg.linetypes.new(name=name, dxfattribs={'description': desc, 'pattern': pattern})


    print('available line types:')
    for linetype in dwg.linetypes:
        print(linetype.dxf.name)

    msp = dwg.modelspace()
    layout = dwg.layout()


    dwg.layers.new(name='CIRCLES', dxfattribs={'linetype': 'DASHED', 'color': 5})
    dwg.layers.new(name='A', dxfattribs={'color': 5})
    dwg.layers.new(name='B', dxfattribs={'color': 5})
    dwg.layers.new(name='C', dxfattribs={'color': 5})

    # WRITE
    for circle in data['circles']:
        r = circle[0]
        center = tuple(circle[1])
        msp.add_circle(center, r, dxfattribs={'layer': 'CIRCLE'})

    for line in data['lines']:
        line_strt = (line[0][0], line[1][0])
        line_end = (line[0][1], line[1][1])
        msp.add_line(line_strt, line_end, dxfattribs={'linetype': line[2],
                                                      'layer': line[3]})

    dwg.saveas('issue08.dxf')

**Comment by rossop** [comment]
Thank you very much!
