### ISSUE TITLE
Add LEADER entity

### ISSUE THREAD

**Issue by ebrahimraeyat** [mozman/ezdxf#80]
Hello @mozman  and very thanks for your useful library. I am writing a pyconcrete library and want to use leader in my drawing. can you please guide me, i can't find this entity in ezdxf.

[pyconcrete](https://github.com/ebrahimraeyat/pyconcrete)

**Comment by mozman** [comment]
adding LEADER is not supported yet and will not supported in the near future

**Comment by ebrahimraeyat** [comment]
> adding LEADER is not supported yet and will not supported in the near future

Thanks. can i copy it from another dxf file. i tried it, but text did not appear. this is my original leader.dxf file:

![image](https://user-images.githubusercontent.com/8196112/56796687-52e17a80-6828-11e9-9868-a01c27596976.png)

```python
import ezdxf
dwg = ezdxf.readfile('/home/ebi/leader.dxf')
msp = dwg.modelspace()

for e in msp:
    if e.dxftype() == 'LEADER':
        leader = e
    if e.dxftype() == 'MTEXT':
        if e.dxf.handle == 'EE':
            lt = e
        else:
            t = e

new_dwg = ezdxf.new('AC1024')
msp2 = new_dwg.modelspace()
leader.dxf.annotation_type = 0
leader.dxf.annotation_handle = lt.dxf.handle
lt.set_text('5~16')
lt.dxf.owner = leader.dxf.owner
msp2.add_entity(lt)
msp2.add_entity(t)
msp2.add_entity(leader)
new_dwg.saveas('/home/ebi/copy_leader.dxf')
```

**Comment by ebrahimraeyat** [comment]
if i read leader from base file like leader.dxf as above and add it to existing dxf file, it change leader to text in my existing dxf file and annotation also change! text convert to point!

input and output file
[leader.zip](https://github.com/mozman/ezdxf/files/3125460/leader.zip)

```python
import ezdxf
doc = ezdxf.readfile('/home/ebi/leader.dxf')
msp = doc.modelspace()

for e in list(msp):
    if e.dxftype() == 'LEADER':
        leader = e
    if e.dxftype() == 'MTEXT':
        if e.dxf.handle == '215':
            lt = e
        else:
            t = e

new_dwg = ezdxf.readfile('/home/ebi/beamtype75.dxf')
# new_dwg = ezdxf.new()
msp2 = new_dwg.modelspace()
block = new_dwg.blocks.new_anonymous_block(base_point=(0, 0))
lt.set_text('{\FROMANSP.SHX|c0;11~20}')
# msp.unlink_entity(lt)
# msp.unlink_entity(t)
# msp.unlink_entity(leader)
block.add_entity(leader)
block.add_entity(lt)
block.add_entity(t)

msp2.add_blockref(block.name, insert=(0, 22))
# msp.move_to_layout(e, msp2)
# msp.move_to_layout(lt, msp2)

new_dwg.saveas('/home/ebi/aleader_after.dxf')
```

![image](https://user-images.githubusercontent.com/8196112/56869604-bbdb1500-6a17-11e9-9613-7e04ffcdabf6.png)

**Comment by ebrahimraeyat** [comment]
I found a c++ implementation of LEADER. here it is:

https://github.com/OSGeo/gdal/blob/master/gdal/ogr/ogrsf_frmts/dxf/ogrdxf_leader.cpp

this is explanation:

https://atlight.github.io/formats/dxf-leader.html

**Comment by mozman** [comment]
Added LEADER support in v0.10b2, this is a beta release with a complete new entity system, tested with many testfiles, but still a beta version! Use the 'develop' branch of the repository or the PyPI [link](https://pypi.org/project/ezdxf/0.10b1/).

ezdxf supports all DXF attributes of the LEADER entity, but as you can see in the documents you referred, the most work has to be done by yourself.

**Comment by ebrahimraeyat** [comment]
very thanks @mozman . I implemented it in my library:

![image](https://user-images.githubusercontent.com/8196112/57562900-82f25700-73ac-11e9-8137-ed819e3b7a66.png)
