### ISSUE TITLE
AcDbPolyline Misc-Closed

### ISSUE THREAD

**Issue by Kiradle** [mozman/ezdxf#81]
### Code :
`import ezdxf

file = ezdxf.readfile("test_102.dxf")

file.saveas("test_102_saveas.dxf")`
### File “test_102.dxf”:
Misc - Closed : **_Yes_**
![snipaste20190422_102329](https://user-images.githubusercontent.com/13702698/56479581-b138f100-64e8-11e9-946e-1ee0054f0a2d.png)

### File "test_102_saveas.dxf"
Misc - Closed : **_No_**
![snipaste20190422_102540](https://user-images.githubusercontent.com/13702698/56479633-070d9900-64e9-11e9-8b01-9540fa76375b.png)

Compare  the files, found this :
Left : "test_102.dxf" ,  Right : "test_102_saveas.dxf"
![snipaste20190422_100615](https://user-images.githubusercontent.com/13702698/56479219-bc8b1d00-64e6-11e9-9a6d-fa286719c246.png)

if I move "90 \n 4" below "AcDbPolyline" , it can be closed. 
I can't find how to fix this.
sorry for my poor English...

**Comment by mozman** [comment]
this issue is fixed in v0.9, or if you using Python 2 v0.8.10

**Comment by Kiradle** [comment]
Thank you!
