### ISSUE TITLE
cylinder_2p in negative z-direction

### ISSUE THREAD

**Issue by AGeissler** [mozman/ezdxf#810]
Trying to create a cylinder_2p object with cylinder extrusion in negativ z-direction leads to "ZeroDivisionError" ('float division'). Tracing this back leads to forms.py and the call in line 849 to reference_frame_z(), line 1275.

The code would seem to lack a check of extrusion direction as in the function 'reference_frame_ext()', which according to the code documentation would seem the correct function to be called, as the heading direction is parallel to the z-axis (WCS).

I experimentally added 
    try:
        return UCS(uy=Z_AXIS.cross(heading), uz=heading, origin=origin)
    except ZeroDivisionError:
        return(reference_frame_ext(UCS(heading), origin=origin))

in line 1275 ff. (forms.py) and this seems to work (no extensive tests done, however).

**Comment by mozman** [comment]
please add code which shows the issue

**Comment by AGeissler** [comment]
Hm. Thanks for the quick reply. Generating an "atomic" code example would be a lot of work. Can I simply give you the full case (one .dxf file, one .py file that does "lots of stuff")?
