### ISSUE TITLE
Arcs not visible in DXF created by AutoCAD Plant3D

### ISSUE THREAD

**Issue by jsimomaa** [mozman/ezdxf#832]
**Describe the bug**
Some parts of the DXF is not rendered

**To Reproduce**
```sh
ezdxf view proxy.dxf
```

Here is the DXF: 
[proxy.zip](https://github.com/mozman/ezdxf/files/10705931/proxy.zip)

**Expected behavior**
Arcs would be visible as well

**Screenshots**
ezdxf view:
![image](https://user-images.githubusercontent.com/4503494/218057924-b6319a06-db52-42e8-b8b8-6f2869feb965.png)

Trueview:
![image](https://user-images.githubusercontent.com/4503494/218057357-27deca16-5a3c-4155-b6bc-8008322aa95b.png)

**Comment by mozman** [comment]
Hi!

The elliptic arc is a new proxy graphic entity to me and it's not documented in the DWG reference from the Open Design Alliance.

I figured out how it works for this example. This is the exploded proxy graphic and it looks fine:

![image](https://user-images.githubusercontent.com/4230966/218094922-6afe06b7-08cf-4619-b8b6-221bd72557a3.png)

But I need more examples that don't just have 180 degree arcs and axes that don't line up with the x- and y-axis of the WCS.

Please, can you provide such PROXY_ENTITY examples?

**Comment by jsimomaa** [comment]
Thank you for the support!

Here is another example with proxy graphics:
[proxy2.zip](https://github.com/mozman/ezdxf/files/10708057/proxy2.zip)

**Comment by mozman** [comment]
My implementation of the elliptic arc entity seems to work:

![image](https://user-images.githubusercontent.com/4230966/218133258-f1e22d29-00a1-4983-b145-36a048cdfa61.png)

I'll close this issue, please open a new issue if you find another example that isn't rendering correctly.
