### ISSUE TITLE
Flattening a closed spline

### ISSUE THREAD

**Issue by tkvw** [mozman/ezdxf#851]
I created a simplistic spline using librecad
![image](https://user-images.githubusercontent.com/621098/225985490-071bdfb4-011c-4625-81b7-f2cc5c088940.png)

And now I want to flatten the spline in individual segments, but the segmentation stops at the endpoint, giving me this result: 
(this is plotted on a makerjs wireframe)
![image](https://user-images.githubusercontent.com/621098/225985375-11086eb4-ba77-41dd-ac83-8f94dd2dec48.png)

Not sure if I am overseeing something? 

```python
vertices = list(entity.flattening(
    distance=0.1))
closed = entity.closed
print(entity.fit_points)
print(entity.control_points)
print(entity.knots)
print(vertices)
```
Results in: 
````
VertexArray = [
(4.316836604832383, 42.0052285344867, 0.0),
(98.52072115318319, 84.60193782322365, 0.0),
(231.7131834383106, -6.988996869971034, 0.0),
(113.4714360169731, 46.23466596259892, 0.0)
]
array('d', [0.0, 0.0, 0.0, 0.5, 1.0, 1.0, 1.0])
[Vec3(4.316836604832383, 42.0052285344867, 0.0), Vec3(15.984479777259878, 46.984535255597045, 0.0), Vec3(27.436438157454663, 51.27327809674384, 0.0), Vec3(38.672711745416734, 54.87145705792709, 0.0), Vec3(49.693300541146094, 57.779072139146784, 0.0), Vec3(60.498204544642746, 59.996123340402924, 0.0), Vec3(71.08742375590668, 61.52261066169553, 0.0), Vec3(81.4609581749379, 62.35853410302458, 0.0), Vec3(91.61880780173642, 62.50389366439007, 0.0), Vec3(101.56097263630222, 61.958689345792024, 0.0), Vec3(111.2874526786353, 60.72292114723042, 0.0), Vec3(120.79824792873569, 58.79658906870528, 0.0), Vec3(130.09335838660334, 56.17969311021659, 0.0), Vec3(139.17278405223828, 52.872233271764344, 0.0), Vec3(148.03652492564055, 48.87420955334855, 0.0), Vec3(156.68458100681008, 44.1856219549692, 0.0), Vec3(165.1169522957469, 38.80647047662631, 0.0), Vec3(172.71945783480214, 33.46883053556401, 0.0), Vec3(178.87791666632685, 28.90477754902646, 0.0), Vec3(183.59232879032112, 25.114311517013657, 0.0), Vec3(186.86269420678494, 22.097432439525594, 0.0), Vec3(188.68901291571825, 19.854140316562276, 0.0), Vec3(189.06065475486096, 19.022589363027397, 0.0), Vec3(189.07128491712103, 18.384435148123703, 0.0), Vec3(188.72090340249855, 17.939677671851193, 0.0), Vec3(188.00951021099343, 17.688316934209872, 0.0), Vec3(185.50368879733531, 17.76578567482079, 0.0), Vec3(181.5538206761467, 18.61684136995645, 0.0), Vec3(176.1599058474276, 20.241484019616856, 0.0), Vec3(169.32194431117807, 22.639713623802006, 0.0), Vec3(161.03993606739803, 25.8115301825119, 0.0), Vec3(140.14377945724652, 34.475924163505915, 0.0), Vec3(113.4714360169731, 46.23466596259892, 0.0)]

````

I am expecting that path 33 would be segmented as well.

**Comment by mozman** [comment]
I need the (zipped) DXF file.

**Comment by tkvw** [comment]
[drawing_spline.zip](https://github.com/mozman/ezdxf/files/11004526/drawing_spline.zip)
Sorry, I missed that

**Comment by mozman** [comment]
LibreCAD seems to create an open SPLINE and sets only the closed flag, this does not work:

Autodesk TrueView:

![image](https://user-images.githubusercontent.com/4230966/225991502-3b33983a-adf8-4c01-91c5-3d6104bc710b.png)

BricsCAD:

![image](https://user-images.githubusercontent.com/4230966/225991601-48c07d0a-a812-425f-9890-01b028cb5a45.png)

This is an issue of LibreCAD.

Please always check your DXF file with a reliable DXF viewer before posting an issue. The DXF output from LibreCAD and QCAD, while getting better and better, is still not good and far from trustworthy.

**Comment by tkvw** [comment]
Thanks for taking a look and your quick response! I'll post an issue with Librecad.
