### ISSUE TITLE
MTEXT entities not correct on ezdxf view

### ISSUE THREAD

**Issue by IvanKachaikinCendas** [mozman/ezdxf#855]
Hi @mozman! First of all, thanks once again for your amazing package that makes my life much easier :)

However, I'm facing a little error with one plan. More specifically, while openning the following file with `ezdxf view`, the content does not look the same as in AutoCAD.

**To Reproduce**
Information and data needed to reproduce the error:
1. A *simplified* Python script which triggers the error: `ezdxf view bad_xref.dxf`
2. Information about the *ezdxf* version and the OS: `ezdxf == 1.0.3`, Windows 11.
3. A DXF to reproduce:
[bad_xref.zip](https://github.com/mozman/ezdxf/files/11090282/bad_xref.zip)

**Expected behavior**
In ideal case, I would expect that it looks just as in AutoCAD :)

**Screenshots**
1. AutoCAD view:
![autocad-view-broken-xref](https://user-images.githubusercontent.com/94542840/228262777-4fd0db82-4c5f-42b8-b561-af097f4db46a.png)
2. `ezdxf view` view:
![ezdxf-view-broken-xref](https://user-images.githubusercontent.com/94542840/228262697-a21f981d-229c-42aa-97a5-b11ead92a99f.png)

P.S.: not sure if you are going to fix this issue right now or if it is in general fixable as it may be a bit weird and actually some strange AutoCAD behaviour. In any case thanks for checking it out and for any feedback 🙏

**Comment by mbway** [comment]
Is the issue here that layers are visible in ezdxf that are invisible by default in autocad?
As-in, if you toggle the layer visibility on the right of the ezdxf viewer are you able to get the view looking the same as autocad?

**Comment by mozman** [comment]
This issue is caused by using absolute inline sizing parameters in the MTEXT entity.

The MTEXT entity in the BLOCK definition has a absolute height definition of H150 and the BLOCK is scaled by a factor of 0.001. The absolute text size is not adjusted when creating the virtual entities from the BLOCK definition. This has to be done in the `MText.transform()` method:

- check if text scaling is required
- fast check if absolute text sizes are present to avoid the slow part in most cases
- slow part if adjustment is required:
    - parse the MTEXT content
    - adjust absolute text sizes:
        - H absolute text height
        - T absolute char spacing (tracking)
        - p absolute paragraph parameters: indentation and tab stops
    - recompile the MTEXT content

The inline resizing feature seems to be rarely used as this is the first reported issue for it and even BricsCAD has some issues:

viewing is correct:
![image](https://user-images.githubusercontent.com/4230966/228426024-60c97474-f7cb-47f4-9039-84b20586b627.png)

but doesn't apply the scaling when exploding the block reference:
![image](https://user-images.githubusercontent.com/4230966/228426168-0138196a-9beb-4138-af80-19c68b371965.png)

**Comment by IvanKachaikinCendas** [comment]
Hi @mozman! Thanks a lot for your feedback as well as for the commits with fixes :)

By the way, this issue was also caused by transform method I presume. Recreated the files a little bit, so they may look a bit different than before, but nevertheless the case that I tried:
- Took the plan [bad_xref_1.zip](https://github.com/mozman/ezdxf/files/11137820/bad_xref_1.zip), opened in AutoCAD and with `ezdxf view`, it looks the same:
\- AutoCAD view
![bad-xref-1-auto](https://user-images.githubusercontent.com/94542840/229499639-81f8c6c7-2398-4f76-a8c7-5f38251023db.png)
\- `ezdxf view` view
![bad-xref-1-ezdxf](https://user-images.githubusercontent.com/94542840/229499684-a5838894-909a-4c7a-b1f4-fa4122acc1ae.png)
- Run the following code
```python
import ezdxf
from ezdxf.math import Matrix44

drawing = ezdxf.readile('bad_xref_1.dxf')
msp = drawing.modelspace()
xref = msp[0]

first_shift = Matrix44.translate(100.0, 100.0, 0.0)
rescale = Matrix44.scale(100.0)
second_shift = Matrix44.translate(-200.0, -200.0, 0.0)
transformation_matrix = Matrix44.chain(first_shift, rescale, second_shift)
inversed_transformation_matrix = transformation_matrix.copy()
inversed_transformation_matrix.inverse()

xref.transform(inversed_transformation_matrix)
xref.move_to_layout(drawing.layouts.get('Empty'))
xref.move_to_layout(msp)

drawing.saveas('bad_xref_1_transformed.dxf')
```
- Took the resaved plan [bad_xref_1_transformed.zip](https://github.com/mozman/ezdxf/files/11137912/bad_xref_1_transformed.zip) and reopened it in AutoCAD and with `ezdxf view`, and now it starts look strange:
\- AutoCAD view:
![bad-xref-1-transformed-auto](https://user-images.githubusercontent.com/94542840/229501974-5f1ad9f7-fc28-4475-be18-de3c3843e3f9.png)
\- `ezdxf view` view:
![bad-xref-1-transformed-ezdxf](https://user-images.githubusercontent.com/94542840/229502051-8764a9de-3d1f-437e-b32f-76bdb1597795.png)

P.S.: not sure if there actually is something to fix in transform method, but thought that you may find it interesting :) Please let me know whether we may close this issue 😋

**Comment by mozman** [comment]
@IvanKachaikinCendas you have to update to the latest version on github, the file `bad_xref_1_transformed.dxf` looks like this with the `ezdxf view` command:

![image](https://user-images.githubusercontent.com/4230966/229549289-f4ecb6f7-c1fb-4b37-8707-dc4008e21ac7.png)

**Comment by IvanKachaikinCendas** [comment]
@mozman Correct, right now it looks correctly. Thanks once again for fixing it! :)
