### ISSUE TITLE
Embedded bitmaps not visible with ezdxf view

### ISSUE THREAD

**Issue by jsimomaa** [mozman/ezdxf#860]
**Describe the bug**
Embedded bitmaps not visible

**To Reproduce**

1.
```bash
ezdxf view imagetest.dxf
```

2.
```bash
$ pip show ezdxf
Name: ezdxf
Version: 1.0.3
Summary: A Python package to create/manipulate DXF drawings.
Home-page: https://ezdxf.mozman.at
Author: Manfred Moitzi
Author-email: me@mozman.at
License: MIT License
Location: /home/vscode/.local/lib/python3.11/site-packages
Requires: pyparsing, typing-extensions
Required-by: 
```
```bash
$ cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

3.
[imagetest.zip](https://github.com/mozman/ezdxf/files/11135661/imagetest.zip)

Trueview:
![image](https://user-images.githubusercontent.com/4503494/229436031-bd078fb4-d1c2-4f12-87e2-92f241ca86ba.png)

ezdxf view:
![image](https://user-images.githubusercontent.com/4503494/229436116-8a6c0cdf-5051-4c26-9195-7d21ec5d6747.png)

**Comment by mozman** [comment]
This is not supported!

**Comment by jsimomaa** [comment]
Thank you for a quick reply! I'm curious why this is not supported i.e. does it require too much work to implement or perhaps some other reason?

**Comment by mbway** [comment]
I don't think there is a fundamental reason why ezdxf couldn't support embedded images when rendering. It has just never been a priority to support them. Same with viewports.

I did consider implementing image support when I was working on the drawing addon but my use case didn't need it so I never got around to it.

**Comment by mozman** [comment]
@mbway Nobody will ever implement this feature. :smile:
