### ISSUE TITLE
A little issue (or misunderstanding) in PaperSpace.get_paper_limits()

### ISSUE THREAD

**Issue by IvanKachaikinCendas** [mozman/ezdxf#864]
First of all, as usual thanks a lot @mozman for your amazing package! Secondly, I am not really sure whether it is an issue, or rather a misunderstanding, so probably I just did not get something. Do not hesitate to move this issue into discussions if it is necessary.

For a plan that you may find below in Layout1, I would expect that the following paper limits (calculated via `get_paper_limits`) and the viewport borders (calculated using `viewport.dxf.center`, `viewport.dxf.width` and `viewport.dxf.height`) are the same.
![paper-limits-issue](https://user-images.githubusercontent.com/94542840/231718988-2559ed8c-d65c-412a-ad77-6701ffb8e111.png)

However they are not, in particular I get `(Vec2(0.0, 0.0), Vec2(12.0, 9.0))` for the layout and `(Vec2(13.642685733584813, 34.81094656765026), Vec2(233.1651213175536, 237.39818915856415))`.

This difference is maybe caused by the fact that `layout.units` is equal to `0` that if I am not mistaken corresponds to inches. So I would expect that using some layout attributes, it may be possible to convert the page limits that I get to something closer that I would like to get. However, I did not find anything useful while printing `layout.dxf_layout.dxfattribs()`, it seems like all the attributes just have their default value of `0` or `1`.

![layout-dxfattribs](https://user-images.githubusercontent.com/94542840/231722031-6db144c9-599e-4c69-96bd-d968e850aae9.png)

**To Reproduce**
Information and data needed to reproduce the error:
1. A *simplified* Python script which triggers the error
```python
import ezdxf

drawing = ezdxf.readile('sample_page_issue_final.dxf')
layout = drawing.layouts.get('Layout1')
paper_limits = layout.get_paper_limits()

viewport = layout.query('VIEWPORT[handle=="C52D"]').entities[0]
vp_xmin = viewport.dxf.center.x - viewport.dxf.width / 2
vp_ymin = viewport.dxf.center.y - viewport.dxf.height / 2
vp_xmax = viewport.dxf.center.x + viewport.dxf.width / 2
vp_ymax = viewport.dxf.center.y + viewport.dxf.height / 2
viewport_borders = (ezdxf.math.Vec2(vp_xmin , vp_ymin), ezdxf.math.Vec2(vp_xmax , vp_ymax))

print(paper_limits)
print(viewport_borders)
```
2. `ezdxf` git commit used: [link](https://github.com/mozman/ezdxf/commit/0ae04d54f44e2ddbdce6af18baa3c2f488bbffe2),  OS: Windows 11.
3. A DXF file:
[sample_page_issue_final.zip](https://github.com/mozman/ezdxf/files/11220772/sample_page_issue_final.zip)

**Comment by IvanKachaikinCendas** [comment]
Hi @mozman! Thanks a lot for your feedback!

So the following happens: in a .dxf file the paper limits are actually very small and much smaller than viewport size. Then, while opening this file in AutoCAD, it somehow understands that the paper size is too small, so it extends it and it starts looking fine. Did I get it correctly?

Moreover, in theory if someone creates a .dxf properly (not like this one, was exported from Revit and never resaved in AutoCAD), with a proper page size, then the method `get_paper_limits()` will return the limits in layout WCS, correct? :)

**Comment by mozman** [comment]
The method `get_paper_limits()` returns the stored limits, which corresponds to the tags with group code 10 and 11 in the DXF LAYOUT object.

![image](https://user-images.githubusercontent.com/4230966/232010518-ec296f61-c400-4a54-a248-5754949dca3a.png)

Which units? I guess these limits are in paperspace units.

**Comment by IvanKachaikinCendas** [comment]
@mozman Ok got it, thanks a lot for your help and guidance!
