### ISSUE TITLE
Att_Defs in ModelSpace are unreachable.

### ISSUE THREAD

**Issue by andresperezcera** [mozman/ezdxf#87]
I've got a DXF file with attribute definitions in modelspace. Those have been used to store data. Is there any way to retrieve this information? I've explored, but I see no way to add or even retrieve such information. I include a sample file with a txt extension. Would anyone suggest a path? Is this even a standards compliant practice?
[sample.txt](https://github.com/mozman/ezdxf/files/3225069/sample.txt)

**Comment by mozman** [comment]
query ATTDEF:
```
import ezdxf
doc = ezdxf.readfile('sample.dxf')
msp = doc.modelspace()
addefs = msp.query('ATTDEF')
print(len(attdefs)
```
There is no layout interface to create an ATTDEF in modelspace but you can use the low level interface:
```
msp.new_entity('ATTDEF', dxfattribs = {
    'tag': 'TAG',
    'text':  'UserText',
    'insert': (3, 3),
})
```

**Comment by andresperezcera** [comment]
Thanks! It totally makes sense! Amazing work on this library, it is saving me a good 2 months time of work. I'll keep an eye to contribute in any way possible.
