### ISSUE TITLE
Help converting from UTF-8 to CP932

### ISSUE THREAD

**Issue by SuperJugy** [mozman/ezdxf#88]
Hi,

I'm trying to write a converter. A friend of mine has AutoCad and a client of his uses VectorWorks 2012. Vector works is exporting DXF files as ANSI_932. AutoCAD was having trouble reading this because it was expecting UTF-8. Also, when my friend creates a DXF from AutoCAD, it creates it as UTF-8 and Vector works also displays gibberish because it was expecting ANSI_932.

I tried the following script to see if it would work. According to the code [comment](https://github.com/mozman/ezdxf/blob/master/ezdxf/drawing.py#L425), in ANSI mode, the UTF-8 characters would be escaped, but that doesn't seem to be happening. I can see that the $DWGCODEPAGE was set to ANSI_932. and also the file itself might be encoded as ANSI_932. but when I try to open it in DWG TrueView 2020 there is nothing there. I don't have AutoCAD to test it, but the original DXF file opens correctly.

```
import ezdxf

dwg = ezdxf.readfile("C:\Test-UTF8.dxf")
dwg.saveas("C:\Test-ANSI932.dxf", "932")
```

I also thought that maybe I need to manually loop the strings and convert them, but the API seems to only allow to query entities, not tags. I would have looped all String tags and try reencoding them before saving.

Am I doing something wrong?

Thanks in advance for your help.

**Comment by mozman** [comment]
For DXF R2007 and later UTF-8 encoding is mandatory, if you (or any CAD application) write DXF R2007+  with another encoding than UTF-8, you produce invalid DXF files.

ezdxf always expects and reads UTF-8 for R2007+ files, you can try to pass a stream with another encoding to `ezdxf.read()` function, but this is untested, because - as I said - you are working with an invalid DXF files.

```
import ezdxf

open('your.dxf', mode='rt, encoding='cp932', errors='ignore) as fp:
    doc = ezdxf.read(fp)
    if doc.dxfversion >= 'AC1021':
        # save file as utf-8
        doc.encoding = 'utf-8'  
```

**Comment by mozman** [comment]
Another simple idea is to convert the DXF files as simple text files:

```
with open('new.dxf', mode='wt', encoding='utf-8') as out_file:
    with open('your.dxf', mode='rt', encoding='cp932') as in_file:
        out_file.writelines(in_file.readlines())
```

**Comment by SuperJugy** [comment]
Hi, thanks for your reply. I didn't check the version. I will have a look. But after analyzing the file, it actually did it correctly. The problem is that apparently autocad is returning a mix of utf8 and cp932 strings. Which means that the strings that already were cp932 are being reencoded into garbage thinking it was utf8.

Is there a good way to check if a byte array is encoding cp932 or utf8?

In any case, I don't think it is a problem with your library, so I will close the issue.
