### ISSUE TITLE
Color of arrow not changing with line color

### ISSUE THREAD

**Issue by maxm199** [mozman/ezdxf#898]
I tried to change the color of the dimensions because I had to insert so many of them that the whole drawing was becoming difficult to read.
I achieved the result to color the dimension text, line and extension line but the arrow always get the 0 color.
In the docs the setting that should make the color change is: dimclrd | dimension line and arrows color
But that parameter just change the line color, not the arrows.
Tried with different programs, different arrow styles in ezdxf, different colors, white and black background... but the issue is still there.

To reproduce the error:

```Python
import ezdxf

new_doc = ezdxf.new("R2010", setup=True)
new_msp = new_doc.modelspace()
style_override = {"dimtxt": 5, "dimtad": 1, "dimtsz": 0, "dimclrt": 1, "dimclrd": 1, "dimclre": 1, "dimasz": 5, "dimblk": ezdxf.ARROWS.closed_filled}
new_msp.add_linear_dim(base=(0, 10), p1=(0, 0), p2=(100, 0), override=style_override).render()
new_doc.saveas("test_dimension_color.dxf")

```

ezdxf 1.0.3
OS windows 11

Expected behavior: arrows are rendered the same color as the dimension line

Screenshots
![image](https://github.com/mozman/ezdxf/assets/1713099/95d4f72d-fae9-4417-91ad-1a9c11029104)

**Comment by maxm199** [comment]
Thank you @mozman !

**Comment by topcloud-xx** [comment]
me too
