### ISSUE TITLE
Corrupt Font Causes Appl to Crash (fonttools then ezdxf)

### ISSUE THREAD

**Issue by jdegenstein** [mozman/ezdxf#902]
**Describe the bug**
User reported that my application kept crashing on launch on their system. Further investigation showed that fonttools is crashing when trying to load a corrupted font, which in turn causes ezdxf to crash, and all upstream packages. 

**To Reproduce**
Information and data needed to reproduce the error:
1. Release of https://github.com/jdegenstein/jmwright-CQ-Editor/releases/tag/0.30-dev on Windows
2. ezdxf-1.1.0b3
3. install corrupt font linked here: https://github.com/jdegenstein/jmwright-CQ-Editor/issues/11 (see this issue for further info)

**Comment by mozman** [comment]
Thank you for testing the beta versions!
