### ISSUE TITLE
[ODA File Converter] Exec format error even though set a+x

### ISSUE THREAD

**Issue by JadeKim042386** [mozman/ezdxf#903]
**Describe the bug**
- system is DARWIN
- i tried ODA convert
    ```python
    def oda_convert(src: str, dst: str, version:str):
        from ezdxf.addons.odafc import convert
        convert(src, dst, replace=True, version=VERSION_MAP["ACAD" + version])
    ```

**To Reproduce**
1. set ODA path (in ezdxf.options._config)
2. `chmod a+x [ODA AppImage path]`
3. ODA convert Run 

**Screenshots**
<img width="960" alt="image" src="https://github.com/mozman/ezdxf/assets/61103343/449422cb-aac0-49c2-a0d7-d66dd515de20">

**Comment by mbway** [comment]
you are on MacOS but AppImage is a Linux executable format. ODAFileConverter is available for MacOS but you need to download the correct executable for your platform: https://www.opendesign.com/guestfiles/oda_file_converter

**Comment by JadeKim042386** [comment]
@mbway Thanks!! I misread the [document](https://ezdxf.readthedocs.io/en/stable/addons/odafc.html)...
I installed ODAFileConverter and it works!
`path = Applications/ODAFileConverter.app/Contents/MacOS/ODAFileConverter`

And I have one more problem...
I also worked it in Docket's Linux environment, but I get an error called 'XDG_RUNTIME_DIR'.

`QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'`
