### ISSUE TITLE
flask web development

### ISSUE THREAD

**Issue by liujiayu6388** [mozman/ezdxf#91]
Register post load tag processor for DXF type: VERTEX; legacy: False
Register post load tag processor for DXF type: LWPOLYLINE; legacy: False
Register post load tag processor for DXF type: MESH; legacy: False
Register post load tag processor for DXF type: SPLINE; legacy: False
Register post load tag processor for DXF type: IDBUFFER; legacy: False
Register post load tag processor for DXF type: FIELDLIST; legacy: False
Register post load tag processor for DXF type: LAYER_FILTER; legacy: False
Register post load tag processor for DXF type: ACDBDICTIONARYWDFLT; legacy: False
Register post load tag processor for DXF type: DICTIONARY; legacy: False
Unsupported header variable: $DIMTXSTY_HANDLE.
Unsupported header variable: $DIMBLK_HANDLE.
Use ezdxf in flask and unable to seveas DXF file

**Comment by mozman** [comment]
?

**Comment by liujiayu6388** [comment]
sorry,the problem was solved.
