### ISSUE TITLE
Default font "Arial.ttf" not found on macOS

### ISSUE THREAD

**Issue by mozman** [mozman/ezdxf#917]
I got a feedback by email, that `ezdxf` v1.1 do not find the default font "Arial.ttf" on macOS and raises and uncaught exception.

Can someone confirm this behavior because I don't have access to macOS.

**Comment by mbway** [comment]
I find [OSX-KVM](https://github.com/kholia/OSX-KVM) (or similarly [Docker-OSX](https://github.com/sickcodes/Docker-OSX) which I haven't used) useful for testing things on MacOS without having an actual Mac. You would need to run Linux first to be able to use it though.
by `v1.1` do you mean the master branch because 1.1 isn't released yet is it?

I downloaded the example dxf from https://github.com/mozman/ezdxf/issues/749 and tested with the latest release (1.0.3) and the master branch. No crash on the latest release but with master:

```
loading file "/Users/matt/Downloads/buggy_mtext.dxf"...
Traceback (most recent call last):
  File "/Users/matt/ezdxf/src/ezdxf/fonts/font_manager.py", line 92, in get
    return self._cache[self.key(font_name)]
KeyError: 'arial.ttf'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/matt/venv/bin/ezdxf", line 8, in <module>
    sys.exit(main())
  File "/Users/matt/ezdxf/src/ezdxf/__main__.py", line 114, in main
    run(args)
  File "/Users/matt/ezdxf/src/ezdxf/commands.py", line 368, in run
    ctx = RenderContext(doc)
  File "/Users/matt/ezdxf/src/ezdxf/addons/drawing/properties.py", line 351, in __init__
    self._setup_text_styles(doc)
  File "/Users/matt/ezdxf/src/ezdxf/addons/drawing/properties.py", line 420, in _setup_text_styles
    self.add_text_style(cast("Textstyle", text_style))
  File "/Users/matt/ezdxf/src/ezdxf/addons/drawing/properties.py", line 511, in add_text_style
    font_face = fonts.resolve_font_face(font_file, order=self.shx_resolve_order)
  File "/Users/matt/ezdxf/src/ezdxf/fonts/fonts.py", line 210, in resolve_font_face
    return find_font_face(font_name)
  File "/Users/matt/ezdxf/src/ezdxf/fonts/fonts.py", line 133, in find_font_face
    return font_manager.get_font_face(font_name)
  File "/Users/matt/ezdxf/src/ezdxf/fonts/font_manager.py", line 354, in get_font_face
    cache_entry = self._font_cache.get(font_name, self.fallback_font_name())
  File "/Users/matt/ezdxf/src/ezdxf/fonts/font_manager.py", line 94, in get
    return self._cache[self.key(fallback)]
KeyError: 'arial.ttf'
```

**Comment by mozman** [comment]
@mbway yes, by v1.1 I mean the top of the master branch

The email sender mentioned than only  "Arial Unicode" exists on macOS. So I added  "arialuni.ttf" as default font for Windows and macOS, maybe your can rerun your test. The unicode font as default font would be the better choice anyway.

The current implementation requires an existing TTF font as default font.

**Comment by mbway** [comment]
that file is not found either. I see that for Big Sur at least:
```
$ ls /Library/Fonts
Arial Unicode.ttf
```
(so that is the only ttf font on a fresh install)

**Comment by mozman** [comment]
It took me  more than 2 hours to setup and install macOS (via kvm) on my notebook (Ryzen 7 from 2020). 
It's slow but it works. I tested the latest commit with PyQt5 and "Arial Unicode.ttf" was found.

Now I have to figure out how to change the font size in the terminal, I can barely read anything :).

**Comment by mbway** [comment]
yeah I find the UI is really slow for some reason but running compute tasks only added around 30% compared to directly on the host in my experience.
If you want to use it long term there are some tweaks that improve things a bit https://github.com/sickcodes/osx-optimizer
the experience using it headless through terminal/ssh is the best IMO

**Comment by mozman** [comment]
@mbway Thank you for your useful tips.

I tried installing it in a "VirtualBox" on my CAD workstation on Windows because it's more powerful than my notebook, but despite the many YouTube videos on the subject, the only success was an endless boot loop. 😄 

The setup via KVM on my Linux notebook works well enough for its purposes.
