### ISSUE TITLE
Convert text to polyline

### ISSUE THREAD

**Issue by tfeldmann** [mozman/ezdxf#92]
Hello and thank you very much for this library!
Is it possible to convert text to polyline entities?
I have a application which creates DXFs for a laser cutter and would like to engrave some text. But the conversion software only handles circles and lines.

**Comment by mozman** [comment]
No, ezdxf can't do this.

**Comment by bobblkabb** [comment]
Not sure if it's okay if I attach to a closed issue but the 'explode' feature introduced in v0.12...does it convert text to polylines?
Asking because the qcad feature which does that is also called 'explode'..

**Comment by mozman** [comment]
This is a high level CAD feature and will never be possible with ezdxf, ezdxf has no access to font features and also has no rendering engine for font rendering.

**Comment by bobblkabb** [comment]
I see. Thanks for the quick response.
And thanks a lot for this package. Great work, it's very useful!
