### ISSUE TITLE
Ezdxf can't load fonts when using pytest

### ISSUE THREAD

**Issue by JohannesVerherstraeten** [mozman/ezdxf#921]
Hi mozman, thanks for maintaining this great library. 

I was experimenting with the export to SVG tutorial, and noticed it doesn't work when I just add `import pytest` on top of it. 

The minimal example to reproduce would be: 
```python
import pytest     # adding this line causes the exception
import ezdxf
from ezdxf.addons.drawing import RenderContext


doc = ezdxf.new()
context = RenderContext(doc)
```
This results in: 
```
Traceback (most recent call last):
  File "/home/johannes/miniconda3/envs/ezdxf_experiment/lib/python3.10/site-packages/ezdxf/fonts/font_manager.py", line 94, in get
    return self._cache[self.key(font_name)]
KeyError: 'txt.shx'
... 
<some extra error handling stacktraces>
```

**The cause** seems to be the first 2 lines in the `_load_font_manager` function in [fonts.py](https://github.com/mozman/ezdxf/blob/master/src/ezdxf/fonts/fonts.py#L278): 
```python
def _load_font_manager() -> None:
    if "pytest" in sys.modules:
        return  # do nothing: system under test (sut)

    fm_path = _get_font_manager_path()
    if fm_path.exists():
        try:
            font_manager.loads(fm_path.read_text())
            return
        except IOError as e:
            logger.info(f"Error loading cache file: {str(e)}")
    build_font_manager_cache(fm_path)
```
Version: master branch at the latest commit [675974c0874b9a9abbb7cabee7592c17e248c1d8](https://github.com/mozman/ezdxf/tree/675974c0874b9a9abbb7cabee7592c17e248c1d8) -> (I am fully aware this is brand new code and not a stable release) 

This complicates using the export functionality during testing. I can of course workaround by redefining this function and leaving out the pytest related lines, so it's not a big problem.

**Comment by mozman** [comment]
To run tests for `ezdxf` on all operating systems and as github action I had to guarantee that some fonts are avialable, therefor I decided to create a special font cache for the system under test (sut), see `/tests/conftest.py`. The fonts are included in the repository in the folder `/fonts` This works as expected for testing `ezdxf` but may cause problems for users of the package.

You may also add a `conftest.py` to yout tests:

```Python
import pytest

from ezdxf.fonts import fonts
from pathlib import Path


@pytest.fixture(scope="session", autouse=True)
def load_sut_font_cache():
    path = Path(__file__)
    font_folder = path.parent.parent / "fonts"
    if font_folder.exists():
        fonts.build_sut_font_manager_cache(font_folder)
    else:
        exit(666)
```

The `font_folder` should point to a folder which contains at least one default font, e.g. `C:\Windows\Fonts`:

```
DEFAULT_FONTS = [
    "ArialUni.ttf",  # for Windows
    "Arial Unicode.ttf",  # for macOS
    "Arial.ttf",  # for the case  "Arial Unicode" does not exist
    "DejaVuSansCondensed.ttf",  # widths of glyphs is similar to Arial
    "DejaVuSans.ttf",
    "LiberationSans-Regular.ttf",
    "OpenSans-Regular.ttf",
]
```

**Comment by mozman** [comment]
I added a special exception for this case: `ezdxf.SystemUnderTest("see issue: https://github.com/mozman/ezdxf/issues/921")`

**Comment by mozman** [comment]
This solution setup the SUT font cache in `conftest.py` and is only triggered when the `ezdxf` test suite is executed.

**Comment by JohannesVerherstraeten** [comment]
That's perfect! Many thanks.
