### ISSUE TITLE
Building font manager cache fails with FileExistsError in Windows

### ISSUE THREAD

**Issue by jsimomaa** [mozman/ezdxf#923]
**Describe the bug**
Building font manager cache fails with `FileExistsError` if user already has a **file** named `.cache` in home:

```python
def build_font_manager_cache(path: pathlib.Path) -> None:
    font_manager.clear()
    font_manager.build()
    s = font_manager.dumps()
    if not path.parent.exists():
        path.parent.mkdir(parents=True)
```

causes:
```
  File "ezdxf\fonts\fonts.py", line 718, in <module>
  File "ezdxf\fonts\fonts.py", line 288, in _load_font_manager
  File "ezdxf\fonts\fonts.py", line 320, in build_font_manager_cache
  File "pathlib.py", line 1121, in mkdir
  File "pathlib.py", line 1116, in mkdir
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'C:\\Users\\A1\\.cache\\ezdxf'
```

**To Reproduce**
Create a file named `.cache` in users home dir

**Expected behavior**
Cache would be created

---

Should the naming of the cache be more application specific like `C:\Users\A1\.ezdxfcache` to avoid clashes?

**Comment by jsimomaa** [comment]
Also while at it shouldn't the cache directory creation be atomic with just:
```python
def build_font_manager_cache(path: pathlib.Path) -> None:
    font_manager.clear()
    font_manager.build()
    s = font_manager.dumps()
    path.parent.mkdir(parents=True, exist_ok=True)
```

**Comment by mozman** [comment]
The cache location and naming follows the freedesktop.org standard `$XDG_CACHE_HOME`: https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

**Comment by mozman** [comment]
To be clear: the directory entry  `C:\Users\A1\.cache` is a file not a directory?

**Comment by jsimomaa** [comment]
> To be clear: the directory entry `C:\Users\A1\.cache` is a file not a directory?
> 
> If so, what application created the file `.cache`?

Yes, it is a file indeed but unfortunately I have no Idea what application initially have created it. The file is empty.

I was unaware of the `$XDG_CACHE_HOME` so thank you for that!

**Comment by jsimomaa** [comment]
Reading through the basedir spec I'm not sure how well (or if not at all) Windows complies with the XDG standards..

**Comment by jsimomaa** [comment]
Exploring a bit I found this library that at least tries to workaround these platform specific issues: https://github.com/platformdirs/platformdirs

**Comment by mozman** [comment]
An additional dependency is not needed for that, just delete the `.cache` file, run `ezdxf` and the problem is solved.

**Comment by mozman** [comment]
As an example that other application do use the `.cache` directory on Windows as well, here is the content of mine:

![image](https://github.com/mozman/ezdxf/assets/4230966/0f66cae2-651a-43d4-8eae-0cc0364dde56)

**Comment by jsimomaa** [comment]
Yes, thank you. I will close the issue
