### ISSUE TITLE
Line break not working

### ISSUE THREAD

**Issue by MatheusZickuhr** [mozman/ezdxf#93]
If I use "\n" the generated DXF file does not open and "\\\P" does nothing. There is another way to break lines?

The ezdxf version I'm using is 0.8.9 (works best for me)

**Comment by mozman** [comment]
Try "\\P;" as line break, "\n" works in ezdxf 0.10 as line break and line breaks work only in MTEXT not in TEXT.

**Comment by MatheusZickuhr** [comment]
> Try "\P;" as line break, "\n" works in ezdxf 0.10 as line break and line breaks work only in MTEXT not in TEXT.

"\P" is working now. The problem is that I was using text, not mtext. Thank you for your help.
