### ISSUE TITLE
import of ezdxf failed in Windows x64, python 3.8

### ISSUE THREAD

**Issue by ndl303** [mozman/ezdxf#934]
**Describe the bug**
First, many thanks for the package. `ezdxf` does not import in my python 3.8  distribution which was installed by Anaconda.  This seems to be related to the `Self` variable in `typing_extensions`, this failure seems to be consistent with expected `typing_extensions` behaviour of  self, see issue [2034](https://github.com/microsoft/pylance-release/issues/2034) .  The `ezdxf `package worked properly (for me) in a python 3.11 Anaconda environment.

**To Reproduce**
```
C:> python
Python 3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import ezdxf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\nickl\anaconda3\envs\altius\lib\site-packages\ezdxf\__init__.py", line 17, in <module>
    from ezdxf.colors import (
  File "C:\Users\nickl\anaconda3\envs\altius\lib\site-packages\ezdxf\colors.py", line 5, in <module>
    from typing_extensions import Self
ImportError: cannot import name 'Self' from 'typing_extensions' (C:\Users\nickl\anaconda3\envs\altius\lib\site-packages\typing_extensions.py)
>>>
```

Information and data needed to reproduce the error:

- Windows 10, x64
- `conda create -n test38 python=3.8 Anaconda`
-  `conda activate test38`
- `pip install ezdxf `
- `python`
- `>>> import ezdxf`

FYI: package versions using `conda list`

```
ezdxf                     1.1.0                    pypi_0    pypi
typing_extensions         3.7.4.3                    py_0

```

**Confidential Data**
If you have sensitive files that you can't disclose, try to remove everything 
sensitive from an existing file or create a brand new one which still triggers 
the error. Alternatively, you can send the zipped files to confidential@mozman.at, 
this data is only saved locally (no cloud upload of any kind) and the files are 
deleted after the error has been fixed.

**Expected behavior**
drop support for python 3.8 and possibly 3.9, 3.10. Or fix ` from typing_extensions import Self `

**Screenshots**

**Comment by mbway** [comment]
`Self` was added to `typing_extensions` in version 4.0.0: [docs](https://typing-extensions.readthedocs.io/en/latest/index.html#Self)
So I suppose the setup.py needs to specify `typing_extensions>=4.0.0` instead of just `typing_extensions`

to fix your problem immediately you can try doing `pip install typing_extensions>=4.0.0`

**Comment by mozman** [comment]
`pip install typing_extensions>=4.6.0` is required for `TypeAlias`
