### ISSUE TITLE
Drawing problem on Chinese text

### ISSUE THREAD

**Issue by yoriyouriri** [mozman/ezdxf#936]
[B2_1010.zip](https://github.com/mozman/ezdxf/files/12864250/B2_1010.zip)
```
dxf_doc = ezdxf.readfile(filepath)
msp = dxf_doc.modelspace()
fig = plt.figure()
ax = fig.add_axes([0, 0, 1, 1])
ctx = RenderContext(dxf_doc, ctb="A-PRINTER.ctb", export_mode=True)
out = MatplotlibBackend(ax)
try:
    try:
        Frontend(ctx, out).draw_layout(msp, finalize=True, filter_func=FilterFunc)
    except ValueError:
        # msp.block_record.extension_dict["ACAD_SORTENTS"] = []
        msp.block_record.extension_dict = None
        Frontend(ctx, out).draw_layout(msp, finalize=True, filter_func=FilterFunc)
except Exception as e:
    logger.error("error", e)
```

![image](https://github.com/mozman/ezdxf/assets/56081362/ab153d64-39b8-4308-a1b8-41c0f0a4763b)
![image](https://github.com/mozman/ezdxf/assets/56081362/2e547c51-7094-442f-94fc-f90d26125d80)

The drawing didn't represent correctly while processing chinese text.

**Comment by mozman** [comment]
Mixed languages in fonts without support for both languages is not supported by `ezdxf`. This is a feature of "big" CAD applications that can switch fonts implicit when rendering text if necessary. `Ezdxf` can only render such text in MTEXT entities when an explicit font switch happens in side the text: `{\fSimSun;你好}Text with default font`

**Comment by mozman** [comment]
I inspected your DXF file and there is a solution for this special case.

All MTEXT entities use the default text style `Standard` which is set to "arial.ttf" and does not support Chinese glyphs.
Changing the font to "arialuni.ttf" solves the issue:
```Python
import ezdxf

doc = ezdxf.readfile("B2_1010.dxf")
default_style = doc.styles.get("Standard")
default_style.dxf.font = "arialuni.ttf"
default_style.set_extended_font_data("arialuni.ttf")
doc.saveas("B2_1010_arialuni.dxf")

```
![image](https://github.com/mozman/ezdxf/assets/4230966/df9eadb4-09d6-4ced-bac4-e036f672467f)

**Comment by yoriyouriri** [comment]
thank u for your reply, i've tried the solution you mentioned above, however, i found some information in the new file  `B2_1010_arialuni.dxf` have been changed, for example:
```
        x_min = dxf_doc.header['$EXTMIN'][0] 
        y_min = dxf_doc.header['$EXTMIN'][1]
        x_max = dxf_doc.header['$EXTMAX'][0]
        y_max = dxf_doc.header['$EXTMAX'][1]
```
now these values are zero ,and i don't know why

**Comment by mozman** [comment]
These are the undocumented quirks of the DXF format. `Ezdxf` copies the `msp.dxf.extmin` and `msp.dxf.extmax` attributes from the LAYOUT entity of the modelspace to the header variables `$EXTMIN`  and `$EXTMAX`, but AutoCAD or whatever CAD application created this DXF file does not maintain these values and so they are 0.

You can add these code to the converter routine to preserve the modelspace extents:
```Python
msp = doc.modelspace()
msp.dxf.extmin = doc.header["$EXTMIN"]
msp.dxf.extmax = doc.header["$EXTMAX"]
```

BTW: You cannot rely on the stored extents and limits, these are often not well maintained and `ezdxf` does not maintain these values either.

**Comment by mozman** [comment]
You can detect the bounding box of the modelspace by `ezdxf` and it's not that slow as i expected:

```Python
from ezdxf import bbox

doc = ezdxf.readfile("B2_1010.dxf")
msp = doc.modelspace()
extents = bbox.extents(msp, fast=True)
msp.dxf.extmin = extents.extmin
msp.dxf.extmax = extents.extmax
```
The difference is not that significant, rounded to 3 decimal places:
store values: (3467.639, 8421.042, -3243.304) (329984.307, 323317.556, 200.0)
detected by ezdxf: (3467.639, 8421.042, -3243.304), (330830.284, 323317.556, 200.0)

**Comment by mozman** [comment]
I updated the metadata update procedure when writing DXF files: ignores the layout extents of the modelspace if both values are (0, 0, 0).

**Comment by yoriyouriri** [comment]
> You can detect the bounding box of the modelspace by `ezdxf` and it's not that slow as i expected:
> 
> ```python
> from ezdxf import bbox
> 
> doc = ezdxf.readfile("B2_1010.dxf")
> msp = doc.modelspace()
> extents = bbox.extents(msp, fast=True)
> msp.dxf.extmin = extents.extmin
> msp.dxf.extmax = extents.extmax
> ```
> 
> The difference is not that significant, rounded to 3 decimal places: stored values: (3467.639, 8421.042, -3243.304) (329984.307, 323317.556, 200.0) detected by ezdxf: (3467.639, 8421.042, -3243.304), (330830.284, 323317.556, 200.0)

thank u for explaining the extents problem patiently, i've tried this solution and it works. however,  after changing the font to "arialuni.ttf", i still cannot draw DXF correctly with MatplotlibBackend, Is there anything I misunderstood？
i also try this        
```
ctx = RenderContext(dxf_doc, ctb="A-PRINTER.ctb", export_mode=True)
out = MatplotlibBackend(ax, font=font_manager.FontProperties(fname='arialuni.ttf'))
```
the output png does not look better
![image](https://github.com/mozman/ezdxf/assets/56081362/3493e1b1-1fe8-48b5-8c20-a9600827445f)

**Comment by yoriyouriri** [comment]
i‘ve read this issue: Drawing problem on ARRAYCLASSIC presentation #380 , is my issue similar to this? 
is there something i can do to output a png containing Chinese like this issue?

**Comment by mozman** [comment]
I created a simplified DXF for this issue:
[MixedLanguages.zip](https://github.com/mozman/ezdxf/files/12866826/MixedLanguages.zip)

Displayed by PyQt: `ezdxf view MixedLanguages.dxf`

![image](https://github.com/mozman/ezdxf/assets/4230966/1fa242eb-25aa-4ee3-b513-426cdba62d5a)

Displayed by Matplotlib: `ezdxf draw MixedLanguages.dxf`

![image](https://github.com/mozman/ezdxf/assets/4230966/cd047a03-eb13-416c-a0c5-a06b04c16772)

**Comment by mozman** [comment]
If you are working on Linux make sure the font "arialuni.ttf" is installed or use a different font with unicode support as replacement font for "arial.ttf". And I also forgot that the font on macOS is called "Arial Unicode.ttf".

**Comment by mozman** [comment]
For Linux users: the font "ARIALUNI.TFF" can be downloaded here:

https://github.com/kaienfr/Font/tree/master/font

I am not sure if this is legal but the `ms-corefonts` which are available for most distributions do not include the "arialuni.ttf" font.

**Comment by yoriyouriri** [comment]
i'm so appreciated for your detailed answer,  i update ezdxf to v1.1.0 and now it works! 
i have one more question, i found the `ezdxf pillow` commond is removed in new version, and i find a similar command `ezdxf draw`, but i don't know how to control the output's height and width if i want to putput a png

**Comment by mozman** [comment]
There is no quick command for that, you have to write a script like the one you started with.

Documentation of the `drawing` add-on: https://ezdxf.mozman.at/docs/addons/drawing.html
FAQ section for the old backends before v1.1: #550
Tutorial for image export by the new backends introduced with v1.1: https://ezdxf.mozman.at/docs/tutorials/image_export.html

**Comment by yoriyouriri** [comment]
ok,i see. Thank you again!

**Comment by yoriyouriri** [comment]
> For Linux users: the font Arial Unicode MS "arialuni.ttf" can be downloaded here:
> 
> https://www.fonts100.com/font+5091_Arial+Unicode+MS.html
> 
> I am not sure if this is legal but the `ms-corefonts` which are available for most distributions do not include the "arialuni.ttf" font.

sorry to bother you again,  i've tried to draw this dxf file with same python script on linux, but it didn't work.  i'm not sure if i installed arialuni.ttf successfully

**Comment by mozman** [comment]
rebuild the font cache: https://ezdxf.mozman.at/docs/tools/fonts.html#rebuilding-the-font-cache

**Comment by yoriyouriri** [comment]
problem solved, thank u!
