### ISSUE TITLE
There's some issues at drawing hatch.

### ISSUE THREAD

**Issue by hudate** [mozman/ezdxf#938]
```python
import ezdxf
from ezdxf.addons.drawing import matplotlib

dxf_file = 'hatch_test2.dxf'
pdf_file = 'hatch_test2.pdf'

dxf_doc = ezdxf.readfile(dxf_file)

doc_msp = dxf_doc.modelspace()

matplotlib.qsave(doc_msp, pdf_file)
```

the png is(the wrong marked with red arrow):
![屏幕截图 2023-10-11 223039](https://github.com/mozman/ezdxf/assets/50773998/b7f25b77-cd31-4b53-8b4f-b8b9280772b2)

the dxf file on ACAD:
![image](https://github.com/mozman/ezdxf/assets/50773998/79fe08e1-d5e0-4bc4-8326-661389812301)

**Comment by mozman** [comment]
I found a solution  (CHEAT).

The problem are the intersections of the pattern lines exact in bounding border points, a circle is represented by 4 Bèzier curves.

![no_jiggling](https://github.com/mozman/ezdxf/assets/4230966/36908222-3545-4770-9221-a622d7bec4be)

To avoid this intersections i move the origin of the pattern by a very small random amount, ~1000th of the pattern line distance:

![jiggling](https://github.com/mozman/ezdxf/assets/4230966/1eb7e477-2eff-4052-9589-dec641e5196f)

This feature is activated by default for the `drawing` add-on, but could be an config option.

**Comment by hudate** [comment]
Bingo, thanks!
