### ISSUE TITLE
hatch scale not recognized by AutoCAD

### ISSUE THREAD

**Issue by jrmagers** [mozman/ezdxf#94]
When setting a hatch pattern 'ANSI31' and custom scale in ezdxf, the scale is not recognized when open with AutoCAD 2018.  This problem is described in the Autodesk forums:

[https://forums.autodesk.com/t5/autocad-forum/hatch-patterns-displayed-incorrectly-when-importing-from-dxf/td-p/8379007](url)

Apparently this has something to do with "the difference of the ACAD.PAT (or ACADISO.PAT) that was used when creating the hatch contrary to the PAT file that was used when the hatch gets modified..."

**Comment by mozman** [comment]
What solution do you expect?

**Comment by mozman** [comment]
Found at least a bug in `Hatch.set_pattern_fill()`: method did not set pattern `scale`, `angle` and `double` values.

I don't know if this solves your problem, because your problem seem to be a CAD application problem, ezdxf can't produce hatch pattern for every existing CAD application when applications have different default pattern definitions. Including predefined pattern is a service provided by myself, not a DXF feature, the DXF reference do not define any hatch pattern.

**Comment by jrmagers** [comment]
I suspect it won't solve the issue because after I open the file in AutoCAD that was edited in ezdxf (where I set the hatch patten and scale), the scale and pattern appear to be set correctly (at least if I examine the properties of the hatch pattern in AutoCAD). But, the displayed hatch scale remains at 1.0. However, if I nudge the scale in AutoCAD, it then updates the display properly.

I suppose this could be an AutoCAD bug, not an ezdxf bug.

**Comment by mozman** [comment]
Leave to issue open, because I want to take a closer look at this problem when I have more time for coding (in the winter).

**Comment by mozman** [comment]
The predefined pattern used in ezdxf have a scale factor 1/25.4 in comparison to the pattern created in BricsCAD 2020 or BricsCAD pattern are 25.4 times larger scaled.

I will change the scaling of the predefined pattern according to the BricsCAD pattern, which are likely the same as AutoCAD uses. 

But I will also add an option to use the old predefined pattern if necessary.

**Comment by mozman** [comment]
Found the general reason for the scaling problem, the pattern is not stored as scaled by factor 1 and  then scaled by the stored scaling factor by the CAD application, the pattern itself has to be stored already scaled by the scaling factor, the stored factor is just the information for the CAD application how much the pattern is already scaled for the case the CAD application has to rescale the pattern.

In the next release v0.11 the pattern scaling should work as expected.
