### ISSUE TITLE
bulge_to_arc start and end angles have sign issues

### ISSUE THREAD

**Issue by sbmarcom** [mozman/ezdxf#943]
**Describe the bug**
When reading in a dxf file and trying to convert the bulge lines in a lwpolyline, sometimes the start or end angles are off by 360 degrees, so 180 would be -180 degrees, or 90 would come out as -270. This causes my code to plot the arc in the other direction. 

**To Reproduce**
Information and data needed to reproduce the error:
1. A *simplified* Python script which triggers the error.
I've attached a zipped folder with a python script, with a dxf to test with, as well as matplot lib images with the default output, and the correct output, which is created when I manually change the start angle for the second arc from -180 to +180. In addition, to make the correct plot, I have to swap the start and end angles. 

3. Information about the *ezdxf* version and the OS.
 This happens on my Mac machine as well as a linux computer running Debian. I am using ezdxf v1.1.1

4. If a 3rd party DXF file causes the error, add a *simplified* and *zipped* 
   DXF file which still triggers the error.

I have added this file

**Expected behavior**
I expect the start and end angles to be the angles from the center point to the start/end points.

**Screenshots**
[bug_report.zip](https://github.com/mozman/ezdxf/files/13065868/bug_report.zip)

**Comment by sbmarcom** [comment]
If needed, I can share more of my code as well, however, it is a fairly big project and I think this is all that is needed to show the issue.

**Comment by mozman** [comment]
This is not a bug in `ezdxf` is't a bug in your rendering algorithm, just normalize the angles for your needs!

`ezdxf` renders the polyline correct:

![image](https://github.com/mozman/ezdxf/assets/4230966/12ff9b2d-9997-44a4-b013-fa478029537b)

**Comment by sbmarcom** [comment]
Interesting, I guess I have a question to check my understanding then. The start angle is the angle from the center point to the start point with the x axis as the 0 degree reference,  and same for the end angle. In the case of the second arc, I don't understand why -180 is the correct start angle. 

When you say normalize the angles, what does that mean?
