### ISSUE TITLE
Invalid DXF attribute "center" for entity LWPOLYLINE

### ISSUE THREAD

**Issue by bandtank** [mozman/ezdxf#944]
**Describe the bug**
Two files were created using AutoCAD LT 2019. When using [Easy DXF Viewer](https://github.com/georgeh1ll/Easy-DXF-Viewer/issues/3) to view the attached file `perimeter.dxf`, I encountered the following error during the rendering of a `LWPOLYLINE` entity:
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/Users/.../.pyenv/versions/3.11.2/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/tkinter/__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "/Users/.../Repositories/Easy-DXF-Viewer/Easy DXF Viewer.py", line 140, in open_file
    visualize_dxf(file_path)
  File "/Users/.../Repositories/Easy-DXF-Viewer/Easy DXF Viewer.py", line 99, in visualize_dxf
    translate_entities(msp)
  File "/Users/.../Repositories/Easy-DXF-Viewer/Easy DXF Viewer.py", line 31, in translate_entities
    min_x = min(ent.dxf.start[0] if ent.dxftype() == 'LINE' else ent.dxf.center[0] for ent in entities)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/.../Repositories/Easy-DXF-Viewer/Easy DXF Viewer.py", line 31, in <genexpr>
    min_x = min(ent.dxf.start[0] if ent.dxftype() == 'LINE' else ent.dxf.center[0] for ent in entities)
                                                                 ^^^^^^^^^^^^^^
  File "/Users/.../Repositories/Easy-DXF-Viewer/venv/lib/python3.11/site-packages/ezdxf/entities/dxfns.py", line 130, in __getattr__
    raise const.DXFAttributeError(
ezdxf.lldxf.const.DXFAttributeError: Invalid DXF attribute "center" for entity LWPOLYLINE
```
The problem is encountered at [line 130](https://github.com/georgeh1ll/Easy-DXF-Viewer/blob/a6f487755ca89c3d4ace8f4ee1f06afbdc4a6939/Easy%20DXF%20Viewer.py#L130). The same error occurs with a second DXF file `elevations.dxf` while rendering a `POINT` entity:
```
ezdxf.lldxf.const.DXFAttributeError: Invalid DXF attribute "center" for entity POINT
```

**Screenshots**
Using the following code:
```
from ezdxf.addons.drawing.matplotlib import MatplotlibBackend
from ezdxf.addons.drawing import Frontend, RenderContext
import ezdxf

import matplotlib.pyplot as plt
import matplotlib as mpl

mpl.rcParams['lines.linewidth'] = 5  # set the value globally
mpl.rcParams['patch.linewidth'] = 5  # set the value globally
mpl.rcParams['hatch.linewidth'] = 5  # set the value globally
mpl.rcParams['axes.linewidth'] = 5  # set the value globally

def convert_dxf2img(path, save_to, img_format, img_res):
    doc = ezdxf.readfile(path)
    msp = doc.modelspace()
    auditor = doc.audit()

    if len(auditor.errors) != 0:
        return
    else:
        fig = plt.figure()
        ax = fig.add_axes([0, 0, 1, 1])
        ctx = RenderContext(doc)
        ctx.set_current_layout(msp)
        #ctx.current_layout.set_colors(bg='#FFFFFF')

        out = MatplotlibBackend(ax)
        Frontend(ctx, out).draw_layout(msp, finalize=True)

        fig.savefig(save_to, dpi=img_res)
        plt.close(fig)

convert_dxf2img("perimeter.dxf", "perimeter.png", img_format = '.png', img_res = 300)
```
`ezdxf` produces the following image for `perimeter.dxf`, which matches what was drawn in AutoCAD:

![image](https://github.com/mozman/ezdxf/assets/1170415/c1a8f11f-767c-4dfb-b0dc-8ffdfde1a979)

Here is how `elevations.dxf` should look:

![image](https://github.com/mozman/ezdxf/assets/1170415/19ac5076-a156-4f62-ace1-e058ade974d2)

Here are the DFX files:
[perimeter.dxf.zip](https://github.com/mozman/ezdxf/files/13166384/perimeter.dxf.zip)
[elevations.dxf.zip](https://github.com/mozman/ezdxf/files/13166487/elevations.dxf.zip)

**Comment by mozman** [comment]
`Easy-DXF-Viewer` is not my repository!!!

**Comment by bandtank** [comment]
The error is in your repository. You don't need to be so exclamatory. At the very least, this is related to your repository's functionality.

**Comment by mozman** [comment]
The LWPOLYLINE entity doesn't have a "center" attribute:

![image](https://github.com/mozman/ezdxf/assets/4230966/779dafad-0b6f-478d-a613-103dfdf3ad47)

You are confusing AutoCAD attributes with DXF attributes and `ezdxf` is not an AutoCAD clone, it's a DXF interface.
