### ISSUE TITLE
fully transparent background not working when export to png or pdf on win10

### ISSUE THREAD

**Issue by fuyb1992** [mozman/ezdxf#962]
**Describe the bug**
fully transparent background not working when export to png on win10

**To Reproduce**
```Python
import ezdxf

from ezdxf.addons.drawing import Frontend, RenderContext, pymupdf, layout, config


def export(doc, output_filename):
    msp = doc.modelspace()
    # 1. create the render context
    context = RenderContext(doc)
    # 2. create the backend
    backend = pymupdf.PyMuPdfBackend()
    # 3. create and configure the frontend
    cfg = config.Configuration(background_policy=config.BackgroundPolicy.CUSTOM, custom_bg_color='#00000000')
    # not working too cfg = config.Configuration(background_policy=config.BackgroundPolicy.OFF)
    frontend = Frontend(context, backend, config=cfg)
    # 4. draw the modelspace
    frontend.draw_layout(msp)
    # 5. create page layout
    page = layout.Page(256, 256, layout.Units.px, margins=layout.Margins.all(30))
    # 6. get the PDF rendering as bytes
    if output_filename.endswith('png'):
        out_bytes = backend.get_pixmap_bytes(page, fmt="png", dpi=96)
    elif output_filename.endswith('pdf'):
        out_bytes = backend.get_pdf_bytes(page)
    else:
        raise Exception('Unsupported file type')
    with open(output_filename, "wb") as fp:
        fp.write(out_bytes)
```

dxf file in the zip
[1629650446E4B889E4BABAE6B299E58F91.zip](https://github.com/mozman/ezdxf/files/13386531/1629650446E4B889E4BABAE6B299E58F91.zip)

**Comment by zhengpingwan** [comment]
这是来自邮箱的自动回复邮件。

**Comment by mozman** [comment]
Your code is correct and works as expected. There is just one minor argument to add:
```Python
out_bytes = backend.get_pixmap_bytes(page, fmt="png", dpi=96, alpha=True)
```

You have to add an alpha channel by using the argument `alpha=True`.

![image](https://github.com/mozman/ezdxf/assets/4230966/0a57cb80-3f9e-4168-936a-7cdbecde8083)

Please close this issue if this fixes your problem.

**Comment by mozman** [comment]
The `PyMuPDFBackend` doesn't support transparent backgrounds for PDFs because I don't know how this works or if this is even supported by `PyMuPDF`.

**Comment by mozman** [comment]
ChatGPT about support of transparent PDF background via `PyMuPDF`:
> As of my last knowledge update in January 2022, PyMuPDF (MuPDF bindings for Python) doesn't provide a direct way to set a transparent background for a page. The library is primarily focused on reading and rendering PDF documents, and its API may not include features for advanced PDF creation or modification.

**Comment by mozman** [comment]
Transparent background for PDFs also doesn't work with the `MatplotlibBackend`:

```Python
import ezdxf

import matplotlib.pyplot as plt
from ezdxf.addons.drawing import Frontend, RenderContext, config, matplotlib


def export(doc, output_filename):
    msp = doc.modelspace()
    context = RenderContext(doc)
    fig: plt.Figure = plt.figure()
    ax: plt.Axes = fig.add_axes((0, 0, 1, 1))

    backend = matplotlib.MatplotlibBackend(ax)
    cfg = config.Configuration(
        background_policy=config.BackgroundPolicy.CUSTOM, custom_bg_color="#ffffff00"
    )
    # BackgroundPolicy.OFF doesn't work either
    frontend = Frontend(context, backend, config=cfg)
    frontend.draw_layout(msp)
    fig.savefig(output_filename, transparent=True)


if __name__ == "__main__":
    doc = ezdxf.readfile("962.dxf")
    export(doc, "962mpl.pdf")

```

**Comment by fuyb1992** [comment]
> Your code is correct and works as expected. There is just one minor argument to add:
> 
> ```python
> out_bytes = backend.get_pixmap_bytes(page, fmt="png", dpi=96, alpha=True)
> ```
> 
> You have to add an alpha channel by using the argument `alpha=True`.
> 
> ![image](https://user-images.githubusercontent.com/4230966/283873922-0a57cb80-3f9e-4168-936a-7cdbecde8083.png)
> 
> Please close this issue if this fixes your problem.

This works for me, thanks a lot

**Comment by fuyb1992** [comment]
> Your code is correct and works as expected. There is just one minor argument to add:
> 
> ```python
> out_bytes = backend.get_pixmap_bytes(page, fmt="png", dpi=96, alpha=True)
> ```
> 
> You have to add an alpha channel by using the argument `alpha=True`.
> 
> ![image](https://user-images.githubusercontent.com/4230966/283873922-0a57cb80-3f9e-4168-936a-7cdbecde8083.png)
> 
> Please close this issue if this fixes your problem.

This works for me, thanks a lot
