### ISSUE TITLE
cannot open with autocad 2019

### ISSUE THREAD

**Issue by sunburst-yz** [mozman/ezdxf#97]
I use the example code but daw nothing.

`
import ezdxf

doc = ezdxf.new('R2010')  # create a new DXF R2010 drawing, official DXF version name: 'AC1024'

msp = doc.modelspace()  # add new entities to the modelspace
msp.add_line((0, 0), (10, 0))  # add a LINE entity
doc.saveas('line.dxf')
`

**Comment by mozman** [comment]
TrueView 2020 opens the file and shows the line:

![image](https://user-images.githubusercontent.com/4230966/67637282-48886200-f8d9-11e9-8af8-652d3ae112ae.png)
