### ISSUE TITLE
Apparently a 0, 0, 0 vector produces ZeroDivisionError: float division

### ISSUE THREAD

**Issue by JohnCC330** [mozman/ezdxf#971]
**Describe the bug**
Apparently a 0, 0, 0 vector produces ZeroDivisionError: float division

**To Reproduce**
I'll try to find a way to produce a simplified test program

The error I get is the following:

```
  File "src/ezdxf/acc/vector.pyx", line 561, in ezdxf.acc.vector.Vec3.spatial_angle.__get__
  File "src/ezdxf/acc/vector.pyx", line 789, in ezdxf.acc.vector.v3_normalize
ZeroDivisionError: float division
```
(Strangely, it really says 'float division' - all references I found on the 'net mention `float division by zero`)

Checking the code there:
```
cdef Vec3 v3_normalize(Vec3 a, double length):
    cdef double factor = length / v3_magnitude(a)
    cdef Vec3 res = Vec3()
    res.x = a.x * factor
    res.y = a.y * factor
    res.z = a.z * factor
    return res
```
I suspect a case of vec3 being 0, 0, 0: This is somewhat strange, but in may case I opened
an external DXF converted from a PDF. Probably the conversion (via `InkScape`) missed the
special case.

Maybe a more elegant exit should be provided in `ezdxf`?
Maybe a reference to the location in the file?

Generally speaking, there should maybe be a test _before_ calling `normalize`?

ezdxf is version 1.1.3b1
`ezdxf audit` doesn't report any issues
`ezdxf browse` does find some `group codes` 330 which it paints red.

**Comment by JohnCC330** [comment]
I'm passing a dxf to ezdxf, which I obtained after converting a PDF to dxf using Inkscape (there's no code of mine involved). It has about 75000 line segments in it - as far as I can see, only LINE segments. The main reason I'm doing this is because for some reason, some line segments are drawn up to 15 times, which makes the file very large and slow to load. I'd like to try and remove all the duplication.

**Comment by mozman** [comment]
Is this an issue in ezdxf and if so where in the code?
