### ISSUE TITLE
fontTools.ttLib.TTLibError

### ISSUE THREAD

**Issue by SuiYu2002** [mozman/ezdxf#976]
File "G:\pythonProject\surveying_mapping\venv\Lib\site-packages\fontTools\ttLib\sfnt.py", line 85, in __init__
    raise TTLibError("Not a TrueType or OpenType font (bad sfntVersion)")
fontTools.ttLib.TTLibError: Not a TrueType or OpenType font (bad sfntVersion)
how can I console this problem?

**Comment by mozman** [comment]
update to v1.1.3

**Comment by SuiYu2002** [comment]
Thank you! This is caused by incompatible versions of python's dependency libraries
