### ISSUE TITLE
explode "ACAD_PROXY_ENTITY" ,  error: required argument is not a float

### ISSUE THREAD

**Issue by xbdr419** [mozman/ezdxf#991]
when I try to expode a "ACAD_PROXY_ENTITY" ，return error: required argument is not a float
I add a print() in sourcecode, to show parameter,  as shown  below：

![image](https://github.com/mozman/ezdxf/assets/19528714/85095614-68f9-415c-8031-a0705780b437)

Looking forward to fixing this issue

**Comment by mozman** [comment]
There is a template for creating an issue - the important part is data or code to reproduce the error, without this information I can't help.

**Comment by xbdr419** [comment]
This a template， Thanks
[http://142.171.244.168:8000/test.zip](url)

**Comment by mozman** [comment]
Can you post a script to find the issue quickly - otherwise the issue have to wait until I have time next year or so.

**Comment by xbdr419** [comment]
Sorry, because it's relatively simple, I didn't post it as shown in the screenshot above

Both error have the same code:

import ezdxf 
f = r"D:\cad\test.dxf"
doc = ezdxf.readfile(f)
msp = doc.modelspace()
for e in msp:
    if e.dxftype() == "ACAD_PROXY_ENTITY" :
        e.explode()
