### ISSUE TITLE
Problems with hidden objects when converting png

### ISSUE THREAD

**Issue by fobecon-mskim** [mozman/ezdxf#992]
**Describe the bug**
The result of converting to png is different from the CAD file!
I've confirmed that the conversion works well by referring to the drawing-related [documentation](https://ezdxf.readthedocs.io/en/stable/addons/drawing.html). 
However, the output seems to be different.

When I exploded something in AutoCAD, something came out. (Like the converted image below)
Your code seems to draw even the hidden objects inside.

How do I draw only the objects that are clearly visible in CAD?

**Result Screenshots**

CAD
![image](https://github.com/mozman/ezdxf/assets/153470823/146422b9-aba9-4323-9f8a-80bc8c6553cb)

converted image
![image](https://github.com/mozman/ezdxf/assets/153470823/fd0b2ff9-d041-4163-9a1c-813229261dee)

**Code**
```python
import matplotlib.pyplot as plt
from ezdxf.addons import odafc
from ezdxf.addons.drawing import RenderContext, Frontend
from ezdxf.addons.drawing.matplotlib import MatplotlibBackend
from ezdxf.addons.drawing.config import Configuration

dpi = 300
file = "sample.dwg"
out_file = "image.png"
doc = odafc.readfile(file)

auditor = doc.audit()
if auditor.has_errors:
    # But is most likely good enough for rendering.
    print(f"Found {len(auditor.errors)} unrecoverable errors.")
if auditor.has_fixes:
    print(f"Fixed {len(auditor.fixes)} errors.")

layout = doc.layouts.get("Model")

# setup drawing add-on configuration
config = Configuration()
fig: plt.Figure = plt.figure(dpi=dpi)
ax: plt.Axes = fig.add_axes([0, 0, 1, 1])
ctx = RenderContext(doc)
out = MatplotlibBackend(ax)
Frontend(ctx, out, config=config).draw_layout(layout, finalize=True)

if out_file is not None:
    print(f'saving to "{out_file}"')
    fig.savefig(out_file, dpi=dpi)
    plt.close(fig)
```

**DWG File**
[link](https://drive.google.com/file/d/1lELgrppFwJ_RqQBE2cdqqZlbvi68-BPb/view?usp=sharing)

**Comment by mozman** [comment]
There is a template for creating an issue - the important part is data or code to reproduce the error, without this information I can't help.

**Comment by fobecon-mskim** [comment]
@mozman 
Oh, I'm sorry. I have attached the DWG file and included the code.

**Comment by mozman** [comment]
Hi!

This is a huge DXF file 59MB when converted from DWG.

`Ezdxf` is maybe not the right kind of tool to handle such huge and complex drawing.

I have no idea which application created this drawing (it's not AutoCAD) but my computer still tries to render this file while writing this comment.

I already condensed the file to 29MB by using the `PURGE` and `WBLOCK` commands in BricsCAD.  

-- still rendering

I don't see any chance to fix this. I don't have the time and the will to debug a 29MB DXF file. Sorry.

-- still rendering ...

The process uses all available memory which means heavy page swapping and a massive slowdown...

-- after 25 min. I stopped the process...

I can and will only help if you can create a small example to reproduce the error.

**Comment by fobecon-mskim** [comment]
@mozman 
I really appreciate your hard work in answering!

I reorganized a specific block in autoCAD and made it smaller.
Here is the [download link](https://drive.google.com/file/d/1G-INJDhGOd6a5eLIh2GYjJSheUMGM6Ip/view?usp=sharing) for the DWG file.

I also ran the code again and the results are as follows.

**AutoCAD screen**
![image](https://github.com/mozman/ezdxf/assets/153470823/f32f358e-0a73-495a-8491-78059b3abe70)

**Export to PDF from AutoCAD**
![image](https://github.com/mozman/ezdxf/assets/153470823/819c9a9e-2f94-4301-ae1c-481cef0c7c39)

**code result**
![image2](https://github.com/mozman/ezdxf/assets/153470823/35f4b059-5fa8-4759-a892-dbd67cf07161)

**Comment by mozman** [comment]
Which `ezdxf` version do you use, because the current version renders nothing for "sample_small.dwg" converted by BricsCAD to DXF R2013.

**Comment by fobecon-mskim** [comment]
I use version '1.1.3'
![image](https://github.com/mozman/ezdxf/assets/153470823/b05c4d2b-54ae-4ce4-9a63-406dae4c7dd0)

and

I modified some of the attached code.
Frontend(ctx, out, config=config).draw_layout(layout, finalize=True)  # finalize False -> True

I made a mistake

**Comment by mozman** [comment]
OK, I can reproduce the error and get the same result as you.

**Comment by fobecon-mskim** [comment]
That's good to hear!

As far as I've checked, it seems that ezdxf draws all possible information when creating a drawing. 
This implies that the issue isn't related to problems arising from PNG conversion.
It appears that ezdxf draws even hidden information.

When checking the CAD screen shown by the 'ezdxf view' command, it's similar to the PNG conversion results.

**ezdxf view**
![image](https://github.com/mozman/ezdxf/assets/153470823/411c5205-d8bf-4720-b021-741aa2ac1761)

**Comment by mozman** [comment]
A quick fix in AutoCAD is to save the visible content via `WBLOCK` in a new DXF file.

The file size goes down to 3.5MB from 20MB and `ezdxf` renders only the visible part:

![wblock2](https://github.com/mozman/ezdxf/assets/4230966/782ac35d-c1ae-49ca-bf12-3108246c85b3)

**Comment by mozman** [comment]
It seems this file uses `SPATIAL_FILTER` objects to clip parts of the modelspace. This is not supported by `ezdxf` - I don't even know how this works.

**Comment by fobecon-mskim** [comment]
Wow! Thank you so much!
You're a lifesaver! 😄
As you mentioned, I was able to get information about the cropped area by checking the spatial filter.
I really appreciate your help!!
